import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {verifyPreparation as previous} from '../nss153/session-binding.mjs';
const root='work/nss154',old=previous(),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),sourceManifest={};
const names=['prepare.py','start-dallas.mjs','match-controlled.mjs','read-controlled.mjs','current-audit-diagnostic.mjs','failed-wan-owner.lua','declared-baseline.mjs','ssh-client.mjs','bounded-pacer.mjs','upload-ack.mjs','upload-server.py','server.py','discover-peer.py','probe-peer.py','client-watchdog.ps1','endpoint-firewall-guardian.py','close-endpoint.mjs','crash-read.lua','epoch-driver.mjs','journal.mjs','process-identity.mjs','pilot-supervisor.mjs','restart-harness.mjs','session-binding.mjs','journal-checks.mjs','qualify.mjs'];
for(const n of names){const f=root+'/'+n;sourceManifest[f]=hash(fs.readFileSync(f));let p;if(n.endsWith('.mjs'))p=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});if(n.endsWith('.py'))p=spawnSync('C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-c','import sys;compile(open(sys.argv[1],encoding="utf-8").read(),sys.argv[1],"exec")',f],{encoding:'utf8',windowsHide:true});if(p)assert.equal(p.status,0,p.stderr);
 if(n.endsWith('.mjs'))for(const m of fs.readFileSync(f,'utf8').matchAll(/\b(?:from|import)\s*['"]([^'"]+)['"]/g)){if(!m[1].startsWith('.'))continue;const d=path.posix.normalize(path.posix.join(root,m[1]));assert.ok(fs.existsSync(d));assert.ok(names.includes(path.posix.relative(root,d))||d in old.sourceManifest,'Unbound dependency '+d);}}
const e=fs.readFileSync(root+'/epoch-driver.mjs','utf8');assert.ok(e.includes('export async function runEpoch'));assert.ok(e.includes('await onDetached(context);await uploadStage(context)'));assert.ok(e.includes("from '../nss149/module-stage.mjs'"));assert.ok(!e.includes('process.argv'));
for(const n of ['start-dallas.mjs','match-controlled.mjs','read-controlled.mjs','current-audit-diagnostic.mjs','epoch-driver.mjs','close-endpoint.mjs'])assert.ok(!fs.readFileSync(root+'/'+n,'utf8').includes('work/nss153'));
const models=JSON.parse(fs.readFileSync(root+'/journal-checks.json'));assert.ok(models.passed&&models.rejectedMalformedJournalModels===15);
const q={passed:true,inheritedBindings:Object.keys(old.sourceManifest).length,sourceManifest,journalledSupervisor:true,nativeFactoryUnchanged:149,budgets:[6,27,100,180,9000,65536,73728],journalModels:models,fullFactoryModelExecuted:false,productionExecution:false};fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,bindings:Object.keys((await import('./session-binding.mjs')).verifyPreparation().sourceManifest).length,malformedJournalRefusals:15,nativeFactoryUnchanged:149,productionWrites:false}));
