// Local size and mapping model only. It cannot authorize hardware admission.
import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';
import{mapClassifiedPair}from'./class-leaf-map.mjs';import{packetTemplate}from'./wan-tag-plan.mjs';import{buildPayload}from'./payload.mjs';import{guardianPlan}from'./guardian-plan.mjs';
import{canonicalSelection}from'../nss27/flow-selection.mjs';import{packGuardian}from'../nss149/pack-guardian.mjs';import{encode}from'../nss11/v7-observe-repair/observe2/transport.mjs';
const root='work/v21-fiveflow',read=p=>JSON.parse(fs.readFileSync(p)),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const label=process.argv[2]??'v1';assert.match(label,/^v\d+$/);const save=(n,v)=>fs.writeFileSync(root+'/'+n+'.json',JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const old=read('work/v16-three/modeled-three-v2-class-frame-private.json'),frame=structuredClone(old.frame),selected={},entries=[['tcp',1],['udp',2],['tcp2',3],['tcp3',4],['tcp4',5]];
frame.flows=entries.map(([slot,w])=>{const f=structuredClone(old.frame.flows.find(x=>x.identity.protocolNumber===(slot==='udp'?17:6)));assert.ok(f);const i=f.identity;i.wan=w;i.mark=w*65536;i.connectionId=String(2000000000+w);i.original.sport=52001+w;i.reply.dport=i.original.sport;i.reply.dst='172.16.255.'+(200+w);i.natUpload.src=i.reply.dst;i.natUpload.sport=i.reply.dport;f.key=[i.wan,i.mark,slot==='udp'?'udp':'tcp',i.original.src,i.original.sport,i.reply.src,i.reply.dst,i.reply.sport,i.reply.dport,i.zone,i.connectionId].join('|');selected[slot]=canonicalSelection(f);return f;});
const mapping=mapClassifiedPair(frame,selected);assert.deepEqual(mapping.decisions.map(d=>d.class),['BULK','RT','BULK','BULK','BULK']);assert.equal(new Set(mapping.decisions.map(d=>d.flow.wan)).size,5);
let checks=2;for(const slot of['tcp','udp','tcp2','tcp3','tcp4']){const bad=structuredClone(frame);bad.flows.find(f=>Number(f.identity.connectionId)===selected[slot].id).decision.class='BE';assert.throws(()=>mapClassifiedPair(bad,selected));checks++;}
const dup=structuredClone(frame);dup.flows.push(dup.flows[4]);assert.throws(()=>mapClassifiedPair(dup,selected));checks++;
const t=packetTemplate(mapping,'c'.repeat(32),59999);t.expected.nftables=t.expected.nftables.filter(x=>x.chain?.name!=='forward'&&x.rule?.chain!=='forward');const tagPlan={table:t.expected.nftables[0].table.name,owner:'c'.repeat(32),mode:'rt',expected:t.expected,wanLeafAssignments:t.wanLeafAssignments,guardedCounters:t.guardedCounters};
for(const[slot,f]of Object.entries(selected))f.classifierKey=frame.flows.find(x=>Number(x.identity.connectionId)===f.id).key;
const gp=read('work/v20-five/session-20261006194426-648cb0de/stage-plan-private.json');for(const k of['guardianSourceSha256','selectedGuardianSha256','oneEpochControlledPair','phaseSourceSha256','qosSourceSha256','execBytes'])delete gp[k];gp.selected=selected;gp.moduleBytes=55872;gp.moduleSha256=read(root+'/runtime-elf-comparison.json').runtimeSha256;
gp.wanPrerequisites.members=entries.map(([slot,w])=>({...gp.wanPrerequisites.members[0],w,ip:selected[slot].reply.dst}));
const values={register_gate:1,diagnostic_only:0};for(const[slot,name]of[['tcp','tcp'],['udp','game'],['tcp2','tcp2'],['tcp3','tcp3'],['tcp4','tcp4']]){const f=selected[slot];Object.assign(values,{[name+'_ct_id_raw']:((f.id>>>24)|((f.id>>>8)&0xff00)|((f.id<<8)&0xff0000)|(f.id<<24))>>>0,[name+'_server']:f.original.dst,[name+'_source_port']:f.original.sport,[name+'_server_port']:f.original.dport,[name+'_ct_mark']:f.mark,[name+'_nat_address']:f.reply.dst,[name+'_nat_port']:f.reply.dport});}values.frozen_record_sha256='f'.repeat(64);gp.insmodArguments=Object.entries(values).map(([k,v])=>k+'='+v).join(' ');
const sources={qos:fs.readFileSync(root+'/qos-physical.lua','utf8'),phase:fs.readFileSync('work/nss69/core-guard-phase.lua','utf8'),classifier:fs.readFileSync(root+'/classifier.lua','utf8'),tags:fs.readFileSync(root+'/classified-tags.lua','utf8'),normalizer:fs.readFileSync(root+'/tag-normalizer.lua','utf8')};
const payload=buildPayload({tagPlan,selected,wanPrerequisites:gp.wanPrerequisites},sources);gp.qosCodeBytes=Buffer.byteLength(payload.stagedCode);gp.qosCodeSha256=hash(payload.stagedCode);gp.tagPlan={table:tagPlan.table,owner:tagPlan.owner,mode:tagPlan.mode};
const batchBytes=Buffer.byteLength(JSON.stringify({nftables:tagPlan.expected.nftables.map((x,i)=>({[i===0?'create':'add']:x}))}));
const guard=packGuardian(fs.readFileSync(root+'/module-stage-guardian.lua','utf8')).replace('__PLAN__',()=>JSON.stringify(guardianPlan(gp))).replace('__CORE_PHASE__',()=>'return{}').replace('__QOS_PHYSICAL__',()=>'return{}');
let guardian,error;try{guardian=encode("lua - <<'V21_GUARD_SIZE'\n"+guard+"\nV21_GUARD_SIZE\n");}catch(e){error=String(e);}
const metric={mappingChecks:checks,modelOnly:true,hardwareEligibility:false,bundleBytes:gp.qosCodeBytes,tagBatchBytes:batchBytes,moduleArgumentCharacters:gp.insmodArguments.length,guardianExecBytes:guardian?.execBytes,guardianError:error,limits:{bundle:73728,nftBatch:49152,insmod:2048,exec:9000},payloadSha256:gp.qosCodeSha256};
save('size-model-'+label+'-private',metric);fs.writeFileSync(root+'/modeled-five-'+label+'-payload-private.lua',payload.stagedCode,{flag:'wx'});save('modeled-five-'+label+'-frame-private',{frame,selected,modelOnly:true,hardwareEligibility:false});save('modeled-five-'+label+'-tag-plan-private',tagPlan);save('modeled-five-'+label+'-guardian-plan-private',gp);
assert.equal(error,undefined);assert.ok(gp.qosCodeBytes<=73728,'Original bundle limit refused');assert.ok(batchBytes<49152);assert.ok(gp.insmodArguments.length<2048);console.log(JSON.stringify({passed:true,...metric}));
