import fs from'node:fs';import crypto from'node:crypto';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';
import{verifyPreparation as inherited}from'../v20-five/session-binding.mjs';import{verifyCandidate}from'./candidate-policy.mjs';import{requireOwnedUpload}from'./owned-load-policy.mjs';
const root='work/v21-fiveflow',read=p=>JSON.parse(fs.readFileSync(p)),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),old=inherited(),native=read(root+'/native-qualified.json'),model=read(root+'/modeled-five-v3-frame-private.json'),plan=read(root+'/modeled-five-v3-guardian-plan-private.json'),tags=read(root+'/modeled-five-v3-tag-plan-private.json');
assert.ok(native.passed&&native.modelOnly&&!native.productionWrites&&native.nftCheckOnlyPassed);const metrics=read(root+'/size-model-v3-private.json');assert.ok(metrics.bundleBytes<=73728&&metrics.guardianExecBytes<=9000&&metrics.tagBatchBytes<49152&&metrics.moduleArgumentCharacters<2048);
const input={...plan,tagPlan:tags,selected:model.selected};verifyCandidate(input);let cases=1;for(const change of [x=>x.wanPrerequisites.members[0].mac='bad',x=>x.wanPrerequisites.members[0].link='wrong',x=>x.wanPrerequisites.members[0].failure=-1,x=>x.selected.tcp3.mark|=0x2000,x=>x.tagPlan.wanLeafAssignments.tcp4.upTag=0,x=>x.selected.tcp4.protocol=17]){const x=structuredClone(input);change(x);assert.throws(()=>verifyCandidate(x));cases++;}
const config={seconds:180,mbps:32,bulkDirection:'download',tcpRates:{tcp:8,tcp2:8,tcp3:8,tcp4:8},tcpPort:22,session:'model'},load={clientPid:1234},status={perTcpMbps:config.tcpRates,tcpMetric:'client-observed stdout download bytes',tcpBytes:1000,bulkTransport:'owned native OpenSSH download',pacerDebtCatchupAllowed:false,maximumPacerCreditBytes:65536,maximumCombinedPacerCreditBytes:65536,session:'model',pid:1234,tcpChildren:['tcp','tcp2','tcp3','tcp4'].map(slot=>({slot,connected:true})),at:100,elapsed:20};assert.equal(requireOwnedUpload(config,status,load,100.1).remainingSeconds,160);cases++;
for(const change of [x=>x.maximumCombinedPacerCreditBytes=65537,x=>x.tcpChildren.pop(),x=>x.tcpChildren[3].connected=false]){const x=structuredClone(status);change(x);assert.throws(()=>requireOwnedUpload(config,x,load,100.1));cases++;}
const manifest={};for(const dir of[root,root+'/endpoint-gate'])for(const name of fs.readdirSync(dir)){if(!(/\.(mjs|lua|py|ps1|c|h)$/.test(name)||name==='Makefile')||name.includes('private')||name.includes('.generated.')||name.endsWith('.mod.c'))continue;const path=dir+'/'+name;if(!fs.statSync(path).isFile())continue;manifest[path]=hash(fs.readFileSync(path));if(name.endsWith('.mjs')){const r=spawnSync(process.execPath,['--check',path],{windowsHide:true,encoding:'utf8'});assert.equal(r.status,0,r.stderr);}}
for(const name of['native-qualified.json','normalizer-qualified.json','qos-native-qualified.json','native-source-qualified.json','runtime-elf-comparison.json'])manifest[root+'/'+name]=hash(fs.readFileSync(root+'/'+name));
const receipt={passed:true,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,hardwareExecuted:false,wholeFactoryModeled:false,fiveExactSlots:true,fiveNaturallyDistinctWansRequired:true,fourTcpBulkOneUdpRt:true,residentClassifierUnchanged:true,sourceFreshnessSeconds:6,kernelSessionSeconds:90,kernelMaximumSeconds:120,ownerSeconds:180,clientSeconds:180,phaseSeconds:60,controlledOfferedMbps:{tcp:8,tcp2:8,tcp3:8,tcp4:8,total:32},combinedCreditBytes:65536,hostChangedScopeChecks:cases,modelBundleBytes:metrics.bundleBytes,modelGuardianExecBytes:metrics.guardianExecBytes,modelTagBatchBytes:metrics.tagBatchBytes,losslessTagDataEncoding:true,factoredPostGuardsByteEquivalentWhenExpanded:true,driverAndFirmwareUnchanged:true};
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,sourceBindings:Object.keys(old.sourceManifest).length+Object.keys(manifest).length,cases,bundleBytes:metrics.bundleBytes,guardianExecBytes:metrics.guardianExecBytes,hardwareExecuted:false}));
