import fs from'node:fs';import crypto from'node:crypto';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import{verifyPreparation as inherited}from'../v23-fiveflow/session-binding.mjs';
const root='work/v24-fiveflow',old=inherited(),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
for(const name of['classifier.lua','classified-tags.lua','fast-path.lua','wan-scope.lua','qos-physical.lua','tag-normalizer.lua','module-stage-guardian.lua','pack-json.mjs','compact-post-guards.mjs','read-controlled.mjs','match-controlled.mjs','payload.mjs','module-stage.mjs','epoch-driver.mjs','current-audit-diagnostic.mjs','owned-load-policy.mjs']){
 const s=fs.readFileSync(root+'/'+name,'utf8').replaceAll('work/v24-fiveflow','work/v23-fiveflow').replaceAll('work\\/v24-fiveflow\\/','work\\/v23-fiveflow\\/');assert.equal(s,fs.readFileSync('work/v23-fiveflow/'+name,'utf8'),name+' changed outside fixture startup');
}
const native=fs.readFileSync(root+'/native-client.mjs','utf8'),model=JSON.parse(fs.readFileSync(root+'/serial-model-qualified.json'));assert.ok(model.passed&&model.checks===6&&!model.hardwareExecuted);assert.ok(native.includes('await first')&&native.includes('},8000)')&&native.includes('180000')&&native.includes('maximumCombinedPacerCreditBytes:65536')&&native.includes("try{for(const slot of ['tcp','tcp2','tcp3','tcp4'])await startTcp(slot,1)}catch(error){finish(error)}"));
const manifest={};for(const name of fs.readdirSync(root))if(/\.(mjs|lua|py|ps1)$/.test(name)&&!name.includes('private')){const path=root+'/'+name;manifest[path]=hash(fs.readFileSync(path));if(name.endsWith('.mjs')){const r=spawnSync(process.execPath,['--check',path],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stderr);}}
for(const name of['native-qualified.json','normalizer-qualified.json','qos-native-qualified.json','serial-model-qualified.json'])manifest[root+'/'+name]=hash(fs.readFileSync(root+'/'+name));
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify({passed:true,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,hardwareExecuted:false,wholeFactoryModeled:false,onlyFixtureConnectionStartupSerialized:true,firstByteDeadlineMilliseconds:8000,fiveSlotNativeAndQoSLuaExact:true,exactPcProcessSocketInventoryUnchanged:true,sourceFreshnessSeconds:6,kernelSessionSeconds:90,kernelMaximumSeconds:120,ownerSeconds:180,clientSeconds:180,phaseSeconds:60,combinedCreditBytes:65536,totalOfferedMbps:32,priorFailuresRetained:true},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,bindings:Object.keys(old.sourceManifest).length+Object.keys(manifest).length,serialModels:6,gateAndQoSUnchanged:true}));
