import fs from 'node:fs';
const s=JSON.parse(fs.readFileSync('outputs/nss37-normalizer-observations.json'));
const f=(n,d=2)=>Number(n).toFixed(d),esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const benchmark=s.nativeBenchmark.results.map(r=>`<tr><td>${r.synthetic?'512 行合成文本':'204 行真实采集文本'}</td><td>${f(r.oldCpuMean*1000)}</td><td>${f(r.newCpuMean*1000)}</td><td>${f(r.cpuReductionPercent,1)}%</td><td>8 对，结果全部相等</td></tr>`).join('');
const labels={before:'安装前',trial:'首次试装',permanent:'重新安装、保留前'};
const windows=Object.entries(s.windows).map(([k,v])=>`<tr><td>${labels[k]}</td><td>${f(v.seconds)}</td><td>${f(v.lan4DownMbps,3)}</td><td>${f(v.lan4DownPps,1)}</td><td>${f(v.cpuBusyPercent)}%</td><td>${f(v.softirqPercent)}%</td><td>+${v.timeSqueezeDelta}</td></tr>`).join('');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSS37 · 分类器解析优化与安全保留</title><style>body{margin:0;background:#f3f5f7;color:#19232d;font:16px/1.75 system-ui,'Microsoft YaHei',sans-serif}main{max-width:1060px;margin:35px auto;padding:34px;background:white;border-radius:16px}h1{font-size:30px;line-height:1.4}h2{margin-top:32px;font-size:21px}p{max-width:95ch}a{color:#075f83}code{overflow-wrap:anywhere;font-size:13px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:11px;text-align:left;border-bottom:1px solid #dce3e8}th{background:#eff5f7}.note{padding:16px 20px;background:#eef6f4;border-left:4px solid #287363}.warn{background:#fff5e4;border-color:#af761b}.scroll{overflow:auto}.muted{color:#566774}@media(max-width:700px){main{margin:0;padding:20px;border-radius:0}h1{font-size:25px}}</style><main>
<p class="muted">Athena AX6600 · 2026-10-03 · 最终现场核验 18:15:57（北京时间）</p><h1>分类器文本解析优化已保留<br>真人高负载 NSS 闭环仍待验证</h1>
<p class="note">这一轮只优化连接文本中的属性提取。相同输入在路由器 Lua 内存中交替运行，解析 CPU 耗时下降约 <strong>40%–43%</strong>，输出保持一致。完成一次真实 180 秒自动回滚后，重新创建检查点、部署并保留。<strong>ECM 全程关闭。</strong></p>
<h2>解决了什么</h2><p>NSS36 的真人尝试在 ECM 开启前遇到数据时间余量不足。此前已测出连接文本校验占用时间较长。本轮进一步定位到 ID、mark、zone 的重复模式扫描，只把 <code>conntrack-source.lua / attrs()</code> 改成字面量定位，再按原规则校验空白边界、非空值和重复项。worker、guardian、分类核心与 leaf 映射未修改。</p><p>没有缩小采集范围、丢弃字段、缓存旧身份、改变 PBR/mark/NAT，或延长来源年龄、发布有效期与学习期限。</p>
<h2>等价性与目标机测量</h2><p><strong>9,087 项解析检查 + 26 项分类生命周期检查通过。</strong>解析检查包括 2,688 个属性边界/值案例、6,381 次完整标准化新旧对照、18 个独立预期；覆盖重复字段、畸形与截断输入、5000 次确定性变异及私有真实采集文本。生命周期使用实际核心和 leaf 函数、模拟计数器/接口/时间，覆盖预热、换端口、旧流退出、完整 mark/NAT/WAN 改变、冷却和 restart/crash 后重新学习；没有向生产服务注入 crash。</p>
<div class="scroll"><table><thead><tr><th>同一批输入</th><th>旧版 CPU ms</th><th>新版 CPU ms</th><th>降幅</th><th>重复测量</th></tr></thead><tbody>${benchmark}</tbody></table></div><p>单位是一次文本标准化的平均 CPU 毫秒。两组共 16 对，输出和统计相等；背景 LAN4 约 0.639 Mbps。512 行输入仅在内存中合成，不是网络发包。</p><p class="warn note">这些结果支持“属性提取是可消除的解析开销”，不能推出整机 CPU 下降 40%，也不能证明 NSS 转发收益或高负载发布时间已达标。</p>
<h2>试装、回滚与现场保护</h2><p>两次安装各自先完成检查点下载、哈希与压缩校验，再核验脱离 SSH 的暂存守护和 180 秒事务守护。首次试装 35 次观测健康，18:03:42 确认独立到期自动恢复旧解析器、worker、guardian、配置和健康服务；控制端未要求提前回滚。18:05 起重新创建检查点安装，35 次观测健康后于 18:07:55 提交保留。</p><p>完整与精简快照中的身份、分类、leaf 与有效期一致。结束审计通过，常驻实例与保留前观测相同；保存的 last-error 属于第一次试装到期，与当前实例不同。ECM IPv4/IPv6 关闭、计数全零；认证/PBR/sing-box/Tailscale 与生产队列通过配置核验，无实验事务、暂存、状态节点或 gate/qdisc 模块残留。</p>
<h2>现场观测记录</h2><div class="scroll"><table><thead><tr><th>窗口</th><th>秒</th><th>LAN4 Mbps</th><th>pps</th><th>busy</th><th>softirq</th><th>time_squeeze</th></tr></thead><tbody>${windows}</tbody></table></div><p>各窗口 35 次观测均健康，包含观测开销，属于不同自然轻负载。<strong>不作前后性能相减。</strong>采集年龄低于 1 秒的观测均为 6/35；保留窗口发布延迟约 0.25–0.29 秒。它们证明轻负载下运行与发布正常，不能替代真人高负载准入验证。</p>
<h2>主线控制器与下一步</h2><p>NSS37 控制器已绑定新配置与 66 项源文件/证明，目标 Lua 编译及完整 tag policy 往返检查通过，另有 10 项同 WAN 选择检查。NSS36 未改变的消费者/backend 证明明确标记为沿用，没有重复计为本轮新检查。</p><p>18:11:17 只读应用核验发现 1 个真实 CS2 RT 候选，Steam bulk 候选为 0，同 WAN 连接对为 0，因此本轮未启动 fast path 试验。bulk/RT NSS leaf、加速后的出口/ct mark/NAT/WAN affinity，以及 CS2 jitter/loss/Miss 均未重新测量。</p><p>下一步先在代表性负载下只读核验数据及时性，必要时继续定位同一分类发布路径的开销；入口窗口成立后，再集中一次真人单 WAN software → NSS → software 验证。现有受控连接对子组仍是 20 Mbps，不能写成整个 Steam 300 Mbps 以上都已进入 NSS。第二 WAN、共享预算和其它 QoS 支线继续等待。</p>
<h2>可核对记录</h2><p>当前部署引用：<code>work/nss37/deployment-latest.json</code><br>配置 SHA256：<code>${esc(s.classifier.configSha256)}</code><br>解析器 SHA256：<code>${esc(s.change.newSha256)}</code></p><p><a href="nss37-normalizer-observations.json">本轮结构化观测</a> · <a href="nss36-admission-timing-report.html">NSS36 真实失败与时序定位</a> · <a href="https://github.com/ZyPulse-zy/athena-nss-mainline">私有 GitHub 主线仓库</a></p><p class="muted">未提交上游 Issue/PR。本轮是本地分类器优化；没有证据把前次时序问题归因为 NSS/ECM 驱动缺陷。</p></main></html>`;
fs.writeFileSync('outputs/nss37-normalizer-report.html',html);console.log(JSON.stringify({report:'outputs/nss37-normalizer-report.html',nssEnabled:false,realHighLoadABACompleted:false}));
