import fs from 'node:fs';import assert from 'node:assert/strict';
const read=p=>JSON.parse(fs.readFileSync(p)),root='work/nss40',r=n=>read(root+'/'+n+'.json');
const rehearsal=r('rehearsal-summary'),raw=read(rehearsal.path+'-private.json'),selected=read(rehearsal.path+'-selected-private.json');
const attempt='work/nss40/real-matched-aba-20261003155259-d8910c25',failed=read(attempt+'/result.json'),freeze=read(attempt+'/frozen-source-manifest-private.json');
assert.ok(!failed.passed&&!failed.matchedForwardingABACompleted);assert.ok(failed.errors[0].includes('stdin:32'));
assert.deepEqual(fs.readdirSync(attempt).filter(x=>!x.startsWith('frozen')).sort(),['controller-error.json','result.json']);
const opening=r('classifier-opening-inspection'),closing=r('classifier-closing-inspection'),audit=r('diagnosed-closing-audit'),diag=r('diagnosed-closing-diagnostic-audit-private');
const prior=read('work/nss39/classifier-postpush-inspection.json');
const metric=(a,b)=>{
 const seconds=b.uptime-a.uptime,parse=s=>s.trim().split(/\s+/).slice(1,9).map(Number),aa=parse(a.cpu),bb=parse(b.cpu),d=bb.map((v,i)=>v-aa[i]),total=d.reduce((x,y)=>x+y,0);
 const squeeze=s=>s.trim().split('\n').reduce((t,line)=>t+parseInt(line.trim().split(/\s+/)[2],16),0);
 assert.ok(seconds>0&&total>0);
 return{seconds,lan4DownMbps:(b.txBytes-a.txBytes)*8/seconds/1e6,lan4DownPps:(b.txPackets-a.txPackets)/seconds,cpuBusyPercent:100*(total-d[3]-d[4])/total,softirqPercent:100*d[6]/total,timeSqueezeDelta:squeeze(b.softnet)-squeeze(a.softnet)};
};
const compact=r('closing-observation'),light=metric(compact.rows[0],compact.rows.at(-1));
const trace=r('audit-trace-first-private');
const rows=raw.rows.map(x=>({atSeconds:x.at-raw.rows[0].at,ready:x.ready,retryable:x.retryable,reason:x.reason?.replace(/^\[string .*?\]:\d+: /,''),sourceSequence:x.adapter.source?.sequence,sourceAge:x.adapter.sourceAge,querySeconds:x.adapter.source?.finishedAtUptime-x.adapter.source?.startedAtUptime,publicationDelaySeconds:x.adapter.source?.publishedAtUptime-x.adapter.source?.startedAtUptime,adapterSeconds:x.adapter.checkSeconds,phaseSeconds:x.phaseSeconds,iterationSeconds:x.iterationSeconds,fullInventory:x.fullInventory}));
const producer=closing.files['classification.json'].producer;
const summary={round:'NSS40',generatedAt:new Date().toISOString(),deploymentReference:'work/nss39/deployment-latest.json',permanentClassifierChanged:false,classifierConfigSha256:closing.files['classification.json'].configSha256,
 preparation:{reusedQualifiedRuntimeManifestItems:r('preparation').qualifiedManifestItems,runtimeRouterPayloadsUnchanged:true,localOutputEntryRelocated:true,localSourcePathErrorCorrectedBeforeRouterTrial:true,fullReadonlyTransportRefusedLocally:true,unreachableMethodsOnlyOmitted:true,completeReadinessAndPhaseScanChecksRetained:true,transportCeilingBytes:9000},
 realReadOnlyAdmission:{observedAt:raw.observedAt,samples:rehearsal.samples,ready:rehearsal.ready,refusals:rehearsal.reasons,selectedWan:selected.tcp.wan,fullTcpMark:selected.tcp.mark,fullUdpMark:selected.udp.mark,sameNat:selected.tcp.reply.dst===selected.udp.reply.dst,zoneZero:selected.tcp.zone===0&&selected.udp.zone===0,actualApplicationOwnershipChecked:true,tupleAndInstanceValidated:true,initialAgeLimitSeconds:1,prelearningAgeLimitSeconds:2,sourceAgeMinSeconds:rehearsal.sourceAgeMinSeconds,adapterMaxSeconds:rehearsal.adapterMaxSeconds,phaseMaxSeconds:rehearsal.phaseMaxSeconds,sourceSequences:[...new Set(rows.filter(x=>x.ready).map(x=>x.sourceSequence))],execBytes:rehearsal.execBytes,routerWrites:false,nssOpened:false,performance:metric(raw.telemetry[0],raw.telemetry[1]),observerCpuSeconds:raw.observerCpuSeconds,observationCostIncludedInCpu:true,notMatchedForwardingABA:true},
 actualTrial:{requested:true,startedAt:'2026-10-03T15:52:59Z',prewriteAuditRefused:true,refusal:'Protected audit snapshot freshness assertion: publication age <9s and source age <6s',originalFile:'work/nss23/operational-audit.lua',originalLine:32,exactFailedAgesRecorded:false,failedPhaseTimingRecorded:false,checkpointCreated:false,productionMutationAttempted:false,wanChanged:false,qdiscCreated:false,tagRulesInstalled:false,gateModuleLoaded:false,ecmOpened:false,matchedForwardingABACompleted:false,hardwareLeafCounters:null,rollbackResult:'Not applicable: rejected before checkpoint and any experimental configuration write',frozenBoundFiles:freeze.entries.length,afterRefusalSourceHashesReverified:true,selectedPairNotFrozenBeforePrewriteRefusal:true,rawApplicationLatestWasRefreshedAfterward:true},
 diagnosticFollowup:{firstReadonlyPassed:trace.passed,firstLockedAuditSeconds:trace.diagnostic.events.at(-1).at-trace.diagnostic.events[0].at,firstFreshness:trace.diagnostic.freshness,secondReadonlyPassed:diag.passed,secondLockedAuditSeconds:diag.diagnostic.events.at(-1).at-diag.diagnostic.events[0].at,secondFreshness:diag.diagnostic.freshness,originalAssertionsRetained:true,diagnosticIntegratedLocalAuditEntry:'work/nss40/current-audit-diagnostic.mjs',perInvocationApplicationArchiveVerified:r('recorded-application-latest').passed,permanentWorkerInstrumented:false,failedHighLoadAuditRootCauseProved:false,sourceOrderingEstablished:'classification publication -> synchronous locked software reconciliation/audit -> full snapshot publication',timingOrderingDoesNotProveFailureCause:true},
 closingSoftwareWindow:{...light,samples:compact.rows.length,allHealthy:compact.rows.every(x=>x.status==='running'&&x.guardianHealthy&&x.accel===0&&x.frontend===1),sourceAgeMinSeconds:Math.min(...compact.rows.map(x=>x.age)),sourceAgeMaxSeconds:Math.max(...compact.rows.map(x=>x.age)),semantic:compact.semantic,unmatchedLightLoad:true},
 finalState:{protectedAudit:Object.fromEntries(['passed','protectedConfigurationUnchanged','exactOwnedNativeAudit','selectors','queryAge','sequence','ecmClosedAndZero'].map(k=>[k,audit[k]])),checkedAt:diag.observedAt,sameProducerSinceTurnStart:producer===opening.files['classification.json'].producer,sameProducerSinceNss39LastInspection:producer===prior.files['classification.json'].producer,currentWorkerHealthy:closing.files['classification.json'].status==='running'&&closing.files['classification.json'].dataHealthy&&closing.files['guardian.json'].healthy,lastErrorBelongsToPriorTrial:closing.files['last-error.json'].producer!==producer,closure:r('final-closure'),application:r('real-reader-qualified')},
 conclusions:{currentAdapterCanPassInitialFreshnessUnderRealHighLoad:true,reliableHighLoadAdmissionProved:false,realHighLoadNssLoopCompleted:false,nssCpuBenefitProvedThisRound:false,cs2JitterLossMissCaptured:false,automaticGameClassificationFullyAccepted:false,highLoadCauseOfStaleProtectedSnapshotKnown:false,upstreamSubmission:false,secondWanExpansionAllowed:false}
};
fs.writeFileSync(root+'/admission-timing-sanitized.json',JSON.stringify({routerWrites:false,nssOpened:false,initialReadinessOnly:true,endpointIdentitiesOmitted:true,rows},null,2)+'\n');
fs.writeFileSync('outputs/nss40-mainline-observations.json',JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify({round:summary.round,highLoadMbps:summary.realReadOnlyAdmission.performance.lan4DownMbps,ready:rehearsal.ready,samples:rehearsal.samples,productionMutationAttempted:false,finalProtectedAuditPassed:audit.passed}));
