import fs from'node:fs';import assert from'node:assert/strict';
const dir=process.argv[2];assert.match(dir,/^work\/nss49\/real-matched-aba-[\d]+-[a-f0-9]+$/);
const r=JSON.parse(fs.readFileSync(dir+'/last-record-private.json'));const selected=JSON.parse(fs.readFileSync(dir+'/selected-private.json'));const wan=selected.tcp.wan;assert.equal(r.abaCompleted,true);
const cpu=s=>s.cpu.split('\n')[0].trim().split(/\s+/).slice(1,9).map(Number);
const soft=s=>s.softnet.trim().split('\n').map(line=>line.trim().split(/\s+/).slice(0,3).map(v=>parseInt(v,16)));
function interval(a,b){
 const seconds=b.uptime-a.uptime;assert.ok(seconds>0);const ca=cpu(a),cb=cpu(b),d=cb.map((v,i)=>v-ca[i]);assert.ok(d.every(v=>v>=0));const total=d.reduce((x,y)=>x+y,0);assert.ok(total>0);
 const sa=soft(a),sb=soft(b);assert.equal(sa.length,sb.length);const sd=[0,0,0];for(let i=0;i<sa.length;i++)for(let k=0;k<3;k++){const n=sb[i][k]-sa[i][k];sd[k]+=n>=0?n:n+2**32;}
 const iface={};for(const name of['lan4','rpwan'+wan]){const x=a.interfaces[name],y=b.interfaces[name];iface[name]={};for(const field of['rx_bytes','tx_bytes','rx_packets','tx_packets','rx_dropped','tx_dropped']){const change=y[field]-x[field];assert.ok(Number.isSafeInteger(change)&&change>=0);iface[name][field]=change;}iface[name].rxMbps=iface[name].rx_bytes*8/seconds/1e6;iface[name].txMbps=iface[name].tx_bytes*8/seconds/1e6;iface[name].rxPps=iface[name].rx_packets/seconds;iface[name].txPps=iface[name].tx_packets/seconds;}
 return{seconds,busyPercent:(total-d[3]-d[4])*100/total,softirqPercent:d[6]*100/total,softnetProcessed:sd[0],softnetDropped:sd[1],timeSqueeze:sd[2],interfaces:iface};
}
const phases=r.phases.map(p=>{const samples=r.samples.slice(p.sampleStart-1,p.sampleEnd);assert.equal(samples.length,11);assert.ok(samples.every(s=>s.phase===p.name&&s.counts['ecm_nss_ipv4/accelerated_count']===(p.name==='B'?2:0)));return{name:p.name,...interval(samples[0],samples.at(-1)),sourceAgeMin:Math.min(...samples.map(s=>s.observation.queryAge)),sourceAgeMax:Math.max(...samples.map(s=>s.observation.queryAge)),acceleratedCount:p.name==='B'?2:0};});
function leaves(q){const result={};for(const m of q.qdisc.matchAll(/qdisc nssfq_codel ([a-f0-9]+:) [^\n]*\n Sent (\d+) bytes (\d+) pkt \(dropped (\d+)/g))result[m[1]]={bytes:Number(m[2]),packets:Number(m[3]),drops:Number(m[4])};return result;}
const start=leaves(r.qosAccelerated),end=leaves(r.qosAfterRetirement);const leafDeltas={};for(const id of['8f05:','8f06:','8fff:']){assert.ok(start[id]&&end[id]);leafDeltas[id]=Object.fromEntries(['bytes','packets','drops'].map(k=>[k,end[id][k]-start[id][k]]));}
const spread=values=>(Math.max(...values)-Math.min(...values))/(values.reduce((a,b)=>a+b,0)/values.length);
const totalSpread=spread(phases.map(p=>p.interfaces.lan4.txMbps));const wanSpread=spread(phases.map(p=>p.interfaces['rpwan'+wan].rxMbps));
const out={passed:true,functionalOnly:true,oneWan:wan,ctMark:selected.tcp.mark,natAndAffinityVerified:true,phases,leafDeltasAroundFastPath:{startUptime:r.qosAccelerated.uptime,endUptime:r.qosAfterRetirement.uptime,includesAcquireAndRetirementBoundary:true,counters:leafDeltas},renewals:r.renewals.length,totalThroughputRelativeSpread:totalSpread,selectedWanThroughputRelativeSpread:wanSpread,observedThroughputWithin10Percent:totalSpread<=0.1&&wanSpread<=0.1,offeredLoadEqualityProven:false,selectedBudgetMbps:20,acceleratedFlowCount:2,cpuBenefitConclusive:false,realHumanGameQualityConclusive:false,automaticGameSession:true,routerRollbackVerified:['wanRestored','mwan3Restored','qosRestored','qosModuleUnloaded','stateNodeRemoved','tagsRemoved','firmwareZeroAfterRetirement'].every(k=>r[k]===true)};
fs.writeFileSync(dir+'/metrics-sanitized.json',JSON.stringify(out,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(out));
