import fs from 'node:fs';import path from 'node:path';import net from 'node:net';import dgram from 'node:dgram';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
import ssh2 from 'file:///C:/Users/lishu/Documents/Codex/2026-09-11/ax6600-re-cs-02-jdcos-4/work/runtime/node_modules/ssh2/lib/index.js';
import {uploadAck} from './upload-ack.mjs';import {createPacer} from './bounded-pacer.mjs';import {cohortPorts,validateChosen} from './cohort-policy.mjs';
const configPath=path.resolve(process.argv[2]),c=JSON.parse(fs.readFileSync(configPath)),dir=path.dirname(configPath);assert.equal(c.mbps,32);assert.equal(c.seconds,180);assert.equal(c.pps,50);assert.equal(c.bulkDirection,'upload');assert.equal(c.tcpPort,22);assert.equal(c.tcpServerAddress,'18.138.159.236');
const token=Buffer.from(c.token,'hex');assert.equal(token.length,32);const began=performance.now(),transports=new Map(),seen=new Set();
const stats={pid:process.pid,session:c.session,startedAt:Date.now()/1000,tcpBytes:0,tcpSubmitted:0,tcpConnected:false,tcpSourcePort:c.tcpSourcePort,udpSourcePort:c.udpSourcePort,udpSent:0,udpReceived:0,errors:[],bulkTransport:'owned SSH upload with bounded software cohort',tcpMetric:'server-confirmed received bytes',pacerDebtCatchupAllowed:false,maximumPacerCreditBytes:65536,tcpPaused:false,preparationCohort:0,selectedTcpPort:null};
const udpOut=fs.createWriteStream(dir+'/udp-samples-private.jsonl'),loadOut=fs.createWriteStream(dir+'/load-samples-private.jsonl');let ended=false,selected=null,rr=0,sock,uploadTimer,udpTimer,statusTimer,hardTimer;
const known=spawnSync('ssh-keygen',['-F',c.tcpServerAddress],{encoding:'utf8',windowsHide:true,timeout:3000});assert.equal(known.status,0);const pins=known.stdout.split(/\r?\n/).filter(x=>x&&!x.startsWith('#')).map(x=>crypto.createHash('sha256').update(Buffer.from(x.trim().split(/\s+/)[2],'base64')).digest('hex'));assert.ok(pins.length);
const quote=x=>"'"+x.replaceAll("'","'\\''")+"'",py=fs.readFileSync(new URL('./upload-server.py',import.meta.url),'utf8');
function dispose(t){t.disposed=true;t.connected=false;t.ssh.destroy()}
function stamp(){if(ended)return;stats.tcpCandidatePorts=selected?[selected.port]:[...transports.values()].filter(t=>!t.disposed&&t.connected&&t.ack>0).map(t=>t.port);stats.softwarePreparationStreams=selected?0:stats.tcpCandidatePorts.length;const x={...stats,at:Date.now()/1000,elapsed:(performance.now()-began)/1000};fs.writeFileSync(dir+'/status-private.json.new',JSON.stringify(x));try{fs.renameSync(dir+'/status-private.json.new',dir+'/status-private.json')}catch(e){if(e.code!=='EPERM'&&e.code!=='EBUSY')throw e;stats.statusPublicationDeferrals=(stats.statusPublicationDeferrals??0)+1}loadOut.write(JSON.stringify(x)+'\n')}
function stop(reason){if(ended)return;ended=true;clearInterval(uploadTimer);clearInterval(udpTimer);clearInterval(statusTimer);clearTimeout(hardTimer);if(reason)stats.errors.push(reason);sock?.close();for(const t of transports.values())dispose(t);fs.writeFileSync(dir+'/result-private.json',JSON.stringify({...stats,finishedAt:Date.now()/1000,seconds:(performance.now()-began)/1000},null,2));udpOut.end();loadOut.end();setTimeout(()=>process.exit(stats.errors.length?1:0),50)}
function connect(port){const t={port,ssh:new ssh2.Client(),connected:false,disposed:false,blocked:false,ack:0,submitted:0};assert.ok(!transports.has(port));transports.set(port,t);
 t.ssh.on('error',e=>{if(t.disposed||ended)return;t.error=e.message;t.connected=false;if(t===selected)stop('Selected SSH: '+e.message)});
 t.ssh.on('close',()=>{if(t.disposed||ended)return;t.connected=false;if(t===selected){stats.tcpConnected=false;stats.tcpClosedAt=Date.now()/1000;if(stats.tcpClosingRequested)loadOut.write(JSON.stringify({event:'tcp-owned-closed',at:stats.tcpClosedAt,sourcePort:t.port,udpSourcePort:stats.udpSourcePort})+'\n');else stop('Unexpected selected SSH close')}});
 t.ssh.on('ready',()=>{if(t.disposed||ended)return;t.ssh.exec('timeout -k 1 185 python3 -u -c '+quote(py),(e,stream)=>{if(t.disposed||ended)return;if(e){t.error=e.message;if(t===selected)stop('Selected SSH exec: '+e.message);return}t.stream=stream;t.connected=true;let pending='';stream.on('data',b=>{if(t.disposed||ended)return;try{pending+=b.toString();assert.ok(pending.length<=8192);let i;while((i=pending.indexOf('\n'))>=0){const line=pending.slice(0,i);pending=pending.slice(i+1);const next=uploadAck(t.ack,line);assert.ok(next<=t.submitted);stats.tcpBytes+=next-t.ack;t.ack=next;assert.ok(stats.tcpBytes<=1024*1024*1024)}}catch(e){stop('Confirmed counter: '+String(e))}});stream.on('drain',()=>{t.blocked=false});stream.on('close',code=>{if(!t.disposed&&t===selected&&!stats.tcpClosingRequested&&!ended)stop('Selected stream exited '+code)});});});
 t.ssh.connect({sock:net.connect({host:c.tcpServerAddress,port:22,localAddress:c.clientAddress,localPort:port}),username:'ubuntu',privateKey:fs.readFileSync(c.sshKeyPath),hostHash:'sha256',hostVerifier:h=>pins.includes(h),readyTimeout:6000,keepaliveInterval:0});
}
function beginCohort(number){assert.ok(selected===null||stats.tcpClosingRequested&&!stats.tcpConnected);assert.equal(number,stats.preparationCohort===0&&transports.size===0?0:1);selected=null;stats.selectedTcpPort=null;stats.tcpConnected=false;stats.tcpClosingRequested=false;stats.preparationCohort=number;for(const p of cohortPorts(c.tcpSourcePort,number))connect(p);loadOut.write(JSON.stringify({event:'software-preparation-cohort',number,at:Date.now()/1000,totalOfferedMbps:32,routerWrites:false})+'\n')}
function choose(port){const available=[...transports.values()].filter(t=>!t.disposed&&t.connected&&t.ack>0&&cohortPorts(c.tcpSourcePort,stats.preparationCohort).includes(t.port)).map(t=>t.port);validateChosen(port,available);selected=transports.get(port);for(const t of transports.values())if(t!==selected&&!t.disposed)dispose(t);stats.tcpSourcePort=port;stats.tcpConnected=true;stats.selectedTcpPort=port;loadOut.write(JSON.stringify({event:'one-owned-tcp-selected',at:Date.now()/1000,port,otherOwnSocketsClosed:true,selectionPolicy:'actual Linux ct mark and classifier, no PBR writes'})+'\n')}
sock=dgram.createSocket('udp4');sock.on('error',e=>stop('UDP: '+e.message));sock.on('message',b=>{if(b.length!==128||!b.subarray(0,32).equals(token))return;const n=Number(b.readBigUInt64BE(32));if(seen.has(n))return;seen.add(n);stats.udpReceived++;udpOut.write(JSON.stringify({event:'reply',sequence:n,at:Date.now()/1000,sourcePort:c.udpSourcePort,rttMs:performance.now()-b.readDoubleBE(40)})+'\n')});sock.bind(c.udpSourcePort,c.clientAddress,()=>sock.connect(c.udpPort,c.serverAddress));let seq=0,lastRequest=null;
udpTimer=setInterval(()=>{if(ended)return;try{const p=dir+'/control.json';if(fs.existsSync(p)){const x=JSON.parse(fs.readFileSync(p));assert.equal(x.session,c.session);assert.equal(x.udpSourcePort??c.udpSourcePort,c.udpSourcePort);if(x.stop){stop();return}if(x.prepareSuccessor&&lastRequest!=='successor'){assert.equal(stats.preparationCohort,0);assert.ok(stats.tcpClosingRequested&&!stats.tcpConnected);lastRequest='successor';beginCohort(1)}if(x.selectTcpPort!==undefined&&x.selectTcpPort!==stats.selectedTcpPort)choose(x.selectTcpPort);if(x.closeTcp&&selected&&stats.tcpConnected&&!stats.tcpClosingRequested){stats.tcpClosingRequested=true;stats.tcpCloseRequestedAt=Date.now()/1000;selected.ssh.end();loadOut.write(JSON.stringify({event:'tcp-owned-close-requested',at:stats.tcpCloseRequestedAt,sourcePort:selected.port,udpSourcePort:c.udpSourcePort})+'\n')}if(x.pauseTcp!==undefined){assert.equal(typeof x.pauseTcp,'boolean');stats.tcpPaused=x.pauseTcp}}
const b=Buffer.alloc(128);token.copy(b);b.writeBigUInt64BE(BigInt(seq),32);b.writeDoubleBE(performance.now(),40);sock.send(b,e=>{if(e&&!ended)stop(String(e))});stats.udpSent++;udpOut.write(JSON.stringify({event:'sent',sequence:seq++,at:Date.now()/1000,sourcePort:c.udpSourcePort})+'\n');}catch(e){stop(String(e))}},20);
const pacer=createPacer(performance.now(),32000000/8),block=Buffer.alloc(16384);uploadTimer=setInterval(()=>{if(ended||stats.tcpPaused||stats.tcpClosingRequested)return;try{const ready=(selected?[selected]:[...transports.values()].filter(t=>cohortPorts(c.tcpSourcePort,stats.preparationCohort).includes(t.port))).filter(t=>!t.disposed&&t.connected&&t.stream&&!t.blocked);for(let i=0;i<4&&pacer.next(performance.now(),ready.length===0);i++){const t=ready[rr++%ready.length];assert.ok(stats.tcpSubmitted+block.length<=1024*1024*1024);t.submitted+=block.length;stats.tcpSubmitted+=block.length;if(!t.stream.write(block))t.blocked=true;ready.splice(0,ready.length,...ready.filter(x=>!x.blocked));}}catch(e){stop(String(e))}},5);
statusTimer=setInterval(stamp,250);hardTimer=setTimeout(()=>stop(),180000);stamp();beginCohort(0);
