import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {verifyPreparation as original} from '../nss156/session-binding-v7.mjs';import {packLua} from '../nss149/pack-lua.mjs';
const root='work/nss157',old=original(),names=['prepare-combined.py','fast-path.lua','payload.mjs','payload-v2.mjs','measure-historical-payload.mjs','measure-historical-v2.mjs','measure-historical-v3.mjs','measure-historical-v4.mjs','prepare-measure-v3.py','combined-models.lua','qualify-native.mjs','prepare-entry.py','session-binding.mjs','pause-control.mjs','pilot-supervisor.mjs','qualify-entry.mjs','start-dallas.mjs','read-controlled.mjs','match-controlled.mjs','module-stage.mjs','current-audit-diagnostic.mjs','close-control.mjs','close-endpoint.mjs','cohort-client.mjs','upload-ack.mjs','bounded-pacer.mjs','cohort-policy.mjs','upload-server.py','server.py','receiver.py','discover-peer.py','probe-peer.py','client-watchdog.ps1','endpoint-firewall-guardian.py','crash-read.lua','module-stage-guardian.lua','epoch-driver.mjs','combined-policy.mjs'],sourceManifest={},hash=b=>crypto.createHash('sha256').update(b).digest('hex');
for(const n of names){const f=root+'/'+n,b=fs.readFileSync(f,'utf8');sourceManifest[f]=hash(b);if(n.endsWith('.mjs')){const t=spawnSync(process.execPath,['--check',f],{windowsHide:true,encoding:'utf8'});assert.equal(t.status,0,t.stderr);for(const m of b.matchAll(/\b(?:from|import)\s*['"]([^'"]+)['"]/g)){if(!m[1].startsWith('.'))continue;const d=path.posix.normalize(path.posix.join(root,m[1]));assert.ok(fs.existsSync(d));assert.ok(names.includes(path.posix.relative(root,d))||d in old.sourceManifest,'Unbound '+d)}}if(n.endsWith('.py')){const t=spawnSync('C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-c','import sys;compile(open(sys.argv[1],encoding="utf-8").read(),sys.argv[1],"exec")',f],{windowsHide:true,encoding:'utf8'});assert.equal(t.status,0,t.stderr)}}
const native=JSON.parse(fs.readFileSync(root+'/native-qualified.json')),fast=fs.readFileSync(root+'/fast-path.lua','utf8'),originalFast=fs.readFileSync('work/nss149/fast-path.lua','utf8');assert.ok(native.passed&&native.model.checks===9&&!native.fullFactoryModeled&&!native.productionExecuted);assert.equal(native.fastSourceSha256,hash(fast));
const cut=(s,a,b)=>s.slice(s.indexOf(a),s.indexOf(b,s.indexOf(a)));for(const[a,b]of[['function M.verifyReclassification(','function M.new('],[' retire=function(C)',' local function tick(']])assert.equal(packLua(cut(fast,a,b)),packLua(cut(originalFast,a,b)));
assert.equal(hash(fs.readFileSync(root+'/module-stage-guardian.lua')),hash(fs.readFileSync('work/nss156/module-stage-guardian.lua')));
const driver=fs.readFileSync(root+'/epoch-driver.mjs','utf8');assert.deepEqual([...driver.matchAll(/['"](work\/nss157\/run\d+\/(?:successor-)?continuity-private\.json)['"]/g)].map(m=>m[1]),['work/nss157/run1/continuity-private.json','work/nss157/run1/successor-continuity-private.json','work/nss157/run2/continuity-private.json','work/nss157/run2/successor-continuity-private.json']);
const audit=fs.readFileSync(root+'/current-audit-diagnostic.mjs','utf8');assert.ok(audit.includes('work\\/nss157\\/'));assert.ok(driver.includes('work/nss157/current-audit-diagnostic.mjs'));assert.ok(fs.readFileSync(root+'/module-stage.mjs','utf8').includes("'./payload-v2.mjs'"));
for(const n of ['cohort-client.mjs','bounded-pacer.mjs','cohort-policy.mjs','endpoint-firewall-guardian.py'])assert.equal(hash(fs.readFileSync(root+'/'+n)),hash(fs.readFileSync('work/nss156/'+n)));
const q={passed:true,inheritedBindings:Object.keys(old.sourceManifest).length,sourceManifest,combinedRetirementEntry:true,productionExecution:false,nativePartialModel:native,fullFactoryModelExecuted:false,originalPreciseClassRetirementImplementationUnchanged:true,wholePairExitAndNormal20SecondEpochRetained:true,exactInputNamespacesVerified:true,softwarePreparationOnlyFourTcpGlobal32Mbps:true,nssExactPairScopeUnchanged:true,permanentClassifierKernelGateAndQoSUnchanged:true,budgets:[6,27,100,180,9000,65536,73728]};fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,bindings:Object.keys((await import('./session-binding.mjs')).verifyPreparation().sourceManifest).length,nativeRamChecks:9,combinedNative157:true,productionExecution:false}));
