"""Freeze the common all-WAN observer and its successful retry, without recasting failure."""
from pathlib import Path
from datetime import datetime,timezone,timedelta
import json,hashlib,shutil,subprocess,importlib.util
w=Path(__file__).resolve().parents[2];repo=w/'athena-nss-mainline';r=w/'work/nss126'
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(b):return hashlib.sha256(b).hexdigest()
def dump(p,o):p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
spec=importlib.util.spec_from_file_location('collector',w/'work/nss101/collect-lifecycle.py');c=importlib.util.module_from_spec(spec);spec.loader.exec_module(c)
case=w/'work/nss125/controlled-matched-aba-20261005204220-e475787b';t=c.stage(case.relative_to(w).as_posix());m=t['metrics'];comparison=load(case/'same-load-comparison.json');up=load(case/'actual-upstream-proof.json');final=load(r/'v1-final-health.json');physical=load(r/'physical-final.json');qual=load(w/'work/nss125/entry-qualified.json')
assert t['passed']and t['completeABA']and t['sourceInputs']==1033 and all(t['rollback'].values())and m['allWanBackgroundObserved']and m['counterObserverSameInAllPhases']
assert final['passed']and physical['passed']and final['ecmStoppedAndZero']and qual['onlyCommonReadOnlyInterfaceListChanged']and len(qual['checks'])==4
failed=load(w/'work/nss125/failed-preparation-v1/receipt.json');assert failed['failureBeforeRouterWrite']and failed['clientUploadBytes']==0 and not failed['ecmOpened']
for name,digest in failed['originalReceipts'].items():assert sha((w/'work/nss125/failed-preparation-v1'/name).read_bytes())==digest
closures=[c.closure(load(w/'work/nss125/failed-preparation-v1/load-reference-private.json')['dir']),c.closure(load(r/'load-reference-private.json')['dir'])]
old=(repo/'evidence/current-runtime.json').read_bytes();assert load(repo/'evidence/current-runtime.json')['round']=='NSS124'and subprocess.check_output(['git','show','HEAD:evidence/current-runtime.json'],cwd=repo)==old
archive=repo/'evidence/nss124-runtime.json';assert not archive.exists();archive.write_bytes(old)
manifest=load(repo/'source-manifest.json');assert len(manifest['sources'])==1498;prefix=sha(json.dumps(manifest['sources'],sort_keys=True,separators=(',',':')).encode())
allowed={125:['prepare.py','bounded-pacer.mjs','upload-ack.mjs','upload-server.py','ssh-client.mjs','session-binding.mjs','qualify.mjs','controlled-session.mjs','current-audit-diagnostic.mjs','match-controlled.mjs','read-controlled.mjs','run.mjs','module-stage.mjs','payload.mjs','pack-lua.mjs','pack-guardian.mjs','compact-default-queues.mjs','uplink-tag-plan.mjs','parse-ecm-any-wan.mjs','fast-path.lua','module-stage-guardian.lua','qos-physical.lua','tag-normalizer.lua','failed-wan-owner.lua','declared-baseline.mjs','service-epoch.mjs'],126:['retry-existing.mjs','analyze-long.py','calibrate-clock.mjs','prove-upstream.py','analyze-uplink-transient.py','health.mjs','read-final-physical.mjs','compare-load.py','save-evidence.py']}
hashes={}
for n,names in allowed.items():
 for name in names:
  src=w/f'work/nss{n}'/name;assert src.is_file();rel=src.relative_to(w).as_posix();dst=repo/'code'/rel;assert not dst.exists();dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst);digest=sha(src.read_bytes());hashes[rel]=digest;manifest['sources'].append({'path':'code/'+rel,'workspaceSource':rel,'sha256':digest,'bytes':src.stat().st_size,'role':'same-observer-all-WAN-counter-evidence'})
manifest['generatedAt']=datetime.now(timezone.utc).isoformat();manifest['lastAppendExport']='NSS126';dump(repo/'source-manifest.json',manifest)
frozen={};freeze=r/'proof-v1/private-inputs';freeze.mkdir(parents=True,exist_ok=False)
for n in [125,126]:
 for src in sorted((w/f'work/nss{n}').rglob('*')):
  if not src.is_file()or any(p in src.parts for p in ['proof-v1','frozen','frozen-qualified-inputs','__pycache__']):continue
  rel=src.relative_to(w);dst=freeze/rel;dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst);frozen[rel.as_posix()]=sha(src.read_bytes());assert sha(dst.read_bytes())==frozen[rel.as_posix()]
dump(r/'private-input-freeze-index.json',frozen)
summary={'round':'NSS126','observedAt':final['observedAt'],'hardwareEntryRound':125,'onlyCommonReadOnlyInterfaceListChanged':True,'allWanBackgroundObserved':True,'oneWan':m['oneWan'],'boundInputs':1033,'offeredUploadMbps':32,'uplinkGroupMbps':60,'downlinkGroupMbps':30,'phaseSeconds':20,'nativeSessionSeconds':27,'independentOwnerSeconds':100,'classifierMaximumLeaseSeconds':6,'completeFunctionalABA':True,'firstSshHandshakeTimeoutPreserved':True,'unchangedQualifiedEntryRetriedOnce':True,'selectedTransferRateComparable':comparison['checks']['server_received_throughput_spread_le_10percent'],'unselectedTrafficSmallInEachPhase':comparison['checks']['unselected_wan_total_below_0_5Mbps_each'],'softwareMeanSoftirqPercent':comparison['softwareMeanSoftirqPercent'],'nssSoftirqPercent':comparison['nssSoftirqPercent'],'strictPresetComparisonAccepted':comparison['comparabilityAccepted'],'strictBackgroundRangeCriterionMarginallyFailed':not comparison['checks']['unselected_wan_total_range_below_0_25Mbps'],'backgroundRangeMbps':max(comparison['unselectedWanTotalRxPlusTxMbps'])-min(comparison['unselectedWanTotalRxPlusTxMbps']),'repeatCpuSignalSupportsContinuingEngineering':True,'noAdditionalCpuProbeToChaseThresholdPlanned':True,'rtLeafDrop':0,'bulkLeafDrop':0,'humanCs2Acceptance':False,'highLoad300MbpsAcceptance':False,'fullCakeReplacementAccepted':False,'preciseRateAccuracyAccepted':False,'residentClassifierChanged':False,'nssPermanentlyEnabled':False,'uiOperated':False,'upstreamSubmitted':False,'temporaryEndpointsClosed':2,'reportVerification':{'sourceValidated':True,'browserRendered':False}}
source={'round':'NSS126','historicPrefixSources':1498,'historicPrefixCanonicalSha256':prefix,'sources':len(hashes),'sourceHashes':hashes,'privateOwnedHostBootstrapExcluded':True,'actualBindingTreesRetained':True,'privateArtifactsFrozen':len(frozen)}
failure={'passed':False,'phase':'controlled-load-preparation','productionRouterWrites':False,'ecmOpened':False,'queueWrites':False,'clientUploadBytes':0,'rejection':'SSH handshake timed out; upload client exited before candidate observation','originalFailurePreserved':True,'originalFrozenReceiptSha256':sha((w/'work/nss125/failed-preparation-v1/receipt.json').read_bytes()),'entryOrTimeoutChangedBeforeRetry':False}
for key,value in {'mainline':summary,'trial':t,'metrics':m,'comparison':comparison,'uplink-proof':up,'preparation-failure':failure,'qualification':qual['checks'],'endpoint-closure':closures,'final-audit':final,'physical-final':physical,'source-proof':source}.items():dump(repo/f'evidence/nss126-{key}.json',value)
runtime={'round':'NSS126','checkedAt':physical['observedAt'],'deploymentReference':'work/nss68/deployment-latest.json','classifierConfigSha256':final['configSha256'],'workerPid':final['workerPid'],'guardianPid':final['guardianPid'],'nssPermanentlyEnabled':False,'residentClassifierChangedThisTurn':False,'qualifiedExperimentalEntry':'work/nss125/controlled-session.mjs','qualifiedExperimentalEntryBoundInputs':1033,'currentNssAdmissionMustBeRefreshedBeforeWrite':True,'audit':final,'physicalRootRestoreAudit':physical,'realHumanGameAcceptance':False,'strictPresetComparisonAccepted':comparison['comparabilityAccepted'],'repeatCpuSignalSupportsContinuingEngineering':True,'historical124RuntimePreservedSha256':sha(old),'nightContinuationUntilBeijing':'2026-10-06T10:00:00+08:00'};dump(repo/'evidence/current-runtime.json',runtime)
when=datetime.fromisoformat(final['observedAt'].replace('Z','+00:00')).astimezone(timezone(timedelta(hours=8))).strftime('%Y-%m-%d %H:%M');speeds='/'.join(f"{p['whole']['clientTcpMbps']:.3f}"for p in m['phases']);softs='/'.join(f"{p['whole']['softirqPercent']:.3f}"for p in m['phases']);udp='、'.join(f"{p['whole']['udp']['received']}/{p['whole']['udp']['sent']}"for p in m['phases']);bg='/'.join(f'{x:.3f}'for x in comparison['unselectedWanTotalRxPlusTxMbps'])
text=f'''更新：{when}，北京时间。最新NSS126整理、实际125入口；常驻68/config581b5d46…c791d7、4859/17139不变，实验已撤销。

**只给三段同一个观察器加五rpwan＋physicalwan＋lan4计数；UP60/DOWN30/有界32上传不改。实际WAN2完整20秒A/B/A2、ECM0→2→0、四leaf/mark/NAT/affinity/六续租和精确恢复通过。服务器确认{speeds}Mbps，softirq {softs}%，与124重复出现接近相同吞吐下的CPU下降。**

见 [实际指标](../evidence/nss126-metrics.json)、[背景和对照](../evidence/nss126-comparison.json)、[轮次](../evidence/nss126-trial.json)、[汇总](../evidence/nss126-mainline.json)、[失败](../evidence/nss126-preparation-failure.json)、[关闭](../evidence/nss126-endpoint-closure.json)、[终态](../evidence/nss126-final-audit.json)。

- 三段未选中WAN总RX＋TX {bg}Mbps，约80/64/103pps，选中TX约2942/2683/2951pps；TCP回复/ACK的包速差异保留。所有squeeze/softnet drop0，四leaf drop0；UDP收/发{udp}，B少2个echo回复，仍非CS2指标。
- 完整指标显示CPU信号与124一致，足以继续最小消费者工程；严格分析合同的背景流量范围0.2513Mbps略超过0.25，原comparability=false和没有正式相对收益值保留。它不作为扩大实验或重复追阈值的理由。短窗、非随机、部分包速不同和其它CPU工作未完全等同这些边界保持；非300Mbps/拥塞延迟/完整CAKE验收。
- 首次125上传SSH握手6秒超时后客户端退出，0上传B、未checkpoint/stage/改队列/开放ECM；原失败冻结。126外部driver对同一1033项125入口只重试一次，没有修改源或超时。新观察器4项检查含目标机7接口实际只读、语法、bundle73521<73728和预计完整记录697727<原1MiB读上限；未放宽6/27/100或传输边界。
- 实际新checkpoint/SHA/gzip、独立100秒owner写前核验，两个端点180秒FW/210秒客户端全退出；最终source{final['queryAge']:.2f}、ECM关闭全零、无事务/stage/state/模块，两个物理mq＋四fq_codel恢复，WAN4仍down/自然四路PBR不改。旧124 runtime原字节保留、实际输入私有冻结。
- 下一步直接把消费者的上行tag映射绑定到实际class和同源身份，未知/未准入RT拒绝；保留resident upTag0、gate/kernel pin/lease，改类精确撤销后才重学，不因字段改变重装常驻。仅这条自动分类→双向leaf主线，不再追加CPU对照来追背景阈值；之后最后一次集中真人。UI停用、不新下载/扩WAN/WiFi/共享预算/autorate；09:50起收尾并暂停本夜接续。
'''
for name,title in [('STATE.md','# 当前状态'),('PLAN.md','# 当前单WAN自动映射主线')]:
 p=repo/'docs'/name;p.write_text(title+'\n\n'+text+'\n## NSS124历史\n\n'+p.read_text(encoding='utf-8'),encoding='utf-8')
p=repo/'docs/EXPERIMENT_LOG.md';head,tail=p.read_text(encoding='utf-8').split('\n',1);p.write_text(head+'\n\n## NSS125–126 · '+when+' · 同观察器与全部WAN背景\n\n'+text+tail,encoding='utf-8')
p=repo/'AGENTS.md';head,tail=p.read_text(encoding='utf-8').split('\n',1);p.write_text(head+'\n\n最新NSS126整理/实际125：仅扩同观察器到5rpwan/wan/lan4，UP60/DOWN30/32上传保持；WAN2真实20秒三段、ECM0/2/0、四leaf/mark/NAT/affinity/6续租及恢复通过，上传'+speeds+'、softirq'+softs+'%，背景'+bg+'Mbps，UDP'+udp+'，四leafdrop0/squeeze0。背景范围0.2513略超分析0.25，原严格comparison=false保持；重复CPU信号可继续工程，不为了阈值重做CPU试验，也非真人/300或完整CAKE验收。125首SSH握手超时/0上传/未stage失败冻结；126同1033项入口只重试一次，无源/超时变更。2端点关闭、新checkpoint及独立100秒守护、原完整终态source3.05/4859/17139/68不变、ECM全零无残留，两根恢复、WAN4仍down。下一步实际class→双向tag最小消费者绑定/未知拒绝/改类精确撤销，再最后真人一次；不重装/新下载/UI/扩WAN；09:50收尾10点前暂停本夜；STATE为准。\n\n'+tail,encoding='utf-8')
p=repo/'docs/ARTIFACT_INDEX.md';p.write_text('# 当前NSS126\n\n[指标](../evidence/nss126-metrics.json) · [对照](../evidence/nss126-comparison.json) · [汇总](../evidence/nss126-mainline.json) · [终态](../evidence/nss126-final-audit.json) · [历史124 runtime](../evidence/nss124-runtime.json)。\n\n'+p.read_text(encoding='utf-8'),encoding='utf-8')
rows=''.join(f'<tr><td>{x["phase"]}</td><td>{x["whole"]["clientTcpMbps"]:.3f}</td><td>{x["whole"]["softirqPercent"]:.3f}%</td><td>{x["whole"]["timeSqueezeDelta"]}</td><td>{x["whole"]["udp"]["received"]}/{x["whole"]["udp"]["sent"]}</td></tr>'for x in m['phases'])
report=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSS126 全WAN背景对照</title><style>body{{background:#f4f4ee;color:#24352d;font:16px/1.8 "Microsoft YaHei",sans-serif}}main{{max-width:1000px;margin:auto;padding:28px 24px}}section{{background:white;padding:22px;border:1px solid #ddd;border-radius:10px;margin:22px 0}}table{{width:100%;border-collapse:collapse}}th,td{{text-align:left;padding:9px;border-bottom:1px solid #ddd}}</style><main><small>ATHENA · {when} 北京时间</small><h1>接近同吞吐下，NSS再次降低softirq</h1><p>只补同一观察器的全部WAN计数；负载和双向QoS不改。真实单WAN2、ECM0→2→0、四leaf命中，实验全部撤销。</p><section><table><tr><th>阶段</th><th>服务器确认Mbps</th><th>softirq</th><th>squeeze</th><th>UDP收/发</th></tr>{rows}</table><p>其它WAN流量{bg}Mbps，约80/64/103pps；上下行bulk/RT queue drop均0，B客户端少2回复。数据与124的CPU信号一致，但不是CS2指标、300Mbps、长期或拥塞验收。分析的背景范围0.2513略超0.25，原严格comparison=false保留，不修改阈值追验收。</p></section><section><h2>失败与恢复</h2><p>首125 SSH握手超时，上传0B且路由器未改。126同一入口只重试一次，成功完成三段/六续租。1033源绑定、新checkpoint和独立100秒守护、两端点关闭、两物理原队列恢复；常驻68不变、ECM关闭全零、WAN4仍down。</p></section><section><h2>继续主线</h2><p>直接把消费者双向tag绑定到实际class和同源身份，未知默认拒绝、改类精确撤销后重学。保持常驻upTag0、现有来源及kernel gate，不为可比阈值重复CPU试验。不操作桌面/新下载，不扩WAN；最后集中真人一次。09:50起收尾，10点前暂停本夜接续。</p><a href="https://github.com/ZyPulse-zy/athena-nss-mainline/blob/main/docs/STATE.md">仓库当前状态</a><p><small>源码核验，未作浏览器渲染验收。</small></p></section></main></html>'''
out=w/'outputs/nss126-mainline-report.html';assert not out.exists();out.write_text(report,encoding='utf-8')
dump(r/'export-receipt.json',{'passed':True,'newSources':len(hashes),'totalSources':len(manifest['sources']),'privateArtifacts':len(frozen),'temporaryEndpointsClosed':2});print(json.dumps({'exported':True,'sources':len(hashes),'totalSources':len(manifest['sources']),'uploadMbps':speeds}))
