import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{compactDefaultQueues}from'./compact-default-queues.mjs';import{packGuardian}from'./pack-guardian.mjs';import{preview}from'./preview-plan.mjs';
import{connectRouter}from'../nss27/connect-router.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';
const root='work/nss113',h=b=>crypto.createHash('sha256').update(b).digest('hex'),checks=[];
const pin=JSON.parse(fs.readFileSync('work/nss16/qos-capacity-private.json')),up=JSON.parse(fs.readFileSync(root+'/uplink-capacity-private.json'));
for(const[name,rows]of [['downlink',pin.interfaces.lan4.qdiscs],['uplink',up.defaultQueues]]){
 const projected=compactDefaultQueues(rows);assert.deepEqual(projected,rows.map(q=>Object.fromEntries(['kind','handle','root','parent','options'].filter(k=>q[k]!==undefined).map(k=>[k,q[k]]))));checks.push({name:name+'-exact-option-projection',passed:true,simulated:true});
 for(const[name2,change]of [['foreign-root',q=>q[0].kind='cake'],['duplicate-parent',q=>q[2].parent=q[1].parent],['handle',q=>q[1].handle='1:'],['missing-row',q=>q.pop()],['unknown-parent',q=>q[1].parent=':9']]){const a=structuredClone(rows);change(a);assert.throws(()=>compactDefaultQueues(a));checks.push({name:name+'-rejects-'+name2,passed:true,simulated:true});}
}
const guardian=fs.readFileSync(root+'/module-stage-guardian.lua','utf8');const packed=packGuardian(guardian);assert.ok(packed.length<guardian.length);for(const tag of ['__PLAN__','__CORE_PHASE__','__QOS_PHYSICAL__'])assert.equal(packed.split('[=['+tag+']=]').length,2);checks.push({name:'three-guardian-literals-preserved',passed:true,simulated:true});
for(const[s,name]of [[guardian.replace('__PLAN__','foreign'),'missing-placeholder'],[guardian+'\nreturn [[foreign]]','unexpected-long-literal']]){assert.throws(()=>packGuardian(s));checks.push({name:'guardian-rejects-'+name,passed:true,simulated:true});}
const planProof=preview();checks.push(...planProof.rows.map((r,i)=>({name:'five-bounded-plan-previews-'+i,...r,simulated:true})));fs.writeFileSync(root+'/transport-preview.json',JSON.stringify(planProof,null,2)+'\n',{flag:'wx'});
const c=await connectRouter();try{const e=encode("lua - <<'NSS113_OWNER_READ'\n"+fs.readFileSync(root+'/failed-wan-owner.lua','utf8')+"\nNSS113_OWNER_READ\n"),raw=receipt(await c.run(e.command),e);fs.writeFileSync(root+'/owner-qualification-raw-private.json',JSON.stringify(raw,null,2)+'\n',{flag:'wx'});assert.equal(raw.code,0,raw.stderr);const s=JSON.parse(raw.stdout);assert.equal(s.commandMatches,true);if(s.running){assert.equal(s.sameProcessBeforeAfter,true);assert.ok(['wrapper','exec-minieap'].includes(s.lifecycle));}else assert.equal(s.instanceStillNotRunning,true);checks.push({name:'actual-failed-wan-process-owner',passed:true,simulated:false,observedRunning:s.running,observedLifecycle:s.lifecycle??'not-running'});}finally{c.close()}
for(const name of fs.readdirSync(root).filter(x=>x.endsWith('.mjs'))){const p=spawnSync(process.execPath,['--check',root+'/'+name],{windowsHide:true,encoding:'utf8'});assert.equal(p.status,0,p.stderr);}
for(const name of ['fast-path.lua','module-stage-guardian.lua','qos-physical.lua','uplink-tag-plan.mjs','parse-ecm-any-wan.mjs'])assert.equal(h(fs.readFileSync(root+'/'+name)),h(fs.readFileSync('work/nss112/'+name)));
const sourceManifest={};for(const f of fs.readdirSync(root))if(/\.(mjs|py|lua|ps1)$/.test(f)&&!f.includes('private'))sourceManifest[root+'/'+f]=h(fs.readFileSync(root+'/'+f));
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify({passed:true,productionExecution:false,qosPayloadUnchangedFrom112:true,onlyPlanFormattingAndAuthenticatorLifecycleCorrected:true,defaultQueueOptionsStillExact:true,transportLimitsUnchanged:true,uplinkCapacitySha256:h(fs.readFileSync(root+'/uplink-capacity-private.json')),checks,sourceManifest},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,checks:checks.length,sourceBindings:Object.keys(sourceManifest).length,observedOwner:checks.at(-1),maximumPreviewExecBytes:Math.max(...planProof.rows.map(x=>x.execBytes))}));
