import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{verifyPreparation as inherited}from'../v12/session-binding.mjs';
const root='work/v13-two',hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),old=inherited(),manifest={};
const native=JSON.parse(fs.readFileSync(root+'/native-qualified.json')),build=JSON.parse(fs.readFileSync('work/v13/endpoint-gate/build-manifest.json')),pin=JSON.parse(fs.readFileSync('work/v13/pin-qualified.json')),elf=JSON.parse(fs.readFileSync('work/v13/runtime-elf-comparison.json'));
assert.ok(native.passed&&native.model.twentySecondsObserved&&native.wanModel.checks===2&&native.nativeExactTagReconstructionPassed);assert.equal(native.fastSourceSha256,hash(root+'/fast-path.lua'));assert.ok(native.combinedHistoricalPayloadBytes<=73728);
assert.ok(build.sdk_original_unchanged&&build.source_inputs_unchanged&&build.old_gate_inputs_unchanged&&pin.passed&&pin.actualPinConditionExtracted&&elf.passed);assert.equal(pin.sourceSha256,hash('work/v13/endpoint-gate/rp_ecm_gate_lab_ct.c'));assert.equal(elf.runtimeSha256,hash('work/v13/endpoint-gate/rp_ecm_gate_lab_ct.runtime.ko'));
for(const n of fs.readdirSync(root))if(/\.(?:mjs|py|lua|ps1)$/.test(n)||n==='native-qualified.json'){const f=root+'/'+n;manifest[f]=hash(f);if(n.endsWith('.mjs')){const p=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}}
for(const n of['endpoint-gate/rp_ecm_gate_lab_ct.c','endpoint-gate/rp_ecm_gate_lab_ct.runtime.ko','endpoint-gate/build-manifest.json','endpoint-gate/control-harness-result.json','renewal-qualified.json','runtime-elf-comparison.json','pin-qualified.json']){const f='work/v13/'+n;manifest[f]=hash(f);}
assert.equal(fs.readFileSync(root+'/download-server.py','utf8'),fs.readFileSync('work/nss149/download-server.py','utf8'));assert.ok(!fs.readFileSync(root+'/epoch-driver.mjs','utf8').includes('wanPrerequisites:{wan:'));assert.ok(!fs.readFileSync(root+'/module-stage.mjs','utf8').includes("from '../nss53/qualification.mjs'"));assert.ok(!fs.readFileSync(root+'/module-stage.mjs','utf8').includes("from '../nss75/refinement.mjs'"));
const q={passed:true,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,twoDistinctNaturallySelectedWans:true,oneTcpBulkOneUdpRt:true,sourceFreshnessSeconds:6,actualControllerSessionSeconds:27,actualNssPhaseSeconds:20,independentOwnerSeconds:100,pbrMarksNatAffinityUnchanged:true,hardwareExecuted:false};fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});const result=(await import('./session-binding.mjs')).verifyPreparation();console.log(JSON.stringify({passed:true,bindings:Object.keys(result.sourceManifest).length,twoWanHardwareNotYetExecuted:true}));
