import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {connectRouter} from '../nss20/connect-router.mjs';import {encode,receipt} from '../nss11/v7-observe-repair/observe2/transport.mjs';
const bytes=fs.readFileSync('work/nss85/fast-path.lua'),source=bytes.toString();const prefix=source.slice(0,source.indexOf('function M.new'))+'return M';
const base={};for(const k of ['tcp_post_up','tcp_post_down','udp_post_up','udp_post_down']){base[k+'_total']={packets:10,bytes:1000};base[k+'_expected']={packets:11,bytes:1040};base[k+'_unexpected']={packets:0,bytes:0};if(k!=='tcp_post_up')base[k+'_expected']={packets:10,bytes:1000}}base.udp_post_neighbor_nonzero={packets:0,bytes:0};
const cases=[];function add(name,edit,pass,pending=false){const c=structuredClone(base);edit?.(c);cases.push({name,c,pass,pending})}
add('recorded 40 byte ACK',null,true);add('original 60 byte ACK',c=>c.tcp_post_up_expected.bytes=1060,true);
add('no discrepancy',c=>c.tcp_post_up_expected={packets:10,bytes:1000},false);add('unknown 50 bytes',c=>c.tcp_post_up_expected.bytes=1050,false);add('two ACKs',c=>c.tcp_post_up_expected={packets:12,bytes:1080},false);
const zero=c=>{c.udp_post_down_total={packets:0,bytes:0};c.udp_post_down_expected={packets:0,bytes:0}};
add('pending initial UDP read',zero,true,true);add('pending forbidden at later sites',zero,false,false);
for(const k of ['tcp_post_up','tcp_post_down','udp_post_up','udp_post_down']){add(k+' wrong tag packet',c=>c[k+'_unexpected'].packets=1,false);add(k+' wrong tag byte',c=>c[k+'_unexpected'].bytes=1,false);add(k+' missing counter',c=>delete c[k+'_total'],false)}
add('neighbor nonzero',c=>c.udp_post_neighbor_nonzero.packets=1,false);add('second direction discrepancy',c=>c.tcp_post_down_expected.packets++,false);add('no total ACK traffic',c=>c.tcp_post_up_total={packets:0,bytes:0},false);add('negative counter',c=>c.udp_post_down_total.packets=-1,false,true);
const code="local j=require('luci.jsonc');local M=assert(loadstring([====["+prefix+"]====]))();local f=j.parse([====["+JSON.stringify(cases)+"]====]);for _,v in ipairs(f)do assert(M.mayRereadAck(v.c,v.pending)==v.pass,v.name)end;print(j.stringify({passed=true,cases=#f,nssAdmissionAllowed=false}))";
const c=await connectRouter();try{const e=encode("/usr/bin/lua - <<'NSS85_PURE_GETTER'\n"+code+"\nNSS85_PURE_GETTER\n"),raw=receipt(await c.run(e.command),e);fs.writeFileSync('work/nss85/getter-raw-private.json',JSON.stringify(raw,null,2));assert.equal(raw.code,0,raw.stderr);const p=JSON.parse(raw.stdout);p.sourceSha256=crypto.createHash('sha256').update(bytes).digest('hex');fs.writeFileSync('work/nss85/getter-qualified.json',JSON.stringify(p,null,2)+'\n');console.log(JSON.stringify(p));}finally{c.close()}
