import {verifyCandidate} from './candidate-policy.mjs';
import{validatePreStageRefinement as validateRefinement}from'./normal-refinement.mjs';
import{buildPayload}from'./payload.mjs';
import{guardianPlan}from'./guardian-plan.mjs';
import{packGuardian}from'../nss149/pack-guardian.mjs';
import {verifyDeployment} from '../nss68/deployment-binding.mjs';
import fs from'node:fs';import crypto from'node:crypto';import assert from'node:assert/strict';import zlib from'node:zlib';import{connectRouter}from'../nss16/connect-router.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');const save=(d,n,v)=>fs.writeFileSync(d+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
export async function readStage(c,ctx){
 const pid=ctx.receipt.ready.pid,dir=ctx.receipt.ready.dir;assert.ok(Number.isInteger(pid)&&pid>1);assert.match(dir,/^\/tmp\/rp-nss25-stage-[a-f0-9]{32}$/);
 const code=String.raw`local n=require('nixio');local fs=require('nixio.fs');local j=require('luci.jsonc');local function read(p,l)local f=assert(io.open(p));local s=f:read(l+1)or'';f:close();assert(#s<=l);return s end;local o={boot=read('/proc/sys/kernel/random/boot_id',128),uptime=tonumber(read('/proc/uptime',128):match('^[%d.]+')),fds={},modulePresent=fs.lstat('/sys/module/rp_ecm_gate_lab_ct')~=nil,qosModulePresent=fs.lstat('/sys/module/qca_nss_qdisc')~=nil}
if fs.lstat('/proc/${pid}/stat')then local a={};for v in assert(read('/proc/${pid}/stat',8192):match('^%d+ %b() (.*)$')):gmatch('%S+')do a[#a+1]=v end;o.identity={pid=${pid},start=a[20],ppid=tonumber(a[2]),pgrp=tonumber(a[3]),session=tonumber(a[4]),state=a[1]};for f in fs.dir('/proc/${pid}/fd')do o.fds[f]=fs.readlink('/proc/${pid}/fd/'..f)end end
local d=fs.lstat('${dir}');o.stateDirectoryPresent=fs.lstat('/root/router-project/experiments/rp-nss25-state-${ctx.plan.owner}')~=nil;o.directoryPresent=d~=nil;if d then assert(d.type=='dir'and d.uid==0 and d.gid==0 and d.modedec==700);o.directory=d;o.owner=read('${dir}/owner',256);o.file=assert(fs.lstat('${dir}/candidate.ko'));if ${ctx.plan.qosStaged?'true':'false'} then o.codeFile=assert(fs.lstat('${dir}/qos.lua'))end;local q=read('${dir}/state.json',1048576);o.record=assert(j.parse(q))end;print(j.stringify(o))`;
 const enc=encode("/usr/bin/lua - <<'NSS16_STAGE_READ'\n"+code+"\nNSS16_STAGE_READ\n");const raw=receipt(await c.run(enc.command),enc);if(raw.code!==0){fs.writeFileSync(ctx.dir+'/stage-read-failed-private.lua',code);save(ctx.dir,'stage-read-failed-raw-private',raw);}assert.equal(raw.code,0);const s=JSON.parse(raw.stdout);s.sameBoot=s.boot.trim()===ctx.plan.boot;return s;
}
export async function beginStage(input,dir,finalizeSelection){
 assert.equal(input.openFrontend,true,'Qualified open wrapper only');verifyCandidate(input);
 const {deployment,config:configuration}=verifyDeployment();assert.equal(configuration.generation,deployment.id);assert.equal(configuration.nssPublication,'classification.json');
 input=structuredClone(input);input.classifierOwner={base:deployment.base,configSha256:deployment.configHash,workerSha256:configuration.files['worker.lua']};
 // The permanent owner supplies source scope and command provenance; no second
 // observer configuration is needed in this bounded runtime plan.
 delete input.observer;
 for(const slot of['tcp','udp','tcp2']){const f=input.selected[slot];assert.equal(f.original.src,'192.168.237.207');assert.equal(f.zone,0);f.classifierKey=[f.wan,f.mark,f.protocol===6?'tcp':'udp',f.original.src,f.original.sport,f.reply.src,f.reply.dst,f.reply.sport,f.reply.dport,f.zone,f.id].join('|');}
 const source=fs.readFileSync('work/v36-sim/module-stage-guardian.lua','utf8');const phase=fs.readFileSync('work/nss69/core-guard-phase.lua','utf8');const qos=fs.readFileSync('work/v36-sim/qos-physical.lua','utf8');const classifier=fs.readFileSync('work/v36-sim/classifier.lua','utf8');const tags=fs.readFileSync('work/v36-sim/classified-tags.lua','utf8');const normalizer=fs.readFileSync('work/v36-sim/tag-normalizer.lua','utf8');const module=fs.readFileSync('work/v16-three/endpoint-gate/rp_ecm_gate_lab_ct.runtime.ko');const proof=JSON.parse(fs.readFileSync('work/v16-three/runtime-elf-comparison.json','utf8'));assert.equal(proof.passed,true);assert.equal(hash(module),proof.runtimeSha256);const qualified=JSON.parse(fs.readFileSync('work/v36-sim/normalizer-qualified.json','utf8'));assert.equal(qualified.passed,true);assert.equal(qualified.sourceSha256,hash(normalizer));assert.ok(!input.qosOnly,'NSS20 always uses verified existing-file staging');
 const build=JSON.parse(fs.readFileSync('work/v16-three/endpoint-gate/build-manifest.json','utf8'));
 assert.ok(build.sdk_original_unchanged&&build.old_gate_inputs_unchanged&&build.source_inputs_unchanged);
 const hz=JSON.parse(fs.readFileSync('work/v16-three/native-source-qualified.json','utf8'));assert.equal(hz.passed,true);assert.equal(hz.sourceSha256,build.source_hashes['rp_ecm_gate_lab_ct.c']);
 let c=await connectRouter(),ctx;
 try{
  const boot=await c.run('cat /proc/sys/kernel/random/boot_id');assert.equal(boot.code,0);const plan={...input,owner:crypto.randomBytes(16).toString('hex'),boot:boot.stdout.trim(),moduleBytes:module.length,moduleSha256:hash(module),ecmSha256:'681cf250053ba3bb7ec1fe28866862ca989bfd168ccee7386139f71e37cc68e2'};
  if(input.mode==='stage'){
   const phaseProof=JSON.parse(fs.readFileSync('work/nss69/phase-qualified.json','utf8'));assert.equal(phaseProof.passed,true);assert.equal(phaseProof.sourceSha256,hash(phase));assert.equal(phaseProof.clockTicks,100);
   const code="local fs=require('nixio.fs');local j=require('luci.jsonc');local function read(p,l)local f=assert(io.open(p));local s=f:read(l+1)or'';f:close();assert(#s<=l);return s end;local lib=assert(loadstring([=["+phase+"]=]))();local r=lib.scan(fs,read);local h=assert(io.popen('/usr/bin/sha256sum /root/router-project/scripts/core-guard.sh'));local digest=h:read('*l'):match('^(%x+) ');h:close();print(j.stringify({pid=r.guard.pid,start=r.guard.start,sha256=digest}))";
   const e=encode("/usr/bin/lua - <<'NSS16_CORE_PHASE_PREPARE'\n"+code+"\nNSS16_CORE_PHASE_PREPARE\n");const raw=receipt(await c.run(e.command),e);save(dir,'core-phase-prepare-private',raw);assert.equal(raw.code,0);plan.coreGuard=JSON.parse(raw.stdout);assert.equal(plan.coreGuard.sha256,'7d4a0360b32ab486dfb7241637e70eb78fbfe4d620ea47b9e7a0eafedfa2012f');
  }
  let{stagedCode,tagSource}=buildPayload(input,{qos,phase,classifier,tags,normalizer});
  plan.tagPlan={table:input.tagPlan.table,owner:input.tagPlan.owner,mode:input.tagPlan.mode};plan.tagPolicyInStagedBundle=true;
  if(input.qosDevice){assert.equal(input.qosStaged,true);assert.ok(['lan1','lan4'].includes(input.qosDevice));const q=JSON.parse(fs.readFileSync('work/v36-sim/qos-native-qualified.json','utf8'));assert.equal(q.passed,true);assert.equal(q.sourceSha256,hash(qos));plan.qosCodeBytes=Buffer.byteLength(stagedCode);plan.qosCodeSha256=hash(stagedCode);assert.equal(plan.qosBoot,plan.boot);assert.equal(plan.qosTc.sha256,'684795dc8c6788c692d339c60410f4e8e70b0e6490611d37147db9176a6e61d7');assert.equal(plan.qosModule.sha256,'7d9c7d0ca82f7fc927bb8948ac6996be1bf4dda14d7b1abbe16a6b0809274af5');}
  let selected=packGuardian(source);
  if(input.qosOnly){
   assert.equal(input.mode,'stage');assert.equal(input.qosDevice,'lan1');
   const create="put(DIR..'/candidate.ko','');ownFile=fcheck('candidate.ko');files['candidate.ko']=ownFile;record.moduleFileIdentity=ownFile;";assert.equal(selected.split(create).length,2);selected=selected.replace(create,()=> 'record.stageComplete=true;record.moduleCandidateNotStaged=true;');
   const p=selected.indexOf('  local stageDue='),q=selected.indexOf('  if P.qosDevice then',p);assert.ok(p>0&&q>p);selected=selected.slice(0,p)+selected.slice(q);
  }
  const guardSyntax=selected.replace('__PLAN__',()=> '{"syntaxOnly":true}').replace('__CORE_PHASE__',()=>input.mode==='deny'&&!input.qosStaged?phase:'return{}').replace('__QOS_PHYSICAL__',()=> 'return{}');
  if(input.qosDevice){for(const [name,text] of [['guardian',guardSyntax],['qos',qos],['classifier',classifier],['tags',tags],['normalizer',normalizer],['tag-policy',tagSource],['phase',phase],['fast-path',fs.readFileSync('work/v36-sim/fast-path.lua','utf8')],['wan-scope',fs.readFileSync('work/v36-sim/wan-scope.lua','utf8')],['state-node',fs.readFileSync('work/nss49/state-node.lua','utf8')]]){assert.ok(!text.includes(']===]'),'Compiler wrapper delimiter collision');let syntax;try{syntax=encode("/usr/bin/lua - <<'NSS16_COMPILE_ONLY'\nlocal s=[===["+text+"]===];assert(loadstring(s));print('SYNTAX_ONLY_PASS')\nNSS16_COMPILE_ONLY\n");}catch(error){assert.equal(name,"classifier","Only the redundant classifier syntax copy may be deferred");assert.equal(String(error),"Error: Transport length refused");assert.equal(input.qosStaged,true);assert.ok(plan.qosCodeBytes>0&&plan.qosCodeBytes<=73728);save(dir,"classifier-syntax-deferred",{sourceSha256:hash(text),reason:String(error),exactGuardedBundleCompilationRequired:true,standaloneCompileDeferred:true,transportLimitUnchanged:true,payloadSha256:plan.qosCodeSha256,payloadBytes:plan.qosCodeBytes});continue;}const check=receipt(await c.run(syntax.command),syntax);save(dir,name+'-syntax-private',check);assert.equal(check.code,0);assert.equal(check.stdout.trim(),'SYNTAX_ONLY_PASS');}}
  const status=await c.run('sh /root/router-project/scripts/transaction.sh status');assert.equal(status.code,0);assert.equal(status.stdout.trim(),'NO_ACTIVE_TRANSACTION');
  const cp=await c.run('sh /root/router-project/scripts/checkpoint.sh before-nss20-module-'+input.mode);save(dir,'stage-checkpoint-private',cp);assert.equal(cp.code,0);const name=cp.stdout.match(/CHECKPOINT=([A-Za-z0-9-]+)/)?.[1];assert.ok(name);const path='/root/router-project/backups/'+name+'/config.tar.gz';const remote=await c.run('sha256sum '+path);assert.equal(remote.code,0);const local=dir+'/stage-checkpoint-config-private.tar.gz';await c.download(path,local);const bytes=fs.readFileSync(local);assert.equal(hash(bytes),remote.stdout.split(/\s/)[0]);zlib.gunzipSync(bytes);save(dir,'stage-checkpoint-verified',{name,sha256:hash(bytes),gzipVerified:true});
  if(finalizeSelection){
   assert.equal(typeof finalizeSelection,'function');
   const refined=validateRefinement(input,await finalizeSelection(structuredClone(input)));
   verifyCandidate(refined);input=refined;
   for(const slot of ['tcp','udp','tcp2']){const f=input.selected[slot];assert.equal(f.original.src,'192.168.237.207');assert.equal(f.zone,0);f.classifierKey=[f.wan,f.mark,f.protocol===6?'tcp':'udp',f.original.src,f.original.sport,f.reply.src,f.reply.dst,f.reply.sport,f.reply.dport,f.zone,f.id].join('|');}
   for(const key of ['selected','frozenHash','insmodArguments'])plan[key]=structuredClone(input[key]);
   ({stagedCode,tagSource}=buildPayload(input,{qos,phase,classifier,tags,normalizer}));
   plan.tagPlan={table:input.tagPlan.table,owner:input.tagPlan.owner,mode:input.tagPlan.mode};
   plan.qosCodeBytes=Buffer.byteLength(stagedCode);plan.qosCodeSha256=hash(stagedCode);
   assert.ok(plan.qosCodeBytes>0&&plan.qosCodeBytes<=73728);
   save(dir,'post-checkpoint-selection-receipt',{passed:true,observedAt:new Date().toISOString(),selectionBeforeDetachedStage:true,originalGameIdentityRetained:true,twoWanAndTwoFlowScopeRetained:true,guardedBundleCompilationStillRequired:true});
  }
  const rendered=selected.replace('__PLAN__',()=>JSON.stringify(guardianPlan(plan))).replace('__CORE_PHASE__',()=>input.mode==='deny'&&!input.qosStaged?phase:'return{}').replace('__QOS_PHYSICAL__',()=> 'return{}');fs.writeFileSync(dir+'/stage-rendered-private.lua',rendered);save(dir,'stage-plan-before-encode-private',{...plan,guardianSourceSha256:hash(source),selectedGuardianSha256:hash(selected),oneEpochControlledPair:true,phaseSourceSha256:hash(phase),qosSourceSha256:hash(qos)});let enc;try{enc=encode("/usr/bin/lua - <<'NSS20_STAGE_BEGIN'\n"+rendered+"\nNSS20_STAGE_BEGIN\n");}catch(error){save(dir,'stage-transport-refused',{error:String(error),rawBytes:Buffer.byteLength(rendered),sourceSha256:hash(rendered),detachedGuardianStarted:false,queueWrites:false});throw error;}save(dir,'stage-plan-private',{...plan,guardianSourceSha256:hash(source),selectedGuardianSha256:hash(selected),oneEpochControlledPair:true,phaseSourceSha256:hash(phase),qosSourceSha256:hash(qos),execBytes:enc.execBytes});
  const planJson=JSON.stringify(plan);assert.ok(!planJson.includes(']=]'),'Guardian data delimiter collision');
  const raw=receipt(await c.run(enc.command),enc);save(dir,'stage-guardian-raw-private',raw);assert.equal(raw.code,0);const r=JSON.parse(raw.stdout);save(dir,'stage-receipt-private',r);assert.equal(r.success,true,r.error);assert.equal(r.rollbackBeforeFirstWrite,true);assert.equal(r.parentIdentityVerified,true);assert.equal(r.pipeInodesVerified,true);ctx={plan,receipt:r,dir,module,qosCode:Buffer.from(stagedCode)};
 }finally{c.close()}
 c=await connectRouter();try{const s=await readStage(c,ctx);save(dir,'stage-detached-private',s);assert.ok(s.sameBoot&&s.directoryPresent);assert.equal(s.identity.ppid,1);assert.equal(s.identity.start,ctx.receipt.ready.stat.start);assert.equal(s.identity.pgrp,s.identity.pid);assert.equal(s.identity.session,s.identity.pid);if(input.qosOnly){for(const fd of ['0','1','2'])assert.equal(s.fds[fd],'/dev/null');}else assert.deepEqual(s.fds,{'0':'/dev/null','1':'/dev/null','2':'/dev/null'});assert.equal(s.modulePresent,false);if(!input.qosOnly){assert.equal(s.file.size,0);assert.equal(s.file.ino,ctx.receipt.moduleFileIdentity.ino);}}finally{c.close()}
 return ctx;
}
export async function stageChunk(c,ctx,offset,data,role='module'){
 assert.ok(!ctx.plan.qosOnly,'Idle queue lifecycle has no candidate upload');
 assert.ok(role==='module'||role==='qos');assert.ok(role!=='qos'||ctx.plan.qosStaged);const expectedBytes=role==='module'?ctx.plan.moduleBytes:ctx.plan.qosCodeBytes;assert.ok(Buffer.isBuffer(data)&&data.length<=3072&&offset>=0&&offset+data.length<=expectedBytes);const r=ctx.receipt.ready,identity=role==='module'?ctx.receipt.moduleFileIdentity:ctx.receipt.qosFileIdentity;
 const p={dir:r.dir,owner:ctx.plan.owner,boot:ctx.plan.boot,deadline:r.deadline,pid:r.pid,start:r.stat.start,fileDev:identity.dev,fileIno:identity.ino,offset,bytes:data.length,moduleBytes:expectedBytes,filename:role==='module'?'candidate.ko':'qos.lua'};
 const code=String.raw`local n=require('nixio');local fs=require('nixio.fs');local j=require('luci.jsonc');local p=assert(j.parse([=[${JSON.stringify(p)}]=]));local data=assert(n.bin.b64decode([=[${data.toString('base64')}]=]));assert(#data==p.bytes);local function read(q)local f=assert(io.open(q));local s=f:read('*a');f:close();return s end;local function now()return assert(tonumber(read('/proc/uptime'):match('^[%d.]+')))end
assert(p.dir:match('^/tmp/rp%-nss25%-stage%-[a-f0-9]+$'));assert(p.filename=='candidate.ko'or p.filename=='qos.lua');assert(read('/proc/sys/kernel/random/boot_id'):gsub('%s+$','')==p.boot);local a={};for v in assert(read('/proc/'..p.pid..'/stat'):match('^%d+ %b() (.*)$')):gmatch('%S+')do a[#a+1]=v end;assert(a[1]~='Z'and a[20]==p.start and tonumber(a[2])==1 and tonumber(a[3])==p.pid and tonumber(a[4])==p.pid);assert(now()<p.deadline-13)
local d=assert(fs.lstat(p.dir));assert(d.type=='dir'and d.uid==0 and d.gid==0 and d.modedec==700);assert(read(p.dir..'/owner')==p.owner..' '..p.boot..' '..p.deadline..'\n');local path=p.dir..'/'..p.filename;local a=assert(fs.lstat(path));local f=assert(n.open(path,'r+'));local b=assert(f:stat());for _,k in ipairs({'dev','ino','type','nlink','uid','gid','modedec','size'})do assert(a[k]==b[k])end;assert(b.dev==p.fileDev and b.ino==p.fileIno and b.type=='reg'and b.nlink==1 and b.uid==0 and b.gid==0 and b.modedec==600 and b.size==p.offset);assert(f:seek(p.offset,'set')==p.offset)
local at=1;while at<=#data do assert(now()<p.deadline-13);local size=assert(f:write(data:sub(at,at+255)));assert(size>0);at=at+size end;local terminal=assert(f:stat());assert(terminal.size==p.offset+p.bytes);assert(f:close());print(j.stringify({written=p.bytes,offset=p.offset,existingFdOnly=true,noCreateOrMkdir=true}))`;
 const enc=encode("/usr/bin/lua - <<'NSS20_EXISTING_FD_STAGE'\n"+code+"\nNSS20_EXISTING_FD_STAGE\n");const raw=receipt(await c.run(enc.command),enc);save(ctx.dir,'chunk-'+role+'-'+offset+'-private',raw);assert.equal(raw.code,0);return JSON.parse(raw.stdout);
}
export async function uploadStage(ctx){
 const c=await connectRouter();try{for(let at=0;at<ctx.module.length;at+=3072)await stageChunk(c,ctx,at,ctx.module.subarray(at,at+3072));if(ctx.plan.qosStaged){for(let at=0;at<ctx.qosCode.length;at+=3072)await stageChunk(c,ctx,at,ctx.qosCode.subarray(at,at+3072),'qos')}const s=await readStage(c,ctx);save(ctx.dir,'stage-uploaded-private',s);assert.equal(s.file.size,ctx.plan.moduleBytes);if(ctx.plan.qosStaged)assert.equal(s.codeFile.size,ctx.plan.qosCodeBytes);return s;}finally{c.close()}
}
export async function waitStageUndo(ctx){
 let i=0;const due=performance.now()+60000;
 while(performance.now()<due){const c=await connectRouter();let s;try{s=await readStage(c,ctx)}finally{c.close()};save(ctx.dir,'stage-state-'+(i++)+'-private',s);assert.ok(s.sameBoot);if(s.record)save(ctx.dir,'stage-latest-record-private',s.record);
  const ended=!s.identity||s.identity.start!==ctx.receipt.ready.stat.start||s.identity.state==='Z';if(!s.directoryPresent&&!s.stateDirectoryPresent&&!s.modulePresent&&(!ctx.plan.qosDevice||!s.qosModulePresent)&&ended){const r={sameBoot:true,ownDirectoryAbsent:true,stateNodeDirectoryAbsent:true,guardianTerminated:true,moduleAbsent:true,...(ctx.plan.qosDevice?{qosModuleAbsent:true}:{})};save(ctx.dir,'stage-undo-verified',r);return r}await new Promise(r=>setTimeout(r,2200));
 }throw Error('Stage/module independent cleanup not verified');
}
