// Bind local entry changes to unchanged NSS39 runtime proof and actual new tests.
import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {verifyPreparation as runtime} from '../nss39/qualification.mjs';
const root='work/nss41',hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),read=n=>JSON.parse(fs.readFileSync(root+'/'+n));
const q=runtime(),old=read('local-entry-v3-qualified.json'),planner=read('publication-wait-qualified.json'),archive=read('preaudit-archive-qualified.json');
assert.ok(q.passed&&planner.passed&&archive.passed);assert.equal(planner.checks,15);assert.equal(archive.checks,3);assert.equal(planner.plannerSha256,hash(root+'/publication-wait.lua'));assert.equal(archive.controllerSha256,hash(root+'/real-session.mjs'));
const sourceManifest={};for(const file of [...Object.keys(old.sourceManifest),...['test-publication-wait.py','test-preaudit-archive.mjs','qualify-entry.mjs'].map(n=>root+'/'+n)])sourceManifest[file]=hash(file);
const nativeFiles=['aligned-final-1','aligned-final-2','aligned-closing'];const native=nativeFiles.filter(label=>fs.existsSync(root+'/'+label+'-audit.json')).map(label=>({label,audit:read(label+'-audit.json'),alignment:read(label+'-alignment-private.json')}));
for(const {audit,alignment} of native){assert.ok(audit.passed&&alignment.passed&&audit.ecmClosedAndZero&&audit.protectedConfigurationUnchanged);assert.equal(alignment.plannerSha256,planner.plannerSha256);assert.equal(alignment.wrapperSha256,hash(root+'/wait-full-publication.mjs'));assert.equal(alignment.lockHeld,false);assert.equal(alignment.nssAdmissionAllowed,false);}
const out={...old,preparedAt:new Date().toISOString(),version:4,sourceManifest,localManifestItems:Object.keys(sourceManifest).length,totalManifestItems:Object.keys({...q.sourceManifest,...sourceManifest}).length,newLocalSafetyChecks:18,newNativeAlignedAudits:native.length,nativeSchedulingQualifiedLightLoad:native.length>=2,schedulingDeadlineSeconds:5,schedulingOuterDeadlineSeconds:6,lockedAuditDeadlineSeconds:6,schedulingOnlyNotNssAdmission:true,nssAdmissionDeadlinesUnchanged:true,actualNssHighLoadQualified:false,permanentClassifierChanged:false,liveWrites:false,derivationNotes:'Derivation entries describe initial v1; current sourceManifest binds final v4 changes. v1/v2/v3 and rejected wrapper arguments are preserved separately.'};
fs.writeFileSync(root+'/local-entry-qualified.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({passed:true,version:4,localBound:Object.keys(sourceManifest).length,totalBound:out.totalManifestItems,newLocalSafetyChecks:18,newNativeAlignedAudits:native.length,routerWrites:false}));
