import fs from 'node:fs';
const s=JSON.parse(fs.readFileSync('outputs/nss41-mainline-observations.json')),l=s.limitedLoad,p=l.performance,f=(v,n=2)=>Number(v).toFixed(n),a=s.schedulingQualification.alignedReadonlyAudits;
const css=fs.readFileSync('outputs/nss39-mainline-report.html','utf8').match(/<style>([\s\S]*?)<\/style>/)[1];
fs.writeFileSync('outputs/nss41-mainline-report.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSS41 · 写前审核与证据封存准备</title><style>${css}</style><main>
<p class="muted">Athena AX6600 · 2026-10-04 凌晨 · 时间为北京时间</p><h1>写前入口已补齐取证与调度<br>真人 NSS 闭环仍待验证</h1>
<p class="note">常驻 NSS39 未修改。新入口先封存当次应用、选中连接和源码，保存审核阶段与年龄，再在<strong>锁外等待下一份新完整快照</strong>。${s.localChecks.newIndependentCases} 项新边界案例和 ${a.length} 次最终版本现场只读审核通过，绑定 ${s.entry.totalBoundFiles} 项输入。尚无本轮真实 NSS flow、bulk/RT leaf 或游戏体验结论。</p>
<h2>本轮改了什么</h2><p>接入 NSS40 已验证的阶段诊断与按次应用证据封存；实际入口在第一次审核之前冻结 selected pair、当次 socket/CT 原始响应及源码清单。审核拒绝时也保留证据。常驻 worker、自动分类策略、PBR、NAT 与 NSS mutation payload 均未修改。</p>
<p>新增只读调度候选：在任何锁、checkpoint 或实验暂存之前，最多等 5 秒出现严格更新的 full snapshot 序列，来源年龄必须小于 2 秒。随后仍执行全部原始持锁审核，来源年龄 &lt;6 秒、发布年龄 &lt;9 秒，外层截止 6 秒。调度通过<strong>不能授权 NSS</strong>；后续 initial &lt;1 秒、pre-learning &lt;2 秒及 45 秒独立恢复原样保留。</p>
<h2>有限 TCP 负载实际观察</h2><p>00:28–00:29，8 条普通 HTTPS TCP 下载，数据丢弃到本机空设备。使用 <a href="${l.officialSource}">Cloudflare 官方测速下载接口</a>，单请求 64 MiB / 25 秒期限，合计上限 512 MiB；没有执行在线下载脚本，没有启动 Steam 或模拟 CS2。实际收到 ${f(l.bytesDownloaded/1024/1024,1)} MiB，1 条完成，7 条到期退出，全部子进程结束。请求到期不是网络丢包指标。</p>
<div class="scroll"><table><thead><tr><th>测量</th><th>整个 ${f(p.seconds)} 秒窗口</th><th>最高约 3 秒窗口</th></tr></thead><tbody><tr><td>LAN4 下行 / pps</td><td>${f(p.lan4DownMbps)} Mbps / ${f(p.lan4DownPps,0)}</td><td>${f(l.peakThreeSecondWindow.lan4DownMbps)} Mbps / ${f(l.peakThreeSecondWindow.lan4DownPps,0)}</td></tr><tr><td>CPU busy / softirq</td><td>${f(p.cpuBusyPercent)}% / ${f(p.softirqPercent)}%</td><td>${f(l.peakThreeSecondWindow.cpuBusyPercent)}% / ${f(l.peakThreeSecondWindow.softirqPercent)}%</td></tr><tr><td>time_squeeze</td><td>+${p.timeSqueezeDelta}</td><td>+${l.peakThreeSecondWindow.timeSqueezeDelta}</td></tr></tbody></table></div>
<p>${l.frames} 帧观察中完整快照来源年龄最高 ${f(l.fullMaxSourceAgeSeconds)} 秒，没有达到 6 秒。3 次原完整审核通过，锁内 0.29–0.43 秒。观察程序自身消耗 ${f(l.observerCpuSeconds,3)} CPU 秒，审核也有额外开销，均包含在整机测量内。该负载低于 NSS40 真人约 323 Mbps，流分布也不同，<strong>未复现旧失败，也未证明旧失败已修复</strong>。上述检查使用接入诊断后的 v1，发生在新增锁外调度之前。</p>
<h2>最终调度版本的验证</h2><div class="scroll"><table><thead><tr><th>现场只读审核</th><th>锁外等待</th><th>锁内审核</th><th>审核来源年龄</th></tr></thead><tbody>${a.map((v,i)=>`<tr><td>${i+1}</td><td>${f(v.waitSeconds)} 秒</td><td>${f(v.lockedSeconds)} 秒</td><td>${f(v.queryAge)} 秒</td></tr>`).join('')}</tbody></table></div>
<p>均为轻负载，保持同一常驻实例，严格选择新序列且没有持锁等待。15 个 Lua 5.1 调度边界案例覆盖超时、旧序列、序列倒退、进程变化、未来时间、健康状态与读错误；3 个实际控制器顺序案例以替换 IO 验证审核失败前完整封存、损坏应用证据拒绝、无连接对不开始。后者使用虚构身份与强制审核失败，没有连接路由器，不算硬件准入或真人测试。</p>
<h2>失败与修正记录</h2><p>第一次新调度调用请求外层 12 秒，被既有 group-runner 的 1–6 秒参数范围拒绝，退出码 2。Lua 没有运行，生产未写。定位参数验证后改为内部 5 秒 / 外层 6 秒，保留了拒绝响应和原版本源码。最初封存测试误把同前缀诊断文件当目录，修正测试目录筛选后通过，控制器没有因此改动。v1/v2/v3 证据与 NSS40 的 72 份历史文件仍保留。</p>
<h2>结束状态与结论边界</h2><p>保护配置、认证/PBR/服务与自有规则审核通过，NSS39 同一实例和守护健康，旧错误仍属以前试装到期。ECM 全零，无实验事务、gate/qdisc、暂存或状态节点。没有实验配置写入，回滚不适用；有限下载依靠自身期限结束。当前没有游戏和下载候选。</p>
<ul><li>支持：新的取证缺口已补齐；锁外等新快照的调度边界在本地案例及轻载现场成立。</li><li>未知：NSS40 高负载过期的具体根因、新入口在真人高负载下能否稳定通过、bulk/RT NSS leaf 与 WAN affinity 是否在该负载同时成立。</li><li>未测：本轮 NSS CPU 收益、CAKE tin 对照、游戏 jitter/loss/Miss。不得用普通下载或历史低负载 NSS 证明替代。</li></ul>
<h2>下一步</h2><p>准备已收敛到一次真实单 WAN CS2＋Steam software→NSS→software。只在当次应用与实例完整匹配、全部新鲜度检查通过后创建 checkpoint，核验独立自动恢复，再开放两条受控 flow。受控子组上限仍是 20 Mbps，不代表整个 Steam 300 Mbps 已加速。若再拒绝，按已封存身份和阶段年龄定位；闭环通过前不扩第二 WAN、共享预算、Wi-Fi 或 autorate。</p>
<p><a href="nss41-mainline-observations.json">结构化证据</a> · <a href="nss40-mainline-report.html">上一轮真实失败</a> · <a href="https://github.com/ZyPulse-zy/athena-nss-mainline">私有仓库</a></p></main></html>`);
console.log(JSON.stringify({report:'outputs/nss41-mainline-report.html',realHighLoadNssCompleted:false}));
