// Preserve original failure; distinguish native completion from host validation.
import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const root='work/nss41',dir=root+'/real-matched-aba-20261003165708-9086b676',read=p=>JSON.parse(fs.readFileSync(p)),r=read(dir+'/last-record-private.json'),selected=read(dir+'/selected-private.json'),proof=read(dir+'/actual-accelerated-state-revalidated.json'),failed=read(dir+'/result.json');
const s=read('outputs/nss41-mainline-observations.json'),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
assert.ok(!failed.passed&&r.abaCompleted&&r.fastPathMeasurement.qualified&&proof.passed);
const cpu=x=>x.cpu.trim().split(/\s+/).slice(1,9).map(Number),squeeze=x=>x.softnet.trim().split('\n').reduce((n,l)=>n+parseInt(l.trim().split(/\s+/)[2],16),0),closure=read(root+'/final-closure.json');
const atBeijing=uptime=>new Date(Date.parse(closure.observedAt)-(closure.uptime-uptime)*1000+8*3600000).toISOString().replace('T',' ').replace('Z',' CST');
const phases=r.phases.map(p=>{const rows=r.samples.slice(p.sampleStart-1,p.sampleEnd),a=rows[0],b=rows.at(-1),x=cpu(a),y=cpu(b),d=y.map((v,i)=>v-x[i]),t=d.reduce((n,v)=>n+v,0),sec=b.uptime-a.uptime;assert.equal(rows.length,11);assert.ok(rows.every(v=>v.counts['ecm_nss_ipv4/accelerated_count']===(p.name==='B'?2:0)));return{name:p.name,seconds:sec,samples:rows.length,startedBeijingApprox:atBeijing(a.uptime),endedBeijingApprox:atBeijing(b.uptime),lan4DownMbps:(b.interfaces.lan4.tx_bytes-a.interfaces.lan4.tx_bytes)*8/sec/1e6,lan4DownPps:(b.interfaces.lan4.tx_packets-a.interfaces.lan4.tx_packets)/sec,wan1DownMbps:(b.interfaces.rpwan1.rx_bytes-a.interfaces.rpwan1.rx_bytes)*8/sec/1e6,cpuBusyPercent:100*(t-d[3]-d[4])/t,softirqPercent:100*d[6]/t,timeSqueezeDelta:squeeze(b)-squeeze(a),acceleratedCount:p.name==='B'?2:0,pendingAccelCountZero:rows.every(v=>v.counts['ecm_nss_ipv4/pending_accel_count']===0),minimumQueryAge:Math.min(...rows.map(v=>v.observation.queryAge)),maximumQueryAge:Math.max(...rows.map(v=>v.observation.queryAge))};});
const queues=snap=>{const out={};for(const block of snap.qdisc.split(/(?=qdisc )/)){const header=block.match(/^qdisc (\S+) (\S+):/),counters=block.match(/Sent (\d+) bytes (\d+) pkt \(dropped (\d+), overlimits (\d+) requeues (\d+)\)/);if(header&&counters)out[header[2]]={kind:header[1],bytes:Number(counters[1]),packets:Number(counters[2]),dropped:Number(counters[3]),overlimits:Number(counters[4])};}return out;};
const from=queues(r.qosAccelerated),to=queues(r.qosAfterRetirement),deltaSeconds=r.qosAfterRetirement.uptime-r.qosAccelerated.uptime,leaves={};
for(const [name,handle] of [['bulk','8f05'],['rt','8f06'],['fallback','8fff']]){leaves[name]={kind:from[handle].kind,handle,windowSeconds:deltaSeconds,bytes:to[handle].bytes-from[handle].bytes,packets:to[handle].packets-from[handle].packets,dropped:to[handle].dropped-from[handle].dropped,mbps:(to[handle].bytes-from[handle].bytes)*8/deltaSeconds/1e6};assert.ok(leaves[name].packets>0);}
const restoredKeys=['firmwareZeroAfterRetirement','tagsRemoved','qosRestored','qosModuleUnloaded','wanRestored','mwan3Restored','stateNodeRemoved','moduleUnloaded'];assert.ok(restoredKeys.every(k=>r[k]===true));
const baseline=read(dir+'/baseline-audit-recovered.json'),audit=read(root+'/recovered-final-audit.json'),before=read(root+'/'+dir.split('/').at(-1)+'-before-audit.json'),afterWait=read(root+'/'+dir.split('/').at(-1)+'-after-alignment-private.json'),post=read(root+'/classifier-posttrial-inspection.json');assert.ok(audit.passed&&closure.passed&&baseline.configurationMatches&&baseline.checks.ecmStoppedAndZero);
const nativeProof={passed:true,realCs2SteamPair:true,wan:1,fullTcpMark:selected.tcp.mark,fullUdpMark:selected.udp.mark,sameNat:selected.tcp.reply.dst===selected.udp.reply.dst,zoneZero:selected.tcp.zone===0&&selected.udp.zone===0,ctInstanceAndTuplePinned:true,packetTagsEstablishedBeforeLearning:true,downBulkTag:proof.proof.tcp.downTag,downRtTag:proof.proof.udp.downTag,nativeFullStateRevalidated:true,actualAcceleratedFlows:2,minimumStableSeconds:5,observedStableSeconds:r.fastPathMeasurement.stableSeconds,nativeRenewals:r.renewals.length,sourceSequences:r.renewals.map(v=>v.sequence),sameQueuePlanAcrossPhases:r.unchangedQoSPlan,phases,leafCounters:leaves,leafCounterWindowIncludesRetirement:true,selectedSubgroupCeilingMbps:20,unselectedFallbackCeilingMbps:950,allSteamFlowsAccelerated:false,nssUploadRtQosProved:false};
fs.writeFileSync(dir+'/functional-runtime-proof-revalidated.json',JSON.stringify(nativeProof,null,2)+'\n');
const validationFiles=['work/nss25/parse-ecm.mjs',...['validate-actual-state.mjs','parse-ecm-any-wan.mjs','prepare-posttrial-audit.mjs','posttrial-protected-audit.mjs','summarize-live.mjs'].map(n=>root+'/'+n)];const validationManifest=Object.fromEntries(validationFiles.map(f=>[f,hash(f)]));fs.writeFileSync(dir+'/posttrial-validation-source-manifest.json',JSON.stringify(validationManifest,null,2)+'\n');for(const [file,h] of Object.entries(validationManifest)){const dst=dir+'/posttrial-validation-frozen/'+file;fs.mkdirSync(dst.slice(0,dst.lastIndexOf('/')),{recursive:true});fs.copyFileSync(file,dst);assert.equal(hash(dst),h);}
s.routerConfigurationWrites=true;
s.actualTrial={attempted:true,attemptDirectory:dir,originalControllerTerminalPassed:false,originalControllerErrors:['WAN affinity absent: legacy report parser hardcoded WAN5','Recovery alignment: no newer full publication meeting <2 s scheduling hint within fixed deadline'],originalFailurePreserved:true,preauditPassed:before.passed,preauditSourceAge:before.queryAge,preauditEvidenceAndSourcesFrozen:true,boundFilesFrozen:83,legacyPostparserIncludedInPreauditManifest:false,checkpointCreatedAndVerified:true,independentOwnerVerifiedBeforeChanges:true,independentOwnerDeadlineSeconds:45,singleWan:1,temporaryPrivateWan:true,physicalLan4NssTree:true,controlledTcpFlows:1,controlledGameUdpFlows:1,nativeExperiment:{...nativeProof},originalTerminalMatchedABACompleted:false,nativePhasesExecuted:true,nativeFunctionalPathRevalidated:true,gateLoaded:true,ecmOpened:true,retirementExplicitAndEarly:true,automaticExpiryNotExercisedThisTrial:true,cleanup:Object.fromEntries(restoredKeys.map(k=>[k,r[k]])),wanHealthAfterUndo:r.wanHealthAfterUndo,baselineAuditRecovered:baseline,originalPostalignmentFailurePreserved:true,recoveryAuditUsedOriginalLockedFreshnessPredicates:true,recoveryAuditCannotAuthorizeNss:true,parserCorrection:rereadParser(),cakeTinPerPhase:null,gameQuality:{numericTelemetryCaptured:false,userFeedback:'没注意到，无法比较',initialExperienceQuestionTimeConversionOffsetSecondsApprox:10,correctedWindowReported:true,causalConclusion:false},sameOfferedLoadVerified:false,cpuBenefitProved:false,rollbackResult:'Native owner completed explicit early retirement and full restore; subsequent original-predicate protected audit and zero-state closure passed. The independent 45 s expiry was armed beforehand but did not fire in this successful native epoch.'};
function rereadParser(){const p=read(root+'/actual-state-parser-qualified.json');return{...p,originalParserWasNotIn83BoundInputs:true,posttrialValidationSourcesNowFrozen:true,controllerFrozenUnchanged:true};}
s.finalState={checkedAt:post.observedAt,protectedAudit:Object.fromEntries(['passed','protectedConfigurationUnchanged','exactOwnedNativeAudit','selectors','queryAge','sequence','ecmClosedAndZero'].map(k=>[k,audit[k]])),sameProducerSinceOpening:post.files['classification.json'].producer===read(root+'/classifier-opening-inspection.json').files['classification.json'].producer,currentWorkerHealthy:post.files['classification.json'].status==='running'&&post.files['classification.json'].dataHealthy&&post.files['guardian.json'].healthy,lastErrorBelongsToPreviousTrial:post.files['last-error.json'].producer!==post.files['classification.json'].producer,closure,application:read(root+'/real-reader-qualified.json')};
s.conclusions={...s.conclusions,realSingleWanCs2SteamFunctionalPathProved:true,actualNssFastPathEnteredUnderHighAggregateDownload:true,realForwardingPhasesExecuted:true,bulkRtLeafAndAffinityProvedThisRound:true,realHighLoadNssLoopCompleted:false,nssCpuBenefitProvedThisRound:false,cs2QualityImprovementProved:false,entrySchedulingReliabilityProved:false,recoveryOnlyWaitWasOverstrictForClosure:true,completeDependencyClosureBound:false,secondWanExpansionAllowed:false};
s.next='In a new round, bind the generic WAN parser and audit its postprocessing dependencies; use original full audit for recovery, while retaining prewrite/new-flow scheduling and all native TTLs. Then stabilize offered load and single-WAN controlled share before another concentrated CPU/game comparison. No second WAN.';
s.generatedAt=new Date().toISOString();fs.writeFileSync('outputs/nss41-mainline-observations.json',JSON.stringify(s,null,2)+'\n');
console.log(JSON.stringify({nativeFunctionalPathProved:true,realWan:1,accelerated:2,bulkLeafPackets:leaves.bulk.packets,rtLeafPackets:leaves.rt.packets,phases:phases.map(p=>({phase:p.name,mbps:p.lan4DownMbps,softirq:p.softirqPercent,busy:p.cpuBusyPercent,timeSqueeze:p.timeSqueezeDelta})),originalFailurePreserved:true,finalRecoveredAuditPassed:true,cpuBenefitProved:false,gameQualityCaptured:false}));
