import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {verifyPreparation} from './session-binding.mjs';
const root='work/nss41',read=p=>JSON.parse(fs.readFileSync(p)),r=n=>read(root+'/'+n+'.json'),q=verifyPreparation(),qualified=r('local-entry-qualified');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const d=r('audit-load-latest'),load=read(d.output+'/publication-private.json'),download=read(d.output+'/download-result-private.json');
const metric=(a,b)=>{const parse=s=>s.trim().split(/\s+/).slice(1,9).map(Number),aa=parse(a.cpu),bb=parse(b.cpu),diff=bb.map((v,i)=>v-aa[i]),total=diff.reduce((x,y)=>x+y,0),seconds=b.uptime-a.uptime;const squeeze=s=>s.trim().split('\n').reduce((sum,line)=>sum+parseInt(line.trim().split(/\s+/)[2],16),0);assert.ok(seconds>0&&total>0);return{seconds,lan4DownMbps:(b.txBytes-a.txBytes)*8/seconds/1e6,lan4DownPps:(b.txPackets-a.txPackets)/seconds,cpuBusyPercent:100*(total-diff[3]-diff[4])/total,softirqPercent:100*diff[6]/total,timeSqueezeDelta:squeeze(b.softnet)-squeeze(a.softnet)};};
const performance=metric(load.telemetry[0],load.telemetry.at(-1)),windows=[];
for(let i=0;i<load.frames.length;i++)for(let k=i+1;k<load.frames.length;k++){const sec=load.frames[k].at-load.frames[i].at;if(sec>3.5)break;if(sec>=3)windows.push({startAtSeconds:load.frames[i].at-load.frames[0].at,...metric(load.frames[i].telemetry,load.frames[k].telemetry)});}
windows.sort((a,b)=>b.lan4DownMbps-a.lan4DownMbps);const peak=windows[0];
const audited=label=>{const a=r(label+'-audit'),e=r(label+'-diagnostic-audit-private');return{label,passed:a.passed,queryAge:a.queryAge,sequence:a.sequence,selectors:a.selectors,ecmClosedAndZero:a.ecmClosedAndZero,lockedSeconds:e.diagnostic.events.at(-1).at-e.diagnostic.events[0].at,freshness:e.diagnostic.freshness,originalAssertionsRetained:e.originalAssertionsRetained};};
const loadAudits=[1,2,3].map(i=>audited(d.output.split('/').at(-1)+'-'+i));
const labels=['aligned-final-1','aligned-final-2','aligned-closing'].filter(label=>fs.existsSync(root+'/'+label+'-audit.json'));
const aligned=labels.map(label=>{const out=r(label+'-alignment-private'),a=out.alignment;return{...audited(label),waitSeconds:a.finishedAt-a.startedAt,initialSequence:a.initialSequence,selectedSequence:a.selectedSequence,alignmentSourceAge:a.sourceAge,alignmentPublicationAge:a.publicationAge,lockHeld:out.lockHeld,nssAdmissionAllowed:out.nssAdmissionAllowed,snapshotExpiryExtended:a.snapshotExpiryExtended,plannerSha256:out.plannerSha256,wrapperSha256:out.wrapperSha256};});
const first=r('classifier-opening-inspection'),last=r('classifier-closing-inspection'),live=last.files['classification.json'],audit=r('aligned-closing-audit');
assert.equal(qualified.totalManifestItems,83);assert.ok(aligned.length===3&&aligned.every(a=>a.passed&&!a.lockHeld&&!a.nssAdmissionAllowed&&!a.snapshotExpiryExtended));assert.equal(hash(root+'/publication-wait.lua'),r('publication-wait-qualified').plannerSha256);
const summary={round:'NSS41',generatedAt:new Date().toISOString(),deploymentReference:'work/nss39/deployment-latest.json',classifierConfigSha256:live.configSha256,permanentClassifierChanged:false,routerConfigurationWrites:false,
 entry:{localEntryVersion:qualified.version,runtimeBoundFiles:68,localBoundFiles:qualified.localManifestItems,totalBoundFiles:qualified.totalManifestItems,runtimeRouterPayloadsUnchanged:true,diagnosticAuditIntegrated:true,originalLockedAuditAssertionsRetained:true,immutableApplicationArchiveIntegrated:true,selectedPairAndSourceFreezeBeforeAudit:true,schedulingWaitOutsideLock:true,requiresStrictlyNewFullPublication:true,schedulingHintSourceAgeSeconds:2,schedulingDeadlineSeconds:5,schedulingOuterDeadlineSeconds:6,lockedAuditDeadlineSeconds:6,lockedSourceAgeLimitSeconds:6,lockedPublicationAgeLimitSeconds:9,nssInitialAgeLimitSeconds:1,nssPrelearningAgeLimitSeconds:2,nssOwnerDeadlineSeconds:45,deadlinesNotExtended:true,schedulingCannotAuthorizeNss:true},
 localChecks:{planner:r('publication-wait-qualified'),preauditArchive:Object.fromEntries(Object.entries(r('preaudit-archive-qualified')).filter(([k])=>k!=='fixtureDirectory')),newIndependentCases:18,nativeIoMockedForLocalCases:true},
 limitedLoad:{purpose:'Observe full/compact publication ages and original full audit during bounded ordinary TCP download; no Steam or game simulation',officialSource:'https://github.com/cloudflare/speedtest/blob/main/README.md',connections:8,aggregateByteCeiling:536870912,eachRequestDeadlineSeconds:25,bytesDownloaded:download.rows.reduce((n,x)=>n+x.metrics.size_download,0),downloadSeconds:download.seconds,completedRequests:download.rows.filter(x=>x.exitCode===0).length,deadlineExitRequests:download.rows.filter(x=>x.exitCode===28).length,allChildrenExited:download.allChildrenExited,frames:load.frames.length,observerCpuSeconds:load.observerCpuSeconds,performance,peakThreeSecondWindow:peak,compactMaxSourceAgeSeconds:Math.max(...load.frames.map(x=>x.compactAge)),fullMaxSourceAgeSeconds:Math.max(...load.frames.map(x=>x.fullAge)),fullSourceAgeAtLeastSixFrames:load.frames.filter(x=>x.fullAge>=6).length,originalAuditResults:loadAudits,entryVersionUsed:'v1 before scheduling change',ecmClosedAndZero:true,nssOpened:false,softwareForwardingOnly:true,includesObserverAndAuditCost:true,notEquivalentToNss40Real323MbpsLoad:true,workerPhaseNotInstrumented:load.workerPhaseNotInstrumented,failedNss40AgeNotReproduced:true},
 schedulingQualification:{alignedReadonlyAudits:aligned,newNativeCases:aligned.length,lightLoadOnly:true,actualHighLoadQualified:false,nssFlowAdmissionQualified:false},
 preservedFailures:{originalNss40EvidenceUnchanged:true,v1FrozenFiles:77,v2LocalFiles:12,v3LocalFiles:12,initialSchedulingOuterSeconds:12,supportedOuterMaximumSeconds:6,initialArgumentValidationExitCode:2,initialLuaExecuted:false,initialRouterConfigurationWrites:false,wrapperRefusalPreserved:true,finalSchedulingOuterSeconds:6,localArchiveFixtureFirstRunCountedDiagnosticFileAsDirectory:true,localArchiveFixtureErrorCorrectedWithoutControllerChange:true},
 actualTrial:{attempted:false,reason:'No current real CS2+Steam application pair at final readonly observation',realCs2RtCandidates:r('real-reader-qualified').actualCs2RtCandidates,realSteamBulkCandidates:r('real-reader-qualified').actualSteamBulkCandidates,ecmOpened:false,gateLoaded:false,nssLeafCounters:null,cakeTinMeasurement:null,acceleratedWanMarkNatMeasurement:null,matchedForwardingABACompleted:false,cs2JitterLossMissCaptured:false,rollbackResult:'Not applicable: no experimental router configuration writes; bounded download subprocesses independently terminated.'},
 finalState:{checkedAt:last.observedAt,protectedAudit:Object.fromEntries(['passed','protectedConfigurationUnchanged','exactOwnedNativeAudit','selectors','queryAge','sequence','ecmClosedAndZero'].map(k=>[k,audit[k]])),sameProducerSinceOpening:live.producer===first.files['classification.json'].producer,currentWorkerHealthy:live.status==='running'&&live.dataHealthy&&last.files['guardian.json'].healthy,lastErrorBelongsToPreviousTrial:last.files['last-error.json'].producer!==live.producer,closure:r('final-closure'),application:r('real-reader-qualified')},
 conclusions:{preauditDiagnosticAndImmutableEvidenceGapAddressed:true,schedulingSafetyQualifiedInLocalCasesAndLightNativeChecks:true,nss40SpecificFailureRootCauseProved:false,fullSnapshotAgeIssueFixedUnderRealHighLoad:false,reliableHighLoadNssAdmissionProved:false,realHighLoadNssLoopCompleted:false,nssCpuBenefitProvedThisRound:false,cs2QualityImprovementProved:false,secondWanExpansionAllowed:false,upstreamSubmission:false},
 next:'Use this newly bound entry for one concentrated real single-WAN CS2+Steam A/B/A2, subject to all original live checks/checkpoint/independent expiry. Do not rerun frozen evidence or expand WAN scope.'};
fs.writeFileSync('outputs/nss41-mainline-observations.json',JSON.stringify(summary,null,2)+'\n');
fs.writeFileSync(root+'/load-publication-sanitized.json',JSON.stringify({round:'NSS41',softwareForwardingOnly:true,routerConfigurationWrites:false,endpointIdentitiesOmitted:true,entryVersion:'v1',rows:load.frames.map(f=>({atSeconds:f.at-load.frames[0].at,compactSequence:f.compactSequence,fullSequence:f.fullSequence,compactSourceAge:f.compactAge,fullSourceAge:f.fullAge,guardianHealthy:f.guardianHealthy}))},null,2)+'\n');
console.log(JSON.stringify({round:'NSS41',newLocalCases:18,nativeAlignedAudits:aligned.length,totalBoundInputs:83,softwareMbps:performance.lan4DownMbps,peakMbps:peak.lan4DownMbps,realNssLoopCompleted:false}));
