import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import{verifyPreparation as inherited}from'../v38-sim/session-binding.mjs';import{mayRetryAcquisition}from'./fixture-retry-policy.mjs';
const root='work/v39-five-sim',old=inherited(),prep=JSON.parse(fs.readFileSync(root+'/prepare-receipt.json')),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
for(const[f,h]of Object.entries(prep.oldHashes)){assert.equal(hash(fs.readFileSync(f)),h,f);assert.equal(old.sourceManifest[f],h,'Five-slot previous bindings must remain inherited');}
for(const name of['classifier.lua','classified-tags.lua','fast-path.lua','wan-scope.lua','qos-physical.lua','tag-normalizer.lua','module-stage-guardian.lua'])assert.deepEqual(fs.readFileSync(root+'/'+name),fs.readFileSync('work/v24-fiveflow/'+name),name);
for(const name of['read-controlled.mjs','owned-load-policy.mjs','module-stage.mjs','payload.mjs','epoch-driver.mjs','class-leaf-map.mjs','wan-tag-plan.mjs']){const s=fs.readFileSync(root+'/'+name,'utf8').replaceAll('work/v39-five-sim','work/v24-fiveflow').replaceAll('work\\/v39-five-sim\\/','work\\/v24-fiveflow\\/');assert.equal(s,fs.readFileSync('work/v24-fiveflow/'+name,'utf8'),name);}
assert.deepEqual(fs.readFileSync(root+'/fixture-retry-policy.mjs'),fs.readFileSync('work/v38-sim/fixture-retry-policy.mjs'));
assert.ok(mayRetryAcquisition({frozen:false,elapsedSeconds:8,attempt:1,hasPayload:false,knownTimeout:true}));for(const override of[{frozen:true},{elapsedSeconds:30},{attempt:3},{hasPayload:true},{knownTimeout:false}])assert.ok(!mayRetryAcquisition({frozen:false,elapsedSeconds:8,attempt:1,hasPayload:false,knownTimeout:true,...override}));
const native=fs.readFileSync(root+'/native-client.mjs','utf8');for(const text of['{tcp:8,tcp2:8,tcp3:8,tcp4:8}',"'CREDIT=16384'",'180000','maximumCombinedPacerCreditBytes:65536',"assert.ok(!fixtureFrozen&&(performance.now()-began)/1000<30",'fixtureFrozen=true'])assert.ok(native.includes(text),text);
assert.ok(fs.readFileSync(root+'/current-audit-diagnostic.mjs','utf8').includes('/^work\\/v39-five-sim\\/session-'));assert.ok(fs.readFileSync(root+'/epoch-driver.mjs','utf8').includes('/^work\\/v39-five-sim\\/pilot-'));
const nativeProof=JSON.parse(fs.readFileSync('work/v21-fiveflow/runtime-elf-comparison.json'));assert.ok(nativeProof.passed);assert.equal(hash(fs.readFileSync('work/v21-fiveflow/endpoint-gate/rp_ecm_gate_lab_ct.runtime.ko')),nativeProof.runtimeSha256);
const manifest={};let dependencies=0;for(const name of fs.readdirSync(root))if(/\.(mjs|lua|py|ps1|json)$/.test(name)&&!name.includes('private')&&!['prepare-receipt.json','entry-qualified.json'].includes(name)){const f=root+'/'+name;manifest[f]=hash(fs.readFileSync(f));if(name.endsWith('.mjs')){for(const m of fs.readFileSync(f,'utf8').matchAll(/(?:from\s*|import\s*)['"](\.{1,2}\/[^'"]+\.mjs)['"]/g)){assert.ok(fs.existsSync(path.resolve(root,m[1])),m[1]);dependencies++;}const p=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}}
const out={passed:true,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,relativeDependenciesExist:dependencies,nativeRuntimeSha256:nativeProof.runtimeSha256,fiveSlotNativeAndQosExactV24:true,priorNativeControlChecksReused:63,priorNativeCtChecksReused:68,priorTargetRamChecksReused:14,onlyFixtureAcquisitionChanged:true,clientSeconds:180,fixtureGuardSeconds:210,phaseSeconds:60,combinedTcpMbps:32,combinedCreditBytes:65536,udpPps:50,udpBytes:128,unconnectedTimeoutAttempts:3,acquisitionWindowSeconds:30,firstPayloadSeconds:8,freezeBeforeCheckpoint:true,originalSourceAndSizeCapsRetained:true,hardwareExecuted:false,cs2Acceptance:false,newCpuAcceptance:false,cutoff:prep.newCutoff};fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(out,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,newSources:Object.keys(manifest).length,bindings:out.inheritedBindings+Object.keys(manifest).length,allAuthorityAndDataPlaneUnmodified:true,fiveNativeModelEvidenceReused:true,hardwareExecuted:false}));
