import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import{verifyPreparation as inherited}from'../v25-normal/session-binding.mjs';
const root='work/v26-normal',old=inherited(),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
for(const name of['classified-tags.lua','classifier.lua','fast-path.lua','wan-scope.lua','qos-physical.lua','tag-normalizer.lua','module-stage-guardian.lua','class-leaf-map.mjs','module-stage.mjs','payload.mjs','parse-ecm.mjs','wan-tag-plan.mjs','candidate-policy.mjs','guardian-plan.mjs'])assert.equal(fs.readFileSync(root+'/'+name,'utf8').replaceAll('work/v26-normal','work/v20-five'),fs.readFileSync('work/v20-five/'+name,'utf8'),name+' data plane changed');
for(const name of['normal-policy.mjs','read-controlled.mjs','read-real-candidates.mjs','epoch-driver.mjs'])assert.equal(fs.readFileSync(root+'/'+name,'utf8').replaceAll('work/v26-normal','work/v25-normal').replaceAll('work\\/v26-normal\\/','work\\/v25-normal\\/'),fs.readFileSync('work/v25-normal/'+name,'utf8'),name+' application policy changed');
const models=JSON.parse(fs.readFileSync(root+'/normal-policy-qualified.json'));assert.ok(models.passed&&models.checks===18&&models.modelOnly);let dependencies=0;const manifest={};
for(const name of fs.readdirSync(root))if(/\.(mjs|lua|py|ps1)$/.test(name)&&!name.includes('private')){
 const file=root+'/'+name;manifest[file]=hash(fs.readFileSync(file));
 if(name.endsWith('.mjs')){const s=fs.readFileSync(file,'utf8');for(const m of s.matchAll(/(?:from\s*|import\s*)['"](\.{1,2}\/[^'"]+\.mjs)['"]/g)){assert.ok(fs.existsSync(path.resolve(root,m[1])),'Missing import '+m[1]);dependencies++;}const p=spawnSync(process.execPath,['--check',file],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}
}
for(const name of['native-qualified.json','normalizer-qualified.json','qos-native-qualified.json','normal-policy-qualified.json'])manifest[root+'/'+name]=hash(fs.readFileSync(root+'/'+name));
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify({passed:true,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,hardwareExecuted:false,wholeFactoryModeled:false,nativeAndLuaFromProvenV20Unchanged:true,normalApplicationPolicyUnchangedFromV25:true,selectorModels:18,relativeDependenciesExist:dependencies,missingImportFailureRetained:true,controlledGeneratorsRemoved:true,maximumExactFlows:3,twoSteamBulkAndOneCs2Rt:true,sourceFreshnessSeconds:6,kernelSessionSeconds:90,kernelMaximumSeconds:120,ownerSeconds:180,phaseSeconds:60,defaultInspectOnly:true,normalMultiWanFactoryHardwareAcceptance:false,humanAcceptance:false,permanentNssDeployment:false},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,bindings:Object.keys(old.sourceManifest).length+Object.keys(manifest).length,selectorModels:18,relativeDependencies:dependencies,hardwareExecuted:false}));
