import{validateAcceleratedState}from'../nss25/parse-ecm.mjs';
import fs from'node:fs';import crypto from'node:crypto';import assert from'node:assert/strict';import{spawn}from'node:child_process';
import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';
import{beginStage,readStage,uploadStage,waitStageUndo}from'./module-stage.mjs';import{connectRouter}from'../nss20/connect-router.mjs';import{readBaseline,auditBaseline}from'../nss15/baseline.mjs';import{parseFlow}from'../nss15/packet-model.mjs';import{packetTemplate}from'../nss16/automatic-leaf-plan.mjs';
const loadMbps=3,tcpMode='download',maxLoadBytes=Math.ceil(loadMbps*55*1000000/8)+2000000,openFrontend=true;assert.equal(process.argv[2],'aba','Only the bounded three-phase candidate is accepted');
const root=process.cwd(),python='C:/Users/lishu/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe';const dir=root+'/work/nss32/aba-trial-'+process.argv[2]+'-'+new Date().toISOString().replace(/\D/g,'').slice(0,14)+'-'+crypto.randomBytes(4).toString('hex');fs.mkdirSync(dir);fs.writeFileSync('work/nss32/aba-latest.json',JSON.stringify({dir},null,2)+'\n');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),save=(name,x)=>fs.writeFileSync(dir+'/'+name+'.json',JSON.stringify(x,null,2)+'\n');
const frozen={};for(const path of ['work/nss32/run-aba.mjs','work/nss32/module-stage.mjs','work/nss32/qualification.mjs','work/nss32/fast-path.lua','work/nss32/classifier.lua','work/nss32/payload.mjs','work/nss32/aba-qualified.json','work/nss32/consumer-qualified.json','work/nss32/mainline-preflight-qualified.json','work/nss25/paired-client.py','work/nss16/paired-client.py','work/nss16/paired-server.py','work/nss15/synchronized-load/client.py','work/nss15/synchronized-load/traffic.py','work/nss32/endpoint-guardian-controller.mjs','work/nss32/endpoint-firewall-guardian.py',...['module-stage-guardian.lua','core-guard-phase.lua','module-stage.mjs','qos-physical.lua','classifier.lua','classified-tags.lua','tag-normalizer.lua','fast-path.lua','wan-scope.lua','state-node.lua','payload.mjs','read-prerequisites.lua','flow-selection.mjs','endpoint-gate/rp_ecm_gate_lab_ct.runtime.ko'].map(f=>'work/nss27/'+f)]){const bytes=fs.readFileSync(path);frozen[path]=hash(bytes);fs.writeFileSync(dir+'/frozen-'+path.replaceAll('/','_'),bytes)}save('source-manifest',frozen);
assert.equal(JSON.parse(fs.readFileSync('work/nss16/paired-loopback-result.json','utf8')).passed,true);assert.equal(JSON.parse(fs.readFileSync('work/nss32/mainline-preflight-qualified.json','utf8')).passed,true);const pin=JSON.parse(fs.readFileSync('work/nss16/qos-capacity-private.json','utf8'));assert.equal(pin.qdiscModuleLoaded,false);assert.equal(pin.interfaces.lan1.carrier,0);const pilot=JSON.parse(fs.readFileSync('work/nss17/staged-idle-pilot-latest.json','utf8'));assert.equal(JSON.parse(fs.readFileSync(pilot.dir+'/stage-undo-verified.json','utf8')).ownDirectoryAbsent,true);assert.equal(JSON.parse(fs.readFileSync(pilot.dir+'/baseline-audit.json','utf8')).configurationMatches,true);
const prepared=JSON.parse(fs.readFileSync('work/nss15/synchronized-load/preparation-manifest.json','utf8')),passed=JSON.parse(fs.readFileSync('work/nss15/synchronized-load/loopback-result.json','utf8'));assert.equal(passed.passed,true);
const pre=JSON.parse(fs.readFileSync('work/nss14/owned-dallas-preflight-private.json','utf8'));const address=pre.configuredPublicAddress;assert.match(address,/^\d+\.\d+\.\d+\.\d+$/);
const traffic=fs.readFileSync('work/nss15/synchronized-load/traffic.py','utf8'),server=fs.readFileSync('work/nss16/paired-server.py','utf8'),clientPath=root+'/work/nss25/paired-client.py';
const sourceBase=50000+8*crypto.randomInt(950);const tokenHex=crypto.randomBytes(16).toString('hex');const cc={localSelfTest:false,tokenHex,durationSeconds:57,udpMeasurementSeconds:55,tcpDurationSeconds:55,tcpMaxBytes:maxLoadBytes,tcpPort:45817,udpPort:45818,clientAddress:'192.168.237.207',serverAddress:address,tcpSourcePort:sourceBase,udpSourcePort:sourceBase+10,udpCandidatePorts:Array.from({length:8},(_,i)=>sourceBase+10+i),neighborSourcePort:sourceBase+25,tcpCandidatePorts:Array.from({length:8},(_,i)=>sourceBase+i),choiceOwner:crypto.randomBytes(16).toString('hex'),tcpStartPath:dir+'/tcp-start',tcpMode,tcpTargetMbps:loadMbps,udpPps:20,udpMaxPackets:1100};fs.writeFileSync(dir+'/client-private.json',JSON.stringify(cc,null,2)+'\n',{flag:'wx'});
save('plan',{schema:'nss32-matched-aba-v1',sourceHashes:{traffic:hash(traffic),server:hash(server),client:hash(fs.readFileSync(clientPath))},independentModuleExpirySeconds:45,initialClassifierEpochSeconds:5,nativeSessionHardMaximumSeconds:12,renewedEpochsRequired:1,phases:[{name:'A',seconds:5},{name:'B',seconds:5},{name:'A2',seconds:5}],cadenceSeconds:0.5,unchangedControlledGroupMbps:20,identicalCommonObserver:true,endpointRuleExpirySeconds:70,serverDurationSeconds:70,serverAppWatchdogSeconds:73,serverOsTimeoutSeconds:75,windowsAppWatchdogSeconds:78,windowsControllerProcessDeadlineSeconds:85,loadMbpsCeiling:loadMbps,tcpMode,udpPps:20,gateScope:'one exact established TCP + UDP, natural same WAN/full mark/NAT; default NOT_YET' ,productionClassifierRestored:true,usesPermanentClassifier:true,packetTagWrites:true,physicalLan4QosWrites:true,newNssPermitRequested:openFrontend,syntheticKernelPermitFixture:false});
function start(exe,args,ms,input){const p=spawn(exe,args,{stdio:input===undefined?['ignore','pipe','pipe']:['pipe','pipe','pipe'],windowsHide:true});let stdout='',stderr='';p.stdout.on('data',b=>stdout+=b.toString());p.stderr.on('data',b=>stderr+=b.toString());p.on('error',e=>stderr+='\n'+(e.code??e.name));if(input!==undefined){p.stdin.on('error',e=>stderr+='\n'+(e.code??e.name));p.stdin.end(input)}const timer=setTimeout(()=>{if(p.exitCode===null)p.kill()},ms);const done=new Promise(resolve=>p.once('close',(code,signal)=>{clearTimeout(timer);resolve({code,signal})}));return{p,done,get stdout(){return stdout},get stderr(){return stderr}}}
async function ready(child,marker,ms=10000){const due=performance.now()+ms;while(!child.stdout.includes(marker)&&child.p.exitCode===null&&performance.now()<due)await new Promise(r=>setTimeout(r,40));assert.ok(child.stdout.includes(marker),'Process readiness absent: '+marker)}
const readCommand=()=>String.raw`/usr/bin/lua - <<'NSS16_FLOW_READ'
local j=require('luci.jsonc');local fs=require('nixio.fs');local function read(p)local f=assert(io.open(p));local s=f:read('*a');f:close();return s end
local function cmd(c)local f=assert(io.popen(c..' 2>&1; rc=$?;printf "\n__NSS16_READ_RC__%s\n" "$rc"'));local s=f:read('*a');f:close();local body,rc=s:match('^(.*)\n__NSS16_READ_RC__(%d+)\n$');assert(body and rc=='0');return body end
local o={boot=read('/proc/sys/kernel/random/boot_id'),uptime=read('/proc/uptime'),cpu=read('/proc/stat'),softnet=read('/proc/net/softnet_stat'),ecm={}}
for _,p in ipairs({'front_end_ipv4_stop','front_end_ipv6_stop','ecm_db/connection_count','ecm_nss_ipv4/accelerated_count','ecm_nss_ipv6/accelerated_count','ecm_nss_ipv4/pending_accel_count','ecm_nss_ipv6/pending_accel_count','ecm_nss_ipv4/pending_decel_count','ecm_nss_ipv6/pending_decel_count'})do o.ecm[p]=tonumber(read('/sys/kernel/debug/ecm/'..p))end
assert((o.ecm.front_end_ipv4_stop==1 or o.ecm.front_end_ipv4_stop==0) and o.ecm.front_end_ipv6_stop==1 and o.ecm['ecm_db/connection_count']<=2 and o.ecm['ecm_nss_ipv4/accelerated_count']<=2 and o.ecm['ecm_nss_ipv6/accelerated_count']==0)
o.tcp=cmd('/usr/bin/timeout -k 1 2 /usr/sbin/conntrack -L -f ipv4 --zone 0 -p tcp --orig-src 192.168.237.207 --orig-dst ${address} --sport ${cc.tcpSourcePort} --dport 45817 -o extended,id');o.udp=cmd('/usr/bin/timeout -k 1 2 /usr/sbin/conntrack -L -f ipv4 --zone 0 -p udp --orig-src 192.168.237.207 --orig-dst ${address} --sport ${cc.udpSourcePort} --dport 45818 -o extended,id')
o.wans={};o.interfaces={};o.queues={};for i=1,5 do local d='rpwan'..i;o.wans[i]=assert(j.parse(cmd('ip -j -4 address show dev '..d)));o.interfaces[d]={};for _,k in ipairs({'rx_bytes','rx_packets','tx_bytes','tx_packets','rx_dropped','tx_dropped'})do o.interfaces[d][k]=tonumber(read('/sys/class/net/'..d..'/statistics/'..k))end;for _,pre in ipairs({'rpwan','rpifb'})do local q=pre..i;o.queues[q]=assert(j.parse(cmd('tc -j -s qdisc show dev '..q)))end end;o.interfaces.lan4={};for _,k in ipairs({'rx_bytes','rx_packets','tx_bytes','tx_packets','rx_dropped','tx_dropped'})do o.interfaces.lan4[k]=tonumber(read('/sys/class/net/lan4/statistics/'..k))end;if fs.lstat('/sys/module/qca_nss_qdisc')then o.queues.lan4={nativeText=cmd('/root/router-project/experiments/nss8-htb2-20261001/tc-nss -s -d qdisc show dev lan4'),representation='nss-native-text'}else o.queues.lan4=assert(j.parse(cmd('tc -j -s qdisc show dev lan4')))end;print(j.stringify(o))
NSS16_FLOW_READ`;
let c,cap,client,endpoint,guard,context,before,wan;
async function capture(name){const raw=await c.run(readCommand());save(name+'-private',raw);assert.equal(raw.code,0);return JSON.parse(raw.stdout)}
try{
 c=await connectRouter();before=await readBaseline(c,dir,'baseline-before');
 const pe=encode("/usr/bin/lua - 5 <<'NSS31_PREREQUISITES'\n"+fs.readFileSync('work/nss27/read-prerequisites.lua','utf8')+"\nNSS31_PREREQUISITES\n");const pr=receipt(await c.run(pe.command),pe);save('prerequisites-raw-private',pr);assert.equal(pr.code,0,pr.stderr);wan=JSON.parse(pr.stdout);save('prerequisites-private',wan);assert.equal(wan.boot,pin.boot.trim());assert.equal(wan.wan,5);
 for(const [source,proof,key]of[['fast-path.lua','aba-qualified.json','sourceSha256'],['classifier.lua','consumer-qualified.json','adapterSha256']]){const p=JSON.parse(fs.readFileSync('work/nss32/'+proof));assert.equal(p.passed,true);assert.equal(p[key],hash(fs.readFileSync('work/nss32/'+source)));}
const absentFlows=await capture('before');assert.ok(!absentFlows.tcp.includes('id=')&&!absentFlows.udp.includes('id='),'Proposed controlled tuple already has CT history');

 const unusedUdp=[];for(const p of cc.udpCandidatePorts){cc.udpSourcePort=p;const old=await capture('pre-pool-udp-'+p);if(!old.udp.includes('id='))unusedUdp.push(p)}assert.ok(unusedUdp.length>0,'No unused controlled UDP candidate');cc.udpCandidatePorts=unusedUdp;cc.udpSourcePort=unusedUdp[0];fs.writeFileSync(dir+'/client-private.json',JSON.stringify(cc,null,2)+'\n');save('udp-history-check',{allSelectedCandidatesHadNoPriorCt:true,unusedCandidates:unusedUdp.length});
 const capSource=fs.readFileSync('work/nss14/passive-ipv4.py','utf8').replace('started + 8','started + 4').replace('metadata.append({',"metadata.append({'sequence': struct.unpack('!Q',data[ihl+24:ihl+32])[0] if data[9]==17 and len(data)>=ihl+32 else None, 'nonceMatches': data[9]==17 and len(data)>=ihl+8+16 and data[ihl+8:ihl+8+16]==bytes.fromhex('"+tokenHex+"'),");
 cap=start('ssh',['-o','BatchMode=yes','-o','ConnectTimeout=6','sub2api-dallas','/usr/bin/timeout --foreground -k 2 8 python3 -B -E -s -u -'],18000,capSource);await ready(cap,'NSS14_PASSIVE_READY');client=start(python,['-B','-E','-s',clientPath,dir+'/client-private.json',dir+'/choice',dir+'/go',dir+'/client-result.json'],85000);await ready(client,'NSS20_UDP_CANDIDATES_STARTED');const udpCandidates=[];for(const p of cc.udpCandidatePorts){cc.udpSourcePort=p;const v=await capture('udp-candidate-'+p);if(v.udp.includes('id=')){const f=parseFlow(v.udp,'udp');udpCandidates.push(f)}}const chosenUdp=udpCandidates.find(f=>f.wan===5);save('udp-natural-selection-private',{candidates:udpCandidates,chosen:chosenUdp});assert.ok(chosenUdp,'No WAN5 within eight natural UDP candidates');cc.udpSourcePort=chosenUdp.original.sport;fs.writeFileSync(dir+'/choice-udp',JSON.stringify({owner:cc.choiceOwner,action:'accept',sourcePort:cc.udpSourcePort})+'\n',{flag:'wx'});await ready(client,'NSS14_HELD_SOCKETS_STARTED');const ce=await cap.done;save('discovery-endpoint-private',{exit:ce,stdout:cap.stdout,stderr:cap.stderr});assert.equal(ce.code,0);
 const initialDiscovery=JSON.parse(cap.stdout.split(/\r?\n/).filter(Boolean).at(-1));
 const selectedWarmup=initialDiscovery.packetMetadata.filter(x=>x.packetType===0&&x.destinationPort===45818&&x.destinationAddress===address&&x.nonceMatches&&x.sequence>=1000000&&x.sequence<2000000);
 // Warmup sequence space is emitted only by the accepted held socket. Candidate
 // probes use a disjoint sequence space. Do not discard already verified data
 // merely because the first capture also contained unselected candidates.
 let rows=selectedWarmup;
 if(!rows.length){cap=start('ssh',['-o','BatchMode=yes','-o','ConnectTimeout=6','sub2api-dallas','/usr/bin/timeout --foreground -k 2 8 python3 -B -E -s -u -'],18000,capSource);await ready(cap,'NSS14_PASSIVE_READY');const selectedCapture=await cap.done;save('selected-udp-discovery-private',{exit:selectedCapture,stdout:cap.stdout,stderr:cap.stderr});assert.equal(selectedCapture.code,0);const discovery=JSON.parse(cap.stdout.split(/\r?\n/).filter(Boolean).at(-1));rows=discovery.packetMetadata.filter(x=>x.packetType===0&&x.destinationPort===45818&&x.destinationAddress===address&&x.nonceMatches&&x.sequence>=1000000&&x.sequence<2000000);}
 const observed=[...new Set(rows.map(x=>x.sourceAddress))];assert.equal(observed.length,1,'Selected UDP nonce and warmup identity absent/ambiguous');assert.equal(new Set(rows.map(x=>x.sourcePort)).size,1,'Selected UDP public port changed');save('selected-warmup-identity-private',{selectedOnly:true,sourcePort:chosenUdp.original.sport,rows,fromInitialCapture:!!selectedWarmup.length,publicPeerAddress:observed[0]});
 const initial=await capture('initial-udp-wan');if(parseFlow(initial.udp,'udp').wan!==5){save('not-selected',{naturalUdpWan:parseFlow(initial.udp,'udp').wan,routerWrites:false,endpointFirewallWrites:false});throw Error('Natural UDP is not on the qualified WAN5; no router or endpoint mutation')}const peers={tcp:observed[0],udp:observed[0]};save('physical-peers-private',peers);save('endpoint-tcp-source-plan',{provisionalRuleSource:'authenticated UDP peer /32',tcpSourceMustBeValidatedByActualAuthenticatedServerResult:true});
 const sc={localSelfTest:false,tokenHex,durationSeconds:70,tcpMaxBytes:maxLoadBytes+500000,tcpPort:45817,udpPort:45818,bindAddress:'0.0.0.0',authorizedPeers:[...new Set(Object.values(peers))],tcpMaxMbps:loadMbps,udpMaxPps:100,udpMaxPackets:1500,traceUdp:true};
 const bootstrap=`import base64,types,sys,json\nt=types.ModuleType('traffic');t.__file__='<reviewed-memory-traffic>';sys.modules['traffic']=t\nexec(compile(base64.b64decode('${Buffer.from(traffic).toString('base64')}'),t.__file__,'exec'),t.__dict__)\ns=types.ModuleType('finite_endpoint');s.__file__='<reviewed-memory-server>'\nexec(compile(base64.b64decode('${Buffer.from(server).toString('base64')}'),s.__file__,'exec'),s.__dict__)\nc=t.config(json.loads(base64.b64decode('${Buffer.from(JSON.stringify(sc)).toString('base64')}')),'server')\nprint(json.dumps(s.run(c)),flush=True)\n`;
 endpoint=start('ssh',['-o','BatchMode=yes','-o','ConnectTimeout=6','sub2api-dallas','/usr/bin/timeout --foreground -k 2 75 python3 -B -E -s -u -'],80000,bootstrap);await ready(endpoint,'NSS12_SYNTHETIC_READY');
 let gs=fs.readFileSync('work/nss32/endpoint-guardian-controller.mjs','utf8');assert.ok(gs.includes('work/nss14/physical-peers-private.json'));gs=gs.replace('work/nss14/physical-peers-private.json',dir.replaceAll('\\','/')+'/physical-peers-private.json');fs.writeFileSync(dir+'/endpoint-guardian-controller.mjs',gs);guard=start(process.execPath,[dir+'/endpoint-guardian-controller.mjs','apply'],32000);const ge=await guard.done;save('endpoint-guardian-controller',{exit:ge,stdout:guard.stdout,stderr:guard.stderr});assert.equal(ge.code,0);assert.ok(guard.stdout.includes('detachedIdentityVerified'));
 fs.writeFileSync(dir+'/tcp-start',cc.choiceOwner+'\n',{flag:'wx'});
 const attempts=[];let chosen;
 for(const[index,port]of cc.tcpCandidatePorts.entries()){
  const marker='NSS16_TCP_CANDIDATE {"index": '+(index+1)+', "sourcePort": '+port+'}';await ready(client,marker,6000);cc.tcpSourcePort=port;let live;
  for(let retry=0;retry<5;retry++){live=await capture('candidate-'+(index+1)+'-'+retry);if(live.tcp.includes('id=')&&live.udp.includes('id='))break;await new Promise(r=>setTimeout(r,200))}
  const tcp=parseFlow(live.tcp,'tcp'),udp=parseFlow(live.udp,'udp');const matches=tcp.wan===5&&tcp.wan===udp.wan&&tcp.reply.dst===udp.reply.dst;
  attempts.push({index:index+1,sourcePort:port,tcp,udp,naturalSameWan:matches});const decision={owner:cc.choiceOwner,index:index+1,sourcePort:port,action:matches?'accept':'continue'};const decisionPath=dir+'/choice.'+(index+1);assert.ok(!fs.existsSync(decisionPath));fs.writeFileSync(decisionPath+'.new',JSON.stringify(decision)+'\n',{flag:'wx'});fs.renameSync(decisionPath+'.new',decisionPath);
  if(matches){chosen={tcp,udp};break}
 }
 save('candidate-selection-private',{attempts,chosen});assert.ok(chosen,'No naturally matching TCP/UDP pair within eight candidates');await ready(client,'NSS16_TCP_SELECTED');
 try{await ready(client,'NSS15_TCP_CONNECTED_WAITING_GO',13000)}catch(e){const pending=await capture('handshake-pending');save('handshake-client-private',{stdout:client.stdout,stderr:client.stderr});assert.ok(pending.tcp.includes(' SYN_SENT ')&&!client.stdout.includes('NSS16_TCP_CONNECT_ERROR'),'Selected TCP did not remain in handshake');await ready(client,'NSS15_TCP_CONNECTED_WAITING_GO',13000)}let warmup;for(let check=0;check<10;check++){warmup=await capture('warmup-'+check);if(warmup.udp.includes('[ASSURED]'))break;await new Promise(r=>setTimeout(r,350))}save('endpoint-warmup-diagnostics-private',{stdout:endpoint.stdout,stderr:endpoint.stderr});assert.ok(warmup.udp.includes('[ASSURED]'),'UDP warmup remained unidirectional before GO');fs.writeFileSync(dir+'/go','go\n',{flag:'wx'});await new Promise(r=>setTimeout(r,1300));const live=await capture('before-gate');const udp=parseFlow(live.udp,'udp'),tcp=parseFlow(live.tcp,'tcp');assert.equal(tcp.wan,udp.wan);assert.equal(tcp.reply.dst,udp.reply.dst);assert.ok(live.tcp.includes(' ESTABLISHED ')&&live.tcp.includes('[ASSURED]')&&live.udp.includes('[ASSURED]'));for(const f of[tcp,udp])assert.ok(live.wans[f.wan-1].some(a=>a.addr_info.some(x=>x.family==='inet'&&x.local===f.reply.dst)));save('selected-flows-private',{udp,tcp,sameWan:true});
 const frozen={schema:'nss20-frozen-classified-pair-v1',boot:live.boot.trim(),uptime:live.uptime,tcp,udp,scope:'synthetic exact WAN5 pair; permanent bulk/RT classifier; renewed native epoch; three five-second software/NSS/software phases; exact default-deny gate'};const frozenBytes=Buffer.from(JSON.stringify(frozen));const frozenHash=hash(frozenBytes);fs.writeFileSync(dir+'/frozen-connection-record-private.json',frozenBytes);
 const values={register_gate:1,diagnostic_only:0,tcp_ct_id_raw:((tcp.id>>>24)|((tcp.id>>>8)&0xff00)|((tcp.id<<8)&0xff0000)|(tcp.id<<24))>>>0,game_ct_id_raw:((udp.id>>>24)|((udp.id>>>8)&0xff00)|((udp.id<<8)&0xff0000)|(udp.id<<24))>>>0,tcp_server:tcp.original.dst,tcp_source_port:tcp.original.sport,tcp_server_port:tcp.original.dport,game_server:udp.original.dst,game_source_port:udp.original.sport,game_server_port:udp.original.dport,frozen_record_sha256:frozenHash,tcp_ct_mark:tcp.mark,game_ct_mark:udp.mark,tcp_nat_address:tcp.reply.dst,game_nat_address:udp.reply.dst,tcp_nat_port:tcp.reply.dport,game_nat_port:udp.reply.dport};const insmodArguments=Object.entries(values).map(([k,v])=>{assert.ok(/^[a-z0-9_]+$/.test(k)&&/^[a-f0-9.]+$/.test(String(v)));return k+'='+v}).join(' ');
 const tagOwner=crypto.randomBytes(16).toString('hex');const model=packetTemplate({decisions:[{slot:'tcp',protocol:6,downTag:2399469568,flow:tcp,validUntilUptime:0},{slot:'udp',protocol:17,downTag:2399535104,flow:udp,validUntilUptime:0}]},tagOwner,cc.neighborSourcePort);
 model.expected.nftables=model.expected.nftables.filter(x=>x.chain?.name!=='forward'&&x.rule?.chain!=='forward');
 const tagPlan={table:model.expected.nftables[0].table.name,owner:tagOwner,mode:'rt',expected:model.expected};
 // Wait read-only for the permanent coordinator; no classifier policy is forced.
 const permanent=JSON.parse(fs.readFileSync('work/nss26/deployment-latest.json'));assert.equal(permanent.committed,true);
 const classDue=performance.now()+9000;let classReady=false;
 while(performance.now()<classDue){
  const wanted=Object.fromEntries(['tcp','udp'].map(slot=>{const f={tcp,udp}[slot];return[[f.wan,f.mark,slot,f.original.src,f.original.sport,f.reply.src,f.reply.dst,f.reply.sport,f.reply.dport,f.zone,f.id].join('|'),true]}));
  const ce=encode("/usr/bin/lua - <<'NSS31_CLASS_PAIR_READ'\n"+String.raw`local j=require('luci.jsonc');local f=assert(io.open('/tmp/router-project-game-classifier/classification.json'));local body=f:read(4194305);f:close();assert(#body<=4194304);local s=assert(j.parse(body));local wanted=assert(j.parse([=[${JSON.stringify(wanted)}]=]));local selected={};for _,flow in ipairs(s.snapshot.flows)do if wanted[flow.key]then selected[#selected+1]=flow end end;s.snapshot.flows=selected;print(j.stringify(s))`+"\nNSS31_CLASS_PAIR_READ\n");
  const cr=receipt(await c.run(ce.command),ce);assert.equal(cr.code,0,cr.stderr);const cs=JSON.parse(cr.stdout);save('permanent-classification-private',cs);
  assert.equal(cs.generation,permanent.id);assert.equal(cs.status,'running');const keys={};
  for(const slot of['tcp','udp']){const f={tcp,udp}[slot];keys[slot]=[f.wan,f.mark,slot,f.original.src,f.original.sport,f.reply.src,f.reply.dst,f.reply.sport,f.reply.dport,f.zone,f.id].join('|');}
  const candidates=Object.fromEntries(['tcp','udp'].map(slot=>[slot,cs.snapshot.flows.find(f=>f.key===keys[slot])]));
  if(candidates.tcp?.decision.class==='BULK'&&candidates.udp?.decision.class==='RT'&&candidates.udp.decision.budgetAdmitted){classReady=true;break}
  await new Promise(r=>setTimeout(r,500));
 }
 assert.equal(classReady,true,'Permanent classifier did not admit this exact pair; no router mutation');
 context=await beginStage({mode:'stage',openFrontend:true,wanPrerequisites:{wan:wan.wan,boot:wan.boot,auth:wan.auth,mode:wan.mode.map(x=>({ifindex:x.ifindex,address:x.address,link_index:x.link_index})),status:{up:wan.status.up,l3_device:wan.status.l3_device,'ipv4-address':wan.status['ipv4-address']}},stateMajor:wan.stateMajor,frozenHash,insmodArguments,autoClassified:true,selected:{tcp,udp},tagPlan,qosStaged:true,qosDevice:'lan4',qosTc:pin.tc,qosModule:pin.qdiscModule,qosBaseline:pin.interfaces.lan4.qdiscs,qosBoot:wan.boot},dir);console.log(JSON.stringify({independentModuleGuardianDetached:true,naturalSameWan:true,candidates:attempts.length,newNssPermit:false}));await uploadStage(context);
 for(let i=0;i<26;i++){const state=await readStage(c,context);save('gate-observation-'+i+'-private',state);if(state.record)save('stage-latest-record-private',state.record);if(!state.directoryPresent)break;await new Promise(r=>setTimeout(r,1500));}
 const cli=await client.done;save('client-process',{exit:cli,stdout:client.stdout,stderr:client.stderr});assert.equal(cli.code,0);const result=JSON.parse(fs.readFileSync(dir+'/client-result.json','utf8'));await capture('measurement-end');const state=await readStage(c,context);save('completed-gate-private',state);if(state.record)save('stage-latest-record-private',state.record);
 await waitStageUndo(context);const ep=await endpoint.done;save('endpoint-process-private',{exit:ep,stdout:endpoint.stdout,stderr:endpoint.stderr});assert.equal(ep.code,0);await capture('after');
 const actualEndpoint=JSON.parse(endpoint.stdout.split(/\r?\n/).filter(Boolean).at(-1));assert.equal(actualEndpoint.tcp.authenticatedSessions,1);assert.equal(actualEndpoint.tcp.authenticatedPeerAddress,peers.tcp,'TCP actual public source differs from planned /32');save('authenticated-source-proof-private',{endpointTcpPeer:actualEndpoint.tcp.authenticatedPeerAddress,endpointTcpPort:actualEndpoint.tcp.authenticatedPeerPort,nonceAuthenticationPassed:true,selectedSocketNoReconnect:result.selection.selectedSocketNoReconnect});const r=JSON.parse(fs.readFileSync(dir+'/stage-latest-record-private.json','utf8'));assert.equal(r.error,undefined,r.error);assert.equal(r.fastPathEpochCompleted,true,r.error);assert.equal(r.abaCompleted,true);assert.equal(r.unchangedQoSPlan,true);assert.deepEqual(r.phases.map(p=>p.name),['A','B','A2']);for(const p of r.phases){assert.equal(p.completed,true);assert.equal(p.cadenceSeconds,0.5);assert.ok(p.seconds>=5&&p.seconds<=6.5);assert.ok(p.sampleCount>=8);assert.equal(p.sampleEnd-p.sampleStart+1,p.sampleCount);for(const s of r.samples.slice(p.sampleStart-1,p.sampleEnd)){assert.equal(s.stop6,1);if(p.name==='B'){assert.equal(s.counts['ecm_db/connection_count'],2);assert.equal(s.counts['ecm_nss_ipv4/accelerated_count'],2)}else assert.ok(Object.values(s.counts).every(x=>x===0));}}assert.equal(r.explicitEarlyRetirement,true);assert.ok(r.renewals.length>0);assert.equal(r.fastPathMeasurement.qualified,true,r.fastPathMeasurement.reason);assert.ok(r.fastPathMeasurement.stableSeconds>=5);for(const sample of r.samples)assert.equal(sample.stop6,1);assert.equal(r.firmwareZeroAfterRetirement,true);assert.equal(r.wanRestored,true);assert.equal(r.mwan3Restored,true);assert.equal(r.automaticPacketTagsCompleted,true,r.error);assert.equal(r.tagsRemoved,true);assert.equal(r.qosConfigured,true);assert.equal(r.qosRestored,true);assert.equal(r.qosModuleUnloaded,true);
 if(openFrontend){assert.equal(Math.max(...r.samples.map(s=>s.counts['ecm_nss_ipv4/accelerated_count'])),2,'Both slots not accelerated');save('actual-accelerated-state-proof',validateAcceleratedState(r.acceleratedState,{tcp,udp}));assert.equal(r.explicitEarlyRetirement,true)}const pins={};save('tag-plan-private',context.plan.tagPlan);
 const counters=Object.fromEntries(r.tagsAfter.nftables.filter(x=>x.rule).map(x=>[x.rule.comment.split(':').at(-1),x.rule.expr.find(e=>e.counter).counter]));
 for(const slot of ['tcp','udp'])for(const direction of ['up','down']){
  const key=slot+'_post_'+direction;assert.ok(counters[key+'_total'].packets>0);assert.equal(counters[key+'_expected'].packets,counters[key+'_total'].packets);assert.equal(counters[key+'_unexpected'].packets,0);assert.ok(counters[slot+'_writer_'+direction].packets>0);
 }
 assert.equal(counters.udp_post_neighbor_nonzero.packets,0);save('actual-getter-counters',counters);

 save('summary',{passed:true,syntheticControlQualificationOnly:true,notGameQualityEvidence:true,abaCompleted:true,phaseWindows:r.phases.map(p=>({name:p.name,startedAt:p.startedAt,endedAt:p.endedAt,seconds:p.seconds,samples:p.sampleCount})),unchangedControlledGroupMbps:20,identicalCommonObserver:true,nativeRenewal:true,nativeExpiryObserved:r.nativeExpiryObserved===true,explicitRetirement:true,fastPathMeasurement:r.fastPathMeasurement,renewals:r.renewals,automaticClassification:true,actualPacketTags:true,physicalQosPort:'lan4',qosRestored:true,tagsRemoved:true,ecmAlwaysStopped:!openFrontend,realNssAdmissionRequested:openFrontend,acceleratedPeak:Math.max(...r.samples.map(s=>s.counts['ecm_nss_ipv4/accelerated_count'])),immutableExpiryVerified:r.nativeExpiryObserved===true,explicitEarlyRetirement:r.explicitEarlyRetirement===true,firmwareZero:true,wanRestored:true,classifiedTcp:'BULK',classifiedUdp:'RT',udpSent:result.udp?.sent,udpReceived:result.udp?.received,tcpBytes:result.tcp?.bytes,productionClassifierRestored:true,usesPermanentClassifier:true});console.log(JSON.stringify({automaticClassification:true,actualPacketTags:true,tagsRemoved:true,physicalQosRestored:true,acceleratedPeak:Math.max(...r.samples.map(s=>s.counts['ecm_nss_ipv4/accelerated_count'])),newNssPermitRequested:openFrontend}));

}catch(e){if(c&&client)try{await capture('failure-readonly')}catch(readError){save('failure-readonly-error',{error:String(readError)})}save('controller-error',{error:String(e),stack:e.stack});console.error(String(e));process.exitCode=1}
finally{
 for(const[name,child]of[['client',client],['capture',cap],['endpoint',endpoint],['endpoint-guardian',guard]])if(child)save(name+'-terminal-private',{stdout:child.stdout,stderr:child.stderr,code:child.p.exitCode});
 for(const child of[client,cap,endpoint,guard])if(child?.p.exitCode===null)child.p.kill();save('process-exits',await Promise.allSettled([client,cap,endpoint,guard].filter(Boolean).map(x=>x.done)));c?.close();
 if(context)try{await waitStageUndo(context)}catch(e){save('undo-error',{error:String(e)});process.exitCode=1}
 if(before){let fresh;try{fresh=await connectRouter();const after=await readBaseline(fresh,dir,'baseline-after');const audit=start(process.execPath,['work/nss30/operational-audit.mjs','after-nss32'],20000);const ae=await audit.done;save('permanent-classifier-audit',{exit:ae,stdout:audit.stdout,stderr:audit.stderr});assert.equal(ae.code,0,'Precise live classifier ownership audit failed');const adjusted={...after,native:before.native};save('baseline-audit',auditBaseline(before,adjusted))}catch(e){save('baseline-audit-error',{error:String(e)});process.exitCode=1}finally{fresh?.close()}}
}
