import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {verifyPreparation as base} from '../nss68/session-binding.mjs';
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),q=base();assert.equal(Object.keys(q.sourceManifest).length,257);
const phase=JSON.parse(fs.readFileSync('work/nss69/phase-qualified.json'));assert.ok(phase.passed&&phase.waitFreshByteIdentical&&phase.limitsUnchanged&&phase.expectedGuardRefusals===3);
function clone(name,edits){let s=fs.readFileSync('work/nss68/'+name,'utf8');for(const[a,b,all=false]of edits){assert.ok(s.includes(a),name+': '+a);if(!all)assert.equal(s.split(a).length,2);s=all?s.replaceAll(a,b):s.replace(a,b);}fs.writeFileSync('work/nss69/'+name,s,{flag:'wx'});}
clone('module-stage.mjs',[["from './deployment-binding.mjs'","from '../nss68/deployment-binding.mjs'"],["work/nss63/core-guard-phase.lua","work/nss69/core-guard-phase.lua"],["work/nss63/phase-qualified.json","work/nss69/phase-qualified.json"]]);
clone('current-audit-diagnostic.mjs',[["from './deployment-binding.mjs'","from '../nss68/deployment-binding.mjs'"],["from './wait-publication-metadata.mjs'","from '../nss68/wait-publication-metadata.mjs'"],['nss68','nss69',true]]);
// The two explicit imports above continue to use the actual committed NSS68 deployment.
const audit=fs.readFileSync('work/nss69/current-audit-diagnostic.mjs','utf8').replaceAll("../nss69/deployment-binding.mjs","../nss68/deployment-binding.mjs").replaceAll("../nss69/wait-publication-metadata.mjs","../nss68/wait-publication-metadata.mjs");fs.writeFileSync('work/nss69/current-audit-diagnostic.mjs',audit);
clone('real-session.mjs',[['nss68','nss69',true]]);
clone('record-candidates.mjs',[['nss68','nss69',true]]);
clone('read-real-candidates.mjs',[["from './deployment-binding.mjs'","from '../nss68/deployment-binding.mjs'"],['work/nss68/','work/nss69/',true]]);
const source=fs.readFileSync('work/nss69/core-guard-phase.lua','utf8'),old=fs.readFileSync('work/nss63/core-guard-phase.lua','utf8');assert.equal(source.slice(source.indexOf('function M.waitFresh')),old.slice(old.indexOf('function M.waitFresh')));
const binding=`import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {verifyPreparation as previous} from '../nss68/session-binding.mjs';
export function verifyPreparation(){const q=previous(),p=JSON.parse(fs.readFileSync('work/nss69/entry-qualified.json'));assert.ok(p.passed&&p.phaseOnlyNativeDelta&&p.originalWaitFreshAndDeadlinesRetained&&p.originalFullAuditAndDeploymentRetained);assert.equal(p.baseBoundInputs,Object.keys(q.sourceManifest).length);for(const[f,h]of Object.entries(p.sourceManifest))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),h,f);return{...q,sourceManifest:{...q.sourceManifest,...p.sourceManifest},phaseStatEofOverlay:true};}
`;fs.writeFileSync('work/nss69/session-binding.mjs',binding,{flag:'wx'});
const files=['core-guard-phase.lua','phase-qualified.json','stat-eof-fixtures.lua','qualify-phase.mjs','module-stage.mjs','current-audit-diagnostic.mjs','real-session.mjs','record-candidates.mjs','read-real-candidates.mjs','session-binding.mjs','build-entry.mjs'];const sourceManifest={};for(const name of files)sourceManifest['work/nss69/'+name]=hash(fs.readFileSync('work/nss69/'+name));
const proof={passed:true,observedAt:new Date().toISOString(),baseBoundInputs:257,newBoundInputs:files.length,phaseOnlyNativeDelta:true,originalWaitFreshAndDeadlinesRetained:true,originalFullAuditAndDeploymentRetained:true,existingGateQosClassifiersAndPayloadUnchanged:true,sourceManifest};fs.writeFileSync('work/nss69/entry-qualified.json',JSON.stringify(proof,null,2)+'\n',{flag:'wx'});const actual=(await import('./session-binding.mjs')).verifyPreparation();assert.equal(Object.keys(actual.sourceManifest).length,268);console.log(JSON.stringify({passed:true,boundInputs:268,phaseByteDelta:Buffer.byteLength(source)-Buffer.byteLength(old),productionClassifierChanged:false,gateQosAndTimersChanged:false}));
