import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
import {verifyPreparation as inherited} from '../nss159/session-binding-v4.mjs';
const old=inherited(),root='work/nss160',h=b=>crypto.createHash('sha256').update(b).digest('hex'),sourceManifest={};
const names=fs.readdirSync(root).filter(n=>/\.(mjs|py|lua|ps1)$/.test(n));
for(const n of names){const f=root+'/'+n;sourceManifest[f]=h(fs.readFileSync(f));if(n.endsWith('.mjs')){const p=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}if(n.endsWith('.py')){const p=spawnSync('C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-X','utf8','-c','import sys;compile(open(sys.argv[1],encoding="utf-8").read(),sys.argv[1],"exec")',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}}
for(const n of names.filter(n=>n.endsWith('.mjs'))){const s=fs.readFileSync(root+'/'+n,'utf8');for(const m of s.matchAll(/(?<!['"])\b(?:from|import)\s*['"]([^'"]+)['"]/g)){if(!m[1].startsWith('.'))continue;const d=path.posix.normalize(path.posix.join(root,m[1]));assert.ok(d in old.sourceManifest||d in sourceManifest,'Unbound '+d);}for(const m of s.matchAll(/(?:readFileSync|runNode|run)\(\s*['"](work\/[^'"]+)['"]/g)){if(!/\.(mjs|lua|py|ps1)$/.test(m[1]))continue;assert.ok(m[1] in old.sourceManifest||m[1] in sourceManifest,'Unbound literal '+m[1]);}}
for(const f of ['work/nss158/fast-path.lua','work/nss158/module-stage.mjs','work/nss27/endpoint-gate/rp_ecm_gate_lab_ct.c'])assert.equal(h(fs.readFileSync(f)),old.sourceManifest[f],f);
const q={passed:true,productionExecution:false,sourceManifest,inheritedBindings:Object.keys(old.sourceManifest).length,nativeUnchanged:true,v1ScopeFrozen:true,maximumGapHardwareAttempts:1,lastRealHumanWindowOnly:true,wholeFactoryModelNotRepeated:true,historicalFunctionalAndCpuProofReused:true,originalBudgetsSeconds:[6,27,100,180],byteLimits:[9000,65536,73728,1048576],permanentDeployment:false};
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,newSources:names.length,totalBindings:Object.keys({...old.sourceManifest,...sourceManifest}).length,nativeUnchanged:true,v1ScopeFrozen:true}));
