import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import dgram from'node:dgram';import{spawn,spawnSync}from'node:child_process';
const configPath=path.resolve(process.argv[2]),c=JSON.parse(fs.readFileSync(configPath)),dir=path.dirname(configPath);
assert.equal(c.mbps,32);assert.equal(c.seconds,180);assert.equal(c.pps,50);assert.equal(c.bulkDirection,'download');assert.equal(c.tcpPort,22);assert.equal(c.tcpServerAddress,'172.93.163.251');assert.deepEqual(c.tcpRates,{tcp:8,tcp2:8,tcp3:8,tcp4:8});
const token=Buffer.from(c.token,'hex');assert.equal(token.length,32);const began=performance.now(),stats={pid:process.pid,session:c.session,startedAt:Date.now()/1000,tcpBytes:0,udpSourcePort:c.udpSourcePort,udpSent:0,udpReceived:0,tcpPort:22,errors:[],tcpChildren:['tcp','tcp2','tcp3','tcp4'].map(slot=>({slot,attempt:0,bytes:0,connected:false})),bulkTransport:'owned native OpenSSH download',tcpMetric:'client-observed stdout download bytes',pacerDebtCatchupAllowed:false,maximumPacerCreditBytes:65536,perTcpMbps:c.tcpRates,maximumCombinedPacerCreditBytes:65536};
const udpOut=fs.createWriteStream(dir+'/udp-samples-private.jsonl'),loadOut=fs.createWriteStream(dir+'/load-samples-private.jsonl'),seen=new Set(),children=new Map(),rotating=new Set();let ended=false,seq=0;
const exe=spawnSync('where.exe',['ssh'],{encoding:'utf8',windowsHide:true});assert.equal(exe.status,0);const sshExe=exe.stdout.trim().split(/\r?\n/)[0];
const originalSender=fs.readFileSync(new URL('./download-server.py',import.meta.url),'utf8');assert.equal(originalSender.split('RATE=32_000_000/8').length,2);assert.equal(originalSender.split('CREDIT=65536').length,2);
const quote=x=>"'"+x.replaceAll("'","'\\''")+"'";
function stamp(){if(ended)return;stats.tcpConnected=stats.tcpChildren.every(x=>x.connected);const v={...stats,at:Date.now()/1000,elapsed:(performance.now()-began)/1000};fs.writeFileSync(dir+'/status-private.json.new',JSON.stringify(v));try{fs.renameSync(dir+'/status-private.json.new',dir+'/status-private.json')}catch(e){if(e.code!=='EPERM'&&e.code!=='EBUSY')throw e;}loadOut.write(JSON.stringify(v)+'\n');}
function finish(error){if(ended)return;ended=true;for(const t of timers)clearInterval(t);clearTimeout(hard);if(error)stats.errors.push(String(error));for(const p of children.values())p.kill();sock.close();fs.writeFileSync(dir+'/result-private.json',JSON.stringify({...stats,seconds:(performance.now()-began)/1000,finishedAt:Date.now()/1000},null,2));udpOut.end();loadOut.end();setTimeout(()=>process.exit(stats.errors.length?1:0),80);}
async function startTcp(slot,attempt){const s=stats.tcpChildren.find(x=>x.slot===slot);assert.ok(s&&!rotating.has(slot)&&attempt===s.attempt+1&&attempt<=8);rotating.add(slot);const old=children.get(slot);if(old&&old.exitCode===null){const closed=new Promise(r=>old.once('close',r));old.kill();await closed;}s.attempt=attempt;s.connected=false;
 const sender=originalSender.replace('RATE=32_000_000/8','RATE='+c.tcpRates[slot]+'_000_000/8').replace('CREDIT=65536','CREDIT=16384');const p=spawn(sshExe,['-o','BatchMode=yes','-o','StrictHostKeyChecking=yes','-o','ConnectTimeout=8','-o','ServerAliveInterval=0','-o','ServerAliveCountMax=1','sub2api-dallas','timeout -k 1 185 python3 -u -c '+quote(sender)],{windowsHide:true,stdio:['ignore','pipe','pipe']});children.set(slot,p);s.ownerPid=p.pid;s.executable=sshExe;s.spawnedAt=new Date().toISOString();let stderr='';
 p.stdout.on('data',b=>{if(p!==children.get(slot)||ended)return;s.connected=true;s.bytes+=b.length;stats.tcpBytes+=b.length;if(stats.tcpBytes>1073741824)finish('Combined delivery byte ceiling');});p.stderr.on('data',b=>{stderr+=b;if(stderr.length>8192)finish('SSH stderr ceiling');});p.on('error',e=>{if(p===children.get(slot))finish(e);});p.on('close',code=>{if(p===children.get(slot)&&!rotating.has(slot)&&!ended)finish(code===0||code===124?undefined:'Owned SSH '+slot+' closed '+code+': '+stderr);});rotating.delete(slot);stamp();
}
const sock=dgram.createSocket('udp4');sock.on('error',finish);sock.on('message',b=>{if(b.length!==128||!b.subarray(0,32).equals(token))return;const n=Number(b.readBigUInt64BE(32));if(seen.has(n))return;seen.add(n);stats.udpReceived++;udpOut.write(JSON.stringify({event:'reply',sequence:n,at:Date.now()/1000,sourcePort:c.udpSourcePort,rttMs:performance.now()-b.readDoubleBE(40)})+'\n');});sock.bind(c.udpSourcePort,c.clientAddress,()=>sock.connect(c.udpPort,c.serverAddress));
const timers=[setInterval(()=>{if(ended)return;try{const p=dir+'/control.json';if(fs.existsSync(p)){const x=JSON.parse(fs.readFileSync(p));assert.equal(x.session,c.session);if(x.stop){finish();return;}assert.equal(x.udpSourcePort??c.udpSourcePort,c.udpSourcePort);if(x.rotateTcp){assert.ok(['tcp','tcp2','tcp3','tcp4'].includes(x.rotateTcp.slot));const s=stats.tcpChildren.find(y=>y.slot===x.rotateTcp.slot);if(x.rotateTcp.attempt>s.attempt&&!rotating.has(s.slot))startTcp(s.slot,x.rotateTcp.attempt).catch(finish);}}
 const b=Buffer.alloc(128);token.copy(b);b.writeBigUInt64BE(BigInt(seq),32);b.writeDoubleBE(performance.now(),40);sock.send(b,e=>{if(e&&!ended)finish(e);});stats.udpSent++;udpOut.write(JSON.stringify({event:'sent',sequence:seq++,at:Date.now()/1000,sourcePort:c.udpSourcePort})+'\n');}catch(e){finish(e);}},20),setInterval(stamp,250)];const hard=setTimeout(()=>finish(),180000);stamp();for(const slot of ['tcp','tcp2','tcp3','tcp4'])await startTcp(slot,1);
