import{activeSlots}from'../resident-general-dev-i-20261008/selection.mjs';
import assert from'node:assert/strict';
export function validateAcceleratedState(raw,selected,remainingUdpOnly=false){
 const slots=activeSlots(selected);if(remainingUdpOnly)assert.ok(selected.udp);
 for(const f of slots.map(k=>selected[k])){assert.ok(Number.isInteger(f.wan)&&f.wan>=1&&f.wan<=5,'Invalid selected WAN');assert.equal(f.zone,0);assert.ok(Number.isSafeInteger(f.id)&&f.id>0&&f.id<=0xffffffff);assert.ok(Number.isSafeInteger(f.mark)&&f.mark>0&&f.mark<=0xffffffff);assert.equal((f.mark>>>16)&255,f.wan,'Selected mark WAN mismatch');assert.equal(f.mark&0x2000,0,'Proxy mark cannot enter controlled NSS');}
 const rows=new Map();for(const line of raw.trim().split('\n')){if(!line)continue;const m=line.match(/^conns\.conn\.(\d+)\.([^=]+)=(.*)$/);assert.ok(m,'Unexpected state line');const r=rows.get(m[1])??{};assert.ok(!(m[2]in r),'Duplicate state key');r[m[2]]=m[3];rows.set(m[1],r)}
 assert.equal(rows.size,remainingUdpOnly?1:slots.length,'Unexpected ECM connection scope');const proof={};
 for(let[slot,tag]of((remainingUdpOnly?['udp']:slots).map(s=>[s,0]))){const f=selected[slot],minor=f.wan*16+(slot==='udp'?6:5),up=(0x8e00+minor)*65536;tag=(0x8f00+minor)*65536;const direction=r=>r.sip_address===f.original.src&&r.dip_address===f.original.dst&&Number(r.sport)===f.original.sport&&Number(r.dport)===f.original.dport?'client-first':r.sip_address===f.original.dst&&r.dip_address===f.original.src&&Number(r.sport)===f.original.dport&&Number(r.dport)===f.original.sport?'server-first':null;const matches=[...rows].filter(([,r])=>Number(r.protocol)===f.protocol&&direction(r));assert.equal(matches.length,1);const[serial,r]=matches[0];const reverse=direction(r)==='server-first';assert.equal(r.ip_version,'4');assert.equal(r.is_routed,'1');assert.equal(r.sip_address_nat,reverse?f.reply.src:f.reply.dst);assert.equal(Number(r.sport_nat),reverse?f.reply.sport:f.reply.dport);assert.equal(r.dip_address_nat,reverse?f.reply.dst:f.reply.src);assert.equal(Number(r.dport_nat),reverse?f.reply.dport:f.reply.sport);assert.equal(r['nss_v4.ported.accel_mode'],'2');assert.equal(Number(r['classifiers.dscp.pr.flow_qos_tag']),reverse?tag:up);assert.equal(Number(r['classifiers.dscp.pr.return_qos_tag']),reverse?up:tag);assert.equal(Number(r['classifiers.dscp.pr.'+(reverse?'return':'flow')+'_mark']),f.mark);
  for(const prefix of reverse?['from_interfaces','from_nat_interfaces']:['to_interfaces','to_nat_interfaces']){assert.ok(Object.entries(r).some(([k,v])=>k.startsWith(prefix+'.')&&k.endsWith('.iface.name')&&v==='rpwan'+f.wan),'WAN affinity absent');assert.ok(Object.entries(r).some(([k,v])=>k.startsWith(prefix+'.')&&k.endsWith('.iface.name')&&v==='wan'),'Physical WAN missing')}
  const lan=reverse?'to_interfaces.':'from_interfaces.';assert.ok(Object.entries(r).some(([k,v])=>k.startsWith(lan)&&k.endsWith('.iface.name')&&v==='lan4'));assert.ok(Object.entries(r).some(([k,v])=>k.startsWith(lan)&&k.endsWith('.iface.name')&&v==='br-lan'));
  proof[slot]={serial,protocol:f.protocol,ecmOrientation:direction(r),accelerated:true,ctMark:f.mark,downTag:tag,upTag:up,natCorrect:true,wanAffinity:f.wan,fromLan4:true,fromBridgeLan:true,slowPathPackets:Number(r['nss_v4.ported.slow_path_packets']),fromPackets:Number(r['adv_stats.from_packet_total']),toPackets:Number(r['adv_stats.to_packet_total'])};
 }
 return{passed:true,connectionCount:rows.size,proof};
}
