import fs from'node:fs';const s=JSON.parse(fs.readFileSync('outputs/nss38-mainline-observations.json'));const f=(x,n=2)=>Number(x).toFixed(n);const t=s.actualTrial;
const windows=[['发布观测，软件转发',s.highLoadPublication.performance],['密集诊断，软件转发',s.postTrialLoopProfile.performance]].map(([name,x])=>`<tr><td>${name}</td><td>${f(x.seconds)}</td><td>${f(x.lan4DownMbps)}</td><td>${f(x.lan4DownPps,0)}</td><td>${f(x.cpuBusyPercent)}%</td><td>${f(x.softirqPercent)}%</td><td>+${x.timeSqueezeDelta}</td></tr>`).join('');
const bench=s.candidate.nativeBenchmark.groups.map(x=>`<tr><td>${x.flows}</td><td>${f(x.oldCpuMs,3)}</td><td>${f(x.newCpuMs,3)}</td><td>${f(x.reductionPercent,1)}%</td></tr>`).join('');
fs.writeFileSync('outputs/nss38-mainline-report.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSS38 · 真人准入与分类器稳定性</title><style>body{margin:0;background:#f3f5f7;color:#19232d;font:16px/1.75 system-ui,'Microsoft YaHei',sans-serif}main{max-width:1060px;margin:35px auto;padding:34px;background:white;border-radius:16px}h1{font-size:30px;line-height:1.4}h2{margin-top:32px;font-size:21px}p{max-width:95ch}a{color:#075f83}code{overflow-wrap:anywhere;font-size:13px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:11px;text-align:left;border-bottom:1px solid #dce3e8}th{background:#eff5f7}.note{padding:16px 20px;background:#eef6f4;border-left:4px solid #287363}.warn{background:#fff5e4;border-color:#af761b}.scroll{overflow:auto}.muted{color:#566774}@media(max-width:700px){main{margin:0;padding:20px;border-radius:0}h1{font-size:25px}}</style><main>
<p class="muted">Athena AX6600 · 2026-10-03 · NSS38，时间均为北京时间</p><h1>真人单 WAN 尝试仍未进入 NSS<br>准入检查已减负，常驻稳定性需先处理</h1>
<p class="note warn">本轮完成真实 CS2 UDP + Steam TCP 的 WAN2 短测准备，但在开启 ECM 前因时间余量不足退出。<strong>bulk / RT leaf 均 0 包，完整 A/B 尚未通过。</strong>独立恢复与现网核验通过。常驻部署仍是 NSS37，ECM 关闭。</p>
<h2>实际尝试与回滚</h2><p>用户开启下载后，先测到 LAN4 353.25 Mbps 的软件负载，随后核验真实对局 UDP 与下载 TCP。22:10 的完整只读准入演练有 44 次检查、6 次通过，两条所选连接 44 次均存在。现场试验前再次核对应用归属、同 WAN、完整 mark 与 NAT。</p>
<p>22:11 起创建并验证 checkpoint，核验脱离控制连接的 45 秒恢复守护，然后只把 WAN2 临时改成 private 并准备物理 LAN4 NSS 队列。初始窗口约 <strong>${f(t.initialAlignmentSeconds)} 秒、32 次检查全部被时间条件拒绝</strong>：pre-learning 余量不足 23 次，tag 设置预留不足 9 次。原逐次记录没有来源序号，不能确定每次延迟的全部成因。</p>
<p>packet tags 尚未安装、gate 未加载、ECM 未开启。bulk / RT leaf 均为 0 字节、0 包；默认 leaf 的 ${t.defaultLeaf.bytes.toLocaleString('en-US')} 字节 / ${t.defaultLeaf.packets.toLocaleString('en-US')} 包只证明默认出口承载流量。WAN、队列、模块、状态节点全部恢复，14 项受保护配置检查通过，认证与 DHCP 身份保持；未触发续认证。保存了 70 份与当次清单匹配的源码和证明副本。</p>
<p>所选 TCP/UDP 都是 WAN2、完整 ct mark <code>0x20000</code>、相同 NAT；这是加速前核验。<strong>尚无本轮加速后的 WAN affinity、leaf 分类或游戏体验证据。</strong>受控子组上限仍为 20 Mbps，不能写成整个 Steam 300 Mbps 以上已加速。</p>
<h2>负载观测：两个独立的软件窗口</h2><div class="scroll"><table><thead><tr><th>窗口</th><th>秒</th><th>Mbps</th><th>pps</th><th>busy</th><th>softirq</th><th>time_squeeze</th></tr></thead><tbody>${windows}</tbody></table></div>
<p>这些是 LAN4 聚合值，包含观察程序成本，负载与时间不同，不能相减当 NSS 收益。353 Mbps 窗口有 81 次观测、14 次 JSON 读取，观察程序 CPU 1.705 秒；发布延迟 0.56–0.81 秒，8 次观测来源年龄低于 1 秒。内核没有子进程枚举接口，原始阶段计数中的 0 表示数据不可用，不能解释为没有规则维护。</p>
<p>失败后的 12 秒密集诊断自身消耗 8.434 秒 CPU 时间，105 次检查均报所选类别不再准入；当时未重新核对客户端应用归属。它不是原失败的重放。实际完整进程枚举 3 次、局部检查 102 次；最大 phase 检查 0.24 秒、adapter 检查 0.19 秒，发布延迟 0.83–1.14 秒。之前一次只读诊断因核心守护数量变化退出，具体瞬态原因未复现。</p>
<h2>只改候选控制器：消除重复检查</h2><p>代码核对发现 ready / observe 会对同一份快照完整校验两遍。候选合并为一次完整检查，保留进程身份、全部候选、CT ID / zone / NAT / 完整 mark、类别、leaf 和有效期检查。没有缓存旧结果、缩小采集范围或放宽期限；sample、续租与精确撤销的原合同保持不变。</p>
<p>核心候选通过 1,470 个新旧决策对照、5 个检查次数约束、212 个准入案例、21 个续租/撤销案例。首次更宽的修改被本地测试发现改变撤销错误形态，已弃用，未用于现场。另一个带诊断的候选通过同样 1,470 个决策对照及 230 个准入/诊断案例，目标 Lua 编译通过；新增来源序号、采集/发布时间、年龄及每次检查耗时。<strong>两个候选均未安装，尚未完成当前部署的整套控制器绑定。</strong></p>
<div class="scroll"><table><thead><tr><th>合成候选数</th><th>旧检查 CPU ms</th><th>新检查 CPU ms</th><th>降幅</th></tr></thead><tbody>${bench}</tbody></table></div>
<p>路由器原生 Lua/jsonc，三种相同内存输入、每组四对交替测量，共 120 次成功 ready 调用。文件系统与准入时钟为模拟；未使用的方法从传输文本中裁去，实际 ready 路径保持。背景约 6.19 Mbps，未生成网络负载。表中收益只适用于准入检查，不是整机 CPU、NSS 或游戏收益，也未证明高负载入口问题已解决。</p>
<h2>新发现：分类器在 22:27 自动重启</h2><p>真实日志记录：带 2 秒 timeout 的 <code>/sbin/tc -j qdisc show dev rpwan1</code> 返回 143，并有 <code>Terminated</code>。调用位于规则维护前的队列检查，随后 apply 子进程失败、worker 退出。日志确认精确恢复成功，服务自动生成新 worker，guardian 进程未变。</p>
<p>22:33 核验时分类器已恢复健康、配置哈希不变、自有规则与现网审核通过。之后同一查询 8 次均约 10 ms、RC 0，均找到 CAKE root。尚未捕获原阻塞栈或信号来源，不能断言是 RTNL、CPU、CAKE 或 NSS 驱动缺陷；也不能因最终健康就宣称全程稳定。</p>
<h2>下一步保持一条主线</h2><p>先处理常驻分类器此次读取失败的诊断与安全恢复边界；不把规则读取失败当成功，不盲目增加超时。随后完成带诊断准入候选的当前部署绑定和只读资格，入口与生命周期都成立后再集中一次真人单 WAN 闭环。不要求用户持续挂游戏或下载。第二 WAN、共享预算和其它 QoS 扩展继续等待。</p>
<p>当前未测得 CS2 jitter / loss / Miss；没有同负载 NSS 阶段，无法判断真实 softirq 或游戏收益。原始连接、日志、检查点、模块与完整配置保留在私有工作区，仓库仅保存白名单源码和脱敏证据。未提交上游 Issue/PR。</p>
<p><a href="nss38-mainline-observations.json">本轮结构化证据</a> · <a href="nss37-normalizer-report.html">NSS37 当前部署来源</a> · <a href="https://github.com/ZyPulse-zy/athena-nss-mainline">私有主线仓库</a></p><p class="muted">常驻引用：work/nss37/deployment-latest.json<br>配置：<code>${s.finalState.configSha256}</code></p></main></html>`);console.log(JSON.stringify({report:'outputs/nss38-mainline-report.html',realHighLoadABACompleted:false,ecmEnabled:false}));
