import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';
const root='work/nss38',trial=root+'/real-matched-aba-20261003141133-251d83e6';const read=p=>JSON.parse(fs.readFileSync(p));const pick=(o,ks)=>Object.fromEntries(ks.filter(k=>k in o).map(k=>[k,o[k]]));const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const d=read('work/nss37/deployment-latest.json'),r=read(trial+'/last-record-private.json'),result=read(trial+'/result.json'),selected=read(trial+'/selected-private.json');
const audit=read(root+'/closing-audit.json'),closure=read(root+'/final-closure.json'),begin=read(root+'/classifier-begin-inspection.json'),end=read(root+'/classifier-closing-inspection.json');
const base=read(trial+'/baseline-audit.json'),undo=read(trial+'/stage-undo-verified.json'),receipt=read(trial+'/stage-receipt-private.json'),cp=read(trial+'/stage-checkpoint-verified.json');
assert.ok(d.committed&&audit.passed&&closure.passed&&base.configurationMatches&&Object.values(undo).every(v=>v===true));assert.ok(receipt.rollbackBeforeFirstWrite&&receipt.parentIdentityVerified&&receipt.pipeInodesVerified&&cp.gzipVerified);
assert.equal(r.moduleLoaded,false);assert.equal(r.newNssPermit,false);assert.equal(result.matchedForwardingABACompleted,false);assert.equal(r.tagEpochUntil,undefined);assert.equal(Object.keys(r.classifierSnapshots).length,0);
const reason=s=>s.replace(/^\[string .*?\]:\d+: /,'');const probes=r.initialAlignment.probes;const reasons={};for(const p of probes){assert.equal(p[1],false);assert.equal(p[3],true);const key=reason(p[2]);reasons[key]=(reasons[key]??0)+1}assert.equal(probes.length,32);
const frozen=read(trial+'/frozen-source-index-private.json');assert.equal(frozen.sources.length,70);
function leaf(handle){const m=r.qosBeforeUndo.qdisc.match(new RegExp('qdisc nssfq_codel '+handle+'[\\s\\S]*?Sent (\\d+) bytes (\\d+) pkt'));assert.ok(m);return{bytes:+m[1],packets:+m[2]}}
function metrics(rows){const a=rows[0],b=rows.at(-1),dt=b.uptime-a.uptime;const cpu=x=>x.cpu.trim().split(/\s+/).slice(1,9).map(Number),x=cpu(a),delta=cpu(b).map((v,i)=>v-x[i]),sum=delta.reduce((a,b)=>a+b,0);const squeeze=x=>x.softnet.trim().split('\n').reduce((n,l)=>n+parseInt(l.trim().split(/\s+/)[2],16),0);return{seconds:dt,lan4DownMbps:(b.txBytes-a.txBytes)*8/dt/1e6,lan4DownPps:(b.txPackets-a.txPackets)/dt,cpuBusyPercent:100*(sum-delta[3]-delta[4])/sum,softirqPercent:100*delta[6]/sum,timeSqueezeDelta:squeeze(b)-squeeze(a),includesObserverCost:true,matchedForwardingABA:false}}
const pub=read(root+'/publication-observation.json'),ps=read(root+'/publication-summary.json'),rehearsal=read(root+'/rehearsal-summary.json'),profile=read(root+'/loop-profile.json'),benchmark=read(root+'/native-adapter-benchmark.json');
const diff=read(root+'/adapter-differential-qualified.json'),admission=read(root+'/candidate-admission-qualified.json'),consumer=read(root+'/candidate-consumer-qualified.json'),td=read(root+'/traced-adapter-differential-qualified.json'),ta=read(root+'/traced-admission-qualified.json'),native=read(root+'/native-candidate-syntax.json');
assert.ok([diff,admission,consumer,td,ta,native,benchmark].every(x=>x.passed));assert.equal(diff.newSha256,sha(root+'/candidate-classifier.lua'));assert.equal(td.newSha256,sha(root+'/candidate-traced-classifier.lua'));assert.equal(ta.fastSourceSha256,sha(root+'/candidate-traced-fast-path.lua'));
const logfile=fs.readFileSync(root+'/recent-log-private.txt','utf8');assert.ok(logfile.includes('22:27:08')&&logfile.includes("'/sbin/tc -j qdisc show dev rpwan1'")&&logfile.includes('__NSS23_RC__143')&&logfile.includes('exactRecovery=true nil'));
const qprobe=read(root+'/qdisc-read-probe.json');assert.ok(qprobe.rows.length===8&&qprobe.rows.every(x=>x.exitCode===0&&x.cakeRoots===1));
const profileReason={};for(const v of profile.rows){const key=reason(v.reason??'');profileReason[key]=(profileReason[key]??0)+1}
const out={round:'NSS38',updatedAt:new Date().toISOString(),deploymentReference:'work/nss37/deployment-latest.json',permanentClassifierChanged:false,
 highLoadPublication:{observedAt:pub.observedAt,performance:metrics(pub.telemetry),samples:pub.frames.length,jsonReads:pub.jsonReads,observerCpuSeconds:pub.observerCpuSeconds,guardianHealthyAtAllSamples:ps.healthy,sourceAgeBelowOneSecond:ps.under1,publicationDelayRangeSeconds:[Math.min(...ps.publications.map(x=>x.delay)),Math.max(...ps.publications.map(x=>x.delay))],candidateCountsRange:[Math.min(...ps.publications.map(x=>x.flows)),Math.max(...ps.publications.map(x=>x.flows))],productionWorkerInstrumented:false,childPhaseCountersUsable:false,childPhaseLimitation:'Kernel lacks CONFIG_PROC_CHILDREN; zero child-phase counters are unavailable data, not proof of absent maintenance.'},
 preTrialRehearsal:{...pick(rehearsal,['samples','ready','ageMin','readMax','publicationDelayMin','publicationDelayMax','selectedTcpPresent','selectedGamePresent','routerWrites']),reasons:Object.fromEntries(Object.entries(rehearsal.reasons).map(([k,v])=>[reason(k),v])),currentApplicationOwnershipRechecked:true},
 actualTrial:{attempted:true,passed:false,matchedForwardingABACompleted:false,applicationPairVerifiedTwiceBeforeCheckpoint:true,wan:selected.tcp.wan,tcpMark:selected.tcp.mark,udpMark:selected.udp.mark,sameFullMark:selected.tcp.mark===selected.udp.mark,sameNat:selected.tcp.reply.dst===selected.udp.reply.dst,selectedSubgroupCeilingMbps:20,unselectedPhysicalFallbackMbps:950,independentOwnerSeconds:45,checkpointVerified:true,rollbackBeforeFirstWrite:true,detachedOwnerVerified:true,temporarySingleWanPrivate:r.wanPrivate.mode==='private',physicalLan4QosTreePrepared:r.qosReady.validation.complete,initialAlignmentSeconds:r.initialAlignment.stop-r.initialAlignment.start,actualLastProbeSeconds:probes.at(-1)[0]-r.initialAlignment.start,probeCount:probes.length,readyCount:0,refusalCounts:reasons,packetTagRulesInstalled:false,gateModuleLoaded:false,nssPermissionGranted:false,bulkLeaf:leaf('8f05:'),rtLeaf:leaf('8f06:'),defaultLeaf:leaf('8fff:'),rollbackPassed:true,wanRestored:r.wanRestored,qosRestored:r.qosRestored,modulesRemoved:true,protectedConfigurationUnchanged:base.configurationMatches,authenticationAndDhcpIdentityPreserved:r.wanHealthAfterUndo===true,renewalReauthenticationTested:false,pbrNatWanAffinityAfterAccelerationProved:false,perProbeSourceSequenceNotRecorded:true,allFailureCausesProved:false,frozenSourceProofCopies:70},
 initialAdmissionTrace:probes.map(p=>({atSeconds:p[0]-r.initialAlignment.start,ready:p[1],reason:reason(p[2]),retryable:p[3]})),
 postTrialLoopProfile:{observedAt:profile.observedAt,samples:profile.rows.length,ready:profile.rows.filter(x=>x.ready).length,reasons:profileReason,observerCpuSeconds:profile.observerCpuSeconds,fullInventories:profile.rows.filter(x=>x.fullInventory).length,scopedScans:profile.rows.filter(x=>!x.fullInventory).length,maxPhaseSeconds:Math.max(...profile.rows.map(x=>x.phaseSeconds)),maxAdapterSeconds:Math.max(...profile.rows.map(x=>x.adapterSeconds)),performance:metrics(profile.telemetry),publicationDelayRangeSeconds:[Math.min(...profile.rows.map(x=>x.publicationDelay)),Math.max(...profile.rows.map(x=>x.publicationDelay))],currentApplicationOwnershipRechecked:false,originalGameNoLongerAdmitted:true,oneEarlierReadOnlyScanAborted:'Core guard count changed; not reproduced in second diagnostic. Transient enumeration is only a hypothesis.',originalFailureCausalAttribution:false},
 candidate:{installed:false,operationalBindingUpdated:false,admissionSemanticsAndDeadlinesUnchanged:true,change:'Remove only redundant full inspection in ready/observe. Renewal, retirement and sample contracts unchanged; no cache or reduced source scope.',baseAdapterSha256:diff.oldSha256,adapterSha256:diff.newSha256,localChecks:{decisionCases:diff.differentialCases,inspectionCountChecks:diff.inspectionCountChecks,admissionCases:admission.checks,renewalRetirementCases:consumer.checks},nativeBenchmark:{...pick(benchmark,['observedAt','elapsedSeconds','backgroundLan4Mbps','groups','rows','successfulReadyCalls','execBytes','oldSha256','newSha256']),scope:'Actual ready path, native Lua/jsonc; identical synthetic 2/32/64-flow publications, mocked filesystem and fixed admission clock. Unreachable sample/retirement/renewal methods pruned. No live admission or forwarding benefit proved.'},discardedBroaderChange:'First wider removal changed retirement error shape in local differential replay; discarded before any live use.',trace:{adapterSha256:td.newSha256,fastSha256:ta.fastSourceSha256,decisionCases:td.differentialCases,inspectionCountChecks:td.inspectionCountChecks,admissionAndDiagnosticChecks:ta.checks,newDiagnosticChecks:18,diagnosticFields:['source sequence','query start/finish','publication time','age at completed check','adapter wall time','phase wall time','iteration wall time'],nativeCompileOnly:native.passed,fullyBoundControllerQualified:false}},
 classifierRestart:{observed:true,logTime:'2026-10-03T22:27:08+08:00',command:'/sbin/tc -j qdisc show dev rpwan1',wrapperTimeoutSeconds:2,exitCode:143,reported:'Terminated',path:'queue read -> backend freshKnown/reconcile -> apply child fails -> worker exits -> procd restarts',exactRecoveryLogged:true,producerChanged:true,guardianProcessUnchanged:begin.files['guardian.json'].pid===end.files['guardian.json'].pid,subsequentProbe:qprobe,underlyingBlockOrSignalCauseProved:false,productionFaultInjected:false,sourceModified:false,nssRelatedCauseProved:false},
 finalState:{observedAt:end.observedAt,configSha256:d.configHash,protectedAudit:pick(audit,['passed','protectedConfigurationUnchanged','exactOwnedNativeAudit','selectors','queryAge','sequence','ecmClosedAndZero']),sameProducerSinceBegin:begin.files['classification.json'].producer===end.files['classification.json'].producer,currentClassifierHealthy:end.files['classification.json'].dataHealthy===true&&end.files['guardian.json'].healthy===true,currentLastErrorBelongsToPreviousInstance:end.files['last-error.json'].producer!==end.files['classification.json'].producer,closure},
 limitations:{realHighLoadABACompleted:false,nssCpuBenefitProved:false,gameJitterLossMissCaptured:false,wholeSteam300MbpsAccelerated:false,completeHighLoadLifecycleQualified:false,publicationTimingFixed:false,adapterOptimizationInstalled:false,upstreamDriverDefectProved:false},
 next:'Preserve classifier fail-closed recovery and diagnose the observed queue-read exit; qualify the candidate controller and per-probe timing against current deployment. Then a concentrated single-WAN real-pair retry only after lifecycle and admission gates pass. No second WAN or QoS side branches.',upstreamSubmission:false};
assert.equal(out.actualTrial.bulkLeaf.packets,0);assert.equal(out.actualTrial.rtLeaf.packets,0);assert.equal(out.finalState.sameProducerSinceBegin,false);
fs.writeFileSync('outputs/nss38-mainline-observations.json',JSON.stringify(out,null,2)+'\n');
const start=profile.rows[0].at;fs.writeFileSync(root+'/loop-timing-sanitized.json',JSON.stringify({observedAt:profile.observedAt,routerWrites:false,originalFailedAttempt:false,currentApplicationOwnershipRechecked:false,rows:profile.rows.map(x=>({...pick(x,['ready','retryable','sourceAge','publicationDelay','querySeconds','phaseSeconds','phaseCpuSeconds','adapterSeconds','adapterCpuSeconds','iterationSeconds','iterationCpuSeconds','fullInventory','phasePassed']),atSeconds:x.at-start,reason:reason(x.reason??'')}))},null,2)+'\n');
console.log(JSON.stringify({trial:out.actualTrial,candidateInstalled:false,restart:pick(out.classifierRestart,['observed','logTime','exitCode','underlyingBlockOrSignalCauseProved']),finalState:out.finalState}));
