import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{verifyPreparation}from'../nss118/session-binding.mjs';import{createPacer}from'./bounded-pacer.mjs';
const root='work/nss119',h=b=>crypto.createHash('sha256').update(b).digest('hex'),checks=[],old=verifyPreparation();
let p=createPacer(0,4000000),bytes=0;for(let t=5;t<=20000;t+=5)for(let i=0;i<4&&p.next(t);i++)bytes+=16384;assert.ok(bytes<=80000000&&bytes>=80000000-16384);checks.push({name:'actual-callback-model-keeps-32Mbps-average',passed:true,simulated:true,submittedBytes:bytes});
p=createPacer(0,4000000);assert.equal(p.next(10000,true),false);let resume=0;while(p.next(10000))resume+=16384;assert.equal(resume,65536);assert.equal(p.next(10000),false);checks.push({name:'ten-second-channel-stall-cannot-create-forty-MB-debt',passed:true,simulated:true,resumeBurstBytes:resume});
assert.throws(()=>p.next(9999));checks.push({name:'clock-regression-refused',passed:true,simulated:true});assert.throws(()=>createPacer(0,Infinity));assert.throws(()=>p.next(NaN));checks.push({name:'nonfinite-configuration-or-clock-refused',passed:true,simulated:true});
for(const name of fs.readdirSync(root).filter(x=>x.endsWith('.mjs'))){const q=spawnSync(process.execPath,['--check',root+'/'+name],{encoding:'utf8',windowsHide:true});assert.equal(q.status,0,q.stderr);}
for(const name of ['fast-path.lua','module-stage-guardian.lua','qos-physical.lua','tag-normalizer.lua','uplink-tag-plan.mjs','parse-ecm-any-wan.mjs'])assert.equal(h(fs.readFileSync(root+'/'+name)),h(fs.readFileSync('work/nss118/'+name)));
for(const name of ['start-dallas.mjs','run.mjs'])assert.equal(fs.readFileSync(root+'/'+name,'utf8').replaceAll('nss119','nss118').replaceAll('NSS119','NSS118'),fs.readFileSync('work/nss118/'+name,'utf8'));
const sourceManifest={};for(const name of fs.readdirSync(root))if(/\.(mjs|py|lua|ps1)$/.test(name))sourceManifest[root+'/'+name]=h(fs.readFileSync(root+'/'+name));
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify({passed:true,productionExecution:false,onlyUploadPacingChanged:true,serverConfirmedDeliveryMetric:true,queueRatesChanged:false,routerPayloadChanged:false,offeredMbps:32,maximumPacerCreditBytes:65536,parentMbps:30,phaseSeconds:20,nativeSessionSeconds:27,independentOwnerSeconds:100,classifierMaximumLeaseSeconds:6,checks,sourceManifest,inheritedBoundInputs:Object.keys(old.sourceManifest).length},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,newBoundaryChecks:checks.length,sourceBindings:Object.keys(sourceManifest).length,hardwareExecution:false}));
