import fs from 'node:fs';import path from 'node:path';import net from 'node:net';import dgram from 'node:dgram';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
import ssh2 from 'file:///C:/Users/lishu/Documents/Codex/2026-09-11/ax6600-re-cs-02-jdcos-4/work/runtime/node_modules/ssh2/lib/index.js';
import {validateServerReady,canReplaceSender,nextPort} from './download-policy.mjs';
const configPath=path.resolve(process.argv[2]),c=JSON.parse(fs.readFileSync(configPath)),dir=path.dirname(configPath);
assert.equal(c.mbps,32);assert.equal(c.seconds,180);assert.equal(c.pps,50);assert.equal(c.bulkDirection,'download');assert.equal(c.tcpPort,22);assert.equal(c.tcpServerAddress,'18.138.159.236');
const token=Buffer.from(c.token,'hex');assert.equal(token.length,32);const began=performance.now(),seen=new Set();
const stats={pid:process.pid,session:c.session,startedAt:Date.now()/1000,tcpBytes:0,tcpConnected:false,tcpSourcePort:c.tcpSourcePort,udpSourcePort:c.udpSourcePort,udpSent:0,udpReceived:0,errors:[],bulkTransport:'owned authenticated SSH TCP download',tcpMetric:'application received payload bytes',pacerDebtCatchupAllowed:false,maximumPacerCreditBytes:65536,tcpPaused:false,selectedTcpPort:null,preparationCohort:0,tcpCandidatePorts:[],onlyOneRemoteSenderAtATime:true,confirmedOldSendersClosed:0};
const udpOut=fs.createWriteStream(dir+'/udp-samples-private.jsonl'),loadOut=fs.createWriteStream(dir+'/load-samples-private.jsonl');let ended=false,client,stream,remoteReady=false,rotatingTo=null,sock,udpTimer,statusTimer,hardTimer;
const known=spawnSync('ssh-keygen',['-F',c.tcpServerAddress],{encoding:'utf8',windowsHide:true,timeout:3000});assert.equal(known.status,0);
const pins=known.stdout.split(/\r?\n/).filter(x=>x&&!x.startsWith('#')).map(x=>crypto.createHash('sha256').update(Buffer.from(x.trim().split(/\s+/)[2],'base64')).digest('hex'));assert.ok(pins.length);
const quote=x=>"'"+x.replaceAll("'","'\\''")+"'",py=fs.readFileSync(new URL('./download-server.py',import.meta.url),'utf8');
function stamp(){if(ended)return;stats.tcpCandidatePorts=stats.tcpConnected&&remoteReady&&rotatingTo===null?[stats.tcpSourcePort]:[];const x={...stats,at:Date.now()/1000,elapsed:(performance.now()-began)/1000};fs.writeFileSync(dir+'/status-private.json.new',JSON.stringify(x));try{fs.renameSync(dir+'/status-private.json.new',dir+'/status-private.json')}catch(e){if(e.code!=='EPERM'&&e.code!=='EBUSY')throw e;stats.statusPublicationDeferrals=(stats.statusPublicationDeferrals??0)+1}loadOut.write(JSON.stringify(x)+'\n');}
function stop(reason){if(ended)return;ended=true;clearInterval(udpTimer);clearInterval(statusTimer);clearTimeout(hardTimer);if(reason)stats.errors.push(reason);sock?.close();if(stream?.writable&&!stream.destroyed)stream.write('STOP\n');client?.destroy();fs.writeFileSync(dir+'/result-private.json',JSON.stringify({...stats,finishedAt:Date.now()/1000,seconds:(performance.now()-began)/1000},null,2));udpOut.end();loadOut.end();setTimeout(()=>process.exit(stats.errors.length?1:0),50);}
function connectTcp(port){assert.equal(rotatingTo,null);assert.ok(port>=c.tcpSourcePort&&port<c.tcpSourcePort+8);remoteReady=false;stats.tcpSourcePort=port;stats.tcpConnected=false;client=new ssh2.Client();const current=client;let closedReceipt=null;
 current.on('error',e=>{if(!ended&&current===client)stop('Owned SSH: '+e.message)});
 current.on('ready',()=>{if(ended||current!==client)return;current.exec('timeout -k 1 185 python3 -u -c '+quote(py),(e,s)=>{if(e){stop(String(e));return}stream=s;let pending='';
  s.stderr.on('data',b=>{if(ended)return;try{pending+=b.toString();assert.ok(pending.length<=4096);let at;while((at=pending.indexOf('\n'))>=0){const x=JSON.parse(pending.slice(0,at));pending=pending.slice(at+1);if(x.event==='ready'){validateServerReady(x);remoteReady=true;stats.tcpConnected=true;}else{assert.equal(x.event,'closed');closedReceipt=x;}}}catch(e){stop('Owned sender receipt: '+String(e));}});
  s.on('data',b=>{if(ended||current!==client)return;stats.tcpBytes+=b.length;if(stats.tcpBytes>1073741824)stop('Original total byte limit exceeded');});
  s.on('close',code=>{if(ended||current!==client)return;try{stats.tcpConnected=false;if(rotatingTo!==null){canReplaceSender(code,closedReceipt);const next=rotatingTo;rotatingTo=null;stats.confirmedOldSendersClosed++;current.destroy();stream=null;loadOut.write(JSON.stringify({event:'owned-sender-closed-before-next',at:Date.now()/1000,sourcePort:port,serverStopped:true})+'\n');connectTcp(next);}else stop(code&&code!==124?'Owned sender exited '+code:undefined);}catch(e){stop(String(e));}});
 });});
 current.connect({sock:net.connect({host:c.tcpServerAddress,port:22,localAddress:c.clientAddress,localPort:port}),username:'ubuntu',privateKey:fs.readFileSync(c.sshKeyPath),hostHash:'sha256',hostVerifier:h=>pins.includes(h),readyTimeout:6000,keepaliveInterval:0});
}
sock=dgram.createSocket('udp4');sock.on('error',e=>stop(String(e)));sock.on('message',b=>{if(b.length!==128||!b.subarray(0,32).equals(token))return;const number=Number(b.readBigUInt64BE(32));if(seen.has(number))return;seen.add(number);stats.udpReceived++;udpOut.write(JSON.stringify({event:'reply',sequence:number,at:Date.now()/1000,sourcePort:c.udpSourcePort,rttMs:performance.now()-b.readDoubleBE(40)})+'\n');});sock.bind(c.udpSourcePort,c.clientAddress,()=>sock.connect(c.udpPort,c.serverAddress));let seq=0;
udpTimer=setInterval(()=>{if(ended)return;try{const p=dir+'/control.json';if(fs.existsSync(p)){const x=JSON.parse(fs.readFileSync(p));assert.equal(x.session,c.session);assert.equal(x.udpSourcePort??c.udpSourcePort,c.udpSourcePort);if(x.stop){stop();return}if(x.selectTcpPort!==undefined){assert.equal(x.selectTcpPort,stats.tcpSourcePort);assert.equal(rotatingTo,null);assert.ok(stats.tcpConnected);stats.selectedTcpPort=x.selectTcpPort;}if(x.tcpSourcePort!==undefined&&x.tcpSourcePort!==stats.tcpSourcePort&&rotatingTo===null){assert.equal(x.tcpSourcePort,nextPort(c.tcpSourcePort,stats.tcpSourcePort,stats.selectedTcpPort));assert.ok(remoteReady&&stream);rotatingTo=x.tcpSourcePort;stats.tcpConnected=false;stream.write('STOP\n');}}
const b=Buffer.alloc(128);token.copy(b);b.writeBigUInt64BE(BigInt(seq),32);b.writeDoubleBE(performance.now(),40);sock.send(b,e=>{if(e&&!ended)stop(String(e))});stats.udpSent++;udpOut.write(JSON.stringify({event:'sent',sequence:seq++,at:Date.now()/1000,sourcePort:c.udpSourcePort})+'\n');}catch(e){stop(String(e));}},20);
statusTimer=setInterval(stamp,250);hardTimer=setTimeout(()=>stop(),180000);stamp();connectTcp(c.tcpSourcePort);
