import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {connectRouter} from '../nss27/connect-router.mjs';import {encode,receipt} from '../nss11/v7-observe-repair/observe2/transport.mjs';
import {packLua} from '../nss149/pack-lua.mjs';import {buildPayload} from './payload.mjs';import {mapClassifiedPair} from '../nss127/class-leaf-map.mjs';import {packetTemplate} from '../nss140/uplink-tag-plan.mjs';
const root='work/v12',dir=root+'/native-qualification';fs.mkdirSync(dir);const fast=fs.readFileSync(root+'/fast-path.lua','utf8'),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const cut=(s,a,b)=>{const i=s.indexOf(a),z=s.indexOf(b,i);assert.ok(i>=0&&z>i,a);return s.slice(i,z)};
const code="local j=require('luci.jsonc');\n"+fs.readFileSync(root+'/duration-model.lua','utf8').replace('__VERIFY__',()=>cut(fast,'function M.verifyReclassification(','function M.new(')).replace('__OBSERVE__',()=>cut(fast,' local function observe()',' local function counters(')).replace('__RETIRE__',()=>cut(fast,' retire=function(C)',' local function tick(')).replace('__TICK_MEASURE__',()=>cut(fast,' local function tick(name)',' function out.align(')).replace('__RUN__',()=>cut(fast,' function out.run(due,',' return out'));
fs.writeFileSync(dir+'/model-rendered-private.lua',code,{flag:'wx'});
const first=JSON.parse(fs.readFileSync('work/nss156/run7/second-case-private.json')),input=JSON.parse(fs.readFileSync(first.dir+'/stage-plan-private.json')),frame=JSON.parse(fs.readFileSync(first.dir+'/post-checkpoint-controlled-receipt-private.json'));
const selected=structuredClone(input.selected);for(const f of Object.values(selected))delete f.classifierKey;const template=packetTemplate(mapClassifiedPair(frame,selected),input.tagPlan.owner,selected.udp.original.sport===59999?59998:59999);template.expected.nftables=template.expected.nftables.filter(x=>x.chain?.name!=='forward'&&x.rule?.chain!=='forward');input.tagPlan={table:template.expected.nftables[0].table.name,owner:input.tagPlan.owner,mode:'rt',expected:template.expected};
const paths={qos:'work/nss149/qos-physical.lua',phase:'work/nss69/core-guard-phase.lua',classifier:'work/nss157/classifier-complete-wait.lua',tags:'work/nss49/classified-tags.lua',normalizer:'work/nss149/tag-normalizer.lua'};
const built=buildPayload(input,Object.fromEntries(Object.entries(paths).map(([k,p])=>[k,fs.readFileSync(p,'utf8')])));const bytes=Buffer.byteLength(built.stagedCode);assert.ok(bytes<=73728);
const codec="local j=require('luci.jsonc');local actual=(function()\n"+built.tagSource+"\nend)();local expected=assert(j.parse([====["+JSON.stringify(input.tagPlan)+"]====]));local function eq(a,b)assert(type(a)==type(b));if type(a)~='table'then assert(a==b);return end;for k,v in pairs(a)do assert(b[k]~=nil);eq(v,b[k])end;for k in pairs(b)do assert(a[k]~=nil)end end;eq(actual,expected);print('EXACT_NATIVE_TAG_RECONSTRUCTION_OK')";
const commands={model:encode("lua - <<'NSS157_COMBINED_MODEL'\n"+code+"\nNSS157_COMBINED_MODEL\n"),syntax:encode("lua - <<'NSS157_SYNTAX'\nassert(loadstring([====["+packLua(fast)+"]====]));print('FAST_SYNTAX_OK')\nNSS157_SYNTAX\n"),codec:encode("lua - <<'NSS157_CODEC'\n"+codec+"\nNSS157_CODEC\n")};
let model;const c=await connectRouter();try{for(const[name,e]of Object.entries(commands)){const raw=receipt(await c.run(e.command),e);fs.writeFileSync(dir+'/'+name+'-raw-private.json',JSON.stringify(raw,null,2)+'\n',{flag:'wx'});assert.equal(raw.code,0,name+' RAM failed; source/output retained');if(name==='model'){model=JSON.parse(raw.stdout);assert.ok(model.passed&&model.checks===1&&model.sixtySecondsObserved&&!model.fullFactoryModeled)}else assert.equal(raw.stdout.trim(),name==='syntax'?'FAST_SYNTAX_OK':'EXACT_NATIVE_TAG_RECONSTRUCTION_OK')}}finally{c.close()}
const result={passed:true,observedAt:new Date().toISOString(),fastSourceSha256:hash(fast),model,fullFactoryModeled:false,nativeFullFastSyntaxPassed:true,nativeExactTagReconstructionPassed:true,oneActualHistoricalClassInputHash:hash(JSON.stringify(frame)),combinedHistoricalPayloadBytes:bytes,originalCaps:[9000,65536,73728],execBytes:Object.fromEntries(Object.entries(commands).map(([k,e])=>[k,e.execBytes])),productionExecuted:false,filesWrittenOnRouter:false,evidenceRecordedExactlyOnceAndTerminalUsesFieldReference:true,originalPreciseGateRetirementBodyUnchanged:true};fs.writeFileSync(root+'/native-qualified.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result));
