import fs from 'node:fs';
const s=JSON.parse(fs.readFileSync('outputs/nss36-admission-timing-observations.json'));
const t=s.actualTrial,m=s.postTrialRehearsal.performance,p=s.publicationPathProfile;
const esc=x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>NSS36 · 真人准入与时序定位</title><style>body{margin:0;background:#f4f6f8;color:#1c2d40;font:16px/1.75 system-ui,sans-serif}main{max-width:1060px;margin:40px auto;background:#fff;padding:32px;border-radius:16px}h1{font-size:29px}h2{font-size:21px;margin-top:30px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:10px;border:1px solid #d7dfe8;text-align:left}code{overflow-wrap:anywhere}.status{border-left:4px solid #b07b18;background:#fff4dd;padding:16px}.muted{color:#56667a}a{color:#155a9c}@media(max-width:700px){main{margin:0;padding:20px;border-radius:0}table{font-size:12px}th,td{padding:6px}}</style><main>
<h1>NSS36：真人短测退出于准入阶段</h1><p class="muted">2026-10-03 · 北京时间 17:14–17:15 现场尝试；后续只读诊断见时间记录</p>
<p class="status">控制器已绑定 NSS35，299 项检查通过。真实 CS2＋Steam 同 WAN 连接对已选中，但 44 次准入均因时间余量不足被拒绝。ECM 未开启，bulk／RT leaf 都为 0 包。独立恢复与现网核验通过，当前仍为软件转发。</p>
<h2>本轮实际改变与回滚</h2><p>配置未更换。候选控制器先检查所选身份和类别，仅对明确的时间余量不足等待下一帧；其余原因立即退出。108 组新旧差分检查的准入结果一致。原有有效期、学习屏障、单流精确 gate 和续租限制保持原样。</p>
<p>现场先核验 CS2 端口及 Steam TCP 归属，再创建并校验检查点，启动独立 45 秒 owner。仅 WAN${t.wan} 临时转 private，并准备物理 LAN4 NSS 队列树。两流完整 mark 均为 <code>0x${t.tcpMark.toString(16)}</code>，原 NAT 相同；尚无加速后的 mark／NAT／WAN affinity 验收。</p>
<p>初始有效等待约 ${t.initialAlignmentSeconds.toFixed(2)} 秒：36 次 pre-learning 余量不足，8 次 tag 设置预留不足。尚未设置 packet tags、加载 gate 或开启 ECM。default leaf 承载约 ${(t.defaultLeaf.bytes/1e6).toFixed(1)} MB；这不证明 bulk／RT 分类成功。WAN 模式、队列、模块、状态节点和受保护配置全部恢复。没有重新认证或 DHCP 续租试验。</p>
<h2>定位所得证据</h2><p>后续 18 秒只读窗口中，原 TCP 候选持续存在，所选游戏已不在候选中；不能据此解释为原现场丢失游戏。分类发布相对 CT 采集起点延迟 0.77–1.21 秒，单次完整读取最多 0.26 秒。初始准入要求采集年龄小于 1 秒，说明发布时间和读取开销会占满这个窗口。原失败没有记录逐次来源序号，全部时延来源尚未证实。</p>
<table><tr><th>单次只读／RAM 微测量</th><th>观测</th></tr><tr><td>连接文本行数</td><td>${p.sourceRows} 行，分类后 ${p.classifiedRows} 行</td></tr><tr><td>CT 查询</td><td>${p.ctQuerySeconds.toFixed(2)} 秒</td></tr><tr><td>文本校验／标准化</td><td>${p.sourceNormalizeSeconds.toFixed(2)} 秒</td></tr><tr><td>分类核心冷回放</td><td>${p.coreReplaySeconds.toFixed(2)} 秒</td></tr><tr><td>现有候选 JSON 解析／重编码</td><td>${p.liveParseSeconds.toFixed(2)}／${p.liveEncodeSeconds.toFixed(2)} 秒</td></tr></table>
<p class="muted">微测量使用独立只读采集及目标内存回放，没有给生产 worker 加计时器；它定位候选开销，不能当作生产逐步追踪或修改后收益。</p>
<h2>软件路径诊断负载</h2><table><tr><th>窗口</th><th>LAN4</th><th>pps</th><th>busy</th><th>softirq</th><th>time_squeeze</th></tr><tr><td>${m.seconds.toFixed(2)} 秒</td><td>${m.lan4DownMbps.toFixed(2)} Mbps</td><td>${m.lan4DownPps.toFixed(0)}</td><td>${m.cpuBusyPercent.toFixed(2)}%</td><td>${m.softirqPercent.toFixed(2)}%</td><td>+${m.timeSqueezeDelta}</td></tr></table><p class="muted">这是短测结束后的单独软件窗口，包含只读观测开销；游戏候选已退出，没有可比较的 NSS 阶段，不能计算 CPU／延迟收益。未取得 CS2 jitter／loss／Miss。</p>
<h2>检查覆盖与当前状态</h2><ul>${s.testParts.map(x=>`<li>${esc(x.name)}：${x.checks} 项。${esc(x.scope??'分层离线检查')}</li>`).join('')}</ul><p>生命周期涵盖冷启动、端口更换、旧流退出、restart／crash 的模拟恢复和精确自有规则接管；没有向生产服务注入 crash。结束审计曾因快照过旧失败，随后复查通过；分类器仍为同一实例，不能据最后一次通过宣称全程新鲜。</p>
<h2>唯一下一步</h2><p>减少 CT 文本校验和分类发布开销，并检查同步软件维护是否拖长采样周期。先做相同输入的差分回放，保持全字段校验、策略和所有新鲜度边界，再准备有独立回滚的部署。无需维持游戏或下载；准备通过后再集中一次真人单 WAN 闭环。暂不扩第二 WAN 或其他 QoS 支线。</p><p><a href="https://github.com/ZyPulse-zy/athena-nss-mainline">私有 GitHub 主线仓库</a> · <a href="nss36-admission-timing-observations.json">结构化观测</a></p></main></html>`;
fs.writeFileSync('outputs/nss36-admission-timing-report.html',html);console.log(JSON.stringify({report:'outputs/nss36-admission-timing-report.html',nssEnabled:false,realABACompleted:false}));
