import fs from 'node:fs';import assert from 'node:assert/strict';
const root='work/nss36',trial=root+'/real-matched-aba-20261003091409-28454bad';
const read=p=>JSON.parse(fs.readFileSync(p));const pick=(o,ks)=>Object.fromEntries(ks.filter(k=>k in o).map(k=>[k,o[k]]));
const d=read('work/nss35/deployment-latest.json'),r=read(trial+'/last-record-private.json'),result=read(trial+'/result.json'),affinity=read(root+'/affinity-qualified.json');
const audit=read(root+'/final-recheck-audit.json'),closure=read(root+'/final-closure.json');
assert.ok(d.committed&&audit.passed&&closure.passed&&affinity.passed);
assert.equal(result.matchedForwardingABACompleted,false);assert.equal(r.newNssPermit,false);assert.equal(r.moduleLoaded,false);
assert.equal(r.tagEpochUntil,undefined);assert.equal(r.classifiedChoice,undefined);assert.equal(Object.keys(r.classifierSnapshots).length,0);
const reason=x=>x.replace(/^\[string .*?\]:\d+: /,'');const probes=r.initialAlignment.probes;const counts={};for(const p of probes){const k=reason(p[2]);counts[k]=(counts[k]??0)+1;assert.equal(p[1],false);assert.equal(p[3],true);}
assert.equal(probes.length,44);
const plan=read(trial+'/stage-plan-private.json'),baseline=read(trial+'/baseline-audit.json'),undo=read(trial+'/stage-undo-verified.json');
const receipt=read(trial+'/stage-receipt-private.json'),cp=read(trial+'/stage-checkpoint-verified.json');
assert.ok(baseline.configurationMatches&&baseline.checks.ecmStoppedAndZero&&Object.values(undo).every(x=>x===true));
assert.ok(receipt.rollbackBeforeFirstWrite&&receipt.parentIdentityVerified&&receipt.pipeInodesVerified&&cp.gzipVerified);
const selected=read(trial+'/selected-private.json');const rehearsal=read(read(root+'/rehearsal-summary.json').path);
function metrics(rows){const a=rows[0],b=rows.at(-1),dt=b.uptime-a.uptime;const cpu=s=>s.cpu.trim().split(/\s+/).slice(1,9).map(Number),x=cpu(a),y=cpu(b),delta=y.map((v,i)=>v-x[i]),total=delta.reduce((s,n)=>s+n,0);const squeeze=s=>s.softnet.trim().split('\n').reduce((n,l)=>n+parseInt(l.trim().split(/\s+/)[2],16),0);return{seconds:dt,lan4DownMbps:(b.txBytes-a.txBytes)*8/dt/1e6,lan4DownPps:(b.txPackets-a.txPackets)/dt,cpuBusyPercent:100*(total-delta[3]-delta[4])/total,softirqPercent:100*delta[6]/total,timeSqueezeDelta:squeeze(b)-squeeze(a),ecmAlwaysClosedAndZero:rows.every(x=>x.stop4===1&&x.accel===0),measurement:'Separate post-trial software-only diagnostic; same attempted game no longer classified; includes observer overhead. Not matched ABA.'};}
function leaf(h){const s=r.qosBeforeUndo.qdisc;const m=s.match(new RegExp('qdisc nssfq_codel '+h+'[\\s\\S]*?Sent (\\d+) bytes (\\d+) pkt'));assert.ok(m);return{bytes:Number(m[1]),packets:Number(m[2])};}
const parts=[['admission',212],['consumer',21],['lifecycle',26],['owned-lifecycle',19]].map(([n,k])=>{const v=read(root+'/'+n+'-qualified.json');assert.ok(v.passed&&v.checks===k);return{name:n,checks:k,scope:v.scope,cases:v.cases}});
const aba=read(root+'/aba-qualified.json');assert.ok(aba.passed&&aba.cases.length===11&&affinity.checks.length===10);
parts.push({name:'target RAM A/B/A2 mocks',checks:aba.cases.length,scope:'Actual target Lua/jsonc with mocked time, counters and native APIs; no forwarding.'},{name:'affinity',checks:affinity.checks.length,scope:'Synthetic exact single-WAN selection constraints; no routing changes.'});
const inspect=read(root+'/classifier-final-inspection.json'),begin=read(root+'/classifier-begin-inspection.json');
const stale=read(root+'/final-ownership-raw-private.json');assert.equal(stale.code,1);assert.ok(stale.stderr.includes('stdin:32: assertion failed!'));
const out={round:'NSS36',updatedAt:new Date().toISOString(),checks:parts.reduce((n,x)=>n+x.checks,0),testParts:parts,
 controller:{deploymentReference:'work/nss35/deployment-latest.json',configuration:pick(affinity.configuration,['configSha256','workerSha256','guardianSha256','classifierCoreSha256','policyUnchanged','ctSourceUnchanged','sourceAndPublicationDeadlinesUnchanged']),adapterSha256:read(root+'/admission-qualified.json').adapterSha256,fastSourceSha256:read(root+'/admission-qualified.json').fastSourceSha256,sourceManifestEntries:Object.keys(affinity.sourceManifest).length,differentialAdmissionCases:108,recordedTimingCases:66,change:'Selected identity/class checks precede margin checks. Only exact local time-reserve failures retry; other refusal exits immediately. Admission TTL, learning barriers, renewal and gate permissions unchanged.'},
 actualTrial:{attempted:true,passed:false,matchedForwardingABACompleted:false,applicationPairVerifiedTwiceBeforeCheckpoint:true,wan:selected.tcp.wan,tcpMark:selected.tcp.mark,udpMark:selected.udp.mark,sameFullMark:selected.tcp.mark===selected.udp.mark,sameNat:selected.tcp.reply.dst===selected.udp.reply.dst,selectedSubgroupCeilingMbps:20,unselectedPhysicalFallbackMbps:950,independentOwnerSeconds:45,checkpointVerified:true,rollbackBeforeFirstWrite:true,detachedOwnerVerified:true,temporarySingleWanPrivate:true,physicalLan4QosTreePrepared:r.qosReady?.validation?.complete===true,initialAlignmentSeconds:r.initialAlignment.stop-r.initialAlignment.start,actualLastProbeSeconds:probes.at(-1)[0]-r.initialAlignment.start,probeCount:probes.length,readyCount:0,refusalCounts:counts,gateModuleLoaded:r.moduleLoaded,nssPermissionGranted:r.newNssPermit,packetTagRulesInstalled:false,bulkLeaf:leaf('8f05:'),rtLeaf:leaf('8f06:'),defaultLeaf:leaf('8fff:'),pbrNatWanAffinityAfterAccelerationProved:false,rollbackPassed:true,wanRestored:r.wanRestored,qosRestored:r.qosRestored,modulesRemoved:undo.moduleAbsent&&undo.qosModuleAbsent,protectedConfigurationUnchanged:baseline.configurationMatches,authenticationAndDhcpIdentityPreserved:r.wanHealthAfterUndo===true,renewalReauthenticationTested:false,initialSourceSequenceNotRecorded:true},
 initialAdmissionTrace:probes.map(p=>({atSeconds:p[0]-r.initialAlignment.start,ready:p[1],reason:reason(p[2]),retryable:p[3]})),
 postTrialRehearsal:{observedAt:rehearsal.observedAt,samples:rehearsal.rows.length,ready:rehearsal.rows.filter(v=>v.ready).length,selectedTcpPresent:rehearsal.rows.filter(v=>v.selected.tcp.present).length,selectedGamePresent:rehearsal.rows.filter(v=>v.selected.udp.present).length,currentApplicationOwnershipRechecked:false,sourceAgeRangeSeconds:[Math.min(...rehearsal.rows.map(v=>v.sourceAge)),Math.max(...rehearsal.rows.map(v=>v.sourceAge))],publicationDelayRangeSeconds:[Math.min(...rehearsal.rows.map(v=>v.publicationDelay)),Math.max(...rehearsal.rows.map(v=>v.publicationDelay))],readMaxSeconds:Math.max(...rehearsal.rows.map(v=>v.readSeconds)),performance:metrics(rehearsal.telemetry)},
 publicationPathProfile:read(root+'/publication-path-profile.json'),
 finalState:{observedAt:inspect.observedAt,configSha256:d.configHash,permanentClassifierUnchanged:true,sameProducer:inspect.files['classification.json'].producer===begin.files['classification.json'].producer,previousAuditRejectedStaleSnapshot:true,subsequentAuditPassed:audit.passed,protectedConfigurationUnchanged:audit.protectedConfigurationUnchanged,exactOwnedNativeAudit:audit.exactOwnedNativeAudit,ecmClosedAndZero:audit.ecmClosedAndZero,selectors:audit.selectors,queryAge:audit.queryAge,sequence:audit.sequence,closure},
 limitations:{realHighLoadABACompleted:false,nssCpuBenefitProved:false,gameJitterLossMissCaptured:false,productionCrashInjected:false,wholeSteam300MbpsAccelerated:false,allPublicationDelayCausesProved:false,completeHighLoadLifecycleQualified:false,sourceOptimizationInstalled:false},
 next:'Reduce verified CT normalization/classification publication cost while preserving exact identities, classifier policy, source scope and every freshness bound; differential replay and bounded deployment/rollback qualification first. Then one concentrated real same-WAN pair retry. No second WAN or QoS side branches.',upstreamSubmission:false};
assert.equal(out.checks,299);assert.equal(out.actualTrial.bulkLeaf.packets,0);assert.equal(out.actualTrial.rtLeaf.packets,0);
fs.writeFileSync('outputs/nss36-admission-timing-observations.json',JSON.stringify(out,null,2)+'\n');
const start=rehearsal.rows[0].at;fs.writeFileSync(root+'/admission-timing-sanitized.json',JSON.stringify({observedAt:rehearsal.observedAt,routerWrites:false,initialFailedAttempt:false,historicalSelectedGameAbsent:true,rows:rehearsal.rows.map(v=>({atSeconds:v.at-start,...pick(v,['ready','retryable','sourceAge','publicationDelay','querySeconds','readSeconds','bytes','status']),reason:reason(v.reason??''),tcpPresent:v.selected.tcp.present,udpPresent:v.selected.udp.present}))},null,2)+'\n');
console.log(JSON.stringify({checks:out.checks,actualTrial:out.actualTrial,postTrialDiagnostic:out.postTrialRehearsal.performance,finalState:out.finalState}));
