import assert from'node:assert/strict';
export function validateAcceleratedState(raw,selected){
 const rows=new Map();for(const line of raw.trim().split('\n')){if(!line)continue;const m=line.match(/^conns\.conn\.(\d+)\.([^=]+)=(.*)$/);assert.ok(m,'Unexpected state line');const r=rows.get(m[1])??{};assert.ok(!(m[2]in r),'Duplicate state key');r[m[2]]=m[3];rows.set(m[1],r)}
 assert.equal(rows.size,2,'Unexpected ECM connection scope');const proof={};
 for(const[slot,tag]of[['tcp',2399469568],['udp',2399535104]]){const f=selected[slot];const direction=r=>r.sip_address===f.original.src&&r.dip_address===f.original.dst&&Number(r.sport)===f.original.sport&&Number(r.dport)===f.original.dport?'client-first':r.sip_address===f.original.dst&&r.dip_address===f.original.src&&Number(r.sport)===f.original.dport&&Number(r.dport)===f.original.sport?'server-first':null;const matches=[...rows].filter(([,r])=>Number(r.protocol)===f.protocol&&direction(r));assert.equal(matches.length,1);const[serial,r]=matches[0];const reverse=direction(r)==='server-first';assert.equal(r.ip_version,'4');assert.equal(r.is_routed,'1');assert.equal(r.sip_address_nat,reverse?f.reply.src:f.reply.dst);assert.equal(Number(r.sport_nat),reverse?f.reply.sport:f.reply.dport);assert.equal(r.dip_address_nat,reverse?f.reply.dst:f.reply.src);assert.equal(Number(r.dport_nat),reverse?f.reply.dport:f.reply.sport);assert.equal(r['nss_v4.ported.accel_mode'],'2');assert.equal(Number(r['classifiers.dscp.pr.flow_qos_tag']),reverse?tag:0);assert.equal(Number(r['classifiers.dscp.pr.return_qos_tag']),reverse?0:tag);assert.equal(Number(r['classifiers.dscp.pr.'+(reverse?'return':'flow')+'_mark']),f.mark);
  for(const prefix of reverse?['from_interfaces','from_nat_interfaces']:['to_interfaces','to_nat_interfaces']){assert.ok(Object.entries(r).some(([k,v])=>k.startsWith(prefix+'.')&&k.endsWith('.iface.name')&&v==='rpwan5'),'WAN affinity absent');assert.ok(Object.entries(r).some(([k,v])=>k.startsWith(prefix+'.')&&k.endsWith('.iface.name')&&v==='wan'),'Physical WAN missing')}
  const lan=reverse?'to_interfaces.':'from_interfaces.';assert.ok(Object.entries(r).some(([k,v])=>k.startsWith(lan)&&k.endsWith('.iface.name')&&v==='lan4'));assert.ok(Object.entries(r).some(([k,v])=>k.startsWith(lan)&&k.endsWith('.iface.name')&&v==='br-lan'));
  proof[slot]={serial,protocol:f.protocol,ecmOrientation:direction(r),accelerated:true,ctMark:f.mark,downTag:tag,upTag:0,natCorrect:true,wanAffinity:5,fromLan4:true,fromBridgeLan:true,slowPathPackets:Number(r['nss_v4.ported.slow_path_packets']),fromPackets:Number(r['adv_stats.from_packet_total']),toPackets:Number(r['adv_stats.to_packet_total'])};
 }
 return{passed:true,connectionCount:rows.size,proof};
}
