// Correct only protocol-specific peer selection; original two /32 rules and guardian.
import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {gzipSync,gunzipSync} from 'node:zlib';
import {persistentSsh} from '../v27-raw/persistent-ssh.mjs';
const root='work/v29-peer-proof',stamp=new Date().toISOString().replace(/\D/g,'').slice(0,14),id=crypto.randomBytes(8).toString('hex'),dir=root+'/run-'+stamp+'-'+id;fs.mkdirSync(dir);
const save=(name,x)=>fs.writeFileSync(dir+'/'+name+'.json',JSON.stringify(x,null,2)+'\n',{flag:'wx'}),hash=x=>crypto.createHash('sha256').update(x).digest('hex'),quote=x=>"'"+x.replaceAll("'","'\\''")+"'";
const c={serverAddress:'172.93.163.251',clientAddress:'192.168.237.207',tcpPort:45817,udpPort:45818,tcpSourcePort:57000+crypto.randomInt(1800),udpSourcePort:59000+crypto.randomInt(800),token:crypto.randomBytes(32).toString('hex'),seconds:25};save('config-private',c);
fs.mkdirSync(dir+'/source-input-private');const sourceInputs=[];for(const p of [root+'/run.mjs',root+'/client.mjs',root+'/capture.py','work/v27-raw/endpoint-firewall-guardian.py','work/v27-raw/receiver.py','work/v27-raw/raw-server.py','work/v27-raw/raw-policy.mjs','work/v27-raw/persistent-ssh.mjs']){const b=fs.readFileSync(p),stored=p.replaceAll('/','__');fs.writeFileSync(dir+'/source-input-private/'+stored,b,{flag:'wx'});sourceInputs.push({path:p,sha256:hash(b),bytes:b.length,stored});}save('source-inputs-private',sourceInputs);
const channel=persistentSsh(),unit='v29-peer-'+id,guardian=fs.readFileSync('work/v27-raw/endpoint-firewall-guardian.py','utf8');let client,startedUnit=false;
async function remote(command,input=''){assert.ok(Buffer.byteLength(command)<=9000);assert.ok(Buffer.byteLength(input)<=65536);const r=await channel.exec(command,input,{milliseconds:12000});save('ssh-'+crypto.randomBytes(4).toString('hex')+'-private',r);assert.equal(r.code,0,'Saved remote step failed');return r.stdout;}
try{
 const free=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',`@{tcp=@(Get-NetTCPConnection -LocalPort ${c.tcpSourcePort} -ErrorAction SilentlyContinue).Count;udp=@(Get-NetUDPEndpoint -LocalPort ${c.udpSourcePort} -ErrorAction SilentlyContinue).Count}|ConvertTo-Json -Compress`],{encoding:'utf8',windowsHide:true,timeout:8000});save('local-ports-private',free);assert.equal(free.status,0);assert.deepEqual(JSON.parse(free.stdout),{tcp:0,udp:0});
 const initial=JSON.parse(await remote('python3 -B -E -s -u -',guardian+"\nb=nft(['-j','list','ruleset'])\nassert not any(x.get('rule',{}).get('comment','').startswith('nss14-') for x in b['nftables'])\nwith open('/proc/sys/kernel/random/boot_id') as f:boot=f.read().strip()\np=subprocess.run(['ss','-H','-lntup'],capture_output=True,text=True,check=True)\nassert ':45817 ' not in p.stdout and ':45818 ' not in p.stdout\nprint(json.dumps({'boot':boot,'before':b,'canonicalSha256':hashlib.sha256(canonical(b).encode()).hexdigest(),'portsClosed':True}))\n"));
 save('endpoint-checkpoint-private',initial);const downloaded=fs.readFileSync(dir+'/endpoint-checkpoint-private.json'),packed=gzipSync(downloaded);fs.writeFileSync(dir+'/endpoint-checkpoint-private.json.gz',packed,{flag:'wx'});assert.deepEqual(gunzipSync(fs.readFileSync(dir+'/endpoint-checkpoint-private.json.gz')),downloaded);save('checkpoint-verified',{downloaded:true,sha256:hash(downloaded),gzipSha256:hash(packed),gzipRoundtripPassed:true,canonicalSha256:initial.canonicalSha256,portsClosed:true,noExistingOwnedRules:true});
 const server=fs.readFileSync('work/v27-raw/receiver.py','utf8')+'\n'+fs.readFileSync('work/v27-raw/raw-server.py','utf8'),settings={token:c.token,mbps:32,seconds:240,tcpPort:45817,udpPort:45818};
 await remote('systemd-run --unit='+unit+' --collect --property=RuntimeMaxSec=250 --property=KillMode=mixed /usr/bin/python3 -u -c '+quote(server)+' '+quote(JSON.stringify(settings)));startedUnit=true;
 const owned=await remote('systemctl show '+unit+' -p MainPID -p ActiveState -p RuntimeMaxUSec -p KillMode; ss -H -lntup');assert.match(owned,/MainPID=[1-9]\d*/);const endpointPid=Number(owned.match(/MainPID=(\d+)/)[1]);assert.ok(owned.includes('ActiveState=active')&&owned.includes('RuntimeMaxUSec=4min 10s')&&owned.includes('KillMode=mixed'));for(const port of [45817,45818])assert.ok(owned.split(/\r?\n/).some(x=>x.includes(':'+port+' ')&&x.includes('pid='+endpointPid+',')));save('independent-endpoint-deadline-private',{unit,pid:endpointPid,state:owned,sourceSha256:hash(server),seconds:250,verifiedBeforeClient:true});
 const capSource=fs.readFileSync(root+'/capture.py','utf8');
 let out='',ended=false;const captured=channel.exec('timeout -k 1 12 python3 -B -E -s -u -c '+quote(capSource)+' '+quote(JSON.stringify(c)),'',{milliseconds:15000,onStdout:s=>out+=s}).then(r=>{ended=true;save('capture-private',r);return r;},e=>{ended=true;const r={code:-1,stdout:out,stderr:String(e)};save('capture-private',r);return r;});
 const before=performance.now();while(!out.includes('OWNED_PEER_CAPTURE_READY')&&!ended&&performance.now()-before<5000)await new Promise(r=>setTimeout(r,10));assert.ok(out.includes('OWNED_PEER_CAPTURE_READY'),'No traffic before capture ready');
 client=spawn(process.execPath,[root+'/client.mjs',dir+'/config-private.json'],{windowsHide:true,stdio:['ignore','pipe','pipe']});let err='';client.stderr.on('data',b=>err+=b);const done=new Promise(resolve=>client.once('close',code=>resolve({code,stderr:err})));save('client-independent-deadline',{pid:client.pid,seconds:25,intrinsicTimerIndependentOfController:true});
 const start=performance.now();while(!out.includes('PEER_READY ')&&!ended&&performance.now()-start<2500)await new Promise(r=>setTimeout(r,10));
 const line=out.split(/\r?\n/).find(x=>x.startsWith('PEER_READY '));assert.ok(line,'No protocol-specific peers within original first-byte budget');const peers=JSON.parse(line.slice(11));assert.ok(Date.now()/1000-peers.at<1);
 const owner=crypto.randomBytes(16).toString('hex'),fw={mode:'apply',owner,peers:{tcp:peers.tcp,udp:peers.udp},boot:initial.boot,baselineCanonicalSha256:initial.canonicalSha256};save('firewall-settings-private',fw);
 const cp=JSON.parse(await remote('python3 -B -E -s -u -',guardian+`\nc=${JSON.stringify(fw)}\nb=nft(['-j','list','ruleset'])\nassert hashlib.sha256(canonical(b).encode()).hexdigest()==c['baselineCanonicalSha256']\nnft(['-c','-j','-f','-'],{'nftables':allow_commands(c)})\nprint(json.dumps({'checkpointStillExact':True,'syntaxPassed':True}))\n`));save('firewall-write-precondition',cp);
 const fwReceipt=JSON.parse(await remote('python3 -B -E -s -u -',guardian+'\nrun('+JSON.stringify(fw)+')\n'));save('firewall-receipt-private',fwReceipt);assert.ok(fwReceipt.applied&&fwReceipt.beforeWriteIndependentGuardianVerified&&fwReceipt.rules.length===2);
 const detached=JSON.parse(await remote('python3 -B -E -s -u -',guardian+`\ni=identity(${fwReceipt.identity.pid})\nassert i['start']==${JSON.stringify(fwReceipt.identity.start)} and i['pgrp']==i['pid'] and i['session']==i['pid'] and i['ppid']==1\nfds={x:os.readlink('/proc/'+str(i['pid'])+'/fd/'+x) for x in os.listdir('/proc/'+str(i['pid'])+'/fd')}\nassert fds=={'0':'/dev/null','1':'/dev/null','2':'/dev/null'}\nprint(json.dumps({'passed':True,'independentGuardianVerified':True,'remainingSeconds':${fwReceipt.deadline}-time.monotonic()}))\n`));save('firewall-detached',detached);assert.ok(detached.remainingSeconds>130);
 const [cap,exit]=await Promise.all([captured,done]);save('client-exit-private',exit);assert.equal(cap.code,0);assert.equal(exit.code,0,exit.stderr);
 const status=JSON.parse(fs.readFileSync(dir+'/client-result-private.json')),summary={passed:status.tcpAuthenticatedReady&&status.tcpBytes>0&&status.udpReceived>0&&status.errors.length===0,observedAt:new Date().toISOString(),tcpAuthenticatedReady:status.tcpAuthenticatedReady,tcpPayloadBytes:status.tcpBytes,udpSent:status.udpSent,udpReturned:status.udpReceived,firstPayloadSeconds:status.firstPayloadAt===undefined?null:status.firstPayloadAt-status.startedAt,clientSeconds:status.seconds,clientErrors:status.errors,protocolSpecificPublicPeersDiffer:peers.tcp!==peers.udp,tcpPeerBeforeAuthenticationWasTimeCorrelatedOnly:true,exactFirewallRules:2,eachSourceRemainsOneIPv4Address:true,independentFirewallExpirySeconds:180,independentEndpointExpirySeconds:250,clientIndependentDeadlineSeconds:25,nssStarted:false,routerConfigurationWrites:false,noOtherServicesChanged:true,output:dir};save('summary',summary);console.log(JSON.stringify(summary));
}catch(e){save('failure-private',{at:new Date().toISOString(),name:e.name,message:e.message,stack:e.stack});console.log(JSON.stringify({passed:false,failureSaved:true,output:dir,nssStarted:false,routerConfigurationWrites:false}));process.exitCode=1;
}finally{
 if(client&&client.exitCode===null)client.kill();
 if(startedUnit){const closed=await channel.exec('systemctl stop '+unit+'; systemctl show '+unit+' -p MainPID -p ActiveState','',{milliseconds:12000}).catch(e=>({code:-1,stderr:String(e)}));save('endpoint-close-private',closed);}
 channel.close();
}
