"""Freeze the UP60 path, failed preparations, and the actual same-flow A/B/A2."""
from pathlib import Path
from datetime import datetime,timezone,timedelta
import json,hashlib,shutil,subprocess,importlib.util,html
w=Path(__file__).resolve().parents[2];repo=w/'athena-nss-mainline';r=w/'work/nss124'
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(b):return hashlib.sha256(b).hexdigest()
def dump(p,o):p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
spec=importlib.util.spec_from_file_location('collector',w/'work/nss101/collect-lifecycle.py');c=importlib.util.module_from_spec(spec);spec.loader.exec_module(c)
case=r/'controlled-matched-aba-20261005201905-e5d4ca9a';t=c.stage(case.relative_to(w).as_posix())
m=t['metrics'];up=load(case/'actual-upstream-proof.json');trans=load(case/'uplink-transient-analysis.json');final=load(r/'v1-final-health.json');physical=load(r/'physical-final.json')
assert t['passed']and t['completeABA']and t['sourceInputs']==1000 and all(t['rollback'].values())
assert m['oneWan']==5 and m['offeredTcpMbps']==32 and m['uplinkParentMbps']==60 and m['qosParentMbps']==30
assert [x['acceleratedCounts']for x in m['phases']]==[[0],[2],[0]]and all(30<x['whole']['clientTcpMbps']<32 for x in m['phases'])
assert up['passed']and up['uplinkLeafDelta']['8e05:']['dropped']==up['uplinkLeafDelta']['8e06:']['dropped']==0
assert final['passed']and physical['passed']and final['ecmStoppedAndZero']
failedcase=w/'work/nss120/controlled-matched-aba-20261005195857-75098850';failedresult=load(failedcase/'result.json')
assert not failedresult['passed']and 'Publication changed during scheduling read'in str(failedresult['errors'])
assert not (failedcase/'stage-receipt-private.json').exists()and not(failedcase/'last-record-private.json').exists()and not(failedcase/'stage-checkpoint-verified.json').exists()
failed={'caseLocalPath':failedcase.relative_to(w).as_posix(),'passed':False,'ecmOpened':False,'detachedStageStarted':False,'queueWrites':False,'checkpointStarted':False,'originalFailurePreserved':True,'rejection':'Publication changed during scheduling read before checkpoint/stage','originalResultSha256':sha((failedcase/'result.json').read_bytes()),'driverPrintedInheritedNss116Label':True,'actualEntry':'work/nss120/controlled-session.mjs'}
matchdriver=load(w/'work/nss123/driver-private.json');assert matchdriver[1]['code']==1 and 'matching exhausted'in matchdriver[1]['stderr']
assert not any(p.is_dir()for p in (w/'work/nss123').glob('controlled-matched-aba-*'))
matching={'passed':False,'preparationOnly':True,'desiredWan':5,'ecmOpened':False,'queueWrites':False,'productionRouterWrites':False,'finitePreparationSeconds':75,'originalFailurePreserved':True,'originalDriverSha256':sha((w/'work/nss123/driver-private.json').read_bytes()),'likelyEndpointPeerPinAndUdpRotationConflict':True,'actualNewUdpWanOrNatPeerProved':False,'resolvedByKeepingUdpSocketAndPeerFixedAndOnlyRotatingOwnedTcp':True,'campusPolicyOrPbrChanged':False}
q120=load(w/'work/nss120/entry-qualified.json');q121=load(w/'work/nss121/matching-qualified.json');q122=load(w/'work/nss122/reader-qualified.json');q124=load(r/'entry-qualified.json')
assert q120['payloadBytes']<=73728 and len(q122['checks'])==8 and q122['maximumRenamedReadRetries']==1 and not q122['originalFullAuditChanged']
assert q124['udpPeerPinKept']and q124['onlyOwnedTcpPortsRotated']and q124['originalFullAuditUnchanged']
hint=load(w/'work/nss122/actual-current-hint.json');assert hint['passed']and not hint['nssAdmissionAllowed']
alignment=load(w/'work/nss122'/f'{case.name}-before-alignment-private.json')
hintactual={'passed':True,'readonly':True,'productionRouterWrites':False,'nssAdmissionAllowed':False,'fullAuditUnchanged':True,'actualStandaloneHintPassed':hint['passed'],'hardwareStageUsedQualifiedReader':True,'discardedAtomicReadsInSuccessfulPreparation':alignment.get('discardedAtomicReads'),'originalStandaloneReceiptSha256':sha((w/'work/nss122/actual-current-hint.json').read_bytes())}
closures=[c.closure(load(w/f'work/nss{n}/load-latest-private.json')['dir'])for n in [120,123]]
lp=w/load(r/'load-latest-private.json')['dir'];fresh=load(r/'endpoint-closure-recheck.json');guard=load(lp/'guard-result-private.json');client=load(lp/'result-private.json');cp=load(lp/'firewall-checkpoint-verified.json');receipt=load(lp/'firewall-receipt-private.json');detached=load(lp/'firewall-detached-private.json')
assert fresh['passed']and guard['passed']and guard['exactClientOnly']and guard['clientExitedBeforeDeadline']and cp['expirySeconds']==180 and receipt['beforeWriteIndependentGuardianVerified']and detached['detachedIdentityVerified']and detached['onlyNullStandardFds']
closures.append({'loadLocalPath':lp.relative_to(w).as_posix(),'temporaryFirewallRulesRemaining':0,'canonicalFirewallBaselineRestored':True,'ownedUnitInactiveMainPidZeroPortsClosed':True,'clientExited':True,'clientGuardPassed':True,'independentFirewallExpirySeconds':180,'independentClientDeadlineSeconds':210,'endpointGuardianVerifiedBeforeWrite':True,'clientRunSeconds':client['seconds'],'initialClosureSshTimeoutPreserved':True,'subsequentReadOnlyClosurePassed':True,'naturalOsDeadlineClosure':True,'clientErrors':client.get('errors',[])})
old=(repo/'evidence/current-runtime.json').read_bytes();assert load(repo/'evidence/current-runtime.json')['round']=='NSS119'and subprocess.check_output(['git','show','HEAD:evidence/current-runtime.json'],cwd=repo)==old
archive=repo/'evidence/nss119-runtime.json';assert not archive.exists();archive.write_bytes(old)
manifest=load(repo/'source-manifest.json');assert len(manifest['sources'])==1400;prefix=sha(json.dumps(manifest['sources'],sort_keys=True,separators=(',',':')).encode())
common=['prepare.py','bounded-pacer.mjs','upload-ack.mjs','upload-server.py','ssh-client.mjs','session-binding.mjs','qualify.mjs','controlled-session.mjs','current-audit-diagnostic.mjs','match-controlled.mjs','read-controlled.mjs','run.mjs','module-stage.mjs','payload.mjs','pack-lua.mjs','pack-guardian.mjs','compact-default-queues.mjs','uplink-tag-plan.mjs','parse-ecm-any-wan.mjs','fast-path.lua','module-stage-guardian.lua','qos-physical.lua','tag-normalizer.lua','failed-wan-owner.lua','declared-baseline.mjs','service-epoch.mjs']
allowed={n:common.copy()for n in [120,123,124]}
allowed[121]=['prepare.py','qualify.mjs','match-target.mjs','natural-target.mjs','run.mjs']
allowed[122]=['prepare.py','qualify.mjs','atomic-hint-read.lua','wait-ready-candidate.mjs','wait-publication-metadata.mjs','inspect-current.mjs']
allowed[124]+=['prepare-analysis.py','analyze-long.py','calibrate-clock.mjs','prove-upstream.py','analyze-uplink-transient.py','health.mjs','read-final-physical.mjs','closure-recheck.mjs','save-evidence.py']
hashes={}
for n,names in allowed.items():
 for name in names:
  src=w/f'work/nss{n}'/name;assert src.is_file();rel=src.relative_to(w).as_posix();dst=repo/'code'/rel;assert not dst.exists();dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst);digest=sha(src.read_bytes());hashes[rel]=digest;manifest['sources'].append({'path':'code/'+rel,'workspaceSource':rel,'sha256':digest,'bytes':src.stat().st_size,'role':'UP60-fixed-peer-and-readonly-publication-hint'})
manifest['generatedAt']=datetime.now(timezone.utc).isoformat();manifest['lastAppendExport']='NSS124';dump(repo/'source-manifest.json',manifest)
frozen={};freeze=r/'proof-v1/private-inputs';freeze.mkdir(parents=True,exist_ok=False)
for n in range(120,125):
 for src in sorted((w/f'work/nss{n}').rglob('*')):
  if not src.is_file()or any(p in src.parts for p in ['proof-v1','frozen','frozen-qualified-inputs','__pycache__']):continue
  rel=src.relative_to(w);dst=freeze/rel;dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst);frozen[rel.as_posix()]=sha(src.read_bytes());assert sha(dst.read_bytes())==frozen[rel.as_posix()]
dump(r/'private-input-freeze-index.json',frozen)
summary={'round':'NSS124','observedAt':final['observedAt'],'routerQosOnlyUplinkBudgetChangedFrom119':True,'offeredUploadMbps':32,'uplinkGroupMbps':60,'uplinkBulkMbps':59,'uplinkRtMbps':1,'downlinkGroupMbps':30,'maximumPacerCreditBytes':65536,'sameWanAs119':True,'oneWan':5,'boundInputs':1000,'phaseSeconds':20,'nativeSessionSeconds':27,'independentOwnerSeconds':100,'classifierMaximumLeaseSeconds':6,'completeFunctionalABA':True,'comparableSelectedTransferRateObserved':True,'allWanBackgroundObserved':False,'nssThroughputRestoredWithLargerUplinkBudget':True,'exactRootCauseOfThirtyMbpsLossProved':False,'softwareMeanSoftirqPercent':sum(m['phases'][i]['whole']['softirqPercent']for i in [0,2])/2,'nssSoftirqPercent':m['phases'][1]['whole']['softirqPercent'],'newStrictCpuComparisonAccepted':False,'rtRepliesComplete':False,'rtLeafDrop':0,'bulkLeafDrop':0,'atomicHintFailureAndFiniteMatchingFailurePreserved':True,'readOnlyAtomicRenameHandlingAdded':True,'strictRateAccuracyAccepted':False,'humanCs2Acceptance':False,'highLoad300MbpsAcceptance':False,'fullCakeReplacementAccepted':False,'residentClassifierChanged':False,'nssPermanentlyEnabled':False,'uiOperated':False,'upstreamSubmitted':False,'temporaryEndpointsClosed':3,'reportVerification':{'sourceValidated':True,'browserRendered':False}}
source={'round':'NSS124','historicPrefixSources':1400,'historicPrefixCanonicalSha256':prefix,'sources':len(hashes),'sourceHashes':hashes,'privateOwnedHostBootstrapExcluded':True,'actualBindingTreesRetained':True,'privateArtifactsFrozen':len(frozen)}
qualification={'uplink60':q120['checks'],'naturalTargetMatcher':q121['checks'],'atomicHintTargetRam':q122['checks'],'fixedUdpPeer':q124['checks'],'atomicReadMaximumRetries':1,'waitSeconds':5,'runnerSeconds':6,'originalFullAuditUnchanged':True,'qualifiedPayloadBytes':q120['payloadBytes']}
for key,value in {'mainline':summary,'trial':t,'prewrite-refusal':failed,'matching-refusal':matching,'metrics':m,'uplink-proof':up,'uplink-analysis':trans,'qualification':qualification,'actual-readonly-hint':hintactual,'endpoint-closure':closures,'final-audit':final,'physical-final':physical,'source-proof':source}.items():dump(repo/f'evidence/nss124-{key}.json',value)
runtime={'round':'NSS124','checkedAt':physical['observedAt'],'deploymentReference':'work/nss68/deployment-latest.json','classifierConfigSha256':final['configSha256'],'workerPid':final['workerPid'],'guardianPid':final['guardianPid'],'nssPermanentlyEnabled':False,'residentClassifierChangedThisTurn':False,'qualifiedExperimentalEntry':'work/nss124/controlled-session.mjs','qualifiedExperimentalEntryBoundInputs':1000,'currentNssAdmissionMustBeRefreshedBeforeWrite':True,'audit':final,'physicalRootRestoreAudit':physical,'realHumanGameAcceptance':False,'newStrictCpuComparisonAccepted':False,'historical119RuntimePreservedSha256':sha(old),'nightContinuationUntilBeijing':'2026-10-06T10:00:00+08:00'};dump(repo/'evidence/current-runtime.json',runtime)
when=datetime.fromisoformat(final['observedAt'].replace('Z','+00:00')).astimezone(timezone(timedelta(hours=8))).strftime('%Y-%m-%d %H:%M');speeds='/'.join(f"{p['whole']['clientTcpMbps']:.3f}"for p in m['phases']);softs='/'.join(f"{p['whole']['softirqPercent']:.3f}"for p in m['phases']);udp='、'.join(f"{p['whole']['udp']['received']}/{p['whole']['udp']['sent']}"for p in m['phases'])
text=f'''更新：{when}，北京时间。最新NSS124；常驻68/config581b5d46…c791d7、4859/17139不变，实验已撤销。

**上行受控组30→60Mbps（bulk29→59、RT1、ceil60），下行30与有界32Mbps上传不改。实际自然WAN5、同一对flow完整20秒A/B/A2，ECM0→2→0、四leaf/mark/NAT/affinity/六次续租/恢复通过；服务器确认{speeds}Mbps，B不再降至约16Mbps。**

见 [实际指标](../evidence/nss124-metrics.json)、[轮次](../evidence/nss124-trial.json)、[汇总](../evidence/nss124-mainline.json)、[拒绝](../evidence/nss124-prewrite-refusal.json)、[匹配失败](../evidence/nss124-matching-refusal.json)、[关闭](../evidence/nss124-endpoint-closure.json)、[终态](../evidence/nss124-final-audit.json)。

- softirq {softs}%，time_squeeze/drop均0；UDP收/发{udp}。上下行bulk/RT queue drop均0，客户端B少一个echo回复，不能写成网络零丢包或CS2效果。选中TCP吞吐可比，暂未同时捕获其它WAN背景，严格整机CPU收益不新增验收。
- 与119同WAN5且同32发送器；上行预算增大后吞吐恢复，支持原30组拥塞相关因素参与，不把跨轮网络变化排除或写成精确AQM根因。60组未饱和，尚未验收60准确限速、拥塞延迟或完整CAKE替代。
- 120经121匹配后，旧只读hint遇发布rename在checkpoint/stage前拒绝，未改路由器。122只将已替换读数丢弃、最多重读一次；8目标RAM边界与实际只读hint通过，原5秒wait/6秒runner及完整审核不改。123强求WAN5而轮换UDP后匹配失败；端点只允许原NAT peer，冲突是合理线索，实际新UDP WAN/peer未捕获，不声称已定因。124保留UDP socket/peer，只自然轮换自己的TCP，未改PBR/认证/端点规则范围。
- 1000项新入口，native27/owner100/source6和9000/65536/73728字节边界不改。实际新checkpoint下载/SHA/gzip与独立守护在写前核验；三端点FW180/客户端210均清理，124首次关闭SSH查询超时原记录保留，随后只读确认规则基线和端口关闭。
- 最终source{final['queryAge']:.2f}、ECM关闭全零、无事务/stage/state/模块，两物理根原mq＋四fq_codel恢复；WAN4仍down、自然四路PBR不改。旧119 runtime原字节保持，完整私有输入冻结。未操作UI/下载/游戏、不改常驻upTag0、不提交上游。
- 下一步只补所有WAN的相同只读计数，保持当前队列/负载/来源和期限，做一次CPU对照；随后收敛真实class到双向leaf的最小消费者映射及改类精确撤销，不重装整套或长期放行未知flow。最后一次集中真人CS2验收；第二WAN/共享预算/WiFi/autorate仍后置。09:50起收尾、报告和推送后暂停本夜接续。
'''
for name,title in [('STATE.md','# 当前状态'),('PLAN.md','# 当前单WAN主线')]:
 p=repo/'docs'/name;p.write_text(title+'\n\n'+text+'\n## NSS119历史\n\n'+p.read_text(encoding='utf-8'),encoding='utf-8')
p=repo/'docs/EXPERIMENT_LOG.md';head,tail=p.read_text(encoding='utf-8').split('\n',1);p.write_text(head+'\n\n## NSS120–124 · '+when+' · 上行预算与真实吞吐恢复\n\n'+text+tail,encoding='utf-8')
p=repo/'AGENTS.md';head,tail=p.read_text(encoding='utf-8').split('\n',1);p.write_text(head+'\n\n最新NSS124：只把UP30/29→60/59，RT1/ceil60、DOWN30、有界32发送与6/27/100期限保持；实际WAN5完整20秒三段，ECM0/2/0、四leaf/mark/NAT/affinity/6续租及恢复通过，确认上传'+speeds+'Mbps、softirq'+softs+'%、UDP'+udp+'，四leafdrop0/squeeze0。B恢复约31，不新增严格整机CPU/真人或60限速验收。120hint rename写前拒绝、123有限匹配失败原义保持；122只读最多重读1次，124保留UDP peer/只换TCP自然同WAN，不改PBR/认证。1000项入口、checkpoint/独立100秒守护和3端点关闭，124首次SSH关闭超时保留、只读复核通过；终态source3.03、4859/17139/68配置不变、ECM全零无残留，两根恢复，WAN4仍down。下一步所有WAN同观察器CPU对照，再最小class→双向leaf/精确撤销，最后真人一次；UI停用、不新下载/重装/扩WAN；09:50收尾、10点前暂停本夜接续；STATE为准。\n\n'+tail,encoding='utf-8')
p=repo/'docs/ARTIFACT_INDEX.md';p.write_text('# 当前NSS124\n\n[指标](../evidence/nss124-metrics.json) · [轮次](../evidence/nss124-trial.json) · [汇总](../evidence/nss124-mainline.json) · [终态](../evidence/nss124-final-audit.json) · [历史119 runtime](../evidence/nss119-runtime.json)。\n\n'+p.read_text(encoding='utf-8'),encoding='utf-8')
rows=''.join(f'<tr><td>{x["phase"]}</td><td>{x["whole"]["clientTcpMbps"]:.3f}</td><td>{x["whole"]["softirqPercent"]:.3f}%</td><td>{x["whole"]["timeSqueezeDelta"]}</td><td>{x["whole"]["udp"]["received"]}/{x["whole"]["udp"]["sent"]}</td></tr>'for x in m['phases'])
report=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSS124 上行吞吐恢复</title><style>body{{background:#f4f4ee;color:#24352d;font:16px/1.8 "Microsoft YaHei",sans-serif}}main{{max-width:1000px;margin:auto;padding:28px 24px}}section{{background:white;padding:22px;border:1px solid #ddd;border-radius:10px;margin:22px 0}}table{{width:100%;border-collapse:collapse}}th,td{{text-align:left;padding:9px;border-bottom:1px solid #ddd}}</style><main><small>ATHENA · {when} 北京时间</small><h1>单WAN双向NSS：上行吞吐恢复至约31Mbps</h1><p>只增上行组30→60，保持下行30和有界32Mbps自有上传。实际ECM0→2→0、四leaf和连接身份正确，实验全部撤销。</p><section><table><tr><th>阶段</th><th>服务器确认Mbps</th><th>softirq</th><th>squeeze</th><th>UDP收/发</th></tr>{rows}</table><p>上下行bulk/RT queue drop均0；客户端B少收到1个echo，不能说网络零丢包。选中吞吐可比，下一轮补其它WAN背景后再评价CPU。不是CS2体验、300Mbps或60限速验收。</p></section><section><h2>失败和修正</h2><p>120旧hint遇文件原子替换，在checkpoint前拒绝；122丢弃替换中的读数、只允许一次重读，原期限与完整审核不变。123轮换UDP寻找WAN5失败，原端点peer锁定可能冲突，未捕获新NAT证明；124固定UDP，仅换自己的TCP端口，自然匹配WAN5，不改PBR或认证。</p><p>新1000项绑定、checkpoint和独立守护写前核验；3端点已关闭。首次关闭SSH超时保留，后续只读确认基线。常驻68/4859/17139与原软件队列恢复，ECM关闭全零，WAN4仍down。</p></section><section><h2>下一步</h2><p>只补所有WAN同窗计数，当前负载/队列不改；之后最小自动class到双向leaf映射及改类精确撤销，最后集中真人一次。不操作桌面或新下载，不扩WAN。09:50起收尾，10点前暂停夜间接续。</p><a href="https://github.com/ZyPulse-zy/athena-nss-mainline/blob/main/docs/STATE.md">仓库状态</a><p><small>报告源码核验，未作浏览器渲染验收。</small></p></section></main></html>'''
out=w/'outputs/nss124-mainline-report.html';assert not out.exists();out.write_text(report,encoding='utf-8')
dump(r/'export-receipt.json',{'passed':True,'newSources':len(hashes),'totalSources':len(manifest['sources']),'uploadMbps':speeds,'privateArtifacts':len(frozen),'temporaryEndpointsClosed':3});print(json.dumps({'exported':True,'sources':len(hashes),'totalSources':len(manifest['sources']),'uploadMbps':speeds}))
