import fs from'node:fs';import crypto from'node:crypto';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import vm from'node:vm';import{verifyPreparation as inherited}from'../v22-fiveflow/session-binding.mjs';
const root='work/v23-fiveflow',old=inherited(),hash=x=>crypto.createHash('sha256').update(x).digest('hex'),save=(n,v)=>fs.writeFileSync(root+'/'+n+'.json',JSON.stringify(v,null,2)+'\n',{flag:'wx'});
for(const name of['classifier.lua','classified-tags.lua','fast-path.lua','wan-scope.lua','qos-physical.lua','tag-normalizer.lua','module-stage-guardian.lua','pack-json.mjs','compact-post-guards.mjs','native-client.mjs','match-controlled.mjs','read-controlled.mjs']){let s=fs.readFileSync(root+'/'+name,'utf8').replaceAll('work/v23-fiveflow','work/v22-fiveflow');assert.equal(s,fs.readFileSync('work/v22-fiveflow/'+name,'utf8'),name+' changed outside inventory scope');}
const current=fs.readFileSync(root+'/current-audit-diagnostic.mjs','utf8'),epoch=fs.readFileSync(root+'/epoch-driver.mjs','utf8'),start=fs.readFileSync(root+'/start-dallas.mjs','utf8'),close=fs.readFileSync(root+'/close-endpoint.mjs','utf8');
assert.ok(current.includes('^work\\/v23-fiveflow\\/session-')&&epoch.includes('^work\\/v23-fiveflow\\/pilot-aba-'));assert.ok(!current.includes('^work\\/v21-fiveflow\\/')&&!epoch.includes('^work\\/v21-fiveflow\\/'));assert.ok(start.includes("const unit='v23-fiveflow-'")&&close.includes('/^v23-fiveflow-'));
const source=fs.readFileSync(root+'/read-controlled.mjs','utf8'),a=source.indexOf('const ps=`'),b=source.indexOf('\nconst pcRaw=',a);assert.ok(a>0&&b>a);const ps=vm.runInNewContext(source.slice(a,b)+';ps',{binding:{configPath:'C:/model/client-config-private.json'}});assert.ok(ps.includes('Get-CimInstance Win32_Process -Filter $filter')&&ps.includes("$all.Count -ne 5")&&ps.includes("Owned SSH child identity changed")&&ps.includes("Get-NetTCPConnection -State Established"));
const quote=x=>"'"+x.replaceAll("'","''")+"'";const parse=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command','$null=[scriptblock]::Create('+quote(ps)+');Write-Output BATCH_EXACT_PC_SYNTAX_PASS'],{encoding:'utf8',windowsHide:true,timeout:8000});save('batch-pc-syntax-private',{code:parse.status,stdout:parse.stdout,stderr:parse.stderr,fixturesOperated:false});assert.equal(parse.status,0,parse.stderr);assert.equal(parse.stdout.trim(),'BATCH_EXACT_PC_SYNTAX_PASS');
const manifest={};for(const name of fs.readdirSync(root))if(/\.(mjs|lua|py|ps1)$/.test(name)&&!name.includes('private')){const p=root+'/'+name;manifest[p]=hash(fs.readFileSync(p));if(name.endsWith('.mjs')){const r=spawnSync(process.execPath,['--check',p],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stderr);}}
for(const name of['native-qualified.json','normalizer-qualified.json','qos-native-qualified.json'])manifest[root+'/'+name]=hash(fs.readFileSync(root+'/'+name));
save('entry-qualified',{passed:true,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,hardwareExecuted:false,wholeFactoryModeled:false,onlyPcProcessSocketInventoryBatched:true,exactBirthParentExecutableArgumentsAndSocketOwnershipRetained:true,fiveSlotNativeAndQoSLuaExact:true,priorTargetRamModelsReused:true,fiveNativeAbiSourceAndRuntimeProofsReused:true,sourceFreshnessSeconds:6,kernelSessionSeconds:90,kernelMaximumSeconds:120,ownerSeconds:180,clientSeconds:180,phaseSeconds:60,combinedCreditBytes:65536,totalOfferedMbps:32,priorNoNssWriteDeadlineFailureRetained:true});console.log(JSON.stringify({passed:true,bindings:Object.keys(old.sourceManifest).length+Object.keys(manifest).length,newInventoryParsed:true,gateAndQoSUnchanged:true}));
