import fs from'node:fs';import assert from'node:assert/strict';import{connectRouter}from'../nss20/connect-router.mjs';import{readBaseline,auditBaseline}from'../nss15/baseline.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';
const ctx=JSON.parse(fs.readFileSync('work/nss33/deployment-latest.json'));const label=process.argv[2]??'operational';assert.match(label,/^[a-zA-Z0-9_-]+$/);const before=JSON.parse(fs.readFileSync(ctx.localDir+'/before-private.json'));const c=await connectRouter();try{
 const after=await readBaseline(c,ctx.localDir,label+'-baseline');const service=after.services['router-project-game-classifier'];assert.equal(service.classifier.running,true);assert.equal(service.guardian.running,true);assert.equal(Object.keys(service).length,2);
 const code=fs.readFileSync('work/nss23/operational-audit.lua','utf8');
 const body='exec 8>/tmp/router-project-transaction.lock\nflock -x 8\n/usr/bin/lua - '+ctx.base+' '+ctx.configHash+" <<'NSS23_AUDIT'\n"+code+'\nNSS23_AUDIT\n';
 const e=encode(ctx.base+'/group-runner 6 /bin/sh -c '+"'"+body.replaceAll("'","'\\''")+"'");const raw=receipt(await c.run(e.command),e);fs.writeFileSync(ctx.localDir+'/'+label+'-ownership-raw-private.json',JSON.stringify(raw,null,2)+'\n');assert.equal(raw.code,0,raw.stderr);const proof=JSON.parse(raw.stdout);fs.writeFileSync(ctx.localDir+'/'+label+'-ownership-private.json',JSON.stringify(proof,null,2)+'\n');assert.equal(service.classifier.pid,proof.pid);assert.equal(service.guardian.pid,proof.guardianPid);
 const adjusted={...after,native:before.native,services:{...after.services}};adjusted.services['router-project-game-classifier']=before.services['router-project-game-classifier'];const baseline=auditBaseline(before,adjusted);
 const out={passed:true,protectedConfigurationUnchanged:baseline.configurationMatches,exactOwnedNativeAudit:proof.exactOwnedNativeAudit,selectors:proof.selectors,producer:proof.producer,queryAge:proof.queryAge,sequence:proof.querySequence,startup:proof.startup,ecmClosedAndZero:baseline.checks.ecmStoppedAndZero,baselineComparisonAllowsOnlyClassifierGenerationAndJournalOwnedSelectors:true};
 fs.writeFileSync(ctx.localDir+'/'+label+'-audit.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
}finally{c.close()}
