import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{tokens,packLua}from'./pack-lua.mjs';import{connectRouter}from'../nss27/connect-router.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';
const root='work/nss140',s=fs.readFileSync(root+'/fast-path.lua','utf8'),original=fs.readFileSync(root+'/fast-path-v1.lua','utf8'),names={record:'R',comparison:'C',parameters:'K',classifier:'A',checkedTags:'G',observed:'O',sample:'S',complete:'E',session:'N',ending:'V',getterUntil:'D',paths:'B',tagBase:'H',allowPending:'W',removeTags:'F',live:'I',learningDue:'J',acquireUntil:'U',renew:'X'},h=b=>crypto.createHash('sha256').update(b).digest('hex');
assert.deepEqual(tokens(s),tokens(original).map(t=>names[t]??t));
const cut=(text,a,b)=>text.slice(text.indexOf(a),text.indexOf(b,text.indexOf(a)));
const prior=fs.readFileSync('work/nss138/fast-path.lua','utf8'),verifier=cut(s,'function M.verifyReclassification(','function M.new(');assert.deepEqual(tokens(verifier),tokens(cut(prior,'function M.verifyReclassification(','function M.new(')).map(t=>names[t]??t));
const actual=JSON.parse(fs.readFileSync('work/nss138/controlled-class-20261005222654-399b3465/last-record-private.json')),comparison=structuredClone(actual.actualReclassification),evidence=comparison.evidence.completeSelected;comparison.evidence={completeSelected:{sameSourceCompleteFrame:evidence.sameSourceCompleteFrame,afterRejectionOnly:evidence.afterRejectionOnly,nssAdmissionAllowed:false,producer:'mock',slots:evidence.slots}};
const model=fs.readFileSync(root+'/observe-retire-models.lua','utf8').replace('__VERIFIER__',()=>verifier).replace('__SAMPLE__',()=>cut(s,' local function S()',' local function observe()')).replace('__RETIRE__',()=>cut(s,' retire=function(C)',' local function tick(name)')).replace('__OBSERVE__',()=>cut(s,' local function observe()',' local function counters(raw)'));
const code="local j=require('luci.jsonc');local comparison=assert(j.parse([====["+JSON.stringify(comparison)+"]====]));\n"+model;fs.writeFileSync(root+'/observe-retire-rendered-private.lua',code,{flag:'wx'});
const syntax=encode("lua - <<'NSS140_FULL_FAST_SYNTAX'\nassert(loadstring([====["+packLua(s)+"]====]));print('FULL_FAST_COMPILED')\nNSS140_FULL_FAST_SYNTAX\n"),e=encode("lua - <<'NSS140_OBSERVE_RETIRE_RAM'\n"+code+"\nNSS140_OBSERVE_RETIRE_RAM\n");
const c=await connectRouter();try{const compile=receipt(await c.run(syntax.command),syntax);fs.writeFileSync(root+'/full-fast-syntax-private.json',JSON.stringify(compile,null,2)+'\n',{flag:'wx'});assert.equal(compile.code,0,compile.stderr);assert.equal(compile.stdout.trim(),'FULL_FAST_COMPILED');const raw=receipt(await c.run(e.command),e);fs.writeFileSync(root+'/observe-retire-raw-private.json',JSON.stringify(raw,null,2)+'\n',{flag:'wx'});assert.equal(raw.code,0,raw.stderr);const p=JSON.parse(raw.stdout);assert.ok(p.passed&&p.checks===10);fs.writeFileSync(root+'/fast-qualified.json',JSON.stringify({...p,sourceSha256:h(s),allOtherTokensAndQuotedStringsExact:true,original138CompleteClassVerifierRetained:true,wholeFactoryCompiledInTargetRam:true,onlyNewObserveAndRetireBranchesExecutedWithMockedBackend:true,wholeFactoryAbaNotExecutedThisRound:true,actualHardwareTestThisVersion:false,syntaxExecBytes:syntax.execBytes,modelExecBytes:e.execBytes},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,checks:p.checks,syntaxExecBytes:syntax.execBytes,modelExecBytes:e.execBytes,productionExecution:false}));}finally{c.close()}
