import{activeSlots}from'../resident-general-dev-20261008/selection.mjs';
import assert from'node:assert/strict';import{verifyPreparation}from'../v12/session-binding.mjs';
export function verifyCandidate(input){
 const q=verifyPreparation();assert.equal(input.mode,'stage');assert.equal(input.openFrontend,true);assert.equal(input.autoClassified,true);assert.equal(input.qosDevice,'lan4');const slots=activeSlots(input.selected),p=input.wanPrerequisites;assert.equal(p.boot,q.boot);assert.ok(p.members.length>=1&&p.members.length<=3);assert.equal(p.members.length,new Set(slots.map(k=>input.selected[k].wan)).size);assert.equal(new Set(p.members.map(e=>e.w)).size,p.members.length);
 for(const f of slots.map(k=>input.selected[k])){assert.ok(Number.isInteger(f.wan)&&f.wan>=1&&f.wan<=5);assert.equal(f.original.src,'192.168.237.207');assert.equal(f.zone,0);assert.equal((f.mark>>>16)&255,f.wan);assert.equal(f.mark&0x2000,0);assert.ok(Number.isInteger(f.id)&&f.id>0&&f.id<=0xffffffff);const e=p.members.find(e=>e.w===f.wan);assert.equal(e.w,f.wan);assert.equal(e.ip,f.reply.dst);assert.ok(Number.isInteger(e.pid)&&e.pid>1);assert.match(e.start,/^\d+$/);assert.ok(Number.isInteger(e.failure)&&e.failure>=0);assert.ok(Number.isInteger(e.index)&&e.index>0&&e.link==='wan');assert.match(e.mac,/^[a-f0-9:]{17}$/);}
 assert.deepEqual(Object.keys(input.tagPlan.wanLeafAssignments).sort(),slots.slice().sort());for(const slot of slots){const f=input.selected[slot];const m=input.tagPlan.wanLeafAssignments[slot],low=slot==='udp'?6:5;assert.equal(m.wan,f.wan);assert.equal(m.class,slot==='udp'?'RT':'BULK');assert.equal(m.upTag,(0x8e00+f.wan*16+low)*65536);assert.equal(m.downTag,(0x8f00+f.wan*16+low)*65536);}
}
export function validateRefinement(before,after){
 const mutable=new Set(['selected','tagPlan','frozenHash','insmodArguments']),fixed=x=>Object.fromEntries(Object.entries(x).filter(([k])=>!mutable.has(k)));assert.deepEqual(fixed(after),fixed(before),'Protected scope changed');
 assert.deepEqual(activeSlots(after.selected),activeSlots(before.selected));for(const slot of activeSlots(before.selected)){const identity=x=>{const y=structuredClone(x);delete y.classifierKey;return y;};assert.deepEqual(identity(after.selected[slot]),identity(before.selected[slot]),'Immutable CT changed');if(after.selected[slot].classifierKey!==undefined)assert.equal(after.selected[slot].classifierKey,before.selected[slot].classifierKey);}
 for(const k of['owner','table','mode'])assert.equal(after.tagPlan[k],before.tagPlan[k]);assert.deepEqual(after.tagPlan.wanLeafAssignments,before.tagPlan.wanLeafAssignments);assert.match(after.frozenHash,/^[a-f0-9]{64}$/);assert.ok(typeof after.insmodArguments==='string'&&after.insmodArguments.length<2048);verifyCandidate(after);return structuredClone(after);
}
