import fs from'node:fs';import assert from'node:assert/strict';import path from'node:path';import{fileURLToPath}from'node:url';import{spawnSync}from'node:child_process';import{hash}from'../resident-dev-20261007/materialize.mjs';
const root='work/resident-general-dev-20261008';
export function verifyGeneralBatch(){const q=JSON.parse(fs.readFileSync(root+'/qualification-latest-private.json'));assert.equal(q.passed,true);for(const [p,h]of Object.entries(q.sourceManifest))assert.equal(hash(fs.readFileSync(p)),h,'General candidate source changed: '+p);assert.equal(q.hardwareQualified,false);return q;}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const dir=root+'/batch-'+Date.now();fs.mkdirSync(dir);let syntax=0;
 const sources=fs.readdirSync(root).filter(n=>/\.(mjs|py)$/.test(n)).map(n=>root+'/'+n).concat(fs.readdirSync(root+'/endpoint-gate').filter(n=>/\.(c|h|py)$/.test(n)||n==='Makefile').map(n=>root+'/endpoint-gate/'+n),[root+'/native-source-qualified.json',root+'/runtime-elf-comparison.json',root+'/endpoint-gate/build-manifest.json',root+'/endpoint-gate/rp_ecm_gate_lab_ct.runtime.ko']);
 for(const p of sources.filter(p=>p.endsWith('.mjs'))){const r=spawnSync(process.execPath,['--check',p],{encoding:'utf8',windowsHide:true});fs.writeFileSync(dir+'/'+path.basename(p)+'.syntax.json',JSON.stringify({code:r.status,stdout:r.stdout,stderr:r.stderr})+'\n',{flag:'wx'});assert.equal(r.status,0,r.stderr);syntax++;}
 const r=spawnSync(process.execPath,[root+'/test-subsets.mjs'],{encoding:'utf8',windowsHide:true,timeout:120000});fs.writeFileSync(dir+'/subsets-raw.json',JSON.stringify({code:r.status,stdout:r.stdout,stderr:r.stderr})+'\n',{flag:'wx'});assert.equal(r.status,0,r.stderr);
 const subset=JSON.parse(fs.readFileSync(root+'/subset-model-latest.json'));assert.equal(subset.passed,true);
 const q={passed:true,hardwareQualified:false,modelOnly:true,routerAccess:false,checks:subset.checks,syntaxSources:syntax,subsetModel:subset,sourceManifest:Object.fromEntries(sources.map(p=>[p,hash(fs.readFileSync(p))])),dir};fs.writeFileSync(dir+'/qualification.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});fs.writeFileSync(root+'/qualification-latest-private.json',JSON.stringify(q,null,2)+'\n');verifyGeneralBatch();console.log(JSON.stringify({passed:true,checks:q.checks,syntaxSources:syntax,dir}));
}
