import fs from'node:fs';import crypto from'node:crypto';import path from'node:path';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import{verifyPreparation as inherited}from'../v39-five-sim/session-binding.mjs';
const root='work/v40-five-sim',old=inherited(),prep=JSON.parse(fs.readFileSync(root+'/prepare-receipt.json')),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const rebase=s=>s.replaceAll('work/v39-five-sim','work/v40-five-sim').replaceAll('work\\/v39-five-sim\\/','work\\/v40-five-sim\\/').replaceAll('v39-five-sim-','v40-five-sim-').replaceAll('v39-final','v40-final');
for(const[f,h]of Object.entries(prep.oldHashes)){assert.equal(hash(fs.readFileSync(f)),h,f);if(['prepare.py','qualify-entry.mjs','session-binding.mjs','native-client.mjs'].includes(path.basename(f)))continue;const p=root+'/'+path.basename(f);assert.deepEqual(fs.readFileSync(p),f.endsWith('.json')?fs.readFileSync(f):Buffer.from(rebase(fs.readFileSync(f,'utf8'))),f);}
const a="if(x.rotateTcp){assert.ok(!fixtureFrozen&&(performance.now()-began)/1000<30,'Natural TCP acquisition is closed');assert.ok(['tcp','tcp2','tcp3','tcp4'].includes(x.rotateTcp.slot));const s=stats.tcpChildren.find(y=>y.slot===x.rotateTcp.slot);if(x.rotateTcp.attempt>s.attempt&&!rotating.has(s.slot))startTcp(s.slot,x.rotateTcp.attempt).catch(finish);}";
const b="if(x.rotateTcp){assert.ok(['tcp','tcp2','tcp3','tcp4'].includes(x.rotateTcp.slot));const s=stats.tcpChildren.find(y=>y.slot===x.rotateTcp.slot);if(x.rotateTcp.attempt>s.attempt&&!rotating.has(s.slot)){assert.ok(!fixtureFrozen&&(performance.now()-began)/1000<30,'Natural TCP acquisition is closed');startTcp(s.slot,x.rotateTcp.attempt).catch(finish);}}";
const before=fs.readFileSync('work/v39-five-sim/native-client.mjs','utf8');assert.equal(before.split(a).length,2);assert.equal(fs.readFileSync(root+'/native-client.mjs','utf8'),rebase(before).replace(a,b));
const manifest={};let dependencies=0;for(const name of fs.readdirSync(root))if(/\.(mjs|lua|py|ps1|json)$/.test(name)&&!name.includes('private')&&!['prepare-receipt.json','entry-qualified.json'].includes(name)){const f=root+'/'+name;manifest[f]=hash(fs.readFileSync(f));if(name.endsWith('.mjs')){for(const m of fs.readFileSync(f,'utf8').matchAll(/(?:from\s*|import\s*)['"](\.{1,2}\/[^'"]+\.mjs)['"]/g)){assert.ok(fs.existsSync(path.resolve(root,m[1])),m[1]);dependencies++;}const p=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}}
const inheritedQ=JSON.parse(fs.readFileSync('work/v39-five-sim/entry-qualified.json')),out={...inheritedQ,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,relativeDependenciesExist:dependencies,onlyCompletedControlCommandBecomesNoop:true,newAcquisitionStillBefore30SecondsAndBeforeFreeze:true,priorActualClientErrorPreserved:true,hardwareExecuted:false,cutoff:prep.cutoff};fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(out,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,newSources:Object.keys(manifest).length,bindings:out.inheritedBindings+Object.keys(manifest).length,onlyStaleControlHandlingChanged:true,hardwareExecuted:false}));
