from pathlib import Path
r=Path('work/nss146')
s=Path('work/nss140/fast-models-v2.lua').read_text()
s=s.replace("local R={deadline=100,adapterSourceSequence=1,adapterProducer=comparisons.evidence.completeSelected.producer}","local R={deadline=100,adapterSourceSequence=1,adapterProducer=comparisons.evidence.completeSelected.producer}\n local Consumer={}\n __COMPARE__\n local epoch={producer=R.adapterProducer,epochUntil=6,decisions={}}\n for _,slot in ipairs({'tcp','udp'})do epoch.decisions[#epoch.decisions+1]={slot=slot,class=slot=='tcp'and'BULK'or'RT',downTag=slot=='tcp'and 2399469568 or 2399535104,classifierKey=slot,flow={id=slot=='tcp'and 1 or 2,mark=65536,wan=1,original={src='client'},reply={src='peer'}}}end\n function Consumer.inspect(snapshot,context,t)assert(t<snapshot.startedAt+6,'Fresh source expired');return{candidates=snapshot.flows}end\n local function snapshot()\n  local q={producer=R.adapterProducer,startedAt=math.floor(at/3)*3,flows={}}\n  if kind=='stale-software-source'and at>=7 then q.startedAt=0 end\n  for _,d in ipairs(epoch.decisions)do q.flows[#q.flows+1]={key=d.classifierKey,identity={connectionId=d.flow.id,mark=d.flow.mark,wan=d.flow.wan,original=d.flow.original,reply=d.flow.reply},decision={class=d.class},leaf={downTag=d.downTag}}end\n  if kind=='software-class-change'and at>=7 then q.flows[1].decision.class='BE';q.flows[1].leaf.downTag=0 end\n  return q\n end")
s=s.replace("local function stopped()assert(stop==1 and total==0)end", "local function stopped()assert(not(kind=='software-control-not-stopped'and at>=7),'Closed software phase lost control');assert(stop==1 and total==0)end")
s=s.replace("function A.compareObserved()\n  if kind=='unchanged'or stop==1 or at<23 then return{action='KEEP_IMMUTABLE_EPOCH'}end", "function A.compareObserved(closed)\n  local checked=Consumer.compareEpoch(epoch,snapshot(),{},at,closed)\n  if checked.action~='KEEP_IMMUTABLE_EPOCH'then return checked end\n  if kind=='unchanged'or kind=='expired-active'or kind=='stale-software-source'or kind=='software-class-change'or kind=='software-control-not-stopped'or stop==1 or at<23 then return checked end")
s=s.replace("function A.resampleClosed()return{provenance={startedAtUptime=at},flows={{validUntilUptime=at+6},{validUntilUptime=at+6}}}end", "function A.resampleClosed()local start=math.floor(at/3)*3;epoch.epochUntil=start+6;R.adapterSourceSequence=math.floor(at/3)+1;return{provenance={startedAtUptime=start},flows={{validUntilUptime=start+6},{validUntilUptime=start+6}}}end")
s=s.replace("function A.acceptRenewal(p,ack)assert(p.nextSequence==ack.sequence);R.adapterSourceSequence=ack.sequence end", "function A.acceptRenewal(p,ack)assert(p.nextSequence==ack.sequence);R.adapterSourceSequence=ack.sequence;if kind~='expired-active'then epoch.epochUntil=ack.classifierUntilMs/1000 end end")
s=s.replace("  assert(stop==1);if kind=='no-full-frame'", "  assert(stop==1);if kind=='no-full-frame'")
s=s.replace("'pin-drift','remaining-shape'})", "'pin-drift','remaining-shape','expired-active','stale-software-source','software-class-change','software-control-not-stopped'})")
assert s.count('__COMPARE__')==1 and s.count("function A.compareObserved(closed)")==1
with (r/'fast-models.lua').open('x',encoding='utf-8') as f:f.write(s)
