import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{verifyPreparation}from'../nss136/session-binding.mjs';import{packGuardian}from'./pack-guardian.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';import{connectRouter}from'../nss27/connect-router.mjs';
const inherited=verifyPreparation(),old=JSON.parse(fs.readFileSync('work/nss136/entry-qualified.json')),root='work/nss137',h=b=>crypto.createHash('sha256').update(b).digest('hex'),sourceManifest={},checks=[];
for(const f of['fast-path.lua','classifier.lua','qos-physical.lua','tag-normalizer.lua','ssh-client.mjs','bounded-pacer.mjs','pack-lua.mjs','parse-ecm-any-wan.mjs','watcher-read.lua']){assert.equal(h(fs.readFileSync(root+'/'+f)),h(fs.readFileSync('work/nss136/'+f)));checks.push({name:'exact-inherited-'+f,passed:true});}
const source=fs.readFileSync(root+'/module-stage-guardian.lua','utf8'),a=source.indexOf('  local ending=deadline-1'),b=source.indexOf('  while now()<ending',a);assert.ok(a>0&&b>a);const policy=source.slice(a,b);
const script=`local j=require('luci.jsonc');local cases=0;local record={};local deadline=100;local function now()return 20 end;local function stopped()end;local function absent()end;local function store()end;local MOD='test';local function evaluate()${policy} return ending end\nassert(evaluate()==99);cases=cases+1;record.classChangeTestCompleted=true;assert(not pcall(evaluate));cases=cases+1;for _,key in ipairs({'moduleUnloaded','tagsRemoved','qosRestored','qosModuleUnloaded','dualPhysicalQueuesRestored','wanRestored','mwan3Restored','stateNodeRemoved'})do record[key]=true end;assert(evaluate()==25 and record.successEarlyCompletion);cases=cases+1;for _,key in ipairs({'moduleUnloaded','tagsRemoved','qosRestored','qosModuleUnloaded','dualPhysicalQueuesRestored','wanRestored','mwan3Restored','stateNodeRemoved'})do record[key]=false;assert(not pcall(evaluate));record[key]=true;cases=cases+1 end;print(j.stringify({passed=true,checks=cases,ramOnly=true,mockedState=true,routerWrites=false}))`;
const c=await connectRouter();try{const e=encode("lua - <<'NSS137_SUCCESS_ONLY_MODELS'\n"+script+"\nNSS137_SUCCESS_ONLY_MODELS\n"),raw=receipt(await c.run(e.command),e);fs.writeFileSync(root+'/success-policy-model-raw-private.json',JSON.stringify(raw,null,2)+'\n',{flag:'wx'});assert.equal(raw.code,0,raw.stderr);const p=JSON.parse(raw.stdout);assert.ok(p.passed&&p.checks===11);checks.push({name:'target-RAM-success-only-early-completion-11-boundaries',passed:true,checks:p.checks});}finally{c.close()}
const plan=JSON.parse(fs.readFileSync('work/nss135/controlled-class-20261005220728-a0f315c4/stage-plan-private.json')),render=packGuardian(source).replace('__PLAN__',()=>JSON.stringify(plan)).replace('__CORE_PHASE__',()=> 'return{}').replace('__QOS_PHYSICAL__',()=> 'return{}');const e=encode("/usr/bin/lua - <<'NSS20_STAGE_BEGIN'\n"+render+"\nNSS20_STAGE_BEGIN\n");assert.ok(e.execBytes<=9000);checks.push({name:'whole-new-guardian-in-original-transport-budget',passed:true,execBytes:e.execBytes,historicalActualPlanOnly:true});
for(const name of fs.readdirSync(root))if(/\.(mjs|py|lua|ps1)$/.test(name)&&!name.includes('private')){const f=root+'/'+name;sourceManifest[f]=h(fs.readFileSync(f));if(name.endsWith('.mjs')){const p=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}}
const p={...old,sourceManifest,inheritedBoundInputs:Object.keys(inherited.sourceManifest).length,successOnlyFullVerifiedRestorationBeforeEarlyCompletion:true,successRecordGraceSeconds:5,independentOwnerIsOriginalMaximum100Seconds:true,checks,productionExecution:false};fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(p,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,checks:checks.length,successPolicyNativeRamChecks:11,payloadBytes:p.payloadBytes,execBytes:e.execBytes,sourceBindings:Object.keys(sourceManifest).length,productionExecution:false}));
