// Correlate only this run's nonce+sequence; no NSS permission or qdisc change.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {connectRouter} from '../nss27/connect-router.mjs';
const root='work/nss108',load=JSON.parse(fs.readFileSync(root+'/load-latest-private.json')),cfg=JSON.parse(fs.readFileSync(load.dir+'/client-config-private.json')),tap=JSON.parse(fs.readFileSync(root+'/tap-stage-latest-private.json'));
const q=x=>"'"+x.replaceAll("'","'\\''")+"'",label='path-'+new Date().toISOString().replace(/\D/g,'').slice(0,14),save=(n,o)=>fs.writeFileSync(load.dir+'/'+label+'-'+n+'.json',JSON.stringify(o,null,2)+'\n',{flag:'wx'});
const serverCode=`import socket,struct,json,time\ntoken=bytes.fromhex(${JSON.stringify(cfg.token)});s=socket.socket(socket.AF_PACKET,socket.SOCK_DGRAM,socket.htons(3));s.settimeout(.1);start=time.monotonic();due=start+12;rows=[]\nprint('NSS108_SERVER_TAP_READY',flush=True)\nwhile time.monotonic()<due:\n try:b,a=s.recvfrom(2048)\n except socket.timeout:continue\n if len(b)<156 or b[0]!=0x45 or b[9]!=17:continue\n sp,dp=struct.unpack('!HH',b[20:24])\n if sp!=45818 and dp!=45818:continue\n if b[28:60]!=token:continue\n rows.append([struct.unpack('!Q',b[60:68])[0],'down' if sp==45818 else 'up',round((time.monotonic()-start)*1000,3),a[0],a[2]])\nprint(json.dumps({'passed':True,'seconds':time.monotonic()-start,'rows':rows,'readonly':True}),flush=True)\n`;
const c=await connectRouter();let p;try{
 assert.equal((await c.run('test -f '+tap.stage.ready.dir+'/udp-path-tap')).code,0,'Independent staging already expired');
 const stop=await c.run('cat /sys/kernel/debug/ecm/front_end_ipv4_stop; cat /sys/kernel/debug/ecm/ecm_nss_ipv4/accelerated_count');assert.equal(stop.stdout.trim(),'1\n0');
 p=spawn('ssh',['-o','BatchMode=yes','-o','ConnectTimeout=8','sub2api-dallas','timeout -k 1 15 python3 -B -E -s -u -c '+q(serverCode)],{windowsHide:true,stdio:['ignore','pipe','pipe']});let sout='',serr='';p.stdout.on('data',b=>sout+=b);p.stderr.on('data',b=>serr+=b);const done=new Promise(r=>p.once('close',r));
 const due=performance.now()+10000;while(!sout.includes('NSS108_SERVER_TAP_READY')&&performance.now()<due&&p.exitCode===null)await new Promise(r=>setTimeout(r,25));assert.ok(sout.includes('NSS108_SERVER_TAP_READY'));
 const raw=await c.run('timeout -k 1 10 '+tap.interpreter+' '+tap.stage.ready.dir+'/udp-path-tap 8 '+cfg.serverAddress+' '+cfg.udpPort+' '+cfg.token);save('router-raw-private',raw);assert.equal(raw.code,0,raw.stderr);const router=JSON.parse(raw.stdout.trim().split('\n').at(-1));assert.ok(router.passed);save('router-private',router);
 const code=await done;save('server-raw-private',{code,stdout:sout,stderr:serr});assert.equal(code,0,serr);const server=JSON.parse(sout.trim().split('\n').at(-1));save('server-private',server);
 await new Promise(r=>setTimeout(r,600));const events=fs.readFileSync(load.dir+'/udp-samples-private.jsonl','utf8').trim().split('\n').map(x=>JSON.parse(x));save('pc-events-private',{events,status:JSON.parse(fs.readFileSync(load.dir+'/status-private.json'))});
 const groups=router.groups.map(g=>({interface:g.interface,packetType:g.packetType,direction:g.direction,unique:g.unique,duplicates:g.duplicates,minSequence:Math.min(...g.sequenceTimes.map(x=>x[0])),maxSequence:Math.max(...g.sequenceTimes.map(x=>x[0]))}));
 const out={passed:true,softwareOnly:true,nssOpened:false,seconds:router.seconds,socketDrops:router.socketDrops,groups,serverUpRows:server.rows.filter(x=>x[1]==='up').length,serverDownRows:server.rows.filter(x=>x[1]==='down').length,pcFinalMatchingPendingAnalysis:true,notCs2Metric:true};save('summary',out);console.log(JSON.stringify(out));
}catch(e){save('failure-private',{error:String(e)});console.error(String(e).split('\n')[0]);process.exitCode=1;}finally{if(p&&p.exitCode===null)p.kill();c.close();}
