import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{verifyPreparation as inherited}from'../v13-two/session-binding-v6.mjs';
const root='work/v14-duration',old=inherited(),manifest={},hash=b=>crypto.createHash('sha256').update(b).digest('hex');
for(const n of fs.readdirSync(root))if(/\.(mjs|lua|py|ps1)$/.test(n)){const f=root+'/'+n;manifest[f]=hash(fs.readFileSync(f));if(n.endsWith('.mjs')){const p=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}}
const native=JSON.parse(fs.readFileSync('work/v13/native-qualified.json'));assert.ok(native.passed&&native.model.sixtySecondsObserved&&native.model.backendMocked&&!native.fullFactoryModeled);assert.equal(native.fastSourceSha256,hash(fs.readFileSync(root+'/fast-path.lua')));
const stage=fs.readFileSync(root+'/module-stage.mjs','utf8');assert.ok(stage.includes("{verifyCandidate,validateRefinement} from './candidate-policy.mjs'"));assert.ok(!stage.includes('nss75/refinement')&&!stage.includes('nss53/qualification'));
const guard=fs.readFileSync(root+'/module-stage-guardian.lua','utf8');assert.ok(guard.includes('local deadline=now()+180;'));const epoch=fs.readFileSync(root+'/epoch-driver.mjs','utf8');assert.ok(epoch.includes('p.seconds>=60&&p.seconds<=61.5&&p.sampleCount>=118'));assert.ok(epoch.includes("n==='last-record-private'?JSON.stringify(v)"));
const supervisor=fs.readFileSync(root+'/pilot-supervisor.mjs','utf8');assert.ok(supervisor.includes('remainingSeconds>=130')&&supervisor.includes('phases[0].seconds>=60'));
const r=JSON.parse(fs.readFileSync('work/v13-two/session-20261006174010-83062d2d/last-record-private.json'));const b=r.phases[0];assert.ok(r.automaticLifecycleEpochCompleted&&b.seconds>=20&&r.wanRestored&&r.dualPhysicalQueuesRestored);const estimate=structuredClone(r),samples=r.samples.filter(s=>s.phase==='B');assert.ok(samples.length===41);estimate.samples=Array.from({length:123},(_,i)=>structuredClone(samples[i%samples.length]));estimate.renewals=Array.from({length:24},(_,i)=>structuredClone(r.renewals[i%r.renewals.length]));const estimatedBytes=Buffer.byteLength(JSON.stringify(estimate));assert.ok(estimatedBytes<900000,'Unchanged 1MiB reader lacks headroom; do not enter hardware');
const q={passed:true,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,originalTwoWanHardwareEvidenceReused:true,exactSixtySecondFastSourceModelReused:true,wholeFactoryModeled:false,sourceFreshnessSeconds:6,observerCadenceSeconds:.5,phaseSeconds:60,kernelSessionSeconds:90,nativeMaximumSessionSeconds:120,ownerSeconds:180,clientSeconds:180,minimumClientRemainingSeconds:130,unchangedNativeRuntime:true,modeledLongRecordBytes:estimatedBytes,modelRecordIsNotHardwareEvidence:true,recordLimitBytes:1048576,hardwareExecuted:false};fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});const result=(await import('./session-binding.mjs')).verifyPreparation();console.log(JSON.stringify({passed:true,bindings:Object.keys(result.sourceManifest).length,phaseSeconds:60,ownerSeconds:180,modeledCompactRecordBytes:estimatedBytes,hardwareNotYetExecuted:true}));
