import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import{spawnSync}from'node:child_process';
import{verifyGeneralBatch}from'../resident-general-dev-20261008/qualification.mjs';
import{verifyLocalBatch}from'../resident-normal-dev-h-20261008/qualification.mjs';
import{verifyServiceBatch}from'../resident-service-dev-h-20261008/qualification.mjs';
const repo='athena-nss-mainline',root='work/resident-task-dev-h-20261008',generalRoot='work/resident-general-dev-20261008',normalRoot='work/resident-normal-dev-h-20261008',serviceRoot='work/resident-service-dev-h-20261008';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const general=verifyGeneralBatch(),normal=verifyLocalBatch(),service=verifyServiceBatch();
const statusRaw=spawnSync(process.execPath,[serviceRoot+'/daemon.mjs','status'],{encoding:'utf8',windowsHide:true});
fs.writeFileSync(root+'/publication-status-raw-private.json',JSON.stringify({code:statusRaw.status,stdout:statusRaw.stdout,stderr:statusRaw.stderr})+'\n',{flag:'wx'});
assert.equal(statusRaw.status,0);const status=JSON.parse(statusRaw.stdout);assert.equal(status.running,true);assert.equal(status.identityVerified,true);assert.equal(status.heartbeatFresh,true);assert.equal(status.startupHealthPassed,true);assert.equal(status.admissionPaused,false);
// This batch is published as a deployed candidate, not as completed hardware acceptance.
assert.equal(status.generationsStarted,0);assert.equal(status.readFailures,0);
const state=read(serviceRoot+'/service-latest-private.json'),startup=read(state.runDirectory+'/startup-health.json');assert.equal(startup.passed,true);assert.equal(startup.routerWrites,false);
const startupRef=read(state.runDirectory+'/startup-health-reference-private.json').root;
const startupProofs={};for(const name of ['read-final-health.mjs','read-physical-final.mjs']){const raw=read(state.runDirectory+'/startup-'+name+'-raw-private.json');assert.equal(raw.code,0);startupProofs[name]=JSON.parse(raw.stdout);assert.equal(startupProofs[name].passed,true);}
const audit=startupProofs['read-final-health.mjs'],physical=startupProofs['read-physical-final.mjs'];assert.equal(audit.ecmClosedAndZero,true);assert.equal(audit.protectedConfigurationUnchanged,true);assert.equal(physical.defaultQueueOptionsAndHandlesExact,true);
const task=read(root+'/dev-h-task-upgrade-private.json');assert.equal(task.passed,true);assert.equal(task.onlyOwnedLaunchArgumentsChanged,true);assert.equal(task.otherRelatedTasksUnchanged,true);
const oldRoot='work/resident-rc1-run-20261008055107-ba4ee68e',oldPilot=read(oldRoot+'/pilot-reference-private.json').directory,oldDir=read(oldPilot+'/case-reference-private.json').dir;
const oldEntry=read(oldRoot+'/entry-result-private.json'),oldRecord=read(oldDir+'/last-record-private.json');assert.equal(oldEntry.state,'RESTORED');assert.equal(oldEntry.restorationPassed,true);assert.equal(oldRecord.stageComplete,true);assert.equal(oldRecord.moduleLoaded,false);assert.equal(oldRecord.newNssPermit,false);assert.ok(oldRecord.error.startsWith('Initial admission refused:'));
const originalManifest=fs.readFileSync(repo+'/source-manifest.json'),manifest=JSON.parse(originalManifest),prefix=structuredClone(manifest.sources);assert.equal(prefix.length,6108);
const originals=Object.fromEntries(prefix.map(x=>[x.path,x.sha256]));for(const [p,h]of Object.entries(originals))assert.equal(hash(fs.readFileSync(repo+'/'+p)),h,p);
const newPaths=[...fs.readdirSync(generalRoot).filter(n=>/\.(mjs|py)$/.test(n)).map(n=>generalRoot+'/'+n),...fs.readdirSync(generalRoot+'/endpoint-gate').filter(n=>/\.(c|h|py)$/.test(n)||n==='Makefile').map(n=>generalRoot+'/endpoint-gate/'+n),...fs.readdirSync(normalRoot).filter(n=>/\.(mjs|ps1)$/.test(n)).map(n=>normalRoot+'/'+n),...fs.readdirSync(serviceRoot).filter(n=>/\.(mjs|ps1)$/.test(n)).map(n=>serviceRoot+'/'+n),root+'/upgrade.ps1',root+'/publish.mjs'];
assert.equal(new Set(newPaths).size,newPaths.length);
let attributes=fs.readFileSync(repo+'/.gitattributes','utf8');const fresh=[];
for(const p of newPaths.sort()){
 assert.ok(!/private|credential|connect-router|\.ko$/.test(path.basename(p)));const bytes=fs.readFileSync(p),dest=repo+'/code/'+p;
 fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,bytes,{flag:'wx'});
 fresh.push({path:'code/'+p,workspaceSource:p,sha256:hash(bytes),bytes:bytes.length,role:'independent-eligible-flow-admission-development-candidate'});
 if(bytes.toString().replaceAll('\r\n','\n').endsWith('\n\n'))attributes+='\ncode/'+p+' whitespace=cr-at-eol,-blank-at-eof';
}
manifest.sources.push(...fresh);assert.deepEqual(manifest.sources.slice(0,prefix.length),prefix);manifest.generatedAt=new Date().toISOString();manifest.residentServiceDevBatch='DEV_H_INDEPENDENT_ELIGIBLE_FLOW_ADMISSION_CANDIDATE';
fs.writeFileSync(repo+'/.gitattributes',attributes.replace(/\n+$/,'')+'\n');fs.writeFileSync(repo+'/source-manifest.json',JSON.stringify(manifest,null,2)+'\n');
const native=read(generalRoot+'/native-source-qualified.json'),elf=read(generalRoot+'/runtime-elf-comparison.json'),build=read(generalRoot+'/endpoint-gate/build-manifest.json');
const evidence={developmentBatch:'dev-h',observedAt:new Date().toISOString(),milestone:'Independent eligible flow admission for resident Multi-WAN NSS controller',
 problem:{previousEntryRequiredTwoBulkDistinctWanAndOneRt:true,previousPreparationClassRefusalWasAfterCheckpointAndStage:true,exactCauseOfOldProjectionOrClassAbsenceUnknown:true,oldDetailedProbeUnavailable:true,oldFailureAndRestorationPreserved:true,userDownloadGameLossStillUnclosedP1:true},
 implementation:{independentEligibleSlots:['tcp','udp','tcp2'],nonemptyMasks:[1,2,3,4,5,6,7],maximumTcpBulk:2,maximumUdpRt:1,twoTcpMayShareWan:true,unusedSlotsDefaultDenied:true,ipv4DirectOwnedClientOnly:true,arbitraryReadableProcessOwnedSocketEligible:true,existingClassifierClassAndRtBudgetRequired:true,unknownAndInvalidFlowsRefused:true,immutableEpochNoHotInsertionOrRetag:true,newFlowsRequireFreshGenerationCheckpointPinsAndOwner:true,knownInitialRefusalWaitRequiresNoNssAndFullStagedRestore:true,projectionAbsenceNeverProvesCtExitOrRealClassChange:true,unknownFailureStillPauses:true},
 localRegression:{generalChecks:general.checks,normalChecks:normal.checks,serviceChecks:service.checks,generalJavascriptSyntax:general.syntaxSources,normalJavascriptSyntax:normal.syntaxSources,serviceJavascriptSyntax:service.syntaxSources,powershellSyntax:service.powershellSources,nativeControlChecks:native.controlChecks,nativeCtChecks:native.ctChecks,nativePredicateChecks:134,sevenSubsetLua51SyntaxAndCounterLeaseModelsPassed:true,subsetSizeModels:general.subsetModel,modelOnly:true,newOptionalNativeHardwareQualified:false},
 nativeBuild:{sourceSha256:native.sourceSha256,headerSha256:native.headerSha256,kernel:'6.18.44',buildCompleted:true,debugStripAllocatedSectionsAndRelocationsPreserved:true,runtimeComparison:elf,hardwareLoaded:false,oldSdkAndFrozenInputsPreserved:true},
 startup:{firstFailure:'P2 obsolete byte-exact assertion refused before router connection',firstFailureGenerations:0,firstFailurePreserved:true,assertionReplacedWithCurrentCandidateAndOriginalBounds:true,currentReadonlyAuditAndPhysicalQueuesPassed:true,ecmClosedAndZero:true,protectedConfigurationUnchanged:true,defaultQueueOptionsAndHandlesExact:true,privateStartupNamespacePreserved:true},
 live:{...status,runDirectory:state.runDirectory},deployment:{onlyOwnedTaskLaunchArgumentsChanged:true,otherRelatedTasksUnchanged:true,otherRelatedTasks:task.otherTasks,noLogonTrigger:true,noFailureRestart:true,noForceTermination:true,heartbeatRemainsPaused:true},
 actualIntegration:{attempted:false,reason:'No eligible natural flow at final fresh read; no traffic created',newCheckpointOrStage:false,newModuleLoaded:false,newNssPermission:false,completed:false},
 priorActualFailure:{startedAt:oldEntry.startedAt,finishedAt:oldEntry.finishedAt,checkpointCreated:true,stageCreated:true,nativeLoaded:false,nssPermission:false,hardwareCompleted:false,restorationPassed:true,oldRuntime:oldRoot},
 limits:{source:6,osSource:6,kernelMaximum:120,owner:180,client:180,phase:90,startsPer20Minutes:4,exec:9000,raw:65536,bundle:73728,nft:49152,record:1048576,actualInputEncodingBeforeEveryWrite:true,freshCheckpointDownloadShaGzipAndIndependentRestoreBeforeEveryWrite:true},
 protected:{classificationPolicyUnchanged:true,fiveWanPbrNatMarkAffinityUnchanged:true,schoolAuthenticationUnchanged:true,singboxTailscaleAndTenCakePreserved:true,qosBudgetsAndTreeUnchanged:true,downSharedMbps:18,upMbps:60,upPerWanMaximumMbps:12,rtPriority:0},
 limitations:['New optional-slot native candidate has local qualification only; actual bounded integration pending natural eligible flow','At most two TCP BULK plus one admitted UDP RT per finite generation','No all-LAN IPv6 proxy QUIC unknown-class admission','Process residence is continuous; NSS generations remain finite90s and rate bounded','No proof that reported CS2 download loss is fixed'],
 scope:{desktopOperated:false,newDownloadOrTrafficCreated:false,downloadPausedOrRateChanged:false,newCpuExperiment:false,newFormalHardwareVersion:false,archiveCreated:false,privateInputsExported:false},sourceHashes:Object.fromEntries(fresh.map(x=>[x.workspaceSource,x.sha256]))};
// Only sanitized model summaries; no real selected tuples, CT rows, owner nonce or config.
fs.writeFileSync(repo+'/evidence/resident-service-dev-h.json',JSON.stringify(evidence,null,2)+'\n',{flag:'wx'});
const stateText=`# 当前接续：dev-h独立合格流入口已部署，等待自然流的现场集成\n\n2026-10-08 14:43，控制器运行、身份和心跳已核对，启动完整只读审核及两物理原队列全部选项/handle通过，ECM关闭全零；当前BULK0/RT0、0新代，准入未暂停。控制使用 work/resident-service-dev-h-20261008/service.ps1 Status / Stop / Start，先核对，不重复启动。heartbeat仍暂停。\n\n本批将固定“两个不同WAN TCP BULK＋一个RT”改为合格流独立准入：1..3有效槽位、最多2 TCP BULK＋1已准入UDP RT；RT可单独进入，BULK无需等待RT，两个TCP可同WAN。Windows可读进程/socket归属、原分类和RT预算、完整CT/mark/NAT/affinity/kernel pin/lease仍必需；未知、代理标记及未用槽位默认拒绝。新流进入新代，旧epoch不热插入或强续。\n\n本地33一般模型、119正常入口、124服务检查及native157控制/109CT/134匹配检查通过；七种非空组合Lua5.1语法、counter/lease及原73728 bundle/9000 exec尺寸模型通过，同6.18.44编译完成。新optional-slot内核尚未加载硬件，完整90秒集成尚未完成；最后新鲜读取无自然合格流，未造流量。现网部署是候选等待，不是硬件验收。\n\ndev-g 13:51拒绝发生在checkpoint/stage后、tag/native/NSS放行前，完整恢复通过；旧probe细节缺失，不能判定CT退出或实际改类。dev-h仅在同帧明确初始准入缺失、无NSS、stage全撤销和最终保护/物理恢复全通过时回到等待，新代重新取源/pin/checkpoint/owner；其它失败仍暂停。首次启动旧源码字节相等断言在连接前拒绝，原输出保存，P2本地修复后实际启动审核通过。\n\n分类、PBR/NAT/mark/affinity、认证、singbox/Tailscale、十CAKE及DOWN18共享/UP60每WAN12/RT优先级保持。source6/OS6/native120/owner180/client180、每20分钟4代、每代90秒和全部字节上限不放宽。没有游戏操作、fixture、新下载、限速/暂停或CPU重测。用户下载时60–70%游戏丢包仍是未关闭P1，不能用本批代码或等待状态宣称体验修复。见[本批事实](../evidence/resident-service-dev-h.json)。\n\n`;
const planText=`# 当前最短路径：dev-h自然合格流的一次有界集成\n\n本地开发批次已收敛，独立准入候选已运行。下一条原有普通流自然达到BULK或已准入RT时，由现有有限入口取得新checkpoint下载/SHA/gzip和控制连接外独立恢复，再验证“新入口→NSS→完整恢复”。不要求游戏、不造fixture、不因无候选反复开实验。没有合格源时保持常驻观察；未知失败暂停并定位，P0先恢复。\n\n通过一次相关子集集成后结束本开发批次；复用既有五WAN/QoS/CPU/恢复证明，不重做全核心或寻找新边界。常驻仍为有限90秒代/20分钟四次，未扩全LAN、IPv6、代理/QUIC、WiFi/autorate/ECN；游戏丢包体验P1单独保持未关闭。新optional-slot内核当前仅本地资格，实际集成待自然负载。详见[STATE](STATE.md)和[本批事实](../evidence/resident-service-dev-h.json)。\n\n`;
const failureText=`# 当前blocker与限制：独立准入现场集成待自然负载\n\nP1：新optional-slot native尚未现场集成，用户大下载游戏丢包仍未关闭。已有正常三流/五WAN/CPU证明不重做。P2：固定组合/不同WAN限制、初始probe诊断丢失、旧startup byte-exact断言本批一起修复，集中本地回归通过。dev-g原拒绝确实已有checkpoint/stage，native和NSS尚未放行且最终恢复通过；缺少原详细probe，精确原因未知，不追溯标为“无写入”或“CT退出”。\n\ndev-h准备期失去准入只有在完整证明无NSS＋stage清理＋保护和两物理恢复通过时返回等待；未知错误/已进入NSS错误仍暂停，P0恢复优先。七种组合仅模型资格，实际无候选不当成功。其它非阻塞限制：有限代而非连续永久NSS；最多两BULK/一RT；单PC直接IPv4；其它协议/代理/全网和高阶功能后续。见[本批事实](../evidence/resident-service-dev-h.json)。\n\n`;
const controlText=`# 当前控制：dev-h独立合格流常驻候选\n\n原工作区运行 powershell -File work/resident-service-dev-h-20261008/service.ps1 -Mode Status / Stop / Start。任务Athena-NSS-Controller-Manual，仅启动参数变更，其它相关任务、权限、触发、重启和终止设置保持；进程运行与实际ECM分别核对。当前运行、BULK0/RT0、0新代，完整现场集成待自然合格负载。\n\n任一合格BULK或已准入RT可独立进入；最多2BULK＋1RT，TCP无需不同WAN。新代仍严格原分类/归属/CT/NAT/mark/affinity/pin/tag/lease、fresh checkpoint及独立恢复；已启动epoch不热替换。没有合格流就等待；只有已证明无NSS且完整恢复的初始准入缺失可再等新源，未知失败暂停。每代90秒/20分钟四次，非永久全网NSS；新native本地资格已通过、硬件待验。见[事实](../evidence/resident-service-dev-h.json)。\n\n`;
for(const [file,text]of[['docs/STATE.md',stateText],['docs/PLAN.md',planText],['docs/KNOWN_FAILURES.md',failureText],['docs/RESIDENT_SERVICE.md',controlText],['docs/RESIDENT_NORMAL_CONTROLLER.md',controlText]])fs.writeFileSync(repo+'/'+file,text+'## 以下保留历史记录\n\n'+fs.readFileSync(repo+'/'+file,'utf8'));
const agency=`# 当前接续：dev-h独立合格流入口候选运行\n\n先读STATE/PLAN/KNOWN_FAILURES/RESIDENT_SERVICE；使用work/resident-service-dev-h-20261008/service.ps1 Status，不重复启动。14:43启动完整只读/两物理恢复审核通过，BULK0/RT0/0新NSS，准入未暂停，heartbeat暂停。独立1..3槽位、最多2BULK＋1RT、允许同WAN，原分类/归属/CT/NAT/mark/affinity/pin/lease和全部期限/字节/恢复保护保持。33一般/119入口/124服务及native157/109/134模型、七子集Lua/尺寸、6.18.44编译通过，新optional native尚未硬件加载；仅等待自然负载一次有界集成，不造fixture/操作游戏/新下载/重做CPU。准备期已stage的缺资格须完整恢复后才等新代，旧g失败细节缺失不retro分类。游戏丢包P1尚未关闭。\n\n## 以下保留历史记录\n\n`;
fs.writeFileSync(repo+'/AGENTS.md',agency+fs.readFileSync(repo+'/AGENTS.md','utf8'));
fs.writeFileSync(repo+'/README.md',`当前接续：dev-h独立合格流入口已部署，启动只读审核通过；合格BULK/RT无需凑齐固定三流。当前0合格流/0新NSS，optional-slot硬件集成待自然负载；原保护和有限代上限保持。见[状态](docs/STATE.md)。\n\n`+fs.readFileSync(repo+'/README.md','utf8'));
fs.writeFileSync(repo+'/docs/EXPERIMENT_LOG.md',`# 2026-10-08 dev-h：独立合格流准入开发批次\n\n固定三流要求撤下，optional native1..3槽/同WANTCP、动态class/tag/counter/lease/cleanup与正常归属入口一起收敛。本地33/119/124和native157/109/134模型、七子集Lua/尺寸及6.18.44编译通过；本地首CT夹具/尺寸/路径断言失败保存后修复，不各开硬件版本。dev-g13:51已有checkpoint/stage后初始分类拒绝，native/NSS前退出并恢复；原缺详细probe不据此推断CT退出或实际改类。新probe保留，仅无NSS并完整恢复的已知准备期拒绝允许新鲜代等待。dev-h首启动旧byte-exact断言在网络前拒绝，P2本地修复和startup模型后实际启动完整只读审核通过。14:43进程运行、BULK0/RT0/0新NSS、准入未暂停；actual optional native尚未加载，没有现场集成通过。当前自然负载消失，不造流量；新鲜条件到来仅接续一次有限集成。源码/脱敏事实集中提交，不新正式版本/HTML/archive；原历史源码及私有失败保持。见[事实](../evidence/resident-service-dev-h.json)。\n\n## 以下保留历史记录\n\n`+fs.readFileSync(repo+'/docs/EXPERIMENT_LOG.md','utf8'));
for(const [p,h]of Object.entries(originals))assert.equal(hash(fs.readFileSync(repo+'/'+p)),h,'Historical source changed: '+p);
fs.writeFileSync(root+'/publication-result.json',JSON.stringify({passed:true,newSources:fresh.length,totalSourceHashes:manifest.sources.length,historicalPrefixPreserved:prefix.length,hardwareIntegrationCompleted:false,startupNamespace:startupRef},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({passed:true,newSources:fresh.length,totalSourceHashes:manifest.sources.length,historicalSourceBytesPreserved:true,hardwareIntegrationCompleted:false}));
