import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {validateAcceleratedState} from './parse-ecm-any-wan.mjs';
const root='work/nss48',dir='work/nss41/real-matched-aba-20261003165708-9086b676',hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),cases=[];
const selected=JSON.parse(fs.readFileSync(dir+'/selected-private.json')),record=JSON.parse(fs.readFileSync(dir+'/last-record-private.json'));
const real=validateAcceleratedState(record.acceleratedState,selected);assert.equal(real.proof.tcp.wanAffinity,1);assert.equal(real.proof.udp.wanAffinity,1);cases.push({case:'frozen actual WAN1 TCP and UDP state',passed:true,kind:'actual-state-replay'});
function selection(wan){const make=(protocol,id,port)=>({protocol,id,zone:0,wan,mark:wan*65536+17,original:{src:'192.168.237.207',dst:'198.51.100.'+(protocol===6?'50':'51'),sport:port,dport:protocol===6?443:27015},reply:{src:'198.51.100.'+(protocol===6?'50':'51'),dst:'203.0.113.10',sport:protocol===6?443:27015,dport:port+100}});return{tcp:make(6,1001,31001),udp:make(17,1002,31002)};}
function state(pair,reverseTcp,reverseUdp){return[['tcp',reverseTcp,2399469568],['udp',reverseUdp,2399535104]].map(([slot,reverse,tag],index)=>{const f=pair[slot],r={ip_version:4,is_routed:1,protocol:f.protocol,sip_address:reverse?f.original.dst:f.original.src,dip_address:reverse?f.original.src:f.original.dst,sport:reverse?f.original.dport:f.original.sport,dport:reverse?f.original.sport:f.original.dport,sip_address_nat:reverse?f.reply.src:f.reply.dst,dip_address_nat:reverse?f.reply.dst:f.reply.src,sport_nat:reverse?f.reply.sport:f.reply.dport,dport_nat:reverse?f.reply.dport:f.reply.sport,'nss_v4.ported.accel_mode':2,'classifiers.dscp.pr.flow_qos_tag':reverse?tag:0,'classifiers.dscp.pr.return_qos_tag':reverse?0:tag,'nss_v4.ported.slow_path_packets':3,'adv_stats.from_packet_total':10,'adv_stats.to_packet_total':20};r['classifiers.dscp.pr.'+(reverse?'return':'flow')+'_mark']=f.mark;const prefixes=reverse?['from_interfaces','from_nat_interfaces']:['to_interfaces','to_nat_interfaces'];for(const p of prefixes){r[p+'.0.iface.name']='rpwan'+f.wan;r[p+'.1.iface.name']='wan';}const lan=reverse?'to_interfaces':'from_interfaces';r[lan+'.0.iface.name']='lan4';r[lan+'.1.iface.name']='br-lan';return Object.entries(r).map(([k,v])=>'conns.conn.'+(1001+index)+'.'+k+'='+v).join('\n');}).join('\n')+'\n';}
for(let wan=1;wan<=5;wan++)for(const rt of [false,true])for(const ru of [false,true]){const pair=selection(wan),out=validateAcceleratedState(state(pair,rt,ru),pair);assert.equal(out.proof.tcp.wanAffinity,wan);assert.equal(out.proof.udp.wanAffinity,wan);cases.push({case:`WAN${wan} TCP ${rt?'server':'client'} and UDP ${ru?'server':'client'} orientation`,passed:true,kind:'synthetic-state'});}
const base=selection(1),raw=state(base,true,false),negative=[];
const wrong=(name,fn)=>{const p=structuredClone(base);fn(p);negative.push([name,raw,p]);};
wrong('selected WAN below range',p=>p.tcp.wan=p.udp.wan=0);wrong('selected WAN above range',p=>p.tcp.wan=p.udp.wan=6);wrong('selected WAN fractional',p=>p.tcp.wan=p.udp.wan=1.5);wrong('mixed selected WAN',p=>p.udp.wan=2);wrong('selected mark disagrees with WAN',p=>p.tcp.mark=p.udp.mark=0x20011);wrong('selected full marks differ',p=>p.udp.mark++);wrong('proxy mark forbidden',p=>p.tcp.mark=p.udp.mark=0x12011);wrong('wrong selected zone',p=>p.udp.zone=1);wrong('invalid CT instance',p=>p.tcp.id=0);wrong('wrong selected protocol',p=>p.tcp.protocol=17);wrong('different selected NAT addresses',p=>p.udp.reply.dst='203.0.113.11');wrong('wrong expected NAT port',p=>p.udp.reply.dport++);
negative.push(['incorrect interface WAN',raw.replaceAll('=rpwan1','=rpwan5'),base],['missing physical WAN layer',raw.replaceAll('=wan\n','=other\n'),base],['missing LAN4 layer',raw.replaceAll('=lan4','=lan1'),base],['missing br-lan layer',raw.replaceAll('=br-lan','=other'),base],['wrong full firmware mark',raw.replaceAll('=65553','=65554'),base],['wrong RT tag',raw.replaceAll('=2399535104','=2399469568'),base],['unaccelerated firmware mode',raw.replaceAll('accel_mode=2','accel_mode=1'),base],['duplicate state attribute',raw+'conns.conn.1001.protocol=6\n',base],['unexpected state line',raw+'unexpected\n',base],['unexpected third connection',raw+'conns.conn.1003.protocol=6\n',base]);
for(const [name,bytes,pair]of negative){assert.throws(()=>validateAcceleratedState(bytes,pair),name);cases.push({case:name,passed:true,kind:'rejection'});}
const out={passed:true,checks:cases.length,actualStateCases:1,syntheticPositiveCases:20,rejectionCases:negative.length,cases,testedSourceManifest:{[root+'/parse-ecm-any-wan.mjs']:hash(root+'/parse-ecm-any-wan.mjs'),[root+'/test-parser.mjs']:hash(root+'/test-parser.mjs')},frozenRawStateSha256:crypto.createHash('sha256').update(record.acceleratedState).digest('hex'),hardwareExperimentRerun:false,scope:'One frozen real hardware-state replay, 20 synthetic WAN/orientation states and explicit invalid-state mutations; no flow admission or live experiment.',routerWrites:false};fs.writeFileSync(root+'/parser-qualified.json',JSON.stringify(out,null,2)+'\n');fs.writeFileSync(root+'/real-state-replayed-private.json',JSON.stringify(real,null,2)+'\n');console.log(JSON.stringify({passed:true,checks:out.checks,actualStateCases:1,syntheticPositiveCases:20,rejectionCases:negative.length}));
