import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';
import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';import{connectRouter}from'../nss27/connect-router.mjs';import{packLua}from'../nss149/pack-lua.mjs';
const root='work/v15-qos',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),qos=fs.readFileSync(root+'/qos-physical.lua','utf8'),normalizer=fs.readFileSync(root+'/tag-normalizer.lua','utf8'),plan=JSON.parse(fs.readFileSync(root+'/modeled-tag-plan-private.json'));
const code=qos.slice(qos.indexOf('local function specs('),qos.indexOf('function M.new('));assert.ok(code.includes('local function validate('));
const specModel=`local P={selected={tcp={wan=4},udp={wan=3}},tagPlan=assert(j.parse([====[${JSON.stringify({wanLeafAssignments:plan.wanLeafAssignments})}]====]))}
local checks=0
for _,up in ipairs({false,true})do local s=specs(P,up);assert(s.shared==(up and 60 or 30)and s.perWan==(up and 30 or 15));local qs,cs={},{};for _,line in pairs(s.qs)do qs[#qs+1]=line..'\\n Sent 100 bytes 1 pkt (dropped 0, overlimits 0 requeues 0)'end;for h,opt in pairs(s.cs)do cs[#cs+1]='class nsshtb '..h..' root '..(s.leaves[h]and'leaf '..s.leaves[h]..' 'or'')..opt..'\\n Sent 100 bytes 1 pkt (dropped 0, overlimits 0 requeues 0)'end;local q=table.concat(qs,'\\n');local c=table.concat(cs,'\\n');assert(validate(q,c,true,s).nativeOptionsValidated);assert(#s.commands==15);local base=up and'8e00:'or'8f00:';assert(table.concat(s.commands,'\\n'):find('parent '..base..'104 classid '..base..'45',1,true));assert(table.concat(s.commands,'\\n'):find('parent '..base..'103 classid '..base..'36',1,true));assert(not pcall(validate,q:gsub('parent '..base..'45','parent '..base..'35'),c,true,s));checks=checks+1 end
print(j.stringify({passed=true,checks=checks,backendMocked=true,actualSpecsAndValidatorExecuted=true,firmwareAcceptance=false}))`;
const normalizerModel=`local P=assert(j.parse([====[${JSON.stringify(plan)}]====]));local N=(function()${packLua(normalizer)} end)();local before=N(P.expected,P);local raw=assert(j.parse(j.stringify(P.expected)));for _,x in ipairs(raw.nftables)do if x.rule then for _,e in ipairs(x.rule.expr)do if e.mangle and e.mangle.key.meta.key=='priority'then e.mangle.value=string.format('%x:0',e.mangle.value/65536)end;if e.match and e.match.left.meta and e.match.left.meta.key=='priority'and type(e.match.right)=='number'and e.match.right>0 then e.match.right=string.format('%x:0',e.match.right/65536)end end end end;assert(N(raw,P)==before);local bad=assert(j.parse(j.stringify(raw)));local changed=false;for _,x in ipairs(bad.nftables)do if x.rule then for _,e in ipairs(x.rule.expr)do if e.mangle then e.mangle.value='8f05:0';changed=true;break end end end;if changed then break end end;assert(changed and not pcall(N,bad,P));print('WAN_NATIVE_TAG_NORMALIZATION_PASS')`;
const commands={qos:encode("lua - <<'V15_QOS_MODEL'\nlocal j=require('luci.jsonc');\n"+code+specModel+"\nV15_QOS_MODEL\n"),normalizer:encode("lua - <<'V15_TAG_MODEL'\nlocal j=require('luci.jsonc');\n"+normalizerModel+"\nV15_TAG_MODEL\n")};
const c=await connectRouter();let model;
try{for(const[name,e]of Object.entries(commands)){const raw=receipt(await c.run(e.command),e);fs.writeFileSync(root+'/'+name+'-native-model-raw-private.json',JSON.stringify(raw,null,2)+'\n',{flag:'wx'});assert.equal(raw.code,0,name+' model failure retained');if(name==='qos'){model=JSON.parse(raw.stdout);assert.ok(model.passed&&model.checks===2&&model.backendMocked)}else assert.equal(raw.stdout.trim(),'WAN_NATIVE_TAG_NORMALIZATION_PASS');}}
finally{c.close();}
const result={passed:true,qosSourceSha256:hash(qos),normalizerSourceSha256:hash(normalizer),qosModel:model,nativeTagNormalization:true,wrongTagRejected:true,wholeFactoryModeled:false,hardwareExecuted:false,productionWrites:false,routerFilesWritten:false,execBytes:Object.fromEntries(Object.entries(commands).map(([k,v])=>[k,v.execBytes]))};fs.writeFileSync(root+'/native-qualified.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result));
