import fs from 'node:fs';import assert from 'node:assert/strict';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
process.chdir(path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'));
const root='work/resident-service-delivery-20261008',service='work/resident-service-dev-20261008',mode=process.argv[2];assert.ok(['first','progress','stopped','retained','tasks'].includes(mode));assert.equal(process.argv[3],undefined);
const save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n',{flag:'wx'});
if(mode==='tasks'){
 const code=String.raw`$ErrorActionPreference='Stop';$b=Get-Content -LiteralPath 'work/resident-service-dev-20261008/tasks-before-private.json' -Raw|ConvertFrom-Json;foreach($x in $b){$xml=Export-ScheduledTask -TaskName $x.taskName -TaskPath $x.taskPath;$sha=[Security.Cryptography.SHA256]::Create();try{$h=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($xml)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()};if($h -ne $x.sha256){throw 'Unrelated known task changed'}};$t=Get-ScheduledTask -TaskName 'Athena-NSS-Controller-Manual' -TaskPath '\';if($t.Triggers.Count -gt 0 -or $t.Settings.RestartCount -gt 0){throw 'Unexpected automatic trigger or restart'};@{passed=$true;knownTaskFingerprintsUnchanged=$b.Count;taskExists=$true;taskState=[string]$t.State;logonTriggerCount=$t.Triggers.Count;restartCount=$t.Settings.RestartCount;runLevel=[string]$t.Principal.RunLevel;hardTerminationDisabled=($t.Settings.AllowHardTerminate -eq $false);unlimitedProcessResidence=($t.Settings.ExecutionTimeLimit -eq 'PT0S')}|ConvertTo-Json -Compress`;
 const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',code],{encoding:'utf8',windowsHide:true,timeout:20000});save(root+'/tasks-dev-b-raw-private.json',{code:r.status,stdout:r.stdout,stderr:r.stderr});assert.equal(r.status,0,r.stderr);const result=JSON.parse(r.stdout);assert.equal(result.hardTerminationDisabled,true);assert.equal(result.unlimitedProcessResidence,true);save(root+'/tasks.json',result);console.log(JSON.stringify(result));
}else{
 const r=spawnSync(process.execPath,[service+'/daemon.mjs','status'],{encoding:'utf8',windowsHide:true,timeout:20000});save(root+'/'+mode+'-status-raw-private.json',{code:r.status,stdout:r.stdout,stderr:r.stderr});assert.equal(r.status,0,r.stderr);const status=JSON.parse(r.stdout),ledger=JSON.parse(fs.readFileSync(service+'/service-latest-private.json'));
 save(root+'/'+mode+'-ledger-private.json',ledger);save(root+'/'+mode+'-status.json',{observedAt:new Date().toISOString(),...status});
 if(mode==='stopped'){assert.equal(status.state,'STOPPED');assert.equal(status.running,false);assert.equal(status.restorationPassed,true);assert.equal(status.controllerLockPresent,false);assert.equal(status.activeGenerationLockPresent,false);}
 else{assert.equal(status.running,true);assert.equal(status.identityVerified,true);assert.equal(status.heartbeatFresh,true);assert.equal(status.startupHealthPassed,true);assert.equal(status.state,'WAITING_FLOW');assert.ok(status.reads>=1);assert.equal(status.generationsStarted,0);assert.equal(status.activeGenerationLockPresent,false);}
 if(mode==='progress'){const prior=JSON.parse(fs.readFileSync(root+'/first-status.json'));assert.ok(status.reads>prior.reads);assert.ok(status.lastObservation.sourceSequence>prior.lastObservation.sourceSequence);assert.ok(Date.parse(status.heartbeatAt)>Date.parse(prior.heartbeatAt));}
 console.log(JSON.stringify({mode,...status}));
}
