"""Collect completed trials; retain failed trials without changing their outcome."""
from pathlib import Path
import hashlib,json,importlib.util,re
w=Path(__file__).resolve().parents[2];r=w/'work/nss139'
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(name,o):
 p=r/(name+'.json');assert not p.exists();p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
spec=importlib.util.spec_from_file_location('collector',w/'work/nss101/collect-lifecycle.py');c=importlib.util.module_from_spec(spec);spec.loader.exec_module(c)
life=load(w/'work/nss138/class-lifecycle-proof.json');assert life['proof']['passed']
first=w/load(w/'work/nss138/experiment-reference.json')['output'];second=w/load(w/'work/nss138/relearning-reference.json')['output'];timing=[]
for case in [first,second]:
 record=load(case/'last-record-private.json');plan=load(case/'stage-plan-private.json');receipt=load(case/'stage-receipt-private.json');undo=load(case/'stage-undo-verified.json')
 assert record['successEarlyCompletion']and record['successRecordGraceSeconds']==5 and record.get('error')is None and all(undo.values())
 assert all(record[k]is True for k in ['moduleUnloaded','tagsRemoved','qosRestored','qosModuleUnloaded','dualPhysicalQueuesRestored','wanRestored','mwan3Restored','stateNodeRemoved'])
 assert plan['execBytes']<=9000 and plan['qosCodeBytes']<=73728
 timing.append({'mode':load(case/'result.json')['mode'],'successOnlyEarlyOwnerCompletion':True,'successRecordGraceSeconds':5,'independentMaximumSeconds':100,'execBytes':plan['execBytes'],'qosBundleBytes':plan['qosCodeBytes'],'guardianVerifiedBeforeWrite':receipt['rollbackBeforeFirstWrite'],'completeUndoVerified':True,'allOriginalQueuesAndModulesRestoredBeforeEarlyCompletion':True})
oldcase='work/nss135/controlled-class-20261005220728-a0f315c4';old=c.stage(oldcase);assert old['passed']and not old['completeABA'];oldrecord=load(w/oldcase/'last-record-private.json');assert oldrecord['classChangeTestCompleted']and load(w/'work/nss135/driver-error.json')['experiment']['passed']
old['overallTwoEpochDriverPassed']=False;old['freshGenerationRelearningAttempted']=False;old['reasonSecondEpochRefused']='Original finite client deadline exhausted while successful old owner waited to its 100-second expiry'
failed=c.stage('work/nss133/controlled-class-20261005220027-abee66d9');assert not failed['passed']and failed['ecmOpened']and all(failed['rollback'].values());assert not (w/'work/nss133/controlled-class-20261005220027-abee66d9/application-pause-private.json').exists()
failed['actualApplicationPauseOccurred']=False;failed['watcherFailure']='Lua gsub returned two values, passing replacement count as tonumber base';failed['classChangePhysicallyProved']=False
sources=load(w/'work/nss138/entry-source-manifest.json');assert len(sources)==1340
for f,h in sources.items():assert sha(w/f)==h and sha(w/'work/nss138/frozen-qualified-inputs'/f)==h
closures=[]
for n in [129,131,132,133,135,136,138]:
 p=w/f'work/nss{n}';ref=load(p/'load-reference-private.json');x=c.closure(ref['dir']);x['round']=f'NSS{n}'
 upload=load(w/ref['dir']/'upload-server-closed-private.json')if (w/ref['dir']/'upload-server-closed-private.json').exists()else None
 x['uploadClosureReceiptName']=next((q.name for q in (w/ref['dir']).glob('*')if 'upload'in q.name and 'closed'in q.name),None)
 closures.append(x)
recovery=w/'work/nss131/controlled-class-20261005214847-744c9b6a';u=load(recovery/'stage-undo-verified.json');assert all(u.values());detached=load(recovery/'stage-detached-private.json');receipt=load(recovery/'stage-receipt-private.json');assert detached['identity']['ppid']==1 and receipt['rollbackBeforeFirstWrite']and receipt['parentIdentityVerified']and receipt['pipeInodesVerified']
recovery131={'originalFailurePreserved':True,'reason':'Concurrent connection helper temporarily changed global process cwd while another upload/record writer used relative paths','checkpointDownloadedShaAndGzipVerified':load(recovery/'stage-checkpoint-verified.json')['gzipVerified'],'guardianVerifiedBeforeWrite':True,'independentMaximumSeconds':100,'partialStagingAttempted':True,'activationOrEcmOpeningProved':False,'actualActivationStateUnavailable':True,'missingRecordNotInvented':True,'undo':u,'laterOriginalFullOperationalAuditPassed':load(w/'work/nss131/v1-final-health.json')['passed']}
exit=load(w/'work/nss130/v1-exit-private.json')['last-error'];assert exit['pid']==4859 and 'rawStatus=256'in exit['error']and 'action=apply'in exit['error'];recovered=load(w/'work/nss130/v2-final-health.json');assert recovered['passed']and recovered['workerPid']==31657 and recovered['guardianPid']==17139
classifier={'previousWorkerPid':4859,'currentWorkerPid':31657,'guardianPid':17139,'naturalProcdRecovery':True,'forcedRestartOrReinstall':False,'observedFailure':{'action':'apply','rawStatus':256,'elapsedSeconds':0.35,'querySequence':exit['lastQuerySequence']},'rootCauseProved':False,'orphanBatchPidCollisionIsUnconfirmedHypothesis':True,'actualChildPidAndStderrUnavailable':True,'oldGuardianFailureRecordBelongsToDifferentHistoricalInstance':True,'fullOriginalAuditPassedAfterRecovery':True,'sourceConfigUnchanged':True,'originalLastErrorSha256':sha(w/'work/nss130/v1-exit-private.json')}
failure137=load(w/'work/nss137/qualification-failure.json');assert not failure137['productionExperimentWrites']and not failure137['checkpointCreated']and not failure137['endpointStarted']
failures=[{'round':'NSS129','stage':'Owned load / read-only matching','productionRouterExperimentStarted':False,'reason':'Permanent classifier worker exited during owned load; procd recovered it','rootCauseProved':False}, {'round':'NSS131-local','stage':'Local binding verification','productionRouterExperimentStarted':False,'reason':'Namespace-only protocol marker was incorrectly required to be byte exact; corrected binding before production staging'}, {'round':'NSS131','stage':'Independent module staging','productionRouterExperimentStarted':True,'reason':recovery131['reason'],'activationOrEcmOpeningProved':False,'actualActivationStateUnavailable':True}, {'round':'NSS132','stage':'Read-only load qualification','productionRouterExperimentStarted':False,'reason':'No recent actual UDP replies before staging','wan':5,'wan5DeterministicFailureProved':False}, {'round':'NSS133','stage':'Exact class change','productionRouterExperimentStarted':True,'reason':failed['watcherFailure'],'ecmOpened':True,'applicationPauseOccurred':False,'realClassChangeProved':False,'rollbackPassed':True}, {'round':'NSS135','stage':'Second independent epoch','productionRouterExperimentStarted':True,'firstExactTcpRetirementPassed':True,'secondEpochStarted':False,'reason':old['reasonSecondEpochRefused']}, {'round':'NSS136','stage':'Pre-write client budget','productionRouterExperimentStarted':False,'reason':'150-second estimate could not cover two 100-second idle owner waits within original 180-second client limit'}, {'round':'NSS137','stage':'Local transport qualification','productionRouterExperimentStarted':False,'reason':failure137['cause'],'targetRamSuccessPolicyChecks':11}]
for f in failures:f['originalFailurePreserved']=True
final=load(r/'v1-final-health.json');physical=load(r/'physical-final.json');assert final['passed']and final['ecmStoppedAndZero']and final['workerPid']==31657 and final['guardianPid']==17139 and physical['passed']
dump('class-lifecycle',life);dump('owner-completion',timing);dump('first-retirement',old);dump('failed-class-change',failed);dump('staging-recovery',recovery131);dump('classifier-recovery',classifier);dump('failures',failures);dump('endpoint-closure',closures)
print(json.dumps({'passed':True,'actualClassChangeAndFreshEpoch':True,'bothActualStages':2,'sourceInputsEach':1340,'retirementPriorRepeatPassed':True,'failedTrialsPreserved':len(failures),'finiteLoadsClosed':len(closures),'currentWorkerPid':31657,'unconfirmedClassifierRootCause':True}))
