"""Publish actual class retirement and new-epoch relearning, preserving history."""
from pathlib import Path
from datetime import datetime,timezone,timedelta
import json,hashlib,shutil,subprocess
w=Path(__file__).resolve().parents[2];repo=w/'athena-nss-mainline';r=w/'work/nss139'
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(b):return hashlib.sha256(b).hexdigest()
def dump(p,o):p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
life=load(r/'class-lifecycle.json');proof=life['proof'];final=load(r/'v1-final-health.json');physical=load(r/'physical-final.json');closures=load(r/'endpoint-closure.json');receiver=load(r/'receiver-closure.json');owner=load(r/'owner-completion.json');qual=load(w/'work/nss138/entry-qualified.json');failures=load(r/'failures.json')
assert proof['passed']and proof['realClassChange']and proof['freshKernelPinAndNativeGeneration']and proof['sameTcpUdpCtIdentitiesAcrossGenerations']and proof['firstStageSourceInputs']==proof['secondStageSourceInputs']==1340
assert final['passed']and final['ecmStoppedAndZero']and final['workerPid']==31657 and final['guardianPid']==17139 and physical['passed']and receiver['passed']and len(closures)==7
assert all(o['completeUndoVerified']and o['execBytes']<=9000 and o['qosBundleBytes']<=73728 for o in owner)
old=(repo/'evidence/current-runtime.json').read_bytes();assert load(repo/'evidence/current-runtime.json')['round']=='NSS128'and subprocess.check_output(['git','show','HEAD:evidence/current-runtime.json'],cwd=repo)==old
archive=repo/'evidence/nss128-runtime.json';assert not archive.exists();archive.write_bytes(old)
manifest=load(repo/'source-manifest.json');assert len(manifest['sources'])==1571;prefix=sha(json.dumps(manifest['sources'],sort_keys=True,separators=(',',':')).encode())
common=['prepare.py','bounded-pacer.mjs','upload-ack.mjs','upload-server.py','ssh-client.mjs','session-binding.mjs','qualify.mjs','controlled-session.mjs','current-audit-diagnostic.mjs','match-controlled.mjs','read-controlled.mjs','run.mjs','module-stage.mjs','payload.mjs','pack-lua.mjs','pack-guardian.mjs','compact-default-queues.mjs','uplink-tag-plan.mjs','parse-ecm-any-wan.mjs','fast-path.lua','module-stage-guardian.lua','qos-physical.lua','tag-normalizer.lua','failed-wan-owner.lua','declared-baseline.mjs','service-epoch.mjs','health.mjs','read-final-physical.mjs','classifier.lua','pause-control.mjs']
allowed={n:list(common)for n in [129,131,132,133,135,136,137,138]}
allowed[129]+=['qualify-v1.mjs']if (w/'work/nss129/qualify-v1.mjs').exists()else[]
allowed[130]=['health.mjs','inspect-classifier-v1.mjs','inspect-classifier.mjs','read-exit.mjs','recover-131.mjs']
allowed[131]+=['repair-binding.mjs','session-binding-v1.mjs']
allowed[134]=['collect-class-lifecycle.py','read-complete-selected.mjs']
for n in [135,136,137,138]:allowed[n]+=['watcher-read.lua']
allowed[137]+=['measure-guardian.mjs']
allowed[139]=['inventory-evidence.py','prepare-audits.py','collect-evidence.py','verify-receivers.mjs','health.mjs','read-final-physical.mjs','save-evidence.py']
hashes={}
for n,names in allowed.items():
 for name in names:
  src=w/f'work/nss{n}'/name;assert src.is_file(),str(src);rel=src.relative_to(w).as_posix();dst=repo/'code'/rel;assert not dst.exists();dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst);digest=sha(src.read_bytes());hashes[rel]=digest;manifest['sources'].append({'path':'code/'+rel,'workspaceSource':rel,'sha256':digest,'bytes':src.stat().st_size,'role':'exact-class-retirement-and-fresh-epoch-relearning'})
manifest['generatedAt']=datetime.now(timezone.utc).isoformat();manifest['lastAppendExport']='NSS139';dump(repo/'source-manifest.json',manifest)
frozen={};freeze=r/'proof-v1/private-inputs';freeze.mkdir(parents=True,exist_ok=False)
for n in range(129,140):
 for src in sorted((w/f'work/nss{n}').rglob('*')):
  if not src.is_file()or any(x in ['proof-v1','frozen','frozen-qualified-inputs','__pycache__']or x.startswith('published-')for x in src.parts):continue
  rel=src.relative_to(w);dst=freeze/rel;dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst);frozen[rel.as_posix()]=sha(src.read_bytes());assert sha(dst.read_bytes())==frozen[rel.as_posix()]
dump(r/'private-input-freeze-index.json',frozen)
summary={'round':'NSS139','hardwareEntryRound':138,'observedAt':final['observedAt'],'boundInputs':1340,'oneWan':2,'onlyTcpBulkAndUdpRt':True,'actualClassChange':'BULK->BE cooldown','completeSameQueryClassEvidence':True,'projectionAbsenceAloneAccepted':False,'exactAffectedTcpCiRetired':True,'remainingUdpSameCiRtTagsVerified':True,'sameSocketCtMarkNatWanAcrossEpochs':True,'newKernelPinAndDifferentEcmCiVerified':True,'ecmCountsFirst':[2,1,0],'ecmCountsSecond':[0,2,0],'nativeSessionSeconds':27,'classifierMaximumLeaseSeconds':6,'independentOwnerMaximumSeconds':100,'clientMaximumSeconds':180,'successOnlyOwnerEarlyCompletionAfterFullRestoration':True,'successReceiptGraceSeconds':5,'failureOwnerMaximumUnchanged':True,'firstRetirementAlsoPassedIn135':True,'overall135RelearningPassed':False,'failedTrialsPreserved':len(failures),'finiteLoadsClosed':7,'ownedSshReceiversRemaining':0,'residentClassifierChanged':False,'residentUpTagZeroUnchanged':True,'naturalWorkerRecoveryObserved':True,'classifierFailureRootCauseProved':False,'newCpuComparison':False,'humanCs2Acceptance':False,'highLoad300MbpsAcceptance':False,'fullCakeReplacementAccepted':False,'nssPermanentlyEnabled':False,'uiOperated':False,'newDownloadStarted':False,'upstreamSubmitted':False,'reportVerification':{'sourceValidated':True,'browserRendered':False}}
source={'round':'NSS139','historicPrefixSources':1571,'historicPrefixCanonicalSha256':prefix,'sources':len(hashes),'sourceHashes':hashes,'privateHostBootstrapExcluded':True,'actualBindingTreesRetained':True,'privateArtifactsFrozen':len(frozen),'oldNss128RuntimeRetainedExactSha256':sha(old)}
qualification={'actualEntryRound':138,'actualBindingInputs':1340,'entryChecks':qual['checks'],'newSuccessOnlyTargetRamChecks':11,'earlierCompleteReclassificationTargetRamChecks':12,'earlierModelsInheritedByteExactNotReexecuted':True,'modelInputsAreMocked':True,'guardianMaxExecBytes':9000,'guardedQosMaxBytes':73728,'wholeStageRecordReadMaximumBytes':1048576,'sourceMaximumAgeSeconds':6,'nativeSessionSeconds':27,'independentOwnerMaximumSeconds':100,'clientMaximumSeconds':180,'actualStages':owner,'firstIncorrectReplayPlanShapeFailurePreserved':True}
evidence={'mainline':summary,'class-lifecycle':life,'owner-completion':owner,'first-retirement':load(r/'first-retirement.json'),'failed-class-change':load(r/'failed-class-change.json'),'staging-recovery':load(r/'staging-recovery.json'),'classifier-recovery':load(r/'classifier-recovery.json'),'failures':failures,'endpoint-closure':closures,'receiver-closure':receiver,'local-audit-invocation-failures':load(r/'local-audit-invocation-failures.json'),'qualification':qualification,'final-audit':final,'physical-final':physical,'source-proof':source}
for k,v in evidence.items():dump(repo/f'evidence/nss139-{k}.json',v)
runtime={'round':'NSS139','checkedAt':final['observedAt'],'deploymentReference':'work/nss68/deployment-latest.json','classifierConfigSha256':final['configSha256'],'workerPid':31657,'guardianPid':17139,'nssPermanentlyEnabled':False,'residentClassifierChangedThisTurn':False,'qualifiedExperimentalEntry':'work/nss138/controlled-session.mjs','qualifiedExperimentalEntryBoundInputs':1340,'currentNssAdmissionMustBeRefreshedBeforeWrite':True,'audit':final,'physicalRootRestoreAudit':physical,'physicalClassChangeRetirementAccepted':True,'freshEpochRelearningSameCtAccepted':True,'realHumanGameAcceptance':False,'newCpuComparisonAcceptedThisTurn':False,'historical128RuntimePreservedSha256':sha(old),'nightContinuationUntilBeijing':'2026-10-06T10:00:00+08:00'};dump(repo/'evidence/current-runtime.json',runtime)
when=datetime.fromisoformat(final['observedAt'].replace('Z','+00:00')).astimezone(timezone(timedelta(hours=8))).strftime('%Y-%m-%d %H:%M')
text=f'''更新：{when}，北京时间。最新NSS139整理、实际138；常驻NSS68/config581b5d46…c791d7，worker自然恢复为31657、guardian17139未变。全部实验已撤销。

**真实同一TCP/UDP完成了自动改类、精确撤销和新代重学：TCP上传暂停后，同源完整分类帧判定BULK→BE/cooldown；比较器仅报告TCP受影响，ECM2→1，UDP保留原CI及双向RT tag；旧代结束为0。恢复应用发送后，同一CT/mark/NAT/WAN用新的分类、内核pin、独立checkpoint/owner重学，新ECM编号得到2→0。**

见 [完整生命周期](../evidence/nss139-class-lifecycle.json)、[汇总](../evidence/nss139-mainline.json)、[成功守护结束](../evidence/nss139-owner-completion.json)、[失败记录](../evidence/nss139-failures.json)、[分类器恢复](../evidence/nss139-classifier-recovery.json)、[端点关闭](../evidence/nss139-endpoint-closure.json)、[原完整终态](../evidence/nss139-final-audit.json)。

- 实际单WAN2、一TCP BULK＋一UDP RT；完整分类query1031/0.18秒，明确TCP仍有相同CT/zone/mark/original/reply/WAN且为BE，UDP仍获准RT。仅投影缺失不能证明改类或CT退出。CPU同步barrier不是firmware销毁ACK；另验实际目标CI缺失、ECM仅剩原UDP、pending全0，剩余旧分类lease约2.29秒后结束旧代，不强续terminal gate、不在旧CI存在时改tag。
- 两次新checkpoint下载/SHA/gzip与独立守护写前核验、两份1340项实际输入当前及冻结副本逐字节匹配；两次原完整前后审核/精确恢复通过。来源6秒/native27秒/owner最大100秒/client180秒、9000/65536/73728字节和1MiB读上限保持。成功只在模块、tag、两物理根、WAN/mwan3/state全部恢复且ECM关闭零计数后，留5秒记录宽限再退出独立owner；失败仍保留原100秒到期路径。没有发送取消信号或提前放弃失败回滚。
- NSS135已有同样真实精确TCP撤销，但第二代因客户端期限不足未开始，原overall失败保留。NSS131连接helper并发修改进程cwd、NSS133 Lua多返回值误作tonumber进制、NSS137预检误带执行后报告字段等失败分别定位并修复；132回包不足与136预算拒绝未stage。完整失败及本地调用错误不改成成功。11项新的目标RAM成功结束边界与原12项完整分类模型分开；旧模型源码相同继承，未反复重跑。
- 常驻worker4859在129负载中自然apply失败（status256、0.35秒），procd恢复31657，guardian17139与源/config不变。实际child PID/stderr缺失，旧orphan batch与PID重用只是未证实线索；没有为此主动重装/重启常驻分类器。新实例实际通过原完整身份审核，不能继续把4859当现网PID。
- 本轮只验功能生命周期，没有新增CPU对照、300Mbps、Steam主下载或真人CS2指标。128此前约30Mbps上传可比短窗的softirq相对低48.64%保持为历史证据，不能扩大成长期/游戏收益。最终source{final['queryAge']:.2f}、selectors0、ECM关闭全零，无事务/stage/state/实验模块，两物理原mq＋四fq_codel恢复；七个有限负载、临时规则/端口/客户端已关闭，自有SSH接收器0残留。WAN4仍认证down，既有四路failover保持。
- 下一步把已经证明的撤销/重学规则并入最后集中真人短测入口；先做必要离线绑定/拒绝路径检查。睡眠期间不操作桌面、Steam/CS2或新下载，不扩WAN/共享预算/WiFi/autorate/ECN，不重复CPU阈值试验。09:50不新生产试验，10点前完成晨间终态/发布并暂停本夜heartbeat。
'''
for name,title in [('STATE.md','# 当前状态'),('PLAN.md','# 下一步：最后集中真人入口')]:
 p=repo/'docs'/name;p.write_text(title+'\n\n'+text+'\n## NSS128历史\n\n'+p.read_text(encoding='utf-8'),encoding='utf-8')
p=repo/'docs/EXPERIMENT_LOG.md';head,tail=p.read_text(encoding='utf-8').split('\n',1);p.write_text(head+'\n\n## NSS129–139 · '+when+' · 真实改类精确撤销及新代重学\n\n'+text+tail,encoding='utf-8')
p=repo/'AGENTS.md';head,tail=p.read_text(encoding='utf-8').split('\n',1);p.write_text(head+'\n\n最新NSS139：实际138/1340项，单WAN2完整真实BULK→BE同query/同CT，比较器只TCP，ECM2→1/原UDP RT CI保持，再旧代0；恢复同socket后新分类/kernel pin/checkpoint/owner与不同CI重学2→0。两完整审核/两根/端点恢复，success-only完整恢复后5秒记录宽限，失败仍100秒，6/27/100/180及字节上限不变。135仅第一撤销过、第二期限拒绝；129/131/132/133/136/137原失败和原因分开冻结。129常驻4859自然apply256/0.35秒退出，procd31657/guardian17139、68/config/upTag0不变；orphan batch只是未证实假设，不改classifier。终态source'+f"{final['queryAge']:.2f}"+'、selectors0、ECM关闭全零，无事务/stage/state/模块，两物理原根/7负载/SSH receiver已恢复，WAN4仍down四路failover不动。旧128 runtime原字节保存，本轮无CPU/300Mbps/真人验收。下一步仅把实测撤销/重学并入最后真人入口，先离线；睡眠不UI/新下载/扩WAN/CPU重复。09:50收尾10点前暂停本夜；STATE为准。\n\n'+tail,encoding='utf-8')
p=repo/'docs/ARTIFACT_INDEX.md';p.write_text('# 当前NSS139\n\n[真实改类与重学](../evidence/nss139-class-lifecycle.json) · [失败](../evidence/nss139-failures.json) · [常驻实例恢复](../evidence/nss139-classifier-recovery.json) · [终态](../evidence/nss139-final-audit.json) · [历史128 runtime](../evidence/nss128-runtime.json)。\n\n'+p.read_text(encoding='utf-8'),encoding='utf-8')
report=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSS139 改类精确撤销与重学</title><style>body{{background:#f4f4ee;color:#24352d;font:16px/1.8 "Microsoft YaHei",sans-serif}}main{{max-width:1000px;margin:auto;padding:28px 24px}}section{{background:white;padding:22px;border:1px solid #ddd;border-radius:10px;margin:22px 0}}table{{width:100%;border-collapse:collapse}}th,td{{text-align:left;padding:9px;border-bottom:1px solid #ddd}}</style><main><small>ATHENA · {when} 北京时间</small><h1>真实改类、精确撤销、新代重学已通过</h1><p>同一TCP/UDP、单WAN2；仅暂停并恢复自有TCP上传，没有改PBR、NAT或出口。</p><section><table><tr><th>步骤</th><th>实际观测</th></tr><tr><td>自动判定</td><td>完整同query帧：TCP BULK→BE/cooldown，UDP仍RT。</td></tr><tr><td>精确撤销</td><td>ECM2→1，目标TCP CI缺失；原UDP CI和双向RT tag保留。</td></tr><tr><td>结束旧代</td><td>ECM→0，模块/tag/两根/WAN/state完整恢复。</td></tr><tr><td>新代重学</td><td>同socket/CT/mark/NAT/WAN，新分类与第二独立checkpoint，新kernel pin及不同ECM CI，2→0。</td></tr></table><p>每代1340项绑定，来源6秒/native27秒/独立owner最大100秒；成功恢复后保留5秒记录宽限，失败到期路径不改。CPU barrier另由实际CI缺失核验，未当firmware ACK。</p></section><section><h2>保留的失败与边界</h2><p>135第一撤销已过，但第二代期限拒绝；131并发cwd、133 Lua多返回值、137预检多带报告字段已定位。原失败均保存。本輪没有新增CPU或真人指标；此前128的48.64% softirq相对降幅只限约30Mbps上传短窗，不能称300Mbps或CS2收益。</p><p>4859在129自然apply失败后由procd恢复31657，guardian17139与68配置保持。具体子进程根因未证实，未重装常驻分类器。</p></section><section><h2>终态与下一步</h2><p>source{final['queryAge']:.2f}、ECM关闭全零、selectors0、无实验残留；两物理原队列、7有限负载及端点已恢复，SSH receiver0。WAN4仍down、四路PBR保持。</p><p>接下来只把实测规则整合到最后集中真人短测入口，离线准备后等待一次真实CS2验收；睡眠期间无桌面/游戏下载，不扩WAN。09:50收尾，10点前暂停本夜接续。</p><a href="https://github.com/ZyPulse-zy/athena-nss-mainline/blob/main/docs/STATE.md">仓库当前状态</a><p><small>源码核验，未作浏览器渲染验收。</small></p></section></main></html>'''
out=w/'outputs/nss139-mainline-report.html';assert not out.exists();out.write_text(report,encoding='utf-8')
dump(r/'export-receipt.json',{'passed':True,'newSources':len(hashes),'totalSources':len(manifest['sources']),'privateArtifacts':len(frozen),'finiteLoadsClosed':7,'actualClassChangeAndFreshGenerationPassed':True});print(json.dumps({'exported':True,'sources':len(hashes),'totalSources':len(manifest['sources']),'privateArtifacts':len(frozen)}))
