"""Publish actual class-derived dual leaf mapping and scoped comparable CPU evidence."""
from pathlib import Path
from datetime import datetime,timezone,timedelta
import json,hashlib,shutil,subprocess,importlib.util
w=Path(__file__).resolve().parents[2];repo=w/'athena-nss-mainline';r=w/'work/nss128'
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def sha(b):return hashlib.sha256(b).hexdigest()
def dump(p,o):p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
spec=importlib.util.spec_from_file_location('collector',w/'work/nss101/collect-lifecycle.py');c=importlib.util.module_from_spec(spec);spec.loader.exec_module(c)
case=r/'controlled-matched-aba-20261005205520-95105879';t=c.stage(case.relative_to(w).as_posix());m=t['metrics'];comparison=load(case/'same-load-comparison.json');mapping=load(case/'actual-class-mapping-proof.json');up=load(case/'actual-upstream-proof.json');final=load(r/'v1-final-health.json');physical=load(r/'physical-final.json');qual=load(r/'entry-qualified.json');model=load(w/'work/nss127/mapping-qualified.json');closure=c.closure(load(r/'load-reference-private.json')['dir'])
assert t['passed']and t['completeABA']and t['sourceInputs']==1069 and all(t['rollback'].values())and comparison['comparabilityAccepted']and all(comparison['checks'].values())
assert mapping['passed']and mapping['mappingUsesActualClassNotProtocol']and mapping['mappedPlanCreatedBeforeFrontendOpened']and qual['onlyMappingSourceChanged']and len(model['checks'])==14
assert final['passed']and physical['passed']and final['ecmStoppedAndZero']and all(x['whole']['udp']['unreturned']==0 for x in m['phases'])
old=(repo/'evidence/current-runtime.json').read_bytes();assert load(repo/'evidence/current-runtime.json')['round']=='NSS126'and subprocess.check_output(['git','show','HEAD:evidence/current-runtime.json'],cwd=repo)==old
archive=repo/'evidence/nss126-runtime.json';assert not archive.exists();archive.write_bytes(old)
manifest=load(repo/'source-manifest.json');assert len(manifest['sources'])==1533;prefix=sha(json.dumps(manifest['sources'],sort_keys=True,separators=(',',':')).encode())
allowed={127:['class-leaf-map.mjs','uplink-tag-plan.mjs','qualify.mjs'],128:['prepare.py','bounded-pacer.mjs','upload-ack.mjs','upload-server.py','ssh-client.mjs','session-binding.mjs','qualify.mjs','controlled-session.mjs','current-audit-diagnostic.mjs','match-controlled.mjs','read-controlled.mjs','run.mjs','module-stage.mjs','payload.mjs','pack-lua.mjs','pack-guardian.mjs','compact-default-queues.mjs','uplink-tag-plan.mjs','parse-ecm-any-wan.mjs','fast-path.lua','module-stage-guardian.lua','qos-physical.lua','tag-normalizer.lua','failed-wan-owner.lua','declared-baseline.mjs','service-epoch.mjs','analyze-long.py','calibrate-clock.mjs','prove-upstream.py','health.mjs','read-final-physical.mjs','compare-load.py','prove-class-mapping.py','save-evidence.py']}
hashes={}
for n,names in allowed.items():
 for name in names:
  src=w/f'work/nss{n}'/name;assert src.is_file();rel=src.relative_to(w).as_posix();dst=repo/'code'/rel;assert not dst.exists();dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst);digest=sha(src.read_bytes());hashes[rel]=digest;manifest['sources'].append({'path':'code/'+rel,'workspaceSource':rel,'sha256':digest,'bytes':src.stat().st_size,'role':'actual-class-derived-dual-leaf-mapping'})
manifest['generatedAt']=datetime.now(timezone.utc).isoformat();manifest['lastAppendExport']='NSS128';dump(repo/'source-manifest.json',manifest)
frozen={};freeze=r/'proof-v1/private-inputs';freeze.mkdir(parents=True,exist_ok=False)
for n in [127,128]:
 for src in sorted((w/f'work/nss{n}').rglob('*')):
  if not src.is_file()or any(p in src.parts for p in ['proof-v1','frozen','frozen-qualified-inputs','__pycache__']):continue
  rel=src.relative_to(w);dst=freeze/rel;dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst);frozen[rel.as_posix()]=sha(src.read_bytes());assert sha(dst.read_bytes())==frozen[rel.as_posix()]
dump(r/'private-input-freeze-index.json',frozen)
summary={'round':'NSS128','observedAt':final['observedAt'],'onlyMappingSourceChanged':True,'mappingByActualClass':True,'allWanBackgroundObserved':True,'oneWan':m['oneWan'],'boundInputs':1069,'offeredUploadMbps':32,'uplinkGroupMbps':60,'downlinkGroupMbps':30,'phaseSeconds':20,'nativeSessionSeconds':27,'independentOwnerSeconds':100,'classifierMaximumLeaseSeconds':6,'completeFunctionalABA':True,'sameHardwareBundleForSameActualClassAndTuples':True,'mappedBeforeEcmLearning':True,'productionPairRestrictedToTcpBulkUdpRt':True,'genericTcpRtUdpBulkModelsOnly':True,'physicalClassChangeRetirementAccepted':False,'scopedShortCpuComparisonAccepted':True,'scopedSoftirqRelativeReductionPercent':comparison['softirqRelativeReductionPercent'],'rtAllProbeRepliesReceived':True,'rtLeafDrop':0,'bulkLeafDrop':0,'humanCs2Acceptance':False,'highLoad300MbpsAcceptance':False,'fullCakeReplacementAccepted':False,'preciseRateAccuracyAccepted':False,'residentClassifierChanged':False,'residentUpTagZeroUnchanged':True,'nssPermanentlyEnabled':False,'uiOperated':False,'upstreamSubmitted':False,'temporaryEndpointsClosed':1,'reportVerification':{'sourceValidated':True,'browserRendered':False}}
source={'round':'NSS128','historicPrefixSources':1533,'historicPrefixCanonicalSha256':prefix,'sources':len(hashes),'sourceHashes':hashes,'privateOwnedHostBootstrapExcluded':True,'actualBindingTreesRetained':True,'privateArtifactsFrozen':len(frozen)}
qualification={'classMapping':model['checks'],'entry':qual['checks'],'originalNativeBundleEquivalent':qual['sameGuardedHardwareBundleForSameActualClassAndTuples'],'payloadBytes':qual['payloadBytes'],'genericCrossProtocolModelsNotHardwareProof':True}
for key,value in {'mainline':summary,'trial':t,'metrics':m,'comparison':comparison,'actual-class-mapping':mapping,'uplink-proof':up,'qualification':qualification,'endpoint-closure':closure,'final-audit':final,'physical-final':physical,'source-proof':source}.items():dump(repo/f'evidence/nss128-{key}.json',value)
runtime={'round':'NSS128','checkedAt':physical['observedAt'],'deploymentReference':'work/nss68/deployment-latest.json','classifierConfigSha256':final['configSha256'],'workerPid':final['workerPid'],'guardianPid':final['guardianPid'],'nssPermanentlyEnabled':False,'residentClassifierChangedThisTurn':False,'qualifiedExperimentalEntry':'work/nss128/controlled-session.mjs','qualifiedExperimentalEntryBoundInputs':1069,'currentNssAdmissionMustBeRefreshedBeforeWrite':True,'audit':final,'physicalRootRestoreAudit':physical,'actualClassDerivedMappingHardwarePassed':True,'realHumanGameAcceptance':False,'scopedShortCpuComparisonAccepted':True,'scopedSoftirqRelativeReductionPercent':comparison['softirqRelativeReductionPercent'],'physicalClassChangeRetirementAccepted':False,'historical126RuntimePreservedSha256':sha(old),'nightContinuationUntilBeijing':'2026-10-06T10:00:00+08:00'};dump(repo/'evidence/current-runtime.json',runtime)
when=datetime.fromisoformat(final['observedAt'].replace('Z','+00:00')).astimezone(timezone(timedelta(hours=8))).strftime('%Y-%m-%d %H:%M');speeds='/'.join(f"{p['whole']['clientTcpMbps']:.3f}"for p in m['phases']);softs='/'.join(f"{p['whole']['softirqPercent']:.3f}"for p in m['phases']);udp='、'.join(f"{p['whole']['udp']['received']}/{p['whole']['udp']['sent']}"for p in m['phases']);bg='/'.join(f'{x:.3f}'for x in comparison['unselectedWanTotalRxPlusTxMbps'])
text=f'''更新：{when}，北京时间。最新NSS128；常驻68/config581b5d46…c791d7、4859/17139保持，实验已撤销。

**消费者上行tag已直接按实际class生成，绑定同源完整CT/mark/NAT/lease。真实WAN1、一TCP BULK＋一UDP RT，学习前映射及实际NSS四tag/四leaf正确，20秒A/B/A2、ECM0→2→0、六续租/精确恢复通过。上传{speeds}Mbps，softirq {softs}%，软件段均值10.21→NSS5.25，短窗可比条件下相对低{comparison['softirqRelativeReductionPercent']:.2f}%。**

见 [实际映射](../evidence/nss128-actual-class-mapping.json)、[指标](../evidence/nss128-metrics.json)、[可比分析](../evidence/nss128-comparison.json)、[轮次](../evidence/nss128-trial.json)、[汇总](../evidence/nss128-mainline.json)、[关闭](../evidence/nss128-endpoint-closure.json)、[终态](../evidence/nss128-final-audit.json)。

- 用实际分类结果和源sequence/完整身份决定上8e05/06、下8f05/06；未知类、未获准RT、mark/NAT/实例/来源/lease变化均拒绝，保留原detached重新分类、kernel pin和默认deny。学习前映射与NSS实际双向tag逐一一致。常驻publication upTag0不改，未为字段重装classifier。
- 127有1个真实历史完整帧回放＋13模型反例/跨协议例，14项通过；TCP RT/UDP BULK只证明mapper按class选值，生产入口仍仅TCP BULK＋UDP RT，不能声称其它组合硬件已验收。128原native/gate/队列/发送器逐字节相同；同实际pair/tuples构成的完整bundle与125一致，3项入口检查/1069绑定，实际checkpoint与控制连接外100秒撤销写前核验。
- 本轮为映射验证并顺带保存同观察器CPU指标，未额外重复CPU探针追126背景门槛。其它WAN总RX＋TX {bg}Mbps，原七项可比合同全部通过；每段20秒、选中吞吐/physicalwan发送与UDP发送率接近。softirq相对低48.64%只限约30Mbps受控上传短窗，非随机/长期/300Mbps、拥塞AQM或真人结果，包速差异保留。
- UDP收/发{udp}、四leaf drop0、squeeze/softnet drop0，端点RTT非CS2 jitter/loss/Miss。下行是TCP ACK与小UDP，未覆盖Steam主下载方向的这套新双向版本。现阶段可确认映射与收益信号；改类的真实精确撤销/新epoch重学尚需独立窄测试。
- 原完整终态source{final['queryAge']:.2f}、ECM关闭全零、无事务/stage/state/模块；两物理mq＋四fq_codel恢复，1临时端点与客户端全关闭，WAN4仍down、自然四路PBR不改。旧126 runtime原字节保留，原始完整输入私有冻结；没有UI、游戏/新下载、账户/认证或上游操作。
- 下一步仅真实class变化的精确撤销/重学：先查原模块slot close/drain与全局续租约束、完整同源分类读取能力，再在一个自有TCP＋UDP上暂停TCP上传诱发BULK→BE，比较器应只报告TCP受影响。关闭新学习、只撤销目标CI并核验其缺失/剩余UDP短窗，再结束旧epoch；新分类与新kernel pin后才重学。原6/27/100与独立恢复保持。若只有投影缺失，不能代替实际改类/CT退出证明。不得为了剩余UDP强续已terminal gate或在旧CI未退时改tag。
- 后续仍只这条自动分类→NSS leaf主线，最后集中真人一次；不扩WAN/共享预算/WiFi/autorate、不重装/新下载/UI。09:50起不新实验，整理晨间终态与报告、推送后暂停本夜接续。
'''
for name,title in [('STATE.md','# 当前状态'),('PLAN.md','# 下一步：单WAN改类精确撤销与重学')]:
 p=repo/'docs'/name;p.write_text(title+'\n\n'+text+'\n## NSS126历史\n\n'+p.read_text(encoding='utf-8'),encoding='utf-8')
p=repo/'docs/EXPERIMENT_LOG.md';head,tail=p.read_text(encoding='utf-8').split('\n',1);p.write_text(head+'\n\n## NSS127–128 · '+when+' · 实际class直接映射双向leaf\n\n'+text+tail,encoding='utf-8')
p=repo/'AGENTS.md';head,tail=p.read_text(encoding='utf-8').split('\n',1);p.write_text(head+'\n\n最新NSS128：消费者双向tag按实际class/同源完整CT mark NAT lease派生，未知与未准入RT拒绝；生产仍TCP BULK＋UDP RT。127一真实历史帧＋13模型共14过，TCPRT/UDPBULK仅模型；128三入口检查/1069项、同tuple完整native bundle不变。实际WAN1完整20秒A/B/A2、ECM0/2/0、四tag/四leaf/mark/NAT/affinity/6续租/精确恢复过，上传'+speeds+'，softirq'+softs+'%，可比7条件全过，短窗相对低48.64%（非300/长期/真人）；UDP'+udp+'、四leafdrop0/squeeze0。原完整终态source2.87/4859/17139/68upTag0不变、ECM全零无残留、两根恢复、端点关闭，WAN4仍down。下一步只真实改类精确撤销/新epoch重学：先审slot close/drain/全局续租和同源完整分类，受控TCP暂停诱发BULK→BE；投影缺失不当改类/CT退出，旧CI未退不改tag/terminal不能强续。6/27/100/checkpoint/独立撤销不改；不再追CPU阈值、不扩WAN/共享预算/WiFi/autorate/新下载/UI。09:50收尾10点前暂停本夜；STATE为准。\n\n'+tail,encoding='utf-8')
p=repo/'docs/ARTIFACT_INDEX.md';p.write_text('# 当前NSS128\n\n[实际class映射](../evidence/nss128-actual-class-mapping.json) · [指标](../evidence/nss128-metrics.json) · [CPU分析](../evidence/nss128-comparison.json) · [汇总](../evidence/nss128-mainline.json) · [终态](../evidence/nss128-final-audit.json) · [历史126 runtime](../evidence/nss126-runtime.json)。\n\n'+p.read_text(encoding='utf-8'),encoding='utf-8')
rows=''.join(f'<tr><td>{x["phase"]}</td><td>{x["whole"]["clientTcpMbps"]:.3f}</td><td>{x["whole"]["softirqPercent"]:.3f}%</td><td>{x["whole"]["timeSqueezeDelta"]}</td><td>{x["whole"]["udp"]["received"]}/{x["whole"]["udp"]["sent"]}</td></tr>'for x in m['phases'])
report=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSS128 实际分类到双向leaf</title><style>body{{background:#f4f4ee;color:#24352d;font:16px/1.8 "Microsoft YaHei",sans-serif}}main{{max-width:1000px;margin:auto;padding:28px 24px}}section{{background:white;padding:22px;border:1px solid #ddd;border-radius:10px;margin:22px 0}}table{{width:100%;border-collapse:collapse}}th,td{{text-align:left;padding:9px;border-bottom:1px solid #ddd}}</style><main><small>ATHENA · {when} 北京时间</small><h1>自动class已直接映射NSS双向leaf</h1><p>实际单WAN1、TCP BULK＋UDP RT；学习前映射与NSS中四tag/四leaf一致，mark/NAT/affinity正确。完整software→NSS→software已恢复原状态。</p><section><table><tr><th>阶段</th><th>确认上传Mbps</th><th>softirq</th><th>squeeze</th><th>UDP收/发</th></tr>{rows}</table><p>原可比合同七项全过；软件softirq平均10.21%，NSS5.25%，短窗相对低48.64%。其它WAN背景{bg}Mbps，四leaf零drop、probe全回包。这是约30Mbps上传工程证据，非300Mbps、长期或真人CS2。TCP包速差异保留，下行主要ACK和小UDP。</p></section><section><h2>自动映射如何验证</h2><p>按实际class而非协议猜测tag，绑定同源sequence/完整CT/mark/NAT/lease；未知或未准入RT拒绝。14项历史回放和模型、3入口检查、1069绑定后实际现场通过。同tuple硬件bundle字节不变，原detached/kernel pin与6/27/100期限保持。TCP RT/UDP BULK只在模型中验证，生产仍严格bulk TCP＋RT UDP。常驻68/upTag0未变。</p></section><section><h2>下一步和终态</h2><p>只补真实改类的精确撤销/新epoch重学：受控暂停TCP上传，先确认完整同源BULK→BE，原模块只撤销受影响CI、核验UDP短窗后结束旧epoch，再新pin重学。投影缺失不当改类或CT退出，旧CI未退不改tag。不操作UI或新下载，不扩WAN。</p><p>终态source2.87、ECM关闭全零、无实验残留、两物理原队列恢复、临时端点关闭；WAN4仍down、四路PBR保持。09:50起收尾，10点前暂停本夜接续。</p><a href="https://github.com/ZyPulse-zy/athena-nss-mainline/blob/main/docs/STATE.md">仓库当前状态</a><p><small>源码核验，未作浏览器渲染验收。</small></p></section></main></html>'''
out=w/'outputs/nss128-mainline-report.html';assert not out.exists();out.write_text(report,encoding='utf-8')
dump(r/'export-receipt.json',{'passed':True,'newSources':len(hashes),'totalSources':len(manifest['sources']),'privateArtifacts':len(frozen),'temporaryEndpointsClosed':1,'scopedSoftirqRelativeReductionPercent':comparison['softirqRelativeReductionPercent']});print(json.dumps({'exported':True,'sources':len(hashes),'totalSources':len(manifest['sources']),'scopedSoftirqRelativeReductionPercent':comparison['softirqRelativeReductionPercent']}))
