"""Preserve v21; only batch Windows process/socket inventory for faster natural matching."""
from pathlib import Path
import shutil
w=Path(__file__).resolve().parents[1];old=w/'work/v21-fiveflow';r=w/'work/v22-fiveflow';r.mkdir()
for p in old.iterdir():
 if p.is_file() and p.suffix in ['.mjs','.lua','.py','.ps1'] and not any(x in p.name for x in ['private','failed','qualify','model-five','prepare-runtime','prepare-fixture','strip-runtime','finalize-five-candidate','diagnose-control','fix-model-port']):
  s=p.read_text().replace('work/v21-fiveflow','work/v22-fiveflow')
  if p.name=='session-binding.mjs':s=s.replace("../v20-five/session-binding.mjs","../v21-fiveflow/session-binding.mjs")
  if p.name=='module-stage.mjs':
   s=s.replace('work/v22-fiveflow/endpoint-gate','work/v21-fiveflow/endpoint-gate').replace('work/v22-fiveflow/runtime-elf-comparison.json','work/v21-fiveflow/runtime-elf-comparison.json').replace('work/v22-fiveflow/native-source-qualified.json','work/v21-fiveflow/native-source-qualified.json')
  (r/p.name).write_text(s,encoding='utf8')
for name in ['native-qualified.json','normalizer-qualified.json','qos-native-qualified.json']:
 shutil.copy2(old/name,r/name)
p=r/'read-controlled.mjs';s=p.read_text();a=s.index('const ps=`');b=s.index('\nconst pcRaw=',a)
ps=r'''const ps=`$ErrorActionPreference='Stop';$b=Get-Content -LiteralPath '${binding.configPath.replaceAll("'","''").replace(/client-config-private.json$/,'client-binding-private.json')}' -Raw|ConvertFrom-Json;$p=Get-Process -Id $b.clientPid -ErrorAction Stop;if($p.StartTime.ToUniversalTime().Ticks -ne [datetime]::Parse($b.clientStart).ToUniversalTime().Ticks -or $p.Path -ne $b.clientExe){throw 'Controlled client instance changed'};$s=Get-Content -LiteralPath '${binding.configPath.replaceAll("'","''").replace(/client-config-private.json$/,'status-private.json')}' -Raw|ConvertFrom-Json;if(@($s.tcpChildren).Count -ne 4){throw 'Four owned SSH children required'};$ids=@([int]$p.Id)+@($s.tcpChildren|ForEach-Object{[int]$_.ownerPid});if(@($ids|Select-Object -Unique).Count -ne 5){throw 'Duplicate process instance'};$filter=($ids|ForEach-Object{'ProcessId='+$_}) -join ' OR ';$all=@(Get-CimInstance Win32_Process -Filter $filter);if($all.Count -ne 5){throw 'Owned process disappeared'};$map=@{};foreach($v in $all){if($map.ContainsKey([int]$v.ProcessId)){throw 'Duplicate process row'};$map[[int]$v.ProcessId]=$v};$cmd=$map[[int]$p.Id].CommandLine;if(-not $cmd.Contains($b.scriptPath)-or -not $cmd.Contains($b.configPath)){throw 'Controlled client arguments changed'};$tcp=@(Get-NetTCPConnection -State Established -ErrorAction SilentlyContinue|Where-Object{$ids -contains [int]$_.OwningProcess});$rows=@();foreach($v in $s.tcpChildren){$k=$map[[int]$v.ownerPid];if($k.ParentProcessId -ne $p.Id -or $k.ExecutablePath -ne $v.executable -or -not $k.CommandLine.Contains('sub2api-dallas') -or -not $k.CommandLine.Contains('python3 -u -c') -or [math]::Abs(([datetime]$k.CreationDate).ToUniversalTime().Subtract([datetime]::Parse($v.spawnedAt).ToUniversalTime()).TotalSeconds) -gt 3){throw 'Owned SSH child identity changed'};foreach($e in @($tcp|Where-Object{$_.OwningProcess -eq [int]$v.ownerPid})){$rows+=@{LocalAddress=$e.LocalAddress;LocalPort=$e.LocalPort;RemoteAddress=$e.RemoteAddress;RemotePort=$e.RemotePort;slot=$v.slot}}};@{pid=$p.Id;tcp=@($rows);udp=@(Get-NetUDPEndpoint -OwningProcess $p.Id -ErrorAction SilentlyContinue|Select-Object LocalAddress,LocalPort)}|ConvertTo-Json -Depth 5 -Compress`;'''
p.write_text(s[:a]+ps+s[b:],encoding='utf8')
print('v22 batched exact process and socket inventory; five gate, QoS and all deadlines unchanged')
