import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{packetTemplate}from'./uplink-tag-plan.mjs';import{buildPayload}from'./payload.mjs';import{connectRouter}from'../nss27/connect-router.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';
const root='work/nss114',h=b=>crypto.createHash('sha256').update(b).digest('hex'),p='work/nss111/controlled-matched-aba-20261005180738-532c1641';
const selected=JSON.parse(fs.readFileSync(p+'/selected-private.json')),native=JSON.parse(fs.readFileSync(p+'/last-record-private.json')).initialTags;
const owner=native.nftables.find(x=>x.table).table.comment;assert.match(owner,/^[a-f0-9]{32}$/);const t=packetTemplate({decisions:[{slot:'tcp',protocol:6,downTag:0x8f050000,flow:selected.tcp,validUntilUptime:1},{slot:'udp',protocol:17,downTag:0x8f060000,flow:selected.udp,validUntilUptime:1}]},owner,59999);t.expected.nftables=t.expected.nftables.filter(x=>x.chain?.name!=='forward'&&x.rule?.chain!=='forward');
for(const x of native.nftables){const r=x.rule;if(!r||!r.comment.slice(owner.length+1).includes('_up'))continue;const tag=r.comment.slice(owner.length+1).startsWith('tcp_')?'8e05:0':'8e06:0';for(const e of r.expr){if(e.mangle?.key.meta?.key==='priority')e.mangle.value=tag;if(e.match?.left.meta?.key==='priority')e.match.right=tag;}}
const normalizer=fs.readFileSync(root+'/tag-normalizer.lua','utf8'),libs={qos:fs.readFileSync(root+'/qos-physical.lua','utf8'),phase:fs.readFileSync('work/nss69/core-guard-phase.lua','utf8'),classifier:fs.readFileSync('work/nss73/classifier.lua','utf8'),tags:fs.readFileSync('work/nss49/classified-tags.lua','utf8'),normalizer};
const plan={table:t.expected.nftables[0].table.name,owner,mode:'rt',expected:t.expected},built=buildPayload({tagPlan:plan},libs),nativePacked=buildPayload({tagPlan:{...plan,expected:native}},libs).tagSource;
assert.ok(Buffer.byteLength(built.stagedCode)<=73728);if(fs.existsSync(root+'/normalizer-fixture-private.json'))assert.deepEqual(JSON.parse(fs.readFileSync(root+'/normalizer-fixture-private.json')),{plan,native});else fs.writeFileSync(root+'/normalizer-fixture-private.json',JSON.stringify({plan,native},null,2)+'\n',{flag:'wx'});
const body='local normalize=assert(loadstring([====['+normalizer+']====]))();local PLAN=(function()'+built.tagSource+'\nend)();local NATIVE=(function()'+nativePacked+'\nend)().expected;\n'+fs.readFileSync(root+'/qualify-normalizer.lua','utf8');
const c=await connectRouter();let q;try{const e=encode("lua - <<'NSS114_NORMALIZER_RAM'\n"+body+"\nNSS114_NORMALIZER_RAM\n"),r=receipt(await c.run(e.command),e);fs.writeFileSync(root+'/normalizer-qualification-raw-private.json',JSON.stringify(r,null,2)+'\n',{flag:'wx'});assert.equal(r.code,0,r.stderr);q=JSON.parse(r.stdout);assert.ok(q.passed&&q.checks.length>=25);fs.writeFileSync(root+'/normalizer-qualification.json',JSON.stringify({...q,sourceSha256:h(normalizer)},null,2)+'\n',{flag:'wx'});}finally{c.close()}
for(const name of fs.readdirSync(root).filter(x=>x.endsWith('.mjs'))){const v=spawnSync(process.execPath,['--check',root+'/'+name],{windowsHide:true,encoding:'utf8'});assert.equal(v.status,0,v.stderr);}
const sources={};for(const name of fs.readdirSync(root))if(/\.(mjs|py|lua|ps1)$/.test(name))sources[root+'/'+name]=h(fs.readFileSync(root+'/'+name));
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify({passed:true,productionExecution:false,onlyControlledDirectionalTagNormalizerChanged:true,normalizerSourceSha256:h(normalizer),payloadBytes:Buffer.byteLength(built.stagedCode),maximumStagedBytes:73728,checks:q.checks,sourceManifest:sources},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,targetRamChecks:q.checks.length,payloadBytes:Buffer.byteLength(built.stagedCode),sources:Object.keys(sources).length,uplinkTagsSimulated:true}));
