import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{verifyPreparation}from'../nss124/session-binding.mjs';import{connectRouter}from'../nss27/connect-router.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';import{packLua}from'./pack-lua.mjs';import{buildPayload}from'./payload.mjs';import{packetTemplate}from'./uplink-tag-plan.mjs';
const root='work/nss125',h=b=>crypto.createHash('sha256').update(b).digest('hex'),old=verifyPreparation(),checks=[],names=['rpwan1','rpwan2','rpwan3','rpwan4','rpwan5','wan','lan4'];
for(const f of ['module-stage-guardian.lua','qos-physical.lua','tag-normalizer.lua','uplink-tag-plan.mjs','parse-ecm-any-wan.mjs','ssh-client.mjs','bounded-pacer.mjs'])assert.equal(h(fs.readFileSync(root+'/'+f)),h(fs.readFileSync('work/nss124/'+f)));
const source=fs.readFileSync(root+'/fast-path.lua','utf8');assert.equal(source.replace("{'rpwan1','rpwan2','rpwan3','rpwan4','rpwan5','wan','lan4'}","{'rpwan'..assert(P.selected.tcp.wan),'lan4'}"),fs.readFileSync('work/nss124/fast-path.lua','utf8'));checks.push({name:'only-common-readonly-interface-list-changed',passed:true,localOnly:true});
const code="local j=require('luci.jsonc');assert(loadstring([====["+packLua(source)+"]====]));local out={};for _,d in ipairs({'rpwan1','rpwan2','rpwan3','rpwan4','rpwan5','wan','lan4'})do out[d]={};for _,k in ipairs({'rx_bytes','rx_packets','tx_bytes','tx_packets','rx_dropped','tx_dropped'})do local f=assert(io.open('/sys/class/net/'..d..'/statistics/'..k));local s=assert(f:read('*a'));f:close();local v=assert(tonumber(s));assert(v>=0 and v%1==0 and v<=9007199254740991);out[d][k]=v end end;print(j.stringify({passed=true,interfaces=out,configurationWrites=false,hardwareQueueExecution=false}))";
const e=encode("/usr/bin/lua - <<'NSS125_OBSERVER_READONLY'\n"+code+"\nNSS125_OBSERVER_READONLY\n"),c=await connectRouter();let actual;try{const raw=receipt(await c.run(e.command),e);fs.writeFileSync(root+'/observer-readonly-private.json',JSON.stringify({...raw,execBytes:e.execBytes},null,2)+'\n',{flag:'wx'});assert.equal(raw.code,0,raw.stderr);actual=JSON.parse(raw.stdout);assert.ok(actual.passed&&Object.keys(actual.interfaces).length===7);checks.push({name:'actual-seven-interfaces-counters-readable-and-fast-syntax',passed:true,readonly:true});}finally{c.close();}
const caseDir='work/nss124/controlled-matched-aba-20261005201905-e5d4ca9a',selected=JSON.parse(fs.readFileSync(caseDir+'/selected-private.json')),owner='a'.repeat(32),template=packetTemplate({decisions:[{slot:'tcp',protocol:6,downTag:0x8f050000,flow:selected.tcp,validUntilUptime:0},{slot:'udp',protocol:17,downTag:0x8f060000,flow:selected.udp,validUntilUptime:0}]},owner,59999);template.expected.nftables=template.expected.nftables.filter(x=>x.chain?.name!=='forward'&&x.rule?.chain!=='forward');
const payload=buildPayload({tagPlan:{table:template.expected.nftables[0].table.name,owner,mode:'rt',expected:template.expected}},{qos:fs.readFileSync(root+'/qos-physical.lua','utf8'),phase:fs.readFileSync('work/nss69/core-guard-phase.lua','utf8'),classifier:fs.readFileSync('work/nss73/classifier.lua','utf8'),tags:fs.readFileSync('work/nss49/classified-tags.lua','utf8'),normalizer:fs.readFileSync(root+'/tag-normalizer.lua','utf8')});const bytes=Buffer.byteLength(payload.stagedCode);assert.ok(bytes<=73728);checks.push({name:'full-bundle-remains-within-original-73728-cap',passed:true,localOnly:true,bytes});fs.writeFileSync(root+'/observer-payload-private.lua',payload.stagedCode,{flag:'wx'});
const projected=JSON.parse(fs.readFileSync(caseDir+'/last-record-private.json'));for(const frame of projected.samples)for(const name of names)if(!frame.interfaces[name])frame.interfaces[name]=Object.fromEntries(Object.keys(actual.interfaces[name]).map(k=>[k,9007199254740991]));const projectedBytes=Buffer.byteLength(JSON.stringify(projected));assert.ok(projectedBytes<=1048576);checks.push({name:'projected-complete-counter-record-under-existing-1MiB-read-bound',passed:true,localOnly:true,bytes:projectedBytes});
for(const name of fs.readdirSync(root).filter(x=>x.endsWith('.mjs'))){const p=spawnSync(process.execPath,['--check',root+'/'+name],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}
const sourceManifest={};for(const name of fs.readdirSync(root))if(/\.(mjs|py|lua|ps1)$/.test(name)&&!name.includes('private'))sourceManifest[root+'/'+name]=h(fs.readFileSync(root+'/'+name));
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify({passed:true,productionExecution:false,onlyCommonReadOnlyInterfaceListChanged:true,queueAndLoadSourcesByteExactFrom124:true,originalFullAuditUnchanged:true,observedInterfaces:names,offeredMbps:32,uplinkMbps:60,downlinkMbps:30,phaseSeconds:20,classifierMaximumLeaseSeconds:6,nativeSessionSeconds:27,independentOwnerSeconds:100,observerCadenceSeconds:.5,sourceManifest,inheritedBoundInputs:Object.keys(old.sourceManifest).length,payloadBytes:bytes,projectedRecordBytes:projectedBytes,checks},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,checks:checks.length,sourceBindings:Object.keys(sourceManifest).length,payloadBytes:bytes,projectedRecordBytes:projectedBytes,hardwareQueueExecution:false}));
