import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';
export const read=p=>JSON.parse(fs.readFileSync(p));export const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
export function verifyCurrentClassifier(){
 const deployment=read('work/nss46/deployment-latest.json');assert.ok(deployment.committed&&deployment.permanentClassifier&&deployment.nssEnabled===false);
 const config=read(deployment.localDir+'/config.json'),oldDeployment=read('work/nss39/deployment-latest.json'),old=read(oldDeployment.localDir+'/config.json');assert.equal(hash(deployment.localDir+'/config.json'),deployment.configHash);
 const row=read('work/nss46/row-qualified.json'),expiry=read('work/nss46/combined-expiry-qualified.json'),backend=read('work/nss45/recovery-qualified.json');assert.ok(row.passed&&row.checks===48&&expiry.passed&&expiry.checks===34&&backend.passed);
 for(const name of ['worker.lua','guardian.lua','conntrack-source.lua']){assert.equal(row.sources[name],config.files[name]);assert.equal(hash(deployment.localDir+'/'+name),config.files[name]);}
 assert.equal(config.files['worker.lua'],expiry.workerSha256);assert.equal(config.files['guardian.lua'],expiry.guardianSha256);assert.equal(config.files['backend.lua'],backend.results[1].sourceSha256);assert.equal(hash(deployment.localDir+'/backend.lua'),config.files['backend.lua']);
 const faultDeployment=read('work/nss46/expiry-fault/deployment-latest.json'),fault=read(faultDeployment.localDir+'/fault-qualified.json'),undo=read(faultDeployment.localDir+'/rollback-qualified.json');assert.ok(fault.passed&&fault.realApplyChild&&fault.applyChildReaped&&fault.exactRecoveryConfirmed&&undo.passed&&undo.automaticExpiryWithoutControllerRollback);
 const rowHistory=read('work/nss45/row-trial/deployment-latest.json');assert.ok(read(rowHistory.localDir+'/rollback-qualified.json').passed);
 const normalized=structuredClone(config);for(const name of ['worker.lua','guardian.lua','conntrack-source.lua','backend.lua'])normalized.files[name]=old.files[name];normalized.installTransaction=old.installTransaction;assert.deepEqual(normalized,old,'Only independently qualified classifier reliability changes and owner binding may differ');
 for(const phase of ['backend-retain','expiry-retain','row-retain']){const d=read('work/nss46/'+phase+'/deployment-latest.json');assert.ok(d.committed&&read(d.localDir+'/permanent-commit.json').committed&&read(d.localDir+'/permanent-before-commit-audit.json').passed);}
 const configuration={base:deployment.base,configSha256:deployment.configHash,workerSha256:config.files['worker.lua'],guardianSha256:config.files['guardian.lua'],classifierCoreSha256:config.files['classifier-core.lua'],ctSourceSha256:config.files['conntrack-source.lua'],backendSha256:config.files['backend.lua'],policyUnchanged:true,sourceAndPublicationDeadlinesUnchanged:true,softwareExpiryRealChildQualified:true,boundedRowRecoveryQualified:true,independentRollbackPreviouslyVerified:true};return{deployment,config,configuration};
}
