import fs from'node:fs';import assert from'node:assert/strict';import{connectRouter}from'../nss20/connect-router.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';
const ctx=JSON.parse(fs.readFileSync('work/nss46/crash-trial/deployment-latest.json'));assert.equal(ctx.committed,false);const c=await connectRouter();const raw=[];try{
const lua=String.raw`local fs=require('nixio.fs');local j=require('luci.jsonc');local n=require('nixio');local function read(p,l)local f=assert(io.open(p));local s=f:read(l+1);f:close();assert(#s<=l);return s end
assert(fs.readlink('/proc/self/fd/8')=='/tmp/router-project-transaction.lock'and read('/proc/self/fdinfo/8',4096):find('FLOCK',1,true));local now=tonumber(read('/proc/uptime',128):match('^[%d.]+'));local id,b,d=read('/root/router-project/active-transaction',512):match('^(%S+) (%S+) (%d+)\n$');assert(id=='${ctx.transactionId}'and now+90<tonumber(d)and b==read('/proc/sys/kernel/random/boot_id',128):gsub('%s+$',''))
local s=assert(j.parse(read('/tmp/router-project-game-classifier/classification.json',4194304)));local g=assert(j.parse(read('/tmp/router-project-game-classifier/guardian.json',8192)));assert(s.status=='running'and s.configSha256=='${ctx.configHash}'and s.nssPermit==false and now<s.snapshot.provenance.startedAtUptime+6 and g.healthy and g.producer==s.producer);assert(not fs.lstat('/tmp/router-project-game-classifier/stopped'));assert(tonumber(read('/sys/kernel/debug/ecm/front_end_ipv4_stop',128))==1 and tonumber(read('/sys/kernel/debug/ecm/ecm_nss_ipv4/accelerated_count',128))==0)
local t={};for x in read('/proc/'..s.pid..'/stat',8192):match('^%d+ %b() (.*)$'):gmatch('%S+')do t[#t+1]=x end;assert(t[1]~='Z'and t[20]==s.start);assert(read('/proc/'..s.pid..'/cmdline',8192)==table.concat({'/usr/bin/lua','${ctx.base}/worker.lua','watch','${ctx.base}','${ctx.configHash}'},'\0')..'\0')
for pid in fs.dir('/proc')do if pid:match('^%d+$')then local f=io.open('/proc/'..pid..'/stat');if f then local text=f:read(8192);f:close();local a={};for v in text:match('^%d+ %b() (.*)$'):gmatch('%S+')do a[#a+1]=v end;assert(tonumber(a[2])~=s.pid,'Worker child active; refuse crash now')end end end
assert(n.kill(s.pid,9));print(j.stringify({passed=true,exactPid=s.pid,exactStart=s.start,oldProducer=s.producer,crashAt=now,noMutationChildActive=true,transactionLocked=true,signal=9,nssEnabled=false}))`;
const body='exec 8>/tmp/router-project-transaction.lock\nflock -x -w 1 8\n/usr/bin/lua - <<\'NSS46_ONE_CRASH\'\n'+lua+'\nNSS46_ONE_CRASH\n';let killed;
for(let i=0;i<8;i++){const e=encode(ctx.base+'/group-runner 6 /bin/sh -c '+"'"+body.replaceAll("'","'\\''")+"'"),r=receipt(await c.run(e.command),e);raw.push(r);if(r.code===0){killed=JSON.parse(r.stdout);break}assert.ok(r.stderr.includes('Worker child active')||r.stderr.includes('assertion failed'),'Unexpected crash prerequisite failure: '+r.stderr);await new Promise(r=>setTimeout(r,300));}fs.writeFileSync(ctx.localDir+'/crash-attempts-raw-private.json',JSON.stringify(raw,null,2)+'\n');assert.ok(killed,'No safe idle point; no crash sent');fs.writeFileSync(ctx.localDir+'/crash-sent.json',JSON.stringify(killed,null,2)+'\n');console.log(JSON.stringify(killed));
const observe=String.raw`local j=require('luci.jsonc');local n=require('nixio');local fs=require('nixio.fs');local function read(p,l)local f=io.open(p);if not f then return nil end;local s=f:read(l+1);f:close();assert(#s<=l);return s end;local rows={};for i=1,100 do local now=tonumber(read('/proc/uptime',128):match('^[%d.]+'));local a=read('/tmp/router-project-game-classifier/classification.json',4194304);local b=read('/tmp/router-project-game-classifier/guardian.json',8192);local s=a and j.parse(a);local g=b and j.parse(b);local p=s and s.snapshot and s.snapshot.provenance;rows[#rows+1]={at=now,pid=s and s.pid,producer=s and s.producer,hash=s and s.configSha256,status=s and s.status,sequence=p and p.sequence,age=p and now-p.startedAtUptime,guardianHealthy=g and g.healthy,guardianProducer=g and g.producer,stopped=fs.lstat('/tmp/router-project-game-classifier/stopped')~=nil,accel=tonumber(read('/sys/kernel/debug/ecm/ecm_nss_ipv4/accelerated_count',128))};n.nanosleep(0,200000000)end;print(j.stringify({rows=rows}))`;
const e=encode("/usr/bin/lua - <<'NSS46_CRASH_OBSERVE'\n"+observe+'\nNSS46_CRASH_OBSERVE\n'),r=receipt(await c.run(e.command),e);fs.writeFileSync(ctx.localDir+'/crash-observation-raw-private.json',JSON.stringify(r,null,2)+'\n');assert.equal(r.code,0,r.stderr);const d=JSON.parse(r.stdout);fs.writeFileSync(ctx.localDir+'/crash-observation-private.json',JSON.stringify(d,null,2)+'\n');const recovered=d.rows.find(x=>x.pid!==killed.exactPid&&x.hash===ctx.configHash&&x.status==='running'&&x.age<6&&x.guardianHealthy&&x.guardianProducer===x.producer&&!x.stopped);const q={passed:!!recovered&&d.rows.every(x=>x.accel===0),oneExactWorkerCrash:true,oldPid:killed.exactPid,newPid:recovered?.pid,recoveredSeconds:recovered&&recovered.at-killed.crashAt,newProducerDifferent:recovered&&recovered.producer!==killed.oldProducer,newInstanceFreshAndGuardianHealthy:!!recovered,nssEnabled:false,highLoadTest:false};fs.writeFileSync(ctx.localDir+'/crash-qualified.json',JSON.stringify(q,null,2)+'\n');console.log(JSON.stringify(q));
}finally{c.close()}
