import fs from'node:fs';import assert from'node:assert/strict';import{connectRouter}from'../nss20/connect-router.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';
const ctx=JSON.parse(fs.readFileSync('work/nss46/expiry-fault/deployment-latest.json'));
const lua=String.raw`local j=require('luci.jsonc');local n=require('nixio');local fs=require('nixio.fs');local function read(p,l)local f=io.open(p);if not f then return nil end;local s=f:read(l+1);f:close();assert(#s<=l);return s end
local function now()return tonumber(read('/proc/uptime',128):match('^[%d.]+'))end
local function doc(name)local raw=read('/tmp/router-project-game-classifier/'..name..'.json',4194304);return raw and j.parse(raw)end
local rows={};local result;local seen={};local began=now()
for i=1,200 do
 local c=doc('classification');local s=doc('snapshot');local a=doc('apply-result');local g=doc('guardian');local p=c and c.snapshot and c.snapshot.provenance;local J=doc('journal');local entries=0;local intents=0
 if J then for _ in pairs(J.entries)do entries=entries+1 end;for _,w in pairs(J.wans)do intents=intents+#w.intents end end
 local row={at=now(),pid=c and c.pid,producer=c and c.producer,status=c and c.status,fullStatus=s and s.status,sequence=p and p.sequence,sourceAge=p and now()-p.startedAtUptime,guardianHealthy=g and g.healthy,guardianProcessHealthy=g and g.processHealthy,degradation=c and c.degradation,entries=entries,intents=intents,frontend=tonumber(read('/sys/kernel/debug/ecm/front_end_ipv4_stop',64)),accelerated=tonumber(read('/sys/kernel/debug/ecm/ecm_nss_ipv4/accelerated_count',64)),stopped=fs.lstat('/tmp/router-project-game-classifier/stopped')~=nil}
 if a and a.observationExpired and not seen[a.querySequence]then seen[a.querySequence]=true;result=a;row.expiredApply=a end
 if i%5==1 or row.expiredApply or row.status=='degraded'or row.status=='error'then rows[#rows+1]=row end
 n.nanosleep(0,200000000)
end
local children={};if result and result.testRuntime then local pid=result.testRuntime.pid;children.applyReaped=fs.lstat('/proc/'..pid)==nil end
print(j.stringify({rows=rows,expiredResult=result,children=children,seconds=now()-began,nssEnabled=false,testFault=true,flowMetadataFabricated=false}))`;
let c;try{let d;if(process.argv.includes('--summarize-existing')){d=JSON.parse(fs.readFileSync(ctx.localDir+'/fault-observation-private.json'));const p=ctx.localDir+'/fault-qualified.json';if(fs.existsSync(p)&&!fs.existsSync(ctx.localDir+'/fault-qualified-first.json'))fs.copyFileSync(p,ctx.localDir+'/fault-qualified-first.json');}else{c=await connectRouter();const e=encode("/usr/bin/lua - <<'NSS46_REAL_APPLY_OBSERVE'\n"+lua+'\nNSS46_REAL_APPLY_OBSERVE\n'),r=receipt(await c.run(e.command),e);fs.writeFileSync(ctx.localDir+'/fault-observation-raw-private.json',JSON.stringify(r,null,2)+'\n');assert.equal(r.code,0,r.stderr);d=JSON.parse(r.stdout);d.observedAt=new Date().toISOString();fs.writeFileSync(ctx.localDir+'/fault-observation-private.json',JSON.stringify(d,null,2)+'\n');}const exp=d.expiredResult??d.rows.find(x=>x.expiredApply)?.expiredApply;const recovered=d.rows.filter(x=>x.status==='degraded'&&x.degradation?.baselineRecoveryComplete);const latest=d.rows.at(-1);const q={passed:!!exp&&d.children.applyReaped&&recovered.length>0&&latest.status==='running'&&d.rows.every(x=>x.frontend===1&&x.accelerated===0&&!x.stopped)&&latest.pid===exp.testRuntime.producerPid,realApplyChild:!!exp?.testRuntime,realApplyPid:exp?.testRuntime.pid,ageAtWriteCheck:exp&&exp.observationExpired.checkedAt-exp.observationExpired.sourceStartedAt,applyChildReaped:d.children.applyReaped,expiredProducerBound:!!exp&&exp.producer===latest.producer,exactRecoveryConfirmed:recovered.length>0,refusedBeforeBatch:!!exp&&exp.snapshot===undefined&&exp.changes===undefined,latestHealthy:latest.status==='running'&&latest.guardianHealthy,latestPid:latest.pid,seconds:d.seconds,nssEnabled:false,testOnlyDelay:true,fakeFlow:false,highLoadProof:false,duplicateJsonTableUsesCapturedFrame:!d.expiredResult&&!!exp};fs.writeFileSync(ctx.localDir+'/fault-qualified.json',JSON.stringify(q,null,2)+'\n');console.log(JSON.stringify(q));}finally{c?.close()}
