from pathlib import Path
import html,json
root=Path(__file__).resolve().parents[2];s=json.loads((root/'outputs/nss46-mainline-observations.json').read_text());esc=lambda v:html.escape(str(v))
blocks=[]
def section(title,text):blocks.append('<section><h2>'+esc(title)+'</h2>'+text+'</section>')
section('这轮实际推进了什么','<p>三项分类器可靠性修复已逐项实装并保留，常驻引用切换到 <code>work/nss46/deployment-latest.json</code>。真实应用子进程过期恢复、真实 worker crash 恢复与新的 NSS 入口现场审核通过。NSS 当前仍关闭；本轮没有真人游戏或高负载 A/B。</p>')
section('真实故障测试','<table><tr><th>测试</th><th>实际结果</th><th>证明范围</th></tr><tr><td>真实观察延迟一次</td><td>来源年龄 '+esc(round(s['realSoftwareExpiry']['ageAtWriteCheck'],2))+' 秒时拒绝写入；精确 recover 子进程 '+esc(round(s['realSoftwareExpiry']['actualRecoveryChildSeconds'],2))+' 秒；同 worker 继续运行</td><td>真实身份、原锁和原期限，两个发布撤回、pending intents 清零；轻载</td></tr><tr><td>精确 kill 一个空闲 worker</td><td>procd 新实例 '+esc(round(s['realWorkerCrash']['recoveredSeconds'],2))+' 秒内恢复新鲜发布和健康 guardian</td><td>真实 crash；未终止活动 mutation 子进程；轻载</td></tr><tr><td>两个独立超时回滚</td><td>均在原 180 秒自然到期恢复四份源码、配置、指针及健康实例</td><td>新 checkpoint、下载哈希与压缩核验；写前确认独立守护身份</td></tr></table>')
section('保留的分类器与新入口','<ul><li>backend 只复用已验证的首次恢复读取；实际写前、写后检查保留。</li><li>过期来源作为明确的有界观测失效处理：撤回发布，精确恢复，清空历史，再观察。</li><li>2048 行上限保留；超限不接收部分结果，未知错误仍拒绝。</li><li>新 NSS 入口绑定 '+esc(s['entry']['boundInputs'])+' 项输入；'+esc(s['entry']['localCases'])+' 项入口离线检查通过。调度等待 classification 的来源年龄为 '+esc(round(s['entry']['classificationHintSourceAgeSeconds'],2))+' 秒，然后执行原完整审核。</li><li>一条 TCP＋一条 UDP、20 Mbps 子组、45 秒 owner、原 1/2/6/9 秒门槛均未扩大；NSS 路由器 Lua 数据面与已验证的 NSS39 字节一致。</li></ul>')
o=s['retainedNaturalObservation'];section('自然轻载观测','<p>'+esc(o['samples'])+' 帧、'+esc(round(o['seconds'],2))+' 秒，同一实例全部健康；来源年龄最高 '+esc(round(o['sourceAgeMax'],2))+' 秒。LAN4 '+esc(round(o['mbps'],3))+' Mbps，'+esc(round(o['pps'],1))+' pps；busy '+esc(round(o['cpuBusyPercent'],2))+'%，softirq '+esc(round(o['softirqPercent'],2))+'%，time_squeeze +'+esc(o['timeSqueezeDelta'])+'。这是轻载状态记录，不能用来推导 CPU 收益。</p>')
section('证据边界与失败记录','<p>expiry 保留试装开场有三帧旧 producer / guardian 预热状态，不能写成从安装第一刻全程健康；当前新实例完整审核后才提交保留。首个故障摘要漏读了 JSON 中重复 table 引用，已从原始帧恢复同一份真实 apply 回执，初始错误摘要留存。入口夹具的旧路径和未绑定 seed 证明已纠正，原失败输出保留；这些本地问题未触发 NSS 写入。</p><p>软件算法的换端口/旧流退出与未知写入者检查仍须与真人高负载运行分开。当前不能声称 CS2 jitter/loss/Miss、CPU 收益、五 WAN 稳定或 NSS QoS 替代已经验收。</p>')
section('当前状态与下一步','<p>最终原完整保护审核通过，分类器和 guardian 健康，ECM 停止且全零；无活动事务、暂存、实验状态或实验 gate/qdisc 模块。last-error 属于受控试装临近到期退出，来源不是当前 worker。</p><p>下一步仅需一次集中真人 CS2＋Steam 窗口，运行新入口 software→NSS→software，记录同一 WAN、受控 bulk/RT leaf 份额、实际吞吐/pps、softirq/time_squeeze 与客户端体验。有真实连接对才测试；当前未检测到配对。第二 WAN、共享预算、Wi-Fi 和 autorate 继续等待。</p>')
doc='<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSS46 分类器实装与新入口</title><style>body{font:16px/1.7 system-ui,sans-serif;color:#dce5ef;background:#101722;margin:0}main{max-width:1050px;margin:45px auto;padding:0 24px}h1{font-size:31px}h2{font-size:22px;color:#8dd9d0}section{margin:28px 0;padding:22px;background:#182435;border-radius:12px}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:12px;border-bottom:1px solid #3e516a}code{overflow-wrap:anywhere;color:#fae0a9}p{margin:10px 0}li{margin:7px 0}.note{color:#a8b9ce}</style><main><h1>NSS46 · 分类器修复已实装</h1><p class="note">2026-10-04 · 真实子进程与 crash 恢复通过 · 真人高负载验收待测</p>'+''.join(blocks)+'<p class="note">完整敏感证据留在私有工作区；脱敏证据和源码进入私有 GitHub。报告源已核验，未通过浏览器视觉渲染验收。</p></main></html>'
dst=root/'outputs/nss46-mainline-report.html';dst.write_text(doc,encoding='utf-8',newline='\n');assert '<table>'in doc and '<script'not in doc and all(token in doc for token in ['6.27','0.8','7.56','112']);print(json.dumps({'report':str(dst),'sourceValidated':True,'browserRendered':False}))
