import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {BoundedFixture} from './fixture.mjs';import {save,read} from '../resident-dev-20261007/materialize.mjs';
const dir='work/resident-normal-dev-c-20261008/fixture-tests-'+Date.now()+'-'+crypto.randomBytes(4).toString('hex');fs.mkdirSync(dir);
const checks=[];async function test(name,fn){await fn();checks.push(name);}
function model(name,{load=true,setup=false,fail=false}={}){
 const root=dir+'/'+name;fs.mkdirSync(root);const scope=root+'/scope';fs.mkdirSync(scope);const f=new BoundedFixture(dir,1);f.root=root;f.scopeDirectory=scope;f.events=[];f.requestStop=()=>f.events.push('request-stop');f.waitUntil=async()=>f.events.push('independent-deadline');
 if(load){const ld=root+'/load';fs.mkdirSync(ld);save(root+'/load-latest-private.json',{dir:ld});save(ld+'/launch-receipt.json',{});save(ld+'/client-binding-private.json',{guardResult:ld+'/guard.json'});save(ld+'/guard.json',{passed:true});}
 if(setup){const sd=root+'/setup';fs.mkdirSync(sd);save(root+'/endpoint-setup-private.json',{dir:sd});save(sd+'/server-launch-intent-private.json',{});}
 f.command=async name=>{f.events.push(name);if(fail&&name==='endpoint-closure')throw Error('original closure failure');if(name==='final-health')save(root+'/closure-pointer.json',{directory:root});};return f;
}
await test('cleanup is idempotent for catch/finally and concurrent callers',async()=>{const f=model('idempotent');const a=f.close({normalRestored:true}),b=f.close({normalRestored:true});assert.equal(a,b);await Promise.all([a,b]);await f.close();assert.deepEqual(f.events,['request-stop','independent-deadline','endpoint-closure','client-closure']);assert.equal(f.clean,true);assert.equal(read(f.scopeDirectory+'/fixture-closure.json').passed,true);});
await test('failed cleanup never overwrites or repeats the original endpoint command',async()=>{const f=model('failed',{fail:true});const p=f.close({normalRestored:true});await assert.rejects(p,/original closure/);assert.equal(f.close(),p);await assert.rejects(f.close(),/original closure/);assert.equal(f.events.filter(x=>x==='endpoint-closure').length,1);assert.equal(f.clean,false);assert.ok(!fs.existsSync(f.scopeDirectory+'/fixture-closure.json'));});
await test('no NSS admission performs the missing final readonly audit once',async()=>{const f=model('no-admission');await f.close();assert.deepEqual(f.events,['request-stop','independent-deadline','endpoint-closure','client-closure','final-health','physical-queues']);assert.ok(fs.existsSync(f.root+'/fixture-client-closure-pointer.json'));});
await test('partial endpoint launch waits original deadline and audits absence of client',async()=>{const f=model('partial',{load:false,setup:true});await f.close();assert.deepEqual(f.events,['independent-deadline','partial-endpoint-closure','no-client-closure','final-health','physical-queues']);});
await test('before endpoint launch creates no client stop or endpoint mutation',async()=>{const f=model('prewrite',{load:false});await f.close();assert.deepEqual(f.events,['final-health','physical-queues']);});
await test('normal product source never imports the external traffic harness',async()=>{for(const name of ['controller.mjs','normal-entry.mjs','run-generation.mjs','normal-reader.mjs']){const s=fs.readFileSync('work/resident-normal-dev-c-20261008/'+name,'utf8');assert.ok(!s.includes("from './fixture.mjs'"));assert.ok(!s.includes('start-dallas.mjs'));}});
await test('partial setup is registered before failure and cleanup has one execution',async()=>{const s=fs.readFileSync('work/resident-normal-dev-c-20261008/integration.mjs','utf8');assert.ok(s.includes('finally{Object.assign(state.fixtures.at(-1)'));assert.ok(s.includes('fixture.close({normalRestored'));const f=model('partial-failure',{load:false,setup:true});await Promise.all([f.close(),f.close()]);assert.equal(f.events.filter(x=>x==='partial-endpoint-closure').length,1);});
const r={passed:true,checks,modelOnly:true,routerAccess:false,fixtureStarted:false};save(dir+'/result.json',r);fs.writeFileSync('work/resident-normal-dev-c-20261008/fixture-tests-latest.json',JSON.stringify({...r,file:dir+'/result.json'},null,2)+'\n');console.log(JSON.stringify({passed:true,checks:checks.length,dir}));
