import fs from'node:fs';import crypto from'node:crypto';import assert from'node:assert/strict';import{canonicalSelection}from'../nss27/flow-selection.mjs';
const root='work/v30-normal',sessions=fs.readdirSync(root).filter(n=>/^session-\d{14}-[a-f0-9]{8}$/.test(n));assert.equal(sessions.length,1);const dir=root+'/'+sessions[0];
const selected=JSON.parse(fs.readFileSync(dir+'/selected-preaudit-private.json')),frame=JSON.parse(fs.readFileSync(root+'/controlled-candidates-private.json')),error=JSON.parse(fs.readFileSync(dir+'/controller-error.json'));
assert.match(error.error,/Controlled exact pair changed after original full audit/);
const slots={};for(const slot of['tcp','udp','tcp2']){const list=slot==='udp'?frame.udp:frame.tcp;slots[slot]={wan:selected[slot].wan,exactApplicationOwnedIdentityStillPresent:list.some(f=>JSON.stringify(canonicalSelection(f))===JSON.stringify(selected[slot])),protocol:selected[slot].protocol};}
fs.writeFileSync(dir+'/rejected-selection-frame-private.json',JSON.stringify(frame,null,2)+'\n',{flag:'wx'});
const result={passed:true,diagnosticOnly:true,refusalBeforeCheckpoint:true,refusal:'Controlled exact pair changed after original full audit',slots,oldTripleWasFirstSelectorResult:frame.pairs.some(p=>JSON.stringify(p)===JSON.stringify(selected)),bulkCandidateCount:frame.tcp.length,gameCandidateCount:frame.udp.length,sourceAge:frame.sourceAge,sourceSequence:frame.sourceSequence,producerMatchesInitial:frame.producer===JSON.parse(fs.readFileSync(dir+'/normal-application-preaudit-private.json')).candidates.producer,anyCheckpointCreated:fs.existsSync(dir+'/stage-checkpoint-private.json'),anyDetachedStageStarted:fs.existsSync(dir+'/stage-receipt-private.json'),nssHardwareAcceptance:false};
result.onlyFirstCandidateOrderingChanged=Object.values(slots).every(s=>s.exactApplicationOwnedIdentityStillPresent)&&!result.oldTripleWasFirstSelectorResult;
result.frameSha256=crypto.createHash('sha256').update(fs.readFileSync(dir+'/rejected-selection-frame-private.json')).digest('hex');fs.writeFileSync(root+'/refusal-analysis.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result));
