import fs from 'node:fs';import assert from 'node:assert/strict';import {packLua} from '../nss149/pack-lua.mjs';
export function buildPayload(input,{qos,phase,classifier,tags,normalizer}){
 const pool=[],refs=[],skeleton=structuredClone(input.tagPlan),rules=skeleton.expected.nftables.filter(x=>x.rule).map(x=>x.rule);assert.ok(rules.length);const meta={};for(const[k,v]of Object.entries(rules[0]))if(k!=='expr'&&k!=='comment'&&rules.every(r=>JSON.stringify(r[k])===JSON.stringify(v)))meta[k]=v;for(const r of rules)for(const k of Object.keys(meta))delete r[k];let prefix=rules[0].comment;assert.equal(typeof prefix,'string');for(const r of rules){assert.equal(typeof r.comment,'string');while(!r.comment.startsWith(prefix))prefix=prefix.slice(0,-1)}for(const r of rules)r.comment=r.comment.slice(prefix.length);
 for(const[i,x]of skeleton.expected.nftables.entries())if(x.rule){const ids=x.rule.expr.map(e=>{let n=pool.findIndex(p=>JSON.stringify(p)===JSON.stringify(e));if(n<0){n=pool.length;pool.push(e)}return n+1});delete x.rule.expr;refs.push([i+1,ids])}
 const only=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).sort().join('|')===[...keys].sort().join('|');
 const packedPool=pool.map(e=>{if(!only(e,['match'])||!only(e.match,['op','left','right']))return e;const {op,left,right}=e.match;if(only(left,['payload'])&&only(left.payload,['protocol','field']))return['p',op,left.payload.protocol,left.payload.field,right];if(only(left,['meta'])&&only(left.meta,['key']))return['m',op,left.meta.key,right];if(only(left,['ct'])&&only(left.ct,['key']))return['c',op,left.ct.key,right];return['x',op,left,right]});
 const decode=v=>{if(!Array.isArray(v))return structuredClone(v);const [kind,op,a,b,c]=v;let left,right;if(kind==='p'){left={payload:{protocol:a,field:b}};right=c}else if(kind==='m'||kind==='c'){left={[kind==='m'?'meta':'ct']:{key:a}};right=b}else{assert.equal(kind,'x');left=a;right=b}return{match:{op,left:structuredClone(left),right:structuredClone(right)}}};
 assert.deepEqual(packedPool.map(decode),pool);const rebuilt=structuredClone(skeleton);for(const x of rebuilt.expected.nftables)if(x.rule){Object.assign(x.rule,structuredClone(meta));x.rule.comment=prefix+x.rule.comment}for(const[row,ids]of refs)rebuilt.expected.nftables[row-1].rule.expr=ids.map(i=>decode(packedPool[i-1]));assert.deepEqual(rebuilt,input.tagPlan);
 const data=JSON.stringify({s:skeleton,p:packedPool,r:refs,m:meta,x:prefix});assert.ok(!data.includes(']====]'));
 const tagSource="local j=require('luci.jsonc');local p=assert(j.parse([====["+data+"]====]));for _,x in ipairs(p.s.expected.nftables)do if x.rule then for k,v in pairs(p.m)do assert(x.rule[k]==nil);x.rule[k]=v end;x.rule.comment=p.x..x.rule.comment end end;for _,r in ipairs(p.r)do local e={};for _,i in ipairs(r[2])do local v=assert(j.parse(j.stringify(p.p[i])));if v[1]then local k,o,a,b,c=v[1],v[2],v[3],v[4],v[5];local l,t;if k=='p'then l={payload={protocol=a,field=b}};t=c elseif k=='m'then l={meta={key=a}};t=b elseif k=='c'then l={ct={key=a}};t=b else assert(k=='x');l=a;t=b end;v={match={op=o,left=l,right=t}}end;e[#e+1]=v end;p.s.expected.nftables[r[1]].rule.expr=e end;return p.s";
 const stagedCode='local qos=(function()\n'+packLua(qos)+'\nend)();local phase=(function()\n'+packLua(phase)+'\nend)();local classifier=(function()\n'+packLua(classifier)+'\nend)();local tags=(function()\n'+packLua(tags)+'\nend)();local normalizer=(function()\n'+packLua(normalizer)+'\nend)();local tagPlan=(function()\n'+tagSource+'\nend)();local fast=(function()\n'+packLua(fs.readFileSync('work/nss158/fast-path.lua','utf8'))+'\nend)();local wan=(function()\n'+packLua(fs.readFileSync('work/nss49/wan-scope.lua','utf8'))+'\nend)();local state=(function()\n'+packLua(fs.readFileSync('work/nss49/state-node.lua','utf8'))+'\nend)();return{qos=qos,phase=phase,classifier=classifier,tags=tags,normalizer=normalizer,tagPlan=tagPlan,fast=fast,wan=wan,state=state}\n';return{stagedCode,tagSource};
}
