import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';
const root='work/nss39',old=JSON.parse(fs.readFileSync('work/nss37/deployment-latest.json')),sha=b=>crypto.createHash('sha256').update(b).digest('hex');assert.ok(old.committed);
const previous=JSON.parse(fs.readFileSync(old.localDir+'/config.json'));assert.equal(sha(fs.readFileSync(old.localDir+'/config.json')),old.configHash);
for(const name of ['guardian.lua','conntrack-source.lua']){const b=fs.readFileSync('athena-nss-mainline/code/deployed-classifier/'+name);assert.equal(sha(b),previous.files[name]);fs.writeFileSync(root+'/'+name,b)}
for(const name of ['worker-qualified.json','tc-native-qualified.json']){const q=JSON.parse(fs.readFileSync(root+'/'+name));assert.ok(q.passed);assert.equal(q.workerSha256,sha(fs.readFileSync(root+'/worker.lua')));assert.equal(q.helperSha256,sha(fs.readFileSync(root+'/tc-command.lua')))}
const b=JSON.parse(fs.readFileSync(root+'/tc-benchmark-qualified.json'));assert.ok(b.passed&&b.groups.every(g=>g.candidateTotalMs<g.oldTotalMs));assert.equal(b.helperSha256,sha(fs.readFileSync(root+'/tc-command.lua')));
let source=fs.readFileSync('work/nss37/upgrade.mjs','utf8'),a=source.indexOf("const root='work/nss37'"),z=source.indexOf("const id='nss37-'");assert.ok(a>0&&z>a);
source=source.slice(0,a)+String.raw`const root='work/nss39',old=JSON.parse(fs.readFileSync('work/nss37/deployment-latest.json')),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),json=o=>JSON.stringify(o,null,2)+'\n';assert.equal(old.committed,true);
const qualified=JSON.parse(fs.readFileSync(root+'/worker-qualified.json')),native=JSON.parse(fs.readFileSync(root+'/tc-native-qualified.json')),bench=JSON.parse(fs.readFileSync(root+'/tc-benchmark-qualified.json'));
assert.ok(qualified.passed&&native.passed&&bench.passed);for(const q of [qualified,native]){assert.equal(q.workerSha256,sha(fs.readFileSync(root+'/worker.lua')));assert.equal(q.helperSha256,sha(fs.readFileSync(root+'/tc-command.lua')))}assert.equal(bench.helperSha256,qualified.helperSha256);assert.ok(bench.groups.every(g=>g.candidateTotalMs<g.oldTotalMs));
const previousConfig=JSON.parse(fs.readFileSync(old.localDir+'/config.json'));for(const n of ['guardian.lua','conntrack-source.lua'])assert.equal(sha(fs.readFileSync(root+'/'+n)),previousConfig.files[n]);
`+source.slice(z);
source=source.replace("const id='nss37-'","const id='nss39-'").replace("normalized.files['conntrack-source.lua']=previousConfig.files['conntrack-source.lua']","normalized.files['worker.lua']=previousConfig.files['worker.lua']").replace('Only attribute extraction may change','Only tc child supervision and mutation diagnostics may change').replace('attributeNormalizerTrial:true','tcChildSupervisionTrial:true');
fs.writeFileSync(root+'/upgrade.mjs',source);
for(const name of ['observe-compact.mjs','verify-rollback.mjs','deployment-audit.mjs'])fs.writeFileSync(root+'/'+name,fs.readFileSync('work/nss37/'+name,'utf8').replaceAll('work/nss37','work/nss39'));
let commit=fs.readFileSync('work/nss37/commit-channel.mjs','utf8').replaceAll('work/nss37','work/nss39').replaceAll('normalizer-trial-qualified.json','worker-trial-qualified.json').replace('equivalentAttributeNormalizer=true','tcChildSupervisionQualified=true');
const g="assert.equal(trial.sourceSha256,JSON.parse(fs.readFileSync(ctx.localDir+'/config.json')).files['conntrack-source.lua']);";assert.ok(commit.includes(g));commit=commit.replace(g,"assert.equal(trial.guardianSha256,JSON.parse(fs.readFileSync(ctx.localDir+'/config.json')).files['guardian.lua']);");fs.writeFileSync(root+'/commit-channel.mjs',commit);
console.log(JSON.stringify({prepared:true,onlyWorkerAndConfigurationBindingChange:true,nssEnabled:false,independentRollbackSeconds:180,routerWrites:false}));
