import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{connectRouter}from'../nss20/connect-router.mjs';
const root='work/nss39',read=p=>JSON.parse(fs.readFileSync(p)),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const ctx=read(root+'/deployment-latest.json'),obs=read(root+'/trial-observation.json'),rollback=read(ctx.localDir+'/rollback-qualified.json');assert.equal(ctx.committed,false);
assert.ok(rollback.passed&&rollback.automaticExpiryWithoutControllerRollback&&rollback.previousNormalizerAndGuardianRestored);
assert.ok(obs.semantic.passed&&obs.semantic.identityDecisionLeafAndExpiryEqual&&obs.rows.length===35);assert.ok(obs.rows.every(r=>r.status==='running'&&r.guardianHealthy&&r.accel===0&&r.frontend===1));assert.equal(new Set(obs.rows.map(r=>r.producer)).size,1);
const audit=read(ctx.localDir+'/trial-before-rollback-audit.json'),restored=read(root+'/restored-audit.json');assert.ok(audit.passed&&restored.passed&&restored.ecmClosedAndZero);assert.equal(audit.producer,obs.rows[0].producer);
const local=read(root+'/worker-qualified.json'),native=read(root+'/tc-native-qualified.json'),bench=read(root+'/tc-benchmark-qualified.json');for(const q of [local,native]){assert.ok(q.passed);assert.equal(q.workerSha256,hash(root+'/worker.lua'));assert.equal(q.helperSha256,hash(root+'/tc-command.lua'))}assert.ok(bench.passed);assert.equal(bench.helperSha256,local.helperSha256);
const proof={passed:true,observedAt:new Date().toISOString(),workerSha256:local.workerSha256,helperSha256:local.helperSha256,guardianSha256:hash(root+'/guardian.lua'),trialTransaction:ctx.transactionId,trialConfigSha256:ctx.configHash,localChecks:local.checks,nativeArgumentChecks:native.checks,nativeProcessCases:native.rows.length,independentRollback:rollback,protectedAudit:audit,restoredAudit:restored,semantic:obs.semantic,healthySamples:obs.rows.length,producerStable:true,highLoadQualified:false,nssEnabled:false,actualEarlierFailureRootCauseConclusive:false};
fs.writeFileSync(root+'/worker-trial-qualified.json',JSON.stringify(proof,null,2)+'\n');fs.writeFileSync(ctx.localDir+'/deployment-trial.json',JSON.stringify(ctx,null,2)+'\n');
const c=await connectRouter();try{await c.upload(ctx.localDir+'/cancel',ctx.stagePath+'/cancel');}finally{c.close()}
console.log(JSON.stringify({passed:true,healthySamples:obs.rows.length,automaticRollback:true,stageCancellationRequested:true}));
