import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';
const root='work/nss39',read=p=>JSON.parse(fs.readFileSync(p)),get=n=>read(root+'/'+n),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const d=get('deployment-latest.json'),cfg=read(d.localDir+'/config.json'),trial=get('worker-trial-qualified.json'),retained=get('retention-qualified.json'),a=get('closing-audit.json'),inspect=get('classifier-final-inspection.json'),closure=get('final-closure.json');assert.ok(d.committed&&trial.passed&&retained.passed&&a.passed&&closure.passed);
const last=inspect.files['classification.json'];assert.equal(last.configSha256,d.configHash);assert.equal(last.status,'running');assert.ok(inspect.files['guardian.json'].healthy);
const cpu=s=>s.trim().split(/\s+/).slice(1).map(Number),squeeze=s=>s.trim().split('\n').reduce((v,l)=>v+parseInt(l.trim().split(/\s+/)[2],16),0);
function window(path){const x=read(path),rows=x.rows,b=rows[0],e=rows.at(-1),dt=e.uptime-b.uptime,u=cpu(b.cpu),v=cpu(e.cpu),delta=v.map((n,i)=>n-u[i]),total=delta.slice(0,8).reduce((x,y)=>x+y,0);return{samples:rows.length,seconds:dt,lan4DownMbps:(e.txBytes-b.txBytes)*8/dt/1e6,lan4DownPps:(e.txPackets-b.txPackets)/dt,cpuBusyPercent:(total-delta[3]-delta[4])*100/total,softirqPercent:delta[6]*100/total,timeSqueezeDelta:squeeze(e.softnet)-squeeze(b.softnet),allHealthy:rows.every(v=>v.status==='running'&&v.guardianHealthy),producerStable:new Set(rows.map(v=>v.producer)).size===1,ecmClosedAndZero:rows.every(v=>v.accel===0&&v.frontend===1),minimumSourceAge:Math.min(...rows.map(v=>v.age)),maximumSourceAge:Math.max(...rows.map(v=>v.age)),semantic:x.semantic}}
const paths=fs.readdirSync(root,{withFileTypes:true}).filter(x=>x.isDirectory()&&x.name.startsWith('nss39-')).map(x=>root+'/'+x.name).sort();assert.equal(paths.length,4);
const installations=paths.map((p,i)=>{const arm=read(p+'/armed-proof.json'),cp=read(p+'/checkpoint.json'),rb=fs.existsSync(p+'/rollback-qualified.json')?read(p+'/rollback-qualified.json'):null;assert.ok(arm.passed&&arm.independentOfSsh&&cp.gzipVerified);return{attempt:i+1,checkpointVerified:true,rollbackVerifiedBeforeConfigMutation:true,independentOfControlConnection:true,deadlineSeconds:180,automaticRollbackVerified:!!rb?.passed,rollbackObservedAt:rb?.observedAt,committed:p===d.localDir,reason:['Initial qualification; deliberately allowed independent expiry','Commit reserve elapsed during local preparation; allowed expiry','Old publication rejected during cold start; resume later missed unchanged commit reserve; allowed expiry','Waited for current producer, sampled and audited within deadline; retained'][i]}});
assert.equal(installations.filter(x=>x.automaticRollbackVerified).length,3);assert.ok(installations.at(-1).committed);
const benchmark=get('tc-benchmark-qualified.json'),native=get('tc-native-qualified.json'),local=get('worker-qualified.json'),q=get('affinity-qualified.json'),nativeConsumer=get('native-consumer-qualified.json'),aba=get('aba-qualified.json'),preflight=get('mainline-preflight-qualified.json'),startup=read(retained.startupPath);assert.ok(q.passed&&nativeConsumer.passed&&aba.passed&&preflight.passed&&startup.passed);
assert.equal(q.configuration.configSha256,d.configHash);assert.ok(read(nativeConsumer.stageProofDirectory+'/cleanup.json').passed);
const app=get('real-reader-qualified.json'),obs=read(retained.observationPath);assert.equal(last.producer,obs.rows.at(-1).producer);assert.equal(a.producer,last.producer);
const out={round:'NSS39',generatedAt:new Date().toISOString(),deploymentReference:root+'/deployment-latest.json',
 classifier:{committed:true,configSha256:d.configHash,workerSha256:cfg.files['worker.lua'],guardianSha256:cfg.files['guardian.lua'],sourceSha256:cfg.files['conntrack-source.lua'],commitAt:d.commitAt},
 change:{oldWorkerSha256:get('candidate-manifest.json').oldWorkerSha256,newWorkerSha256:sha(root+'/worker.lua'),helperSha256:sha(root+'/tc-command.lua'),onlyTcSupervisionAndFailureDiagnosticsChanged:true,policySourceScopeAndDeadlinesUnchanged:true,tcDeadlineSeconds:2,outerMutationDeadlineSeconds:6,failedCommandStillFatal:true,noReadFailureRetryAdded:true},
 hypothesis:{detachedTimeoutWatchdogAddsOuterReapLatency:true,originalNatural143RootCauseProved:false,officialSource:get('busybox-source-reference.json'),runtimeBusybox:'1.38.0',firmwareSourcePatchesCompared:false},
 oldWrapperReproduction:{rows:get('timeout-path-qualified-private.json').rows.map(({raw,...v})=>v),productionFaultInjected:false},
 helperChecks:{localCases:local.checks,localCaseNames:local.cases,nativeArgumentCases:native.checks,nativeProcessCases:native.rows.map(x=>({name:x.name,seconds:x.seconds,outerExit:x.outerExit,allFixtureChildrenGone:x.allFixtureChildrenGone,operationSucceeded:x.result?.ok??null,diagnostic:x.result?.ok===false?x.result.result:null})),actualTcWriteFaultInjected:false},
 readOnlyBenchmark:{groups:benchmark.groups,backgroundLan4Mbps:benchmark.backgroundLan4Mbps,pairedSamples:benchmark.rows.length,realTcCommands:true,configurationWrites:false,metric:'Complete isolated wrapper wall time including process cleanup, not CPU or forwarding performance'},
 installations,independentRollback:trial.independentRollback?{passed:trial.independentRollback.passed,automaticExpiryWithoutControllerRollback:true,previousWorkerAndConfigRestored:true}:null,
 windows:{trial:window(root+'/trial-observation.json'),expiredSecondInstall:window(root+'/permanent-observation.json'),thirdColdStart:window(root+'/retained-observation.json'),thirdAfterWarming:window(root+'/after-warming-observation.json'),retained:window(retained.observationPath)},
 startup:{initialObservationRejectedOldProducer:true,thirdInitialUnhealthySamples:get('retained-observation.json').rows.filter(r=>!r.guardianHealthy).length,oldPublicationNeverAuthorized:true,retentionReadinessCurrentInstallationBound:startup.currentInstallationBound,retentionReadinessProbes:startup.rows.length},
 controller:{boundToCurrentDeployment:true,configuration:q.configuration,sourceManifestEntries:Object.keys(q.sourceManifest).length,affinityChecks:q.checks.length,admissionChecks:get('admission-qualified.json').checks,renewalLocalChecks:get('consumer-qualified.json').checks,coreLifecycleChecks:get('lifecycle-qualified.json').checks,ownedLifecycleChecks:get('owned-lifecycle-qualified.json').checks,nativeConsumerChecks:nativeConsumer.checks,nativeAbaCases:aba.cases.length,nativeSourceComplete:true,nativeIoAndClocksMocked:true,nativeTemporaryStageIndependentlyRemoved:true,exactTagPolicyRoundtrip:preflight.exactPackedPolicyRoundtrip,compiledUnits:Object.keys(preflight.checks).length,stagedBytes:preflight.stagedBytes,stageExecBytes:preflight.stageExecBytes,transportExecCeiling:9000,adapterSha256:sha(root+'/classifier.lua'),fastSha256:sha(root+'/fast-path.lua'),historicalNss38DifferentialCasesReused:1470,historicalInspectionCountChecksReused:5,hardwareHighLoadQualified:false},
 application:{observedAt:app.observedAt,gameProcessRunning:app.gameProcessRunning,steamProcessRunning:app.steamProcessRunning,actualCs2RtCandidates:app.actualCs2RtCandidates,actualSteamBulkCandidates:app.actualSteamBulkCandidates,sameWanPairs:app.sameWanCandidates.length,nssAdmissionAllowed:false},
 finalState:{auditObservedAt:fs.statSync(root+'/closing-audit.json').mtime.toISOString(),protectedAudit:Object.fromEntries(Object.entries(a).filter(([k])=>!['producer','startup'].includes(k))),closure,currentClassifierHealthy:true,sameProducerSinceRetainedObservation:true,lastErrorBelongsToCurrentProducer:inspect.files['last-error.json']?.producer===last.producer,lastErrorReason:'Earlier uncommitted trial reached fixed rollback deadline',ecmClosedAndZero:true,noExperimentalLeafInstalled:true},
 actualFastPathTrial:{attempted:false,ecmOpened:false,leafCountersAvailable:false,acceleratedFlowMarkNatWanTested:false},
 limitations:{realHighLoadABACompleted:false,nssCpuBenefitProved:false,gameJitterLossMissCaptured:false,completeLongTermStabilityQualified:false,originalNaturalFailureRootCauseProved:false,monitoringIncludesObserverCost:true,softwareWindowsLoadMatched:false,upstreamSubmitted:false}};
fs.writeFileSync('outputs/nss39-mainline-observations.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({saved:true,permanentDeployment:39,rollbackPasses:3,controllerSourceBindings:out.controller.sourceManifestEntries,windows:out.windows,realHighLoadABACompleted:false}));
