import{persistentSsh}from'./persistent-ssh.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import path from 'node:path';import {spawn,spawnSync} from 'node:child_process';
const root='work/v45-run-20261007095552-bdd974e0',session=crypto.randomBytes(8).toString('hex'),dir=root+'/load-'+new Date().toISOString().replace(/\D/g,'').slice(0,14)+'-'+session;fs.mkdirSync(dir);
const save=(n,v)=>fs.writeFileSync(dir+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const quote=x=>"'"+x.replaceAll("'","'\\''")+"'";
const channel=persistentSsh();try{
async function ssh(command,input){const p=await channel.exec(command,input);save('ssh-'+crypto.randomBytes(3).toString('hex')+'-private',p);assert.equal(p.code,0,p.stderr);return p.stdout;}
const priorLoad=JSON.parse(fs.readFileSync('work/nss149/load-latest-private.json'));const priorConfig=JSON.parse(fs.readFileSync(priorLoad.dir+'/client-config-private.json'));const priorRuntime=JSON.parse(fs.readFileSync('work/nss149/automatic-history-private.json'));assert.equal(priorRuntime.history.length,1);assert.equal(priorRuntime.history[0].closedAndRestored,true);assert.equal(priorRuntime.history[0].selected.udp.wan,1);assert.equal(priorConfig.udpPort,45818);assert.equal(priorConfig.serverAddress,'172.93.163.251');const seededUdpPort=59000+crypto.randomInt(800);assert.ok(Number.isInteger(seededUdpPort)&&seededUdpPort>=59000&&seededUdpPort<59800);const portCheck=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command','@{count=@(Get-NetUDPEndpoint -LocalPort '+seededUdpPort+' -ErrorAction SilentlyContinue).Count}|ConvertTo-Json -Compress'],{encoding:'utf8',windowsHide:true,timeout:8000});save('prior-owned-port-preflight-private',{code:portCheck.status,stdout:portCheck.stdout,stderr:portCheck.stderr});assert.equal(portCheck.status,0);assert.equal(JSON.parse(portCheck.stdout.replace(/^\uFEFF/,'')).count,0);save('prior-owned-port-seed-private',{originalProof:priorRuntime,priorConfig,linuxPbrStillSelectsWan:true,udpNotRotatedDuringMatching:true,oneFreshInitialOwnedUdpPort:true,historicalSourcePortNotReused:seededUdpPort!==priorConfig.udpSourcePort});
const unit='v45-run-20261007095552-bdd974e0-'+session;const checkpoint=await ssh('ss -H -lntup; cat /proc/sys/kernel/random/boot_id');save('server-checkpoint-private',{observedAt:new Date().toISOString(),before:checkpoint,ephemeralEndpointOnly:true});
assert.ok(!checkpoint.includes(':45817 ')&&!checkpoint.includes(':45818 '),'Endpoint ports already used');
const conf={token:crypto.randomBytes(32).toString('hex'),mbps:32,seconds:240,tcpPort:45817,udpPort:45818};const serverSource=fs.readFileSync(root+'/receiver.py','utf8')+'\n'+fs.readFileSync(root+'/server.py','utf8');
await ssh('systemd-run --unit='+unit+' --collect --property=RuntimeMaxSec=250 --property=KillMode=mixed /usr/bin/python3 -u -c '+quote(serverSource)+' '+quote(JSON.stringify(conf)));
const state=await ssh('systemctl show '+unit+' -p MainPID -p ActiveState -p RuntimeMaxUSec -p KillMode; ss -H -lntup');assert.ok(state.includes('ActiveState=active')&&state.includes('RuntimeMaxUSec=4min 10s')&&state.includes('KillMode=mixed'));assert.match(state,/MainPID=[1-9]\d*/);assert.ok(state.includes(':45817 ')&&state.includes(':45818 '));save('server-deadline-private',{unit,state,verifiedBeforeClientTraffic:true,independentOsDeadlineSeconds:250});
const config={...conf,seconds:180,pps:50,clientAddress:'192.168.237.207',serverAddress:'172.93.163.251',tcpSourcePort:57000+crypto.randomInt(800),udpSourcePort:seededUdpPort,session};
assert.equal(process.argv[2],'download');assert.equal(process.argv[3],undefined);config.bulkDirection='download';config.tcpRates={tcp:8,tcp2:8,tcp3:8,tcp4:8};config.tcpServerAddress=config.serverAddress;config.tcpPort=22;config.tcpSourcePort=0;
const configPath=path.resolve(dir+'/client-config-private.json');save('client-config-private',config);
const capSource=fs.readFileSync(root+'/discover-peer.py','utf8');let peers=[];
for(let attempt=1;attempt<=3;attempt++){
 let out='',err='',capFinished=false;
 const capDone=channel.exec('timeout -k 1 8 python3 -u -c '+quote(capSource)+' '+quote(conf.token),'',{milliseconds:17000,onStdout:s=>out+=s}).then(r=>{capFinished=true;err=r.stderr;return r;},e=>{capFinished=true;return{code:-1,stderr:String(e)};});
 const due=performance.now()+10000;while(!out.includes('NSS156_PASSIVE_READY')&&performance.now()<due&&!capFinished)await new Promise(r=>setTimeout(r,30));assert.ok(out.includes('NSS156_PASSIVE_READY'),'Passive capture not ready');
 const probe=spawnSync('python',['-u',root+'/probe-peer.py',JSON.stringify(config)],{encoding:'utf8',windowsHide:true,timeout:6000});save('probe-'+attempt+'-private',{code:probe.status,stdout:probe.stdout,stderr:probe.stderr});assert.equal(probe.status,0);
 const capResult=await capDone;save('peer-discovery-'+attempt+'-private',{code:capResult.code,stdout:out,stderr:err});assert.equal(capResult.code,0,err);
 const captured=JSON.parse(out.trim().split(/\r?\n/).at(-1));peers=[...new Set(captured.authenticatedRows.filter(r=>r.nonceVerified&&r.destinationAddress===config.serverAddress).map(r=>r.sourceAddress))];assert.ok(peers.length<=1,'Authenticated actual public peer ambiguous');
 if(peers.length===1)break;
}
assert.equal(peers.length,1,'Authenticated actual public peer absent after bounded same-port discovery');
const guardian=fs.readFileSync(root+'/endpoint-firewall-guardian.py','utf8');const owner=crypto.randomBytes(16).toString('hex');const partial={mode:'apply',owner,peers:{tcp:peers[0],udp:peers[0]}};
const cpCode=guardian+`\nc=${JSON.stringify(partial)}\nbefore=nft(['-j','list','ruleset'])\nchains=[x['chain'] for x in before['nftables'] if 'chain' in x and x['chain']['family']=='inet' and x['chain']['table']=='sub2api' and x['chain']['name']=='input']\nassert len(chains)==1 and chains[0]['hook']=='input' and chains[0]['policy']=='drop'\nassert not any(x.get('rule',{}).get('comment','').startswith('nss14-') for x in before['nftables'])\nnft(['-c','-j','-f','-'],{'nftables':allow_commands(c)})\nwith open('/proc/sys/kernel/random/boot_id') as f:boot=f.read().strip()\nprint(json.dumps({'before':before,'boot':boot,'canonicalSha256':hashlib.sha256(canonical(before).encode()).hexdigest(),'dryRunPassed':True}))\n`;
const cpRaw=await ssh('python3 -B -E -s -u -',cpCode);save('firewall-checkpoint-private',JSON.parse(cpRaw));const cp=JSON.parse(cpRaw);assert.ok(cp.dryRunPassed);const settings={...partial,boot:cp.boot,baselineCanonicalSha256:cp.canonicalSha256};save('firewall-settings-private',settings);save('firewall-checkpoint-verified',{checkpointSha256:hash(cpRaw),sourceSha256:hash(guardian),expirySeconds:180,exactTwoRules:true,peerAuthNonceVerified:true});
const raw=await ssh('python3 -B -E -s -u -',guardian+'\nrun('+JSON.stringify(settings)+')\n');const receipt=JSON.parse(raw);save('firewall-receipt-private',receipt);assert.ok(receipt.applied&&receipt.beforeWriteIndependentGuardianVerified);assert.equal(receipt.rules.length,2);
const check=guardian+`\nc=${JSON.stringify(settings)}\npid=${receipt.identity.pid}\ni=identity(pid)\nassert i['start']==${JSON.stringify(receipt.identity.start)} and i['pgrp']==pid and i['session']==pid and i['ppid']==1\nfds={x:os.readlink('/proc/'+str(pid)+'/fd/'+x) for x in os.listdir('/proc/'+str(pid)+'/fd')}\nassert fds=={'0':'/dev/null','1':'/dev/null','2':'/dev/null'}\nowned=[x['rule'] for x in nft(['-j','list','ruleset'])['nftables'] if x.get('rule',{}).get('comment','').startswith('nss14-'+c['owner']+'-')]\nassert len(owned)==2\nprint(json.dumps({'detachedIdentityVerified':True,'onlyNullStandardFds':True,'remainingSeconds':${receipt.deadline}-time.monotonic()}))\n`;
const detached=JSON.parse(await ssh('python3 -B -E -s -u -',check));save('firewall-detached-private',detached);assert.ok(detached.remainingSeconds>130&&detached.detachedIdentityVerified);
const literal=x=>"'"+x.replaceAll("'","''")+"'";const client=path.resolve(root+'/native-client.mjs'),guard=path.resolve(root+'/client-watchdog.ps1'),binding=path.resolve(dir+'/client-binding-private.json');
const ps=`$ErrorActionPreference='Stop';$taskExe=(Get-Command python).Source;$taskClient=Start-Process -WindowStyle Hidden -FilePath $taskExe -ArgumentList @('-u',('"'+${literal(client)}+'"'),('"'+${literal(configPath)}+'"')) -RedirectStandardOutput ${literal(path.resolve(dir+'/client-stdout-private.txt'))} -RedirectStandardError ${literal(path.resolve(dir+'/client-stderr-private.txt'))} -PassThru;$taskInfo=@{clientPid=$taskClient.Id;clientStart=$taskClient.StartTime.ToUniversalTime().ToString('o');clientExe=$taskExe;scriptPath=${literal(client)};configPath=${literal(configPath)};guardResult=${literal(path.resolve(dir+'/guard-result-private.json'))}};$taskInfo|ConvertTo-Json|Set-Content -LiteralPath ${literal(binding)} -Encoding UTF8;$taskGuard=Start-Process -WindowStyle Hidden -FilePath powershell.exe -ArgumentList @('-NoProfile','-NonInteractive','-File',('"'+${literal(guard)}+'"'),'-BindingPath',('"'+${literal(binding)}+'"')) -PassThru;@{clientPid=$taskClient.Id;guardPid=$taskGuard.Id;guardStart=$taskGuard.StartTime.ToUniversalTime().ToString('o')}|ConvertTo-Json -Compress`;
const launch=ps.replace("$taskExe=(Get-Command python).Source",'$taskExe='+literal(process.execPath)).replace("@('-u',","@(");
const p=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',launch],{encoding:'utf8',windowsHide:true,timeout:10000});save('client-launch-private',{code:p.status,stdout:p.stdout,stderr:p.stderr,error:p.error?String(p.error):null,signal:p.signal});assert.equal(p.status,0,p.stderr);const started=JSON.parse(p.stdout);save('launch-receipt',{...started,unit,dir,configPath,serverIndependentDeadlineSeconds:250,clientIndependentDeadlineSeconds:210});fs.writeFileSync(root+'/load-latest-private.json',JSON.stringify({dir,...started,unit},null,2)+'\n');console.log(JSON.stringify({started:true,dir,clientPid:started.clientPid,guardPid:started.guardPid,tcpTargetMbps:config.mbps,udpPps:50,serverDeadlineSeconds:250,clientDeadlineSeconds:210,temporaryFirewallRules:2,firewallDeadlineSeconds:180,firewallDetachedVerified:true,bulkTransport:'owned native OpenSSH download'}));

}finally{channel.close();}
