import fs from'node:fs';import crypto from'node:crypto';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import{verifyPreparation as inherited}from'../v24-fiveflow/session-binding.mjs';
const root='work/v27-raw',old=inherited(),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
for(const name of ['classifier.lua','classified-tags.lua','fast-path.lua','wan-scope.lua','qos-physical.lua','tag-normalizer.lua','module-stage-guardian.lua','pack-json.mjs','compact-post-guards.mjs','match-controlled.mjs','payload.mjs','module-stage.mjs','epoch-driver.mjs','current-audit-diagnostic.mjs','class-leaf-map.mjs','wan-tag-plan.mjs','parse-ecm.mjs','client-watchdog.ps1','endpoint-firewall-guardian.py']){
 const s=fs.readFileSync(root+'/'+name,'utf8').replaceAll('work/v27-raw','work/v24-fiveflow').replaceAll('work\\/v27-raw\\/','work\\/v24-fiveflow\\/').replaceAll('v27-raw-','v24-fiveflow-');assert.equal(s,fs.readFileSync('work/v24-fiveflow/'+name,'utf8'),name+' changed outside the raw fixture');
}
const results={};for(const[name,exe,args]of[['server','C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-X','utf8',root+'/model-raw-server.py']],['policy',process.execPath,[root+'/model-raw-policy.mjs']]]){const p=spawnSync(exe,args,{encoding:'utf8',windowsHide:true,timeout:15000});fs.writeFileSync(root+'/raw-'+name+'-model-process-private.json',JSON.stringify({code:p.status,stdout:p.stdout,stderr:p.stderr},null,2)+'\n',{flag:'wx'});assert.equal(p.status,0,p.stderr);results[name]=JSON.parse(p.stdout);assert.ok(results[name].passed);}
const manifest={};for(const name of fs.readdirSync(root))if(/\.(mjs|lua|py|ps1)$/.test(name)&&!name.includes('private')){const f=root+'/'+name;manifest[f]=hash(fs.readFileSync(f));if(name.endsWith('.mjs')){const p=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}}
for(const name of ['native-qualified.json','normalizer-qualified.json','qos-native-qualified.json'])manifest[root+'/'+name]=hash(fs.readFileSync(root+'/'+name));
fs.writeFileSync(root+'/raw-model-qualified.json',JSON.stringify({passed:true,server:results.server,policy:results.policy,onlyOwnFixtureTransportChanged:true,productionWrites:false},null,2)+'\n',{flag:'wx'});manifest[root+'/raw-model-qualified.json']=hash(fs.readFileSync(root+'/raw-model-qualified.json'));
const q={passed:true,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,nativeAndQosByteEquivalent:true,fiveSlotHardwareExecuted:false,wholeFactoryModeled:false,rawSenderLocalChecks:results.server.checks,rawPolicyChecks:results.policy.checks,clientSeconds:180,ownerSeconds:180,kernelSessionSeconds:90,kernelMaximumSeconds:120,sourceFreshnessSeconds:6,phaseSeconds:60,totalOfferedMbps:32,combinedCreditBytes:65536,endpointOsSeconds:250,endpointFirewallSeconds:180,priorSshFailuresPreserved:true};
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,bindings:q.inheritedBindings+Object.keys(manifest).length,serverChecks:results.server.checks,policyChecks:results.policy.checks,nativeAndQosUnchanged:true,hardwareAcceptance:false}));
