import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import net from'node:net';import dgram from'node:dgram';import{slots,sourcePort,validateReady}from'./raw-policy.mjs';
const configPath=path.resolve(process.argv[2]),c=JSON.parse(fs.readFileSync(configPath)),dir=path.dirname(configPath);
assert.equal(c.mbps,32);assert.equal(c.seconds,180);assert.equal(c.pps,50);assert.equal(c.bulkDirection,'download');assert.equal(c.tcpPort,45817);assert.equal(c.tcpServerAddress,'172.93.163.251');assert.equal(c.clientAddress,'192.168.237.207');assert.deepEqual(c.tcpRates,{tcp:8,tcp2:8,tcp3:8,tcp4:8});
assert.equal(new Set(slots.flatMap(s=>Array.from({length:8},(_,i)=>sourcePort(c,s,i+1)))).size,32);
const token=Buffer.from(c.token,'hex');assert.equal(token.length,32);const began=performance.now(),stats={pid:process.pid,session:c.session,startedAt:Date.now()/1000,tcpBytes:0,udpSourcePort:c.udpSourcePort,udpSent:0,udpReceived:0,tcpPort:45817,errors:[],tcpChildren:slots.map(slot=>({slot,attempt:0,bytes:0,connected:false})),bulkTransport:'owned nonce-authenticated raw TCP download',tcpMetric:'client-observed raw payload bytes',pacerDebtCatchupAllowed:false,maximumPacerCreditBytes:65536,perTcpMbps:c.tcpRates,maximumCombinedPacerCreditBytes:65536};
const udpOut=fs.createWriteStream(dir+'/udp-samples-private.jsonl'),loadOut=fs.createWriteStream(dir+'/load-samples-private.jsonl'),seen=new Set(),sockets=new Map(),rotating=new Set();let ended=false,seq=0;
function stamp(){if(ended)return;stats.tcpConnected=stats.tcpChildren.every(x=>x.connected);const v={...stats,at:Date.now()/1000,elapsed:(performance.now()-began)/1000};fs.writeFileSync(dir+'/status-private.json.new',JSON.stringify(v));try{fs.renameSync(dir+'/status-private.json.new',dir+'/status-private.json')}catch(e){if(e.code!=='EPERM'&&e.code!=='EBUSY')throw e;stats.statusPublicationDeferrals=(stats.statusPublicationDeferrals??0)+1;}loadOut.write(JSON.stringify(v)+'\n');}
function finish(error){if(ended)return;ended=true;for(const t of timers)clearInterval(t);clearTimeout(hard);if(error)stats.errors.push(String(error));for(const s of sockets.values())s.destroy();sock.close();fs.writeFileSync(dir+'/result-private.json',JSON.stringify({...stats,seconds:(performance.now()-began)/1000,finishedAt:Date.now()/1000},null,2));udpOut.end();loadOut.end();setTimeout(()=>process.exit(stats.errors.length?1:0),80);}
async function startTcp(slot,attempt){
 const s=stats.tcpChildren.find(x=>x.slot===slot);assert.ok(s&&!rotating.has(slot)&&attempt===s.attempt+1&&attempt<=8);rotating.add(slot);s.connected=false;const old=sockets.get(slot);
 if(old&&!old.destroyed){await new Promise((resolve,reject)=>{const t=setTimeout(()=>{old.destroy();reject(Error('Old owned raw sender did not close before replacement'))},2000);old.once('close',()=>{clearTimeout(t);resolve()});old.end('STOP\n');});}
 s.attempt=attempt;s.sourcePort=sourcePort(c,slot,attempt);s.ownerPid=process.pid;s.executable=process.execPath;s.spawnedAt=new Date().toISOString();
 const socket=net.connect({host:c.tcpServerAddress,port:45817,localAddress:c.clientAddress,localPort:s.sourcePort});sockets.set(slot,socket);socket.setNoDelay(true);let ready=false,pending=Buffer.alloc(0),resolveReady,rejectReady;
 const first=new Promise((resolve,reject)=>{resolveReady=resolve;rejectReady=reject}),timer=setTimeout(()=>rejectReady(Error('Owned raw first-byte deadline '+slot)),8000);
 socket.on('connect',()=>socket.write(Buffer.concat([token,Buffer.from([slots.indexOf(slot)])])));
 socket.on('data',b=>{if(ended||socket!==sockets.get(slot))return;try{if(!ready){pending=Buffer.concat([pending,b]);const at=pending.indexOf(10);if(at<0){assert.ok(pending.length<=512);return;}assert.ok(at<=512);validateReady(JSON.parse(pending.subarray(0,at).toString()),slot);ready=true;b=pending.subarray(at+1);pending=Buffer.alloc(0);}
  if(b.length){s.connected=true;s.bytes+=b.length;stats.tcpBytes+=b.length;clearTimeout(timer);resolveReady();if(stats.tcpBytes>1073741824)finish('Combined delivery byte ceiling');}
 }catch(e){rejectReady(e);finish(e);}});
 socket.on('error',e=>{rejectReady(e);if(!ended&&socket===sockets.get(slot))finish(e)});
 socket.on('close',()=>{rejectReady(Error('Owned raw socket closed before payload '+slot));if(!ended&&socket===sockets.get(slot)&&!rotating.has(slot))finish('Owned raw sender closed unexpectedly '+slot);});
 try{await first;}finally{clearTimeout(timer);rotating.delete(slot);stamp();}
}
const sock=dgram.createSocket('udp4');sock.on('error',finish);sock.on('message',b=>{if(b.length!==128||!b.subarray(0,32).equals(token))return;const n=Number(b.readBigUInt64BE(32));if(seen.has(n))return;seen.add(n);stats.udpReceived++;udpOut.write(JSON.stringify({event:'reply',sequence:n,at:Date.now()/1000,sourcePort:c.udpSourcePort,rttMs:performance.now()-b.readDoubleBE(40)})+'\n');});sock.bind(c.udpSourcePort,c.clientAddress,()=>sock.connect(c.udpPort,c.serverAddress));
const timers=[setInterval(()=>{if(ended)return;try{const p=dir+'/control.json';if(fs.existsSync(p)){const x=JSON.parse(fs.readFileSync(p));assert.equal(x.session,c.session);if(x.stop){finish();return;}assert.equal(x.udpSourcePort??c.udpSourcePort,c.udpSourcePort);if(x.rotateTcp){assert.ok(slots.includes(x.rotateTcp.slot));const s=stats.tcpChildren.find(y=>y.slot===x.rotateTcp.slot);if(x.rotateTcp.attempt>s.attempt&&!rotating.has(s.slot))startTcp(s.slot,x.rotateTcp.attempt).catch(finish);}}
 const b=Buffer.alloc(128);token.copy(b);b.writeBigUInt64BE(BigInt(seq),32);b.writeDoubleBE(performance.now(),40);sock.send(b,e=>{if(e&&!ended)finish(e)});stats.udpSent++;udpOut.write(JSON.stringify({event:'sent',sequence:seq++,at:Date.now()/1000,sourcePort:c.udpSourcePort})+'\n');}catch(e){finish(e);}},20),setInterval(stamp,250)];const hard=setTimeout(()=>finish(),180000);stamp();try{for(const slot of slots)await startTcp(slot,1);}catch(e){finish(e);}
