"""Render observations without inventing missing accelerated/client phases."""
import html,json
from pathlib import Path
root=Path(__file__).resolve().parents[2]
data=json.loads((root/'outputs/nss52-mainline-observations.json').read_text(encoding='utf-8'))
e=lambda s:html.escape(str(s))
failures={'selected-class-not-admitted':'选中连接已不在可接纳分类中；拒绝帧的具体槽位未记录，不能倒推原因','locked-source-age-6.47s':'完整持锁审核：来源 6.47 秒，超过原 6 秒期限','historical-service-pid-baseline':'运行中 sing-box core/guard 的 PID 与安装时历史基线不同','core-sleep-deadline':'无法在原 200 ms 条件内确认新的 core guard sleep 子进程'}
attemptRows=''.join(f"<tr><td>{a['attempt']} · {e(a['entryRound'])}</td><td>{e(failures[a['failure']])}</td><td>{'有 checkpoint / 单 WAN 临时暂存' if a['productionTemporaryStageOccurred'] else '写前拒绝'}</td><td>{'软件 A，11 帧' if a['completedPhases'] else '无测量阶段'}</td><td>未开放</td><td>{'精确恢复＋独立清理＋完整审核通过' if a.get('rollbackPassed') else '无暂存需恢复'}</td></tr>"for a in data['attempts'])
softwareRows=''.join(f"<tr><td>第 {i+4} 次 · WAN{p['wan']}</td><td>{p['seconds']:.2f} s / {p['samples']}</td><td>{p['interfaces']['lan4']['txMbps']:.2f}</td><td>{p['interfaces']['rpwan5']['rxMbps']:.2f}</td><td>{p['interfaces']['lan4']['txPps']:,.0f}</td><td>{p['busyPercent']:.2f}%</td><td>{p['softirqPercent']:.2f}%</td><td>+{p['timeSqueeze']}</td></tr>"for i,p in enumerate(data['partialSoftwareMeasurements']['cases']))
hudRows=''
for i,p in enumerate(data['clientSoftwareMeasurements']['cases']):
    frames=p['frames'];central=sum(f['central']for f in frames)
    def span(field):
        values=[f[field]for f in frames];return str(min(values))if min(values)==max(values)else f'{min(values)}–{max(values)}'
    hudRows+=f"<tr><td>第 {i+4} 次软件 A</td><td>{len(frames)} / 中央 {central}</td><td>{span('pingMs')} ms</td><td>{span('jitterDownMs')} ms</td><td>{span('lossDownPercent')}%</td><td>{span('missDownPercent')}%</td><td>没有 NSS B</td></tr>"
traceRows=''.join(f"<tr><td>{e(g['name'])}</td><td>{g['passedAttempts']} / {len(g['attempts'])}</td><td>{max(a['maximumScanSeconds'] for a in g['attempts'])*1000:.0f} ms</td><td>{max(a['maximumConsumerSeconds'] for a in g['attempts'])*1000:.0f} ms</td></tr>"for g in data['readonlyProfiling']['groups'])
p=data['phase52UninstalledCandidate'];bench=p['parentParserBenchSeconds'];reduction=(1-bench['new']/bench['old'])*100
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSS52：高负载准入延迟定位与恢复记录</title>
<style>body{margin:0;background:#f4f6f8;color:#233346;font:16px/1.8 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1160px;margin:32px auto;padding:0 24px 48px}h1{font-size:30px;line-height:1.4}h2{font-size:21px;margin:30px 0 12px}.card{background:#fff;border:1px solid #dbe3ec;border-radius:12px;padding:22px;margin:18px 0}.note{border-left:5px solid #b98221}.ok{border-left:5px solid #237e6f}.small{font-size:14px;color:#5a6d82}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:14px}td,th{border-bottom:1px solid #e2e7ed;text-align:left;padding:10px;vertical-align:top}th{background:#edf2f7}a{color:#235f9b}code{overflow-wrap:anywhere;color:#285482}</style>
<main><p class="small">Athena AX6600 · NSS50–NSS52 · 2026-10-04 · 单 WAN 主线</p><h1>高负载入口延迟已定位，完整 NSS 客户端对照仍待完成</h1>
<div class="card note"><strong>本轮没有开放 ECM，也没有完成新的 software → NSS → software。</strong><p>六次真实应用连接尝试中，两次只有软件 A 阶段完成，其余在审核或初始分类阶段拒绝。四次进行了有 checkpoint 和独立 45 秒回滚的单 WAN 临时暂存，全部恢复并通过原完整保护审核；另外两次在任何暂存前拒绝。</p><p>NSS49 既有功能证明保持：真实 CS2 UDP / Steam TCP 已进入 RT / bulk leaf，ECM 0→2→0，mark/NAT/WAN affinity 与恢复正确。本轮新增的是延迟根因、候选修复和软件阶段客户端记录，不能将它们写成新的 NSS 或 CPU / 真人游戏收益。</p></div>
<h2>实际执行与恢复</h2><div class="card scroll"><table><thead><tr><th>次序</th><th>实际失败</th><th>现网改动</th><th>观测</th><th>ECM</th><th>恢复</th></tr></thead><tbody>ATTEMPTS</tbody></table></div>
<p class="small">选中分类拒绝时只留下通用断言，缺少该帧的具体 TCP / UDP 分类理由。后来连接退出或 Steam 完成，不能用于重构此前失败的唯一原因。没有清空 conntrack、重建十个生产 qdisc、改五路认证或放宽原来源 / 学习 / owner 期限。</p>
<h2>两段真实软件负载记录</h2><div class="card scroll"><table><thead><tr><th>阶段</th><th>秒 / 帧</th><th>LAN4 Mbps</th><th>WAN5 Mbps</th><th>LAN4 pps</th><th>busy</th><th>softirq</th><th>time_squeeze</th></tr></thead><tbody>SOFTWARE</tbody></table><p class="small">两段均 ECM 关闭全零、softnet drop +0。软件转发和 CAKE fallback 工作，但共同实验的 LAN4 NSS 队列树已暂存，因此不是未暂存的原始基线。负载不同，不做两次之间的因果比较。没有 B / A2 速率与 leaf 计数，也没有本轮有效 CAKE tin 对照。</p></div>
<h2>客户端 HUD 已真正取得</h2><div class="card scroll"><table><thead><tr><th>阶段</th><th>实际截图数</th><th>ping</th><th>下行 jitter</th><th>下行 loss</th><th>下行 Miss</th><th>比较条件</th></tr></thead><tbody>HUD</tbody></table><p>真实 Sky 截图和完整在线死亡竞赛场景逐帧检查，使用路由器 / PC 往返时钟锚点映射到软件 A。此轮由助手进入服务器，客户端闲置 / 死亡 / 重生，没有真人操控或主观体验。原始截图、连接身份和进程信息仅留私有工作区。</p><p class="small">HUD 使用滚动或峰值指标，中央截图仍可能包含先前历史；Miss 与原始丢包分别记录。指标含义见 <a href="https://help.steampowered.com/en/faqs/view/5E6F-5B36-5485-F6B9">Valve 的 Source 2 网络指标说明</a>。没有 NSS B 不能判断 QoS 改善，未显示数据不填零。</p></div>
<h2>两个明确的控制器问题</h2><div class="card"><p><strong>历史 PID 基线误拒绝：</strong>写前只读状态中 sing-box core / guard 健康、命令完全相同，但 PID 与 NSS47 安装时不同。NSS50 仅允许实验开始前这两项健康 PID 变化，随即固定本次服务实例；任何实验期间变化仍拒绝。24 项本地边界案例、新 128 项输入绑定、目标原完整只读审核通过。没有推断服务为何重启，也没有为了通过而重启它们。</p><p><strong>进程发现成本超过学习前窗口：</strong>旧 helper 在目标子进程退出后重新读取全机进程的 stat / argv / wchan。真实下载约 350 Mbps 的只读 profiler 中最大一次回调 740 ms，三个尝试均错过原 200 ms 条件。暂停下载后同一路径 3/3 通过。这证明高负载下的读取延迟会阻塞控制器，不能解释成 NSS 驱动不支持加速。</p></div>
<div class="card scroll"><table><thead><tr><th>只读观察</th><th>通过 / 尝试</th><th>最长回调</th><th>最长分类读取</th></tr></thead><tbody>TRACES</tbody></table><p class="small">执行原完整 candidates / readContext / consumer 检查；仅省略未使用的 adapter 函数和 profiler 中的整行注释以适配传输尺寸。每轮最多约 7 秒，ECM 全程关闭，core guard 未停止 / 修改 / 发信号。不同窗口未证明 offered load 完全相同。</p></div>
<h2>候选修复达到哪一步</h2><div class="card"><p><strong>NSS51：</strong>只枚举并完整核验固定 guard 的直接子进程；初始全局发现、PID / start / argv / parent / wchan 核验、200 ms 和绝对出生时间条件保持。22 项进程模型及两次真实只读阶段通过，新入口完整绑定 140 项输入并通过目标审核。但真实下载只读观察仅 1/3 通过，不能说已稳定修复；随后真实控制器仍在选中分类阶段拒绝，没有到 NSS B。</p><p><strong>NSS52：</strong>进一步只解析无关进程的父进程字段，避免每行拆分全部 stat 字段。目标身份仍做原完整检查，等待源码字节一致。原 22 项模型重放，加 12 项父进程解析差分，合计 34 项检查及两次真实轻载只读阶段通过。纯解析 10,000 遍：BENCH；属于解析 microbenchmark，不是整机转发收益。</p><p><strong>NSS52 未安装、未绑定生产入口、未通过新的高负载验证。</strong>这项候选和全部旧失败分别冻结，不覆盖 NSS49 / NSS51 的原始证明。没有放宽 TTL、增加流数、加大 20 Mbps 预算或修改内核 / driver / firmware。</p></div>
<h2>当前终态与下一步</h2><div class="card ok"><p>DOOM Eternal 经用户授权作为下载负载，79.2 GB 下载已在 17:14 完成，当前网络 / 磁盘读数为零；没有购买或启动 DOOM，也没有为了续测卸载重装。CS2 已退出测试服务器，三项 HUD 显示恢复到“条件较差时”。</p><p>17:30 原完整持锁保护审核通过；常驻仍 NSS47 地址缓存＋NSS46 三项可靠性修复，同一 worker / guardian / 启动身份连续。ECM 停止且全零，无根事务、NSS 暂存目录、实验状态节点、gate 或 qdisc 实验模块。它不是完整高负载故障恢复 / 长期稳定证明。</p><p>下一步只解决这条主线：在下一次真实下载窗确认高负载进程发现稳定，补失败帧具体分类诊断，保持同一 TCP＋UDP 连接，然后一次完成软件 → NSS → 软件和客户端 HUD。已有分类器安装与 99 / 13 项旧资格不重复准备；第二 WAN、共享预算、Wi-Fi、autorate 继续等待。</p></div>
<h2>源码问题 backlog</h2><div class="card"><p>本地记录 service PID 历史基线与进程发现耗时两个问题，包含最小复现、文件位置和修改前后观察。它们首先属于当前私有测试控制器；尚未证明为 qca-nss-ecm 或 NSS 上游缺陷，不直接提交 Issue / PR。</p><p><a href="https://github.com/ZyPulse-zy/athena-nss-mainline">私有主线仓库</a> · <a href="nss52-mainline-observations.json">脱敏结构化观测</a> · <a href="nss49-mainline-report.html">NSS49 历史功能证明</a></p></div>
<p class="small">本报告源和引用经程序检查；浏览器渲染尚未验收。源码镜像、输入绑定资格、目标模型、真实软件负载、NSS fast path 与真人体验分别记录。</p></main></html>'''
for key,value in [('ATTEMPTS',attemptRows),('SOFTWARE',softwareRows),('HUD',hudRows),('TRACES',traceRows),('BENCH',f"{bench['old']:.6f} → {bench['new']:.6f} 秒（减少 {reduction:.2f}%）")]:page=page.replace(key,value)
with (root/'outputs/nss52-mainline-report.html').open('x',encoding='utf-8',newline='\n')as f:f.write(page)
for round in ['nss50','nss51']:
    small=f'<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>{round.upper()} 记录</title><body style="font:17px/1.8 system-ui;padding:40px"><h1>{round.upper()}：原失败与恢复已保留</h1><p>本轮没有打开 ECM，没有完整 NSS A/B/A2。最新汇总包含软件客户端指标、高负载读取根因和未安装候选。</p><p><a href="nss52-mainline-report.html">打开 NSS50–NSS52 完整报告</a> · <a href="{round}-mainline-observations.json">本轮脱敏观测</a></p></body></html>'
    with(root/f'outputs/{round}-mainline-report.html').open('x',encoding='utf-8',newline='\n')as f:f.write(small)
for expected in ['本轮没有开放 ECM','1/3 通过','未安装、未绑定生产入口','software → NSS → software','740 ms']:assert expected in page
assert all((root/'outputs'/p).is_file()for p in ['nss49-mainline-report.html','nss52-mainline-observations.json'])
data['reportVerification']['sourceValidated']=True
(root/'outputs/nss52-mainline-observations.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
print(json.dumps({'created':['nss50-mainline-report.html','nss51-mainline-report.html','nss52-mainline-report.html'],'sourceValidated':True,'browserRendered':False}))
