import assert from 'node:assert/strict';
import crypto from 'node:crypto';
export const ID='nss12-forwardtag1-20261001',RENDER_ID='nss12-forwardrender1-20261001';
export const TABLE='rp_nss12_forwardtag1_20261001',LAB='/root/router-project/experiments/'+ID;
export const GROUP_SHA='2854059fc58fc304cee00bf2467a2d1725f836828c99aa3b8c6e53b4b3dc73e2';
export const TAG_UP=0,TAG_DOWN=0x8f060000,OFFLINE_ONLY=true;
export const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),json=x=>JSON.stringify(x,null,2)+'\n';
export function canonical(x){if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';return JSON.stringify(x);}
const uint=(n,max=0xffffffff)=>Number.isSafeInteger(n)&&n>=0&&n<=max;
export function ip(s){assert.equal(typeof s,'string');const a=s.split('.');assert.equal(a.length,4);assert.ok(a.every(v=>/^(0|[1-9]\d{0,2})$/.test(v)&&Number(v)<=255));return s;}
export function flow(f){assert.equal(f.protocol,17);assert.equal(f.zone,0);assert.ok(uint(f.connectionId)&&f.connectionId>0);assert.ok(uint(f.mark));assert.ok([1,2,3,4,5].includes(f.wan));assert.equal((f.mark&0xff0000)>>>16,f.wan);for(const t of [f.original,f.reply]){ip(t.src);ip(t.dst);for(const p of [t.sport,t.dport])assert.ok(uint(p,65535)&&p>0);}assert.equal(f.original.dst,f.reply.src);assert.equal(f.original.dport,f.reply.sport);return f;}
export function producer(p){assert.equal(p.source,'local-synthetic-udp');assert.equal(p.synthetic,true);assert.equal(p.automaticRT,false);assert.equal(p.processName,'python');assert.ok(uint(p.pid,0x7fffffff)&&p.pid>0);assert.ok(Number.isFinite(Date.parse(p.startTimeUtc)));assert.ok(Array.isArray(p.argv)&&p.argv.length>=2&&p.argv.every(x=>typeof x==='string'&&!x.includes('\0')));assert.equal(typeof p.commandLine,'string');assert.ok(p.commandLine.length>0);assert.ok(p.argv[1].replaceAll('\\','/').endsWith('/windows-client.py'));assert.ok(uint(p.port,65535)&&p.port>0);for(const k of ['windows-client.py','traffic.py'])assert.match(p.sourceHashes[k],/^[a-f0-9]{64}$/);assert.deepEqual(Object.keys(p.sourceHashes).sort(),['traffic.py','windows-client.py']);assert.match(p.configSha256,/^[a-f0-9]{64}$/);assert.match(p.interpreterSha256,/^[a-f0-9]{64}$/);return p;}
export function software(s){assert.equal(s.ecm.stop4,1);assert.equal(s.ecm.stop6,1);for(const k of ['db','accel4','accel6','pending4','pending6','decel4','decel6'])assert.equal(s.ecm[k],0);assert.equal(s.kernel,'6.18.44');assert.equal(s.arch,'aarch64');assert.doesNotMatch(s.modules,/^(?:rp_ecm_gate\S*|rp_ct_priority_observer|qca_nss_qdisc)\s/m);}
export function fresh(s,f,p,boot,deadline){software(s);flow(f);producer(p);assert.equal(s.boot,boot);assert.ok(Number.isFinite(s.uptime)&&s.uptime<deadline);assert.ok(s.uptime>=s.ctObservedAtUptime&&s.uptime-s.ctObservedAtUptime<=2);assert.equal(s.queryZone,0);assert.equal(s.queryExitCode,0);assert.deepEqual(s.selected,f);assert.deepEqual(s.producer,p);assert.equal(s.uniqueUdpOwner,true);assert.equal(p.port,f.original.sport);assert.ok(s.producerAgeSeconds>=0&&s.producerAgeSeconds<=2);assert.equal(s.route.length,1);assert.equal(s.route[0].dev,'rpwan'+f.wan);assert.equal(Number(s.route[0].table),100+f.wan);assert.equal(s.route[0].prefsrc??s.route[0].src,f.reply.dst);assert.ok(s.wanAddresses.includes(f.reply.dst));return true;}
export function observation(s,f,p,boot,deadline){fresh(s,f,p,boot,deadline);const end=Math.min(s.uptime+6,s.uptime+6-s.producerAgeSeconds,deadline);assert.ok(end>s.uptime+2);return {version:1,id:ID,boot,ownerDeadline:deadline,source:'local-synthetic-udp-sideband',producer:p,selected:f,row:{observedAtUptime:s.uptime,validUntilUptime:end},envelope:{observedAtUptime:s.uptime,validUntilUptime:end},lease:{enabled:true,validUntilUptime:end,ownerDeadline:deadline},automaticRT:false,nssPermit:false,heldPointer:false,kernelAbsoluteDeadline:false};}
export function observationFresh(o,t,boot,deadline){assert.equal(o.id,ID);assert.equal(o.boot,boot);assert.equal(o.ownerDeadline,deadline);assert.equal(o.lease.enabled,true);assert.equal(o.lease.ownerDeadline,deadline);assert.equal(o.automaticRT,false);assert.equal(o.nssPermit,false);assert.equal(o.heldPointer,false);assert.equal(o.kernelAbsoluteDeadline,false);assert.ok(t>=o.row.observedAtUptime&&t>=o.envelope.observedAtUptime&&t<Math.min(o.row.validUntilUptime,o.envelope.validUntilUptime,o.lease.validUntilUptime,deadline));producer(o.producer);flow(o.selected);}
export const ct=(key,dir)=>({ct:{key,...(dir?{dir}:{})}}),meta=key=>({meta:{key}}),payload=(protocol,field)=>({payload:{protocol,field}}),match=(left,right,op='==')=>({match:{op,left,right}});
export function normalizeMatch(e){const alias={nfproto:{ipv4:2},l4proto:{udp:17},protocol:{udp:17},state:{established:2},direction:{original:0,reply:1}};const k=x=>x?.meta?.key??x?.ct?.key;const val=(x,key)=>typeof x==='string'&&Object.hasOwn(alias[key]??{},x)?alias[key][x]:x;const x=structuredClone(e);if(x.match)x.match.right=val(x.match.right,k(x.match.left));return x;}
export function normalizeRule(r){assert.match(r.comment,new RegExp('^'+ID+':[a-f0-9]{64}:'));const name=r.comment.split(':').at(-1);let e=r.expr.map(x=>{assert.equal(Object.keys(x).length,1);assert.ok(['match','jump','return','counter','mangle'].includes(Object.keys(x)[0]),'Unknown statement');if(x.counter){assert.deepEqual(Object.keys(x.counter).sort(),['bytes','packets']);for(const n of Object.values(x.counter))assert.ok(uint(n,Number.MAX_SAFE_INTEGER));return {counter:{packets:0,bytes:0}};}if(x.mangle){assert.deepEqual(x.mangle.key,meta('priority'));assert.ok([TAG_UP,TAG_DOWN].includes(x.mangle.value),'Only full32bit approved priority setter');}return normalizeMatch(x);});
 const n=name.match(/^(w|f|p)_(up|down)_neighborhood$/);if(n){const base=n[1]==='w'?'writer':n[1]==='f'?'forward_getter':'post_getter';assert.equal(r.chain,base);assert.ok(e.length===5||e.length===7);const prefix=[match(meta('nfproto'),2),match(meta('l4proto'),17)];if(e.length===7){assert.deepEqual(e.slice(0,2),prefix);e=e.slice(2);}for(const[i,pr,key]of [[0,'ip','saddr'],[1,'ip','daddr'],[2,'udp','sport'],[3,'udp','dport']]){const value=e[i]?.match?.right;assert.deepEqual(e[i],match(payload(pr,key),value));if(pr==='ip')ip(value);else assert.ok(uint(value,65535)&&value>0);}assert.deepEqual(e[4],{jump:{target:n[1]+'_'+n[2]}});e=[...prefix,...e];}
 const s=name.match(/^(w|f|p)_(up|down)_reject_(unconfirmed|dying)$/);if(s){assert.equal(r.chain,s[1]+'_'+s[2]);assert.equal(e.length,3);const mask=s[3]==='unconfirmed'?8:512,op=s[3]==='unconfirmed'?'==':'!=',native=s[3]==='unconfirmed'?'!':'in';const planned=match({'&':[ct('status'),mask]},0,op),folded=match(ct('status'),mask,native);assert.ok(canonical(e[0])===canonical(planned)||canonical(e[0])===canonical(folded));assert.deepEqual(e[1],{counter:{packets:0,bytes:0}});assert.deepEqual(e[2],{return:null});e[0]=planned;}
 return e;}
export function rules(selected,token){const f=flow(selected);assert.match(token,/^[a-f0-9]{64}$/);const objects=[{table:{family:'inet',name:TABLE}}];const counter={counter:{packets:0,bytes:0}},ret={return:null};const chain=(name,hook,prio)=>objects.push({chain:{family:'inet',table:TABLE,name,...(hook?{type:'filter',hook,prio,policy:'accept'}:{})}});const rule=(chain,name,expr)=>objects.push({rule:{family:'inet',table:TABLE,chain,comment:ID+':'+token+':'+name,expr:structuredClone(expr)}});
 for(const[stage,base,hook,prio]of [['w','writer','forward',-150],['f','forward_getter','forward',-149],['p','post_getter','postrouting',99]]){chain(base,hook,prio);for(const d of ['up','down']){const name=stage+'_'+d,up=d==='up',packet=up?f.original:{src:f.original.dst,dst:f.original.src,sport:f.original.dport,dport:f.original.sport};chain(name);rule(base,name+'_neighborhood',[match(meta('nfproto'),2),match(meta('l4proto'),17),match(payload('ip','saddr'),packet.src),match(payload('ip','daddr'),packet.dst),match(payload('udp','sport'),packet.sport),match(payload('udp','dport'),packet.dport),{jump:{target:name}}]);rule(name,name+'_seen',[counter]);const reject=(suffix,left,right,op='!=')=>rule(name,name+'_reject_'+suffix,[match(left,right,op),counter,ret]);reject('iif',meta('iifname'),up?'br-lan':'rpwan'+f.wan);reject('oif',meta('oifname'),up?'rpwan'+f.wan:'br-lan');reject('state',ct('state'),2);reject('unconfirmed',{'&':[ct('status'),8]},0,'==');reject('dying',{'&':[ct('status'),512]},0,'!=');reject('direction',ct('direction'),up?0:1);reject('zone',ct('zone'),0);reject('mark',ct('mark'),f.mark);reject('ct_protocol',ct('protocol'),17);reject('id',ct('id'),f.connectionId);for(const[dir,t]of [['original',f.original],['reply',f.reply]])for(const[key,value]of [['ip saddr',t.src],['ip daddr',t.dst],['proto-src',t.sport],['proto-dst',t.dport]])reject(dir+'_'+key.replace('ip ','').replaceAll('-','_'),ct(key,dir),value);rule(name,name+'_base_match',[counter]);const tag=up?TAG_UP:TAG_DOWN;if(stage==='w')rule(name,name+'_written',[counter,{mangle:{key:meta('priority'),value:tag}},ret]);else{rule(name,name+'_expected',[match(meta('priority'),tag),counter,ret]);rule(name,name+'_unexpected',[counter,ret]);}rule(name,name+'_return',[ret]);}}
 return {expected:{nftables:objects},batch:{nftables:objects.map((x,i)=>({[i===0?'create':'add']:x}))}};}
export function staticTable(raw){assert.ok(Array.isArray(raw.nftables));const tables=[],chains=new Map(),rows=new Map(),comments=new Set();for(let x of raw.nftables){assert.equal(Object.keys(x).length,1);if(x.metainfo)continue;x=x.add??x.create??x;assert.equal(Object.keys(x).length,1);const[k,value]=Object.entries(x)[0];assert.ok(['table','chain','rule'].includes(k));const v=structuredClone(value);delete v.handle;assert.equal(v.family,'inet');assert.equal(k==='table'?v.name:v.table,TABLE);if(k==='table')tables.push({table:v});else if(k==='chain'){assert.ok(!chains.has(v.name));chains.set(v.name,{chain:v});}else{assert.ok(!comments.has(v.comment));comments.add(v.comment);v.expr=normalizeRule(v);if(!rows.has(v.chain))rows.set(v.chain,[]);rows.get(v.chain).push({rule:v});}}assert.equal(tables.length,1);for(const name of rows.keys())assert.ok(chains.has(name));return {nftables:[...tables,...[...chains.keys()].sort().flatMap(k=>[chains.get(k),...(rows.get(k)??[])])]};}
export function qualify(first,last){assert.equal(canonical(staticTable(first)),canonical(staticTable(last)));const read=o=>Object.fromEntries(o.nftables.filter(x=>x.rule).map(x=>x.rule).filter(x=>x.expr.some(y=>y.counter)).map(x=>[x.comment.split(':').at(-1),x.expr.find(y=>y.counter).counter]));const a=read(first),b=read(last),delta={};assert.deepEqual(Object.keys(a),Object.keys(b));for(const k of Object.keys(a)){delta[k]={};for(const unit of ['packets','bytes']){delta[k][unit]=b[k][unit]-a[k][unit];assert.ok(uint(delta[k][unit],Number.MAX_SAFE_INTEGER));}}
 for(const stage of ['w','f','p'])for(const d of ['up','down']){const n=stage+'_'+d,reject=Object.keys(delta).filter(k=>k.startsWith(n+'_reject_'));for(const u of ['packets','bytes']){const rejected=reject.reduce((v,k)=>v+delta[k][u],0);assert.equal(delta[n+'_seen'][u],rejected+delta[n+'_base_match'][u]);assert.equal(rejected,0);if(stage==='w')assert.equal(delta[n+'_written'][u],delta[n+'_base_match'][u]);else{assert.equal(delta[n+'_base_match'][u],delta[n+'_expected'][u]+delta[n+'_unexpected'][u]);assert.equal(delta[n+'_unexpected'][u],0);}}assert.ok(delta[n+'_base_match'].packets>0);}return {passed:true,delta,synthetic:true,automaticRT:false,softwarePriorityOnly:true,nssPermit:false,leafProof:false,lossOrJitter:false,crossStagePacketConservationClaim:false};}
