import assert from'node:assert/strict';import{verifyPreparation}from'../v12/session-binding.mjs';
export function verifyCandidate(input){
 const q=verifyPreparation();assert.equal(input.mode,'stage');assert.equal(input.openFrontend,true);assert.equal(input.autoClassified,true);assert.equal(input.qosDevice,'lan4');const a=input.selected.tcp,b=input.selected.udp,d=input.selected.tcp2,p=input.wanPrerequisites;assert.notEqual(a.wan,d.wan);assert.equal(p.boot,q.boot);assert.ok(p.members.length>=2&&p.members.length<=3);assert.equal(p.members.length,new Set([a.wan,b.wan,d.wan]).size);
 for(const f of[a,b,d]){assert.ok(Number.isInteger(f.wan)&&f.wan>=1&&f.wan<=5);assert.equal(f.original.src,'192.168.237.207');assert.equal(f.zone,0);assert.equal((f.mark>>>16)&255,f.wan);assert.equal(f.mark&0x2000,0);assert.ok(Number.isInteger(f.id)&&f.id>0&&f.id<=0xffffffff);const e=p.members.find(e=>e.w===f.wan);assert.equal(e.w,f.wan);assert.equal(e.ip,f.reply.dst);assert.ok(Number.isInteger(e.pid)&&e.pid>1);assert.match(e.start,/^\d+$/);assert.ok(Number.isInteger(e.failure)&&e.failure>=0);assert.ok(Number.isInteger(e.index)&&e.index>0&&e.link==='wan');assert.match(e.mac,/^[a-f0-9:]{17}$/);}
 assert.equal(a.protocol,6);assert.equal(b.protocol,17);assert.equal(d.protocol,6);for(const[slot,f]of[['tcp',a],['udp',b],['tcp2',d]]){const m=input.tagPlan.wanLeafAssignments[slot],low=slot==='udp'?6:5;assert.equal(m.wan,f.wan);assert.equal(m.class,slot==='udp'?'RT':'BULK');assert.equal(m.upTag,(0x8e00+f.wan*16+low)*65536);assert.equal(m.downTag,(0x8f00+f.wan*16+low)*65536);}
}
export function validateRefinement(before,after){
 const mutable=new Set(['selected','tagPlan','frozenHash','insmodArguments']),fixed=x=>Object.fromEntries(Object.entries(x).filter(([k])=>!mutable.has(k)));assert.deepEqual(fixed(after),fixed(before),'Protected scope changed');
 for(const slot of['tcp','udp','tcp2']){const identity=x=>{const y=structuredClone(x);delete y.classifierKey;return y;};assert.deepEqual(identity(after.selected[slot]),identity(before.selected[slot]),'Immutable CT changed');if(after.selected[slot].classifierKey!==undefined)assert.equal(after.selected[slot].classifierKey,before.selected[slot].classifierKey);}
 for(const k of['owner','table','mode'])assert.equal(after.tagPlan[k],before.tagPlan[k]);assert.deepEqual(after.tagPlan.wanLeafAssignments,before.tagPlan.wanLeafAssignments);assert.match(after.frozenHash,/^[a-f0-9]{64}$/);assert.ok(typeof after.insmodArguments==='string'&&after.insmodArguments.length<2048);verifyCandidate(after);return structuredClone(after);
}
