// Read-only closure after two bounded SSH timeouts; never overwrite their receipts.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const root='work/nss110',load=JSON.parse(fs.readFileSync(root+'/load-latest-private.json'));assert.match(load.unit,/^nss110-[a-f0-9]{16}$/);
function read(command,name){const p=spawnSync('ssh',['-o','BatchMode=yes','-o','ConnectTimeout=8','-o','ServerAliveInterval=3','-o','ServerAliveCountMax=2','sub2api-dallas',command],{encoding:'utf8',windowsHide:true,timeout:25000});const record={code:p.status,signal:p.signal,error:p.error?.code,stdout:p.stdout,stderr:p.stderr,observedAt:new Date().toISOString(),readonly:true};fs.writeFileSync(load.dir+'/'+name+'-private.json',JSON.stringify(record,null,2)+'\n',{flag:'wx'});assert.equal(p.status,0,'Read-only endpoint closure query failed: '+(p.error?.code??p.status));return p.stdout;}
const rules=read('timeout -k 1 8 nft -j list ruleset','firewall-recheck');
const parsed=JSON.parse(rules);const owned=parsed.nftables.filter(x=>x.rule?.comment?.startsWith('nss14-'));assert.equal(owned.length,0,'Independent firewall expiry not observed');
const unit=read('systemctl show '+load.unit+'.service -p MainPID -p ActiveState; ss -H -lntup sport = :45817; ss -H -lntup sport = :45818','unit-recheck');assert.ok(unit.includes('MainPID=0')&&unit.includes('ActiveState=inactive')&&!unit.includes('LISTEN')&&!unit.includes('UNCONN'));
const py="import sys,json,hashlib;from pathlib import Path;ns={'__name__':'closure_check'};exec(Path('work/nss110/endpoint-firewall-guardian.py').read_text(),ns);r=Path(sys.argv[1]);v=json.loads((r/'firewall-recheck-private.json').read_text());q=json.loads(v['stdout']);cp=json.loads((r/'firewall-checkpoint-private.json').read_text());assert hashlib.sha256(ns['canonical'](q).encode()).hexdigest()==cp['canonicalSha256'];print('EXACT_BASELINE_RESTORED')";
const p=spawnSync('C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-c',py,load.dir],{encoding:'utf8',windowsHide:true,timeout:4000});assert.equal(p.status,0,p.stderr);assert.equal(p.stdout.trim(),'EXACT_BASELINE_RESTORED');
const value={passed:true,readonly:true,ownedRulesRemaining:0,baselineRestored:true,exactOwnedEndpointClosed:true,naturalOsDeadlineClosure:true,initialSshTimeoutsPreserved:true};
fs.writeFileSync(root+'/endpoint-closure-recheck.json',JSON.stringify(value,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(value));
