import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{verifyPreparation as prior}from'./session-binding-v4.mjs';
const r='work/nss151',old=prior(),h=b=>crypto.createHash('sha256').update(b).digest('hex'),names=['class-session-v5.mjs','epoch-session-v5.mjs','current-audit-diagnostic-v5.mjs','run-v5.mjs','session-binding-v5.mjs','qualify-v5.mjs','prepare-v5.py'],sourceManifest={};
for(const n of names){const f=r+'/'+n,s=fs.readFileSync(f,'utf8');sourceManifest[f]=h(fs.readFileSync(f));
 if(!n.startsWith('qualify')&&!n.startsWith('prepare'))for(const m of s.matchAll(/['"](work\/[^'"\n]+\.(?:mjs|lua|py|ps1|json))['"]/g))if(!m[1].endsWith('entry-qualified-v5.json')&&!m[1].endsWith('/continuity-private.json'))assert.ok(fs.existsSync(m[1]),'Missing literal input: '+m[1]);
 if(n.endsWith('.mjs'))for(const m of s.matchAll(/from\s*['"]([^'"]+)['"]/g))if(m[1].startsWith('.'))assert.ok(fs.existsSync(path.resolve(path.dirname(f),m[1])));
 const p=n.endsWith('.mjs')?spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true}):spawnSync('C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-c','import sys;compile(open(sys.argv[1],encoding="utf-8").read(),sys.argv[1],"exec")',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);
}
const run=fs.readFileSync(r+'/run-v5.mjs','utf8');assert.ok(run.includes("[pre.split('/').at(-1)+'-preflight','prewrite',pre]"));assert.ok(!run.includes("['class-transition-preflight','prewrite',pre]"));assert.ok(run.includes("run(root+'/close-endpoint-v4.mjs'"));assert.ok(run.includes("run(root+'/start-dallas-v3.mjs'"));
for(const n of['class-session-v5.mjs','epoch-session-v5.mjs'])assert.ok(fs.readFileSync(r+'/'+n,'utf8').includes("assert.equal(continuityPath,'work/nss151/run-v5/continuity-private.json')"));
const q={passed:true,inheritedBindings:Object.keys(old.sourceManifest).length,sourceManifest,uniquePreflightLabel:true,existingNativeFactoriesUnchanged:true,policyModelsUnchanged:38,budgets:[6,27,100,9000,65536,73728],productionExecution:false};fs.writeFileSync(r+'/entry-qualified-v5.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});const v=(await import('./session-binding-v5.mjs')).verifyPreparation();console.log(JSON.stringify({passed:true,bindings:Object.keys(v.sourceManifest).length,uniquePreflightLabel:true,routerWrites:false}));
