import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{verifyPreparation as prior}from'./session-binding.mjs';
const r='work/nss151',old=prior(),h=b=>crypto.createHash('sha256').update(b).digest('hex');
const names=['current-audit-diagnostic-v2.mjs','class-session-v2.mjs','epoch-session-v2.mjs','run-v2.mjs','session-binding-v2.mjs','qualify-v2.mjs','prepare-v2.py','prepare-complete-v2.py'];const sourceManifest={};
for(const n of names){const f=r+'/'+n;sourceManifest[f]=h(fs.readFileSync(f));const p=n.endsWith('.mjs')?spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true}):spawnSync('C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-c','import sys;compile(open(sys.argv[1],encoding="utf-8").read(),sys.argv[1],"exec")',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}
const text=fs.readFileSync(r+'/current-audit-diagnostic-v2.mjs','utf8'),literal=text.match(/assert\.match\(caseDir,(\/\^work[^\n]+?\/)\);/);assert.ok(literal);const regex=Function('return '+literal[1])();
for(const kind of['automatic-epoch','controlled-class'])assert.ok(regex.test('work/nss151/'+kind+'-20261006000000-aabbccdd'));assert.ok(!regex.test('work/nss150/automatic-epoch-20261006000000-aabbccdd'));
for(const n of['class-session-v2.mjs','epoch-session-v2.mjs'])assert.ok(fs.readFileSync(r+'/'+n,'utf8').includes("assert.equal(continuityPath,'work/nss151/run-v2/continuity-private.json')"));
const q={passed:true,inheritedBindings:Object.keys(old.sourceManifest).length,sourceManifest,onlyAuditNamespaceAndVersionedPathsChanged:true,explicitEscapedAuditNamespaceTested:true,originalPreflightRejectionBeforeRouterOrLoad:true,existingNativeFactoriesUnchanged:true,policyModelsUnchanged:38,budgets:[6,27,100,9000,65536,73728],productionExecution:false};
fs.writeFileSync(r+'/entry-qualified-v2.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});const v=(await import('./session-binding-v2.mjs')).verifyPreparation();console.log(JSON.stringify({passed:true,bindings:Object.keys(v.sourceManifest).length,namespaceRegexChecks:3,policyUnchanged:true,routerWrites:false}));
