import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{verifyPreparation as prior}from'../nss151/session-binding-v5.mjs';
const root='work/nss152',old=prior(),h=b=>crypto.createHash('sha256').update(b).digest('hex'),names=['prepare.py','read-controlled.mjs','match-controlled.mjs','server.py','probe-peer.py','endpoint-firewall-guardian.py','client-watchdog.ps1','discover-peer.py','ssh-client.mjs','upload-server.py','upload-ack.mjs','bounded-pacer.mjs','health.mjs','read-final-physical.mjs','start-dallas.mjs','close-endpoint.mjs','current-audit-diagnostic.mjs','epoch-session.mjs','declared-baseline.mjs','failed-wan-owner.lua','session-binding.mjs','qualify.mjs','crash-controller.mjs','crash-read.lua'],sourceManifest={};
for(const n of names){const f=root+'/'+n,s=fs.readFileSync(f,'utf8');sourceManifest[f]=h(fs.readFileSync(f));if(n.endsWith('.mjs')){for(const m of s.matchAll(/from\s*['"]([^'"]+)['"]/g))if(m[1].startsWith('.'))assert.ok(fs.existsSync(path.resolve(path.dirname(f),m[1])));const p=spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}if(n.endsWith('.py')){const p=spawnSync('C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-c','import sys;compile(open(sys.argv[1],encoding="utf-8").read(),sys.argv[1],"exec")',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}}
for(const n of['epoch-session.mjs','current-audit-diagnostic.mjs','start-dallas.mjs'])assert.ok(!fs.readFileSync(root+'/'+n,'utf8').includes('work/nss151/'));
assert.ok(fs.readFileSync(root+'/epoch-session.mjs','utf8').includes("assert.equal(continuityPath,'work/nss152/run/continuity-private.json')"));
assert.ok(fs.readFileSync(root+'/start-dallas.mjs','utf8').includes("const unit='nss152-'"));assert.ok(fs.readFileSync(root+'/close-endpoint.mjs','utf8').includes('/^nss152-[a-f0-9]{16}$/'));
assert.ok(fs.readFileSync(root+'/current-audit-diagnostic.mjs','utf8').includes('/^work\\/nss152\\/'));
const a=fs.readFileSync(root+'/epoch-session.mjs','utf8'),b=fs.readFileSync('work/nss151/epoch-session-v5.mjs','utf8');assert.equal(a.replaceAll('work/nss152/','work/nss151/').replace("'./session-binding.mjs'","'./session-binding-v5.mjs'").replaceAll('current-audit-diagnostic.mjs','current-audit-diagnostic-v5.mjs').replaceAll('work/nss49/current-audit-diagnostic-v5.mjs','work/nss49/current-audit-diagnostic.mjs').replace('run/continuity-private.json','run-v5/continuity-private.json'),b);
const q={passed:true,inheritedBindings:Object.keys(old.sourceManifest).length,sourceManifest,singleOwnedControllerCrash:true,exactEpochControllerByteMapping:true,nativeFactoryUnchanged:149,allInheritedPolicyChecksRetained:true,budgets:[6,27,100,9000,65536,73728],productionExecution:false};fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});const v=(await import('./session-binding.mjs')).verifyPreparation();console.log(JSON.stringify({passed:true,bindings:Object.keys(v.sourceManifest).length,singleOwnedControllerOnly:true,nativeFactoryUnchanged:true,routerWrites:false}));
