import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{uploadAck}from'./upload-ack.mjs';
const root='work/nss116',h=b=>crypto.createHash('sha256').update(b).digest('hex'),checks=[];
for(const[name,old,text,ok]of [['initial-empty',0,'{"received":0}',true],['confirmed-progress',10,'{"received":11}',true],['equal-repeat',10,'{"received":10}',true],['rollback',10,'{"received":9}',false],['fractional',0,'{"received":0.5}',false],['negative',0,'{"received":-1}',false],['over-byte-cap',0,'{"received":1073741825}',false],['string',0,'{"received":"1"}',false],['missing',0,'{}',false],['foreign-field',0,'{"received":1,"submitted":2}',false],['not-json',0,'partial',false]]){let accepted=false;try{uploadAck(old,text);accepted=true}catch{}assert.equal(accepted,ok,name);checks.push({name,passed:true,simulated:true,accepted});}
const source=fs.readFileSync(root+'/upload-server.py','utf8'),bytes=1024*1024;
const p=spawnSync('wsl.exe',['-d','Athena-Cake-Build','--','python3','-u','-c',source],{input:Buffer.alloc(bytes),windowsHide:true,encoding:'utf8',timeout:10000,maxBuffer:65536});fs.writeFileSync(root+'/local-receiver-raw.json',JSON.stringify({code:p.status,stdout:p.stdout,stderr:p.stderr,error:p.error?.code,actualInputBytes:bytes},null,2)+'\n',{flag:'wx'});assert.equal(p.status,0,p.stderr);let confirmed=0;for(const line of p.stdout.trim().split('\n'))confirmed=uploadAck(confirmed,line);assert.equal(confirmed,bytes);checks.push({name:'actual-posix-receiver-confirmed-one-mib-and-eof-exit',passed:true,simulated:false,localOnly:true});
for(const name of fs.readdirSync(root).filter(x=>x.endsWith('.mjs'))){const q=spawnSync(process.execPath,['--check',root+'/'+name],{windowsHide:true,encoding:'utf8'});assert.equal(q.status,0,q.stderr);}
for(const name of ['fast-path.lua','module-stage-guardian.lua','qos-physical.lua','tag-normalizer.lua','uplink-tag-plan.mjs','parse-ecm-any-wan.mjs'])assert.equal(h(fs.readFileSync(root+'/'+name)),h(fs.readFileSync('work/nss114/'+name)));
const sourceManifest={};for(const name of fs.readdirSync(root))if(/\.(mjs|py|lua|ps1)$/.test(name))sourceManifest[root+'/'+name]=h(fs.readFileSync(root+'/'+name));
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify({passed:true,productionExecution:false,onlyBulkLoadDirectionChanged:true,serverConfirmedDeliveryMetric:true,queueRatesChanged:false,routerPayloadChanged:false,initialUploadTargetMbps:48,phaseSeconds:20,nativeSessionSeconds:27,independentOwnerSeconds:100,checks,sourceManifest},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,checks:checks.length,actualLocalReceiverBytes:confirmed,sourceBindings:Object.keys(sourceManifest).length,remoteHardwareExecution:false}));
