import fs from'node:fs';import assert from'node:assert/strict';import{connectRouter}from'../nss20/connect-router.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';
const path='work/nss47/cache-retain/deployment-latest.json',ctx=JSON.parse(fs.readFileSync(path));assert.equal(ctx.committed,false);
const proof=JSON.parse(fs.readFileSync(ctx.localDir+'/permanent-before-commit-audit.json'));assert.equal(proof.passed,true);
const qualified=JSON.parse(fs.readFileSync('work/nss47/cache-qualified.json')),native=JSON.parse(fs.readFileSync('work/nss47/native-cache-qualified.json')),bound=JSON.parse(fs.readFileSync('work/nss47/cache-bound-qualified.json')),trial=JSON.parse(fs.readFileSync('work/nss47/cache-trial/deployment-latest.json')),undo=JSON.parse(fs.readFileSync(trial.localDir+'/rollback-qualified.json'));assert.ok(qualified.passed&&native.passed&&bound.passed&&undo.passed&&undo.automaticExpiryWithoutControllerRollback&&undo.previousClassifierCoreRestored);const cfg=JSON.parse(fs.readFileSync(ctx.localDir+'/config.json'));assert.equal(qualified.candidateSha256,cfg.files['classifier-core.lua']);assert.equal(native.candidateSha256,qualified.candidateSha256);assert.equal(bound.candidateSha256,qualified.candidateSha256);
const c=await connectRouter();try{
 const lua=String.raw`local j=require('luci.jsonc');local fs=require('nixio.fs');local function read(p,l)local f=assert(io.open(p));local s=f:read(l+1)or'';f:close();assert(#s<=l);return s end;local now=tonumber(read('/proc/uptime',128):match('^[%d.]+'));local id,b,d=read('/root/router-project/active-transaction',512):match('^(%S+) (%S+) (%d+)\n$');assert(id=='__ID__'and b==read('/proc/sys/kernel/random/boot_id',128):gsub('%s+$','')and now+40<tonumber(d));assert(read('/root/router-project/game-classifier-generation',512)=='__BASE__ __HASH__\n');local s=assert(j.parse(read('/tmp/router-project-game-classifier/snapshot.json',4194304)));local g=assert(j.parse(read('/tmp/router-project-game-classifier/guardian.json',8192)));assert(s.status=='running'and s.generation=='__GEN__'and s.configSha256=='__HASH__'and s.nssPermit==false and not s.error and now<s.snapshot.provenance.startedAtUptime+6);assert(g.healthy==true and g.generation==s.generation and now-g.atUptime<6);local a=assert(j.parse(read('/tmp/router-project-game-classifier/classification.json',4194304)));assert(a.snapshot.admissionProjection and a.snapshot.admissionProjection.version==1 and a.snapshot.admissionProjection.scope=='bulk-and-admitted-rt');assert(a.publication=='before-software-baseline'and a.status=='running'and a.generation==s.generation and a.producer==s.producer and a.configSha256==s.configSha256 and a.nssPermit==false and now<a.snapshot.provenance.startedAtUptime+6);assert(not fs.lstat('/tmp/router-project-game-classifier/stopped'));assert(not fs.lstat('/sys/module/rp_ecm_gate_lab_ct'));assert(not fs.lstat('/sys/module/qca_nss_qdisc'));for _,p in ipairs({'front_end_ipv4_stop','front_end_ipv6_stop'})do assert(tonumber(read('/sys/kernel/debug/ecm/'..p,128))==1)end;for _,p in ipairs({'ecm_db/connection_count','ecm_nss_ipv4/accelerated_count','ecm_nss_ipv6/accelerated_count','ecm_nss_ipv4/pending_accel_count','ecm_nss_ipv6/pending_accel_count','ecm_nss_ipv4/pending_decel_count','ecm_nss_ipv6/pending_decel_count'})do assert(tonumber(read('/sys/kernel/debug/ecm/'..p,128))==0)end;local path='/root/router-project/transactions/__ID__/verification.txt';assert(not fs.lstat(path));local f=assert(io.open(path,'w'));assert(f:write(j.stringify({classifierRecovered=true,exactProtectedAudit=true,boundedPureAddressCacheQualified=true,existingSourceTimeAndRowBoundsPreserved=true,nssEnabled=false,producer=s.producer,atUptime=now})..'\n'));assert(f:close());assert(fs.chmod(path,600));print('NSS26_PRECOMMIT_VERIFIED')`.replaceAll('__ID__',()=>ctx.transactionId).replaceAll('__BASE__',()=>ctx.base).replaceAll('__HASH__',()=>ctx.configHash).replaceAll('__GEN__',()=>ctx.id);
 const body='exec 8>/tmp/router-project-transaction.lock\nflock -x 8\n/usr/bin/lua - <<\'NSS26_COMMIT\'\n'+lua+'\nNSS26_COMMIT\nexec 8>&-\nsh /root/router-project/scripts/transaction.sh commit '+ctx.transactionId+'\n';
 const e=encode(body),raw=receipt(await c.run(e.command),e);fs.writeFileSync(ctx.localDir+'/commit-raw-private.json',JSON.stringify(raw,null,2)+'\n');assert.equal(raw.code,0,raw.stderr);assert.ok(raw.stdout.includes('COMMITTED='+ctx.transactionId));ctx.committed=true;ctx.permanentClassifier=true;ctx.nssEnabled=false;ctx.commitAt=new Date().toISOString();fs.writeFileSync(path,JSON.stringify(ctx,null,2)+'\n');fs.writeFileSync(ctx.localDir+'/permanent-commit.json',JSON.stringify({committed:true,transactionId:ctx.transactionId,configHash:ctx.configHash,commitAt:ctx.commitAt,nssEnabled:false},null,2)+'\n');
 fs.writeFileSync('work/nss47/deployment-latest.json',JSON.stringify(ctx,null,2)+'\n');
 await c.upload(ctx.localDir+'/cancel',ctx.stagePath+'/cancel');console.log(JSON.stringify({permanentClassifierCommitted:true,independentHealthGuardian:true,nssEnabled:false,passiveStageCancellationRequested:true}));
}finally{c.close()}
