"""Adapt only the controlled exact-flow consumer to two TCP BULK plus UDP RT."""
from pathlib import Path
import re
r=Path(__file__).resolve().parent
def edit(f,fn):
 p=r/f;p.write_text(fn(p.read_text(encoding='utf-8')),encoding='utf-8')
slots="['tcp','udp','tcp2']";luas="{'tcp','udp','tcp2'}"
edit('class-leaf-map.mjs',lambda s:s.replace("['tcp','udp']",slots).replace("slot==='tcp'?6:17","slot==='udp'?17:6").replace('assert.notEqual(selected.tcp.wan,selected.udp.wan)','assert.notEqual(selected.tcp.wan,selected.tcp2.wan)'))
edit('classifier.lua',lambda s:s.replace("{'tcp','udp'}",luas).replace("slot=='tcp'and 6 or 17","slot=='udp'and 17 or 6").replace("slot=='tcp'and'BULK'or'RT'","slot=='udp'and'RT'or'BULK'").replace("slot=='tcp'and 2399469568 or 2399535104","slot=='udp'and 2399535104 or 2399469568").replace("slot=='tcp'and dec.reason~='bulk'","slot~='udp'and dec.reason~='bulk'").replace("selected.tcp.wan~=selected.udp.wan","selected.tcp.wan~=selected.tcp2.wan").replace('==2,\'Complete evidence','==3,\'Complete evidence').replace('assert(#chosen==2)','assert(#chosen==3)').replace("{'tcp','udp'},reason",luas+",reason").replace('not detail.slots.udp.present)','not detail.slots.udp.present or not detail.slots.tcp2.present)'))
edit('tag-normalizer.lua',lambda s:s.replace("{'tcp','udp'}",luas).replace("slot=='tcp'and 5 or 6","slot=='udp'and 6 or 5").replace("slot=='tcp'and'BULK'or'RT'","slot=='udp'and'RT'or'BULK'").replace('PLAN.wanLeafAssignments.tcp.wan~=PLAN.wanLeafAssignments.udp.wan','PLAN.wanLeafAssignments.tcp.wan~=PLAN.wanLeafAssignments.tcp2.wan'))
edit('qos-physical.lua',lambda s:s.replace('local wans={P.selected.tcp.wan,P.selected.udp.wan};assert(wans[1]~=wans[2]);table.sort(wans)','local wans,seen={},{};for _,slot in ipairs({\'tcp\',\'udp\',\'tcp2\'})do local w=P.selected[slot].wan;if not seen[w]then seen[w]=true;wans[#wans+1]=w end end;assert(#wans>=2 and #wans<=3 and P.selected.tcp.wan~=P.selected.tcp2.wan);table.sort(wans)').replace('local each=shared/2','local each=shared/#wans').replace("slot=='tcp'and 5 or 6","slot=='udp'and 6 or 5").replace("slot=='tcp'and'BULK'or'RT'","slot=='udp'and'RT'or'BULK'"))
edit('wan-scope.lua',lambda s:s.replace('assert(#members==2)','assert(#members>=2 and #members<=3)').replace(" for i,f in ipairs({P.selected.tcp,P.selected.udp})do local e=members[i];assert(e.w==f.wan and e.ip==f.reply.dst and e.w%1==0 and e.w>=1 and e.w<=5)end\n assert(members[1].w~=members[2].w)"," local map={};for _,e in ipairs(members)do assert(not map[e.w]);map[e.w]=e end;for _,f in pairs(P.selected)do local e=assert(map[f.wan]);assert(e.ip==f.reply.dst and e.w%1==0 and e.w>=1 and e.w<=5)end;assert(P.selected.tcp.wan~=P.selected.tcp2.wan)").replace('record.wanRestored=not own[1]and not own[2];','record.wanRestored=true;for _,v in pairs(own)do if v then record.wanRestored=false end end;'))
edit('candidate-policy.mjs',lambda s:s.replace("const a=input.selected.tcp,b=input.selected.udp,p=input.wanPrerequisites;assert.notEqual(a.wan,b.wan);assert.equal(p.boot,q.boot);assert.equal(p.members.length,2);","const a=input.selected.tcp,b=input.selected.udp,d=input.selected.tcp2,p=input.wanPrerequisites;assert.notEqual(a.wan,d.wan);assert.equal(p.boot,q.boot);assert.ok(p.members.length>=2&&p.members.length<=3);assert.equal(p.members.length,new Set([a.wan,b.wan,d.wan]).size);").replace('for(const[i,f]of[a,b].entries())','for(const f of[a,b,d])').replace('const e=p.members[i]','const e=p.members.find(e=>e.w===f.wan)').replace("assert.equal(b.protocol,17);","assert.equal(b.protocol,17);assert.equal(d.protocol,6);").replace("[['tcp',a],['udp',b]]","[['tcp',a],['udp',b],['tcp2',d]]").replace("slot==='tcp'?5:6","slot==='udp'?6:5").replace("slot==='tcp'?'BULK':'RT'","slot==='udp'?'RT':'BULK'").replace("['tcp','udp']",slots))
edit('parse-ecm.mjs',lambda s:s.replace('selected.tcp&&selected.udp','selected.tcp&&selected.udp&&selected.tcp2').replace('selected.tcp.wan,selected.udp.wan','selected.tcp.wan,selected.tcp2.wan').replace('[selected.tcp,selected.udp]','[selected.tcp,selected.udp,selected.tcp2]').replace('remainingUdpOnly?1:2','remainingUdpOnly?1:3').replace("['tcp',2399469568],['udp',2399535104]","['tcp',2399469568],['udp',2399535104],['tcp2',2399469568]").replace("slot==='tcp'?5:6","slot==='udp'?6:5"))
def fast(s):
 s=s.replace("{'tcp','game'}","{'tcp','game','tcp2'}").replace("k.tcp_permit=='Y'and k.game_permit=='Y'","k.tcp_permit=='Y'and k.game_permit=='Y'and k.tcp2_permit=='Y'")
 s=s.replace("{'tcp_post_up','tcp_post_down','udp_post_up','udp_post_down'}","{'tcp_post_up','tcp_post_down','udp_post_up','udp_post_down','tcp2_post_up','tcp2_post_down'}")
 s=s.replace("v<=2,'Unexpected ECM scope'","v<=3,'Unexpected ECM scope'").replace("accelerated_count']~=2","accelerated_count']~=3").replace("connection_count']~=2","connection_count']~=3")
 s=s.replace('P.selected.tcp.wan~=P.selected.udp.wan','P.selected.tcp.wan~=P.selected.tcp2.wan').replace('{P.selected.tcp,P.selected.udp}','{P.selected.tcp,P.selected.udp,P.selected.tcp2}')
 start=s.index('function M.verifyReclassification(');end=s.index('function M.new(',start);s=s[:start]+s[end:]
 s=s.replace('local supported=pcall(M.verifyReclassification,C,R.adapterProducer)\n    if supported then retire(C);return{terminalReason=\'AUTHENTICATED_BULK_TO_BE\',comparisonRecord=\'actualReclassification\'}end\n    ','')
 start=s.index(' retire=function(C)');end=s.index(' local function tick(name)',start);s=s[:start]+s[end:]
 s=s.replace('local active=false;local retire','local active=false')
 return s
edit('fast-path.lua',fast)
# The tag runner also requires three actual classification identities in one query.
s=(r.parents[0]/'nss49/classified-tags.lua').read_text();s=s.replace("{'tcp','udp'}",luas).replace('pair.tcp and pair.udp and pair.tcp.decision','pair.tcp and pair.udp and pair.tcp2 and pair.tcp2.decision.class==\'BULK\'and pair.tcp.decision').replace('flows={pair.tcp,pair.udp}','flows={pair.tcp,pair.udp,pair.tcp2}')
(r/'classified-tags.lua').write_text(s)
edit('module-stage.mjs',lambda s:s.replace("['tcp','udp']",slots).replace('f.wan,f.mark,slot,f.original.src',"f.wan,f.mark,f.protocol===6?'tcp':'udp',f.original.src").replace("work/nss49/classified-tags.lua","work/v16-three/classified-tags.lua").replace('work/v13/endpoint-gate','work/v16-three/endpoint-gate').replace('work/v13/runtime-elf-comparison.json','work/v16-three/runtime-elf-comparison.json').replace('work/v13/renewal-qualified.json','work/v16-three/native-source-qualified.json'))
edit('module-stage-guardian.lua',lambda s:s.replace("{'tcp','game'}","{'tcp','game','tcp2'}").replace("'eligible_tcp','eligible_game'","'eligible_tcp','eligible_game','eligible_tcp2'").replace("'allowed_tcp','allowed_game'","'allowed_tcp','allowed_game','allowed_tcp2'").replace("'tcp_state','game_state'","'tcp_state','game_state','tcp2_state'").replace("'tcp_pinned_state','game_pinned_state'","'tcp_pinned_state','game_pinned_state','tcp2_pinned_state'").replace("'tcp_permit','game_permit'","'tcp_permit','game_permit','tcp2_permit'").replace("'expiry_tcp','expiry_game'","'expiry_tcp','expiry_game','expiry_tcp2'"))
def epoch(s):
 s=s.replace("['tcp','udp']",slots).replace("[['tcp','tcp'],['udp','game']]","[['tcp','tcp'],['udp','game'],['tcp2','tcp2']]").replace("p.name==='B'?2:0","p.name==='B'?3:0")
 s=s.replace('const prerequisites=[];','const prerequisites=[];')
 s=s.replace("const f=selected[slot];const e=encode(\"/usr/bin/lua - \"+f.wan", "const f=selected[slot];if(prerequisites.some(q=>q.wan===f.wan))continue;const e=encode(\"/usr/bin/lua - \"+f.wan")
 s=s.replace("assert.equal(classified.decisions[1].class,'RT');","assert.equal(classified.decisions[1].class,'RT');assert.equal(classified.decisions[2].class,'BULK');")
 s=s.replace("&&fresh.tcp.some(f=>JSON.stringify(convert(f))===JSON.stringify(selected.tcp))","&&fresh.tcp.some(f=>JSON.stringify(convert(f))===JSON.stringify(selected.tcp))&&fresh.tcp.some(f=>JSON.stringify(convert(f))===JSON.stringify(selected.tcp2))")
 s=s.replace('twoWans:[selected.tcp.wan,selected.udp.wan]','naturalWanSet:[...new Set(Object.values(selected).map(f=>f.wan))],twoTcpBulkOneUdpRt:true')
 return s
edit('epoch-driver.mjs',epoch)
edit('pilot-supervisor.mjs',lambda s:s.replace('selected.tcp.wan!==selected.udp.wan','selected.tcp.wan!==selected.tcp2.wan').replace("sixtySecondHardwareSessionCompleted:true","sixtySecondHardwareSessionCompleted:true,threeExactFlows:true"))
edit('owned-load-policy.mjs',lambda s:s.replace("assert.equal(status.tcpConnected,true);","assert.ok(status.tcpChildren&&status.tcpChildren.length===2&&status.tcpChildren.every(c=>c.connected));"))
edit('start-dallas.mjs',lambda s:s.replace('v15-qos-','v16-three-'))
print('Three-flow controlled consumer integrated; no live experiment started')
