import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';
import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';import{connectRouter}from'../nss27/connect-router.mjs';import{packLua}from'../nss149/pack-lua.mjs';import{packGuardian}from'../nss149/pack-guardian.mjs';import{guardianPlan}from'./guardian-plan.mjs';
const root='work/v16-three',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
const plan=read(root+'/modeled-three-v2-tag-plan-private.json'),model=read(root+'/modeled-three-v2-class-frame-private.json'),qos=fs.readFileSync(root+'/qos-physical.lua','utf8'),norm=fs.readFileSync(root+'/tag-normalizer.lua','utf8'),classifier=fs.readFileSync(root+'/classifier.lua','utf8'),fast=fs.readFileSync(root+'/fast-path.lua','utf8');
const oldRecord=read('work/v15-qos/session-20261006182044-545bff6b/last-record-private.json'),p=structuredClone(oldRecord.classifierSnapshots[0].provenance),flow=model.frame.flows[0];
Object.assign(p,{sequence:model.frame.sourceSequence,startedAtUptime:flow.observationStartedAtUptime,finishedAtUptime:flow.observedAtUptime});
const parts=model.frame.producer.split(':'),c={generation:parts[0],boot:parts[1],pid:Number(parts[2]),start:parts[3],base:'/root/router-project/classifier/'+parts[0],configSha256:'581b5d46c9d3772ccd94f5f36510bccf665899f210c43b4deaa5155067c791d7',alive:true,stopped:false,guardianHealthy:true,authorizedClient:'192.168.237.207',sourceCommand:p.command};c.workerArgv=['/usr/bin/lua',c.base+'/worker.lua','watch',c.base,c.configSha256].join('\0')+'\0';
const s={version:23,status:'running',nssPermit:false,generation:c.generation,boot:c.boot,configSha256:c.configSha256,pid:c.pid,start:c.start,producer:model.frame.producer,atUptime:p.finishedAtUptime,snapshot:{flows:model.frame.flows,provenance:p}};
for(const d of Object.values(model.selected)){const f=s.snapshot.flows.find(x=>Number(x.identity.connectionId)===d.id&&x.identity.protocolNumber===d.protocol);d.classifierKey=f.key;}
const end=classifier.indexOf('\nlocal describeSelection=');assert.ok(end>0);const consumer=classifier.slice(0,end);
const consumerTest=consumer+`\nlocal x=assert(j.parse([====[${JSON.stringify({s,c,selected:model.selected})}]====]));x.c.workerArgv=table.concat({'/usr/bin/lua',x.c.base..'/worker.lua','watch',x.c.base,x.c.configSha256},string.char(0))..string.char(0);local now=x.s.snapshot.provenance.finishedAtUptime+0.1;local e=Consumer.pair(x.s,x.c,now,x.selected);assert(#e.decisions==3);assert(Consumer.compareEpoch(e,x.s,x.c,now,false).action=='KEEP_IMMUTABLE_EPOCH');local target=x.s.snapshot.flows[#x.s.snapshot.flows];target.decision={class='BE',reason='cooldown',budgetAdmitted=false};target.leaf.class='BE';target.leaf.candidate=false;target.leaf.downTag=0;local z=Consumer.compareEpoch(e,x.s,x.c,now,false);assert(z.action=='RETIRE_EXACT_SELECTED_SLOTS'and #z.affected==1 and z.affected[1]=='tcp2');assert(not pcall(Consumer.pair,x.s,x.c,now,x.selected));print('TRIPLET_SAME_QUERY_CLASS_AND_CHANGE_PASS')`;
const specs=qos.slice(qos.indexOf('local function specs('),qos.indexOf('function M.new('));
const qosTest=specs+`\nlocal P={selected=assert(j.parse([====[${JSON.stringify(model.selected)}]====])),tagPlan=assert(j.parse([====[${JSON.stringify({wanLeafAssignments:plan.wanLeafAssignments})}]====]))};local checks=0;for _,up in ipairs({false,true})do local a=specs(P,up);assert(#a.wans==3 and a.perWan==(up and 20 or 10) and #a.commands==20);local qs,cs={},{};for _,v in pairs(a.qs)do qs[#qs+1]=v..'\\n Sent 100 bytes 1 pkt (dropped 0, overlimits 0 requeues 0)'end;for h,v in pairs(a.cs)do cs[#cs+1]='class nsshtb '..h..' root '..(a.leaves[h]and'leaf '..a.leaves[h]..' 'or'')..v..'\\n Sent 100 bytes 1 pkt (dropped 0, overlimits 0 requeues 0)'end;assert(validate(table.concat(qs,'\\n'),table.concat(cs,'\\n'),true,a).nativeOptionsValidated);checks=checks+1 end;P.selected.udp.wan=P.selected.tcp.wan;P.tagPlan.wanLeafAssignments.udp.wan=P.selected.tcp.wan;P.tagPlan.wanLeafAssignments.udp.upTag=(0x8e00+P.selected.tcp.wan*16+6)*65536;P.tagPlan.wanLeafAssignments.udp.downTag=(0x8f00+P.selected.tcp.wan*16+6)*65536;assert(specs(P,false).perWan==15 and #specs(P,false).commands==15);print(j.stringify({passed=true,checks=checks+1,backendMocked=true}))`;
const normTest=`local P=assert(j.parse([====[${JSON.stringify(plan)}]====]));local N=(function()${packLua(norm)} end)();local before=N(P.expected,P);local raw=assert(j.parse(j.stringify(P.expected)));for _,x in ipairs(raw.nftables)do if x.rule then for _,e in ipairs(x.rule.expr)do if e.mangle and e.mangle.key.meta.key=='priority'then e.mangle.value=string.format('%x:0',e.mangle.value/65536)end;if e.match and e.match.left.meta and e.match.left.meta.key=='priority'and type(e.match.right)=='number'and e.match.right>0 then e.match.right=string.format('%x:0',e.match.right/65536)end end end end;assert(N(raw,P)==before);local bad=assert(j.parse(j.stringify(raw)));local changed=false;for _,x in ipairs(bad.nftables)do if x.rule and x.rule.comment:find(':tcp2_writer_',1,true)then for _,e in ipairs(x.rule.expr)do if e.mangle then e.mangle.value='8f05:0';changed=true;break end end end;if changed then break end end;assert(changed and not pcall(N,bad,P));print('THIRD_SLOT_NATIVE_TAG_NORMALIZATION_PASS')`;
const counterTest=`local M=(function()${packLua(fast)} end)();local c={};for _,slot in ipairs({'tcp','udp','tcp2'})do for _,dir in ipairs({'up','down'})do for _,kind in ipairs({'total','expected','unexpected'})do c[slot..'_post_'..dir..'_'..kind]={packets=kind=='unexpected'and 0 or 2,bytes=kind=='unexpected'and 0 or 300}end end end;c.udp_post_neighbor_nonzero={packets=0,bytes=0};assert(not M.tagCounterAudit(c,false).pending);c.tcp2_post_down_unexpected={packets=1,bytes=150};assert(not pcall(M.tagCounterAudit,c,false));print('THIRD_SLOT_COUNTER_DEFAULT_DENY_PASS')`;
// Size and syntax use a representative frozen historical plan, never admission.
const gp=read('work/v15-qos/session-20261006182044-545bff6b/stage-plan-private.json');for(const k of ['guardianSourceSha256','selectedGuardianSha256','oneEpochControlledPair','phaseSourceSha256','qosSourceSha256','execBytes'])delete gp[k];gp.selected=model.selected;gp.moduleBytes=44616;gp.moduleSha256='d53f5cc076f38edabbbd576b19a2fb1befed3e1acc1cb4ae7703c0e0efab12a2';gp.qosCodeBytes=fs.statSync(root+'/modeled-three-v2-payload-private.lua').size;gp.qosCodeSha256=hash(fs.readFileSync(root+'/modeled-three-v2-payload-private.lua'));
gp.insmodArguments+=' tcp2_ct_id_raw=1234567 tcp2_ct_mark=327680 tcp2_nat_address=172.16.91.189 tcp2_nat_port=51789 tcp2_source_port=51789 tcp2_server_port=22 tcp2_server=172.93.163.251';gp.wanPrerequisites.members.push({...gp.wanPrerequisites.members[0],w:5,ip:'172.16.91.189'});
const guard=packGuardian(fs.readFileSync(root+'/module-stage-guardian.lua','utf8')).replace('__PLAN__',()=>JSON.stringify(guardianPlan(gp))).replace('__CORE_PHASE__',()=>'return{}').replace('__QOS_PHYSICAL__',()=>'return{}');let guardian;
try{guardian=encode("lua - <<'V16_GUARD_MODEL_SIZE'\n"+guard+"\nV16_GUARD_MODEL_SIZE\n");}catch(e){fs.writeFileSync(root+'/guardian-model-size-v2-failure-private.json',JSON.stringify({error:String(e),bytes:Buffer.byteLength(guard),productionWrites:false},null,2)+'\n',{flag:'wx'});throw e;}
const sourceTests={consumer:consumerTest,qos:qosTest,normalizer:normTest,counters:counterTest,guardianSyntax:`assert(loadstring([====[${guard}]====]));print('GUARDIAN_SYNTAX_PASS')`,classifierConsumerSyntax:`assert(loadstring([====[${packLua(consumer)}]====]));print('CLASSIFIER_CONSUMER_SYNTAX_PASS')`,classifierAdapterSyntax:`assert(loadstring([====[${packLua(classifier.slice(end))}]====]));print('CLASSIFIER_ADAPTER_SYNTAX_PASS')`};
const commands=Object.fromEntries(Object.entries(sourceTests).map(([name,source])=>[name,encode("lua - <<'V16_RAM_MODEL'\nlocal j=require('luci.jsonc');\n"+source+"\nV16_RAM_MODEL\n")]));const results={};const channel=await connectRouter();try{for(const[name,e]of Object.entries(commands)){const raw=receipt(await channel.run(e.command),e);fs.writeFileSync(root+'/'+name+'-ram-model-v6-raw-private.json',JSON.stringify(raw,null,2)+'\n',{flag:'wx'});assert.equal(raw.code,0,name+' model failure retained');results[name]=raw.stdout.trim();}}finally{channel.close();}
const out={passed:true,threeSlotConsumerClassChangeModel:true,qosTwoOrThreeWanModel:true,nativeThirdTagNormalizationAndWrongTagRefusal:true,thirdSlotTagCounterDefaultDeny:true,guardianExecBytes:guardian.execBytes,execBytes:Object.fromEntries(Object.entries(commands).map(([k,v])=>[k,v.execBytes])),backendMocked:true,hardwareExecuted:false,productionWrites:false,routerFilesWritten:false,sourceHashes:{classifier:hash(classifier),qos:hash(qos),normalizer:hash(norm),fast:hash(fast)},results};fs.writeFileSync(root+'/native-qualified.json',JSON.stringify(out,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(out));
