import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import path from 'node:path';import {spawnSync} from 'node:child_process';
const root='work/nss79',session=crypto.randomBytes(8).toString('hex');const dir=root+'/load-'+new Date().toISOString().replace(/\D/g,'').slice(0,14)+'-'+session;fs.mkdirSync(dir);
const save=(n,v)=>fs.writeFileSync(dir+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
const quote=x=>"'"+x.replaceAll("'","'\\''")+"'";
function ssh(command){const p=spawnSync('ssh',['-o','BatchMode=yes','-o','ConnectTimeout=8','sg',command],{encoding:'utf8',windowsHide:true,timeout:20000});save('ssh-'+crypto.randomBytes(3).toString('hex')+'-private',{code:p.status,stdout:p.stdout,stderr:p.stderr});assert.equal(p.status,0,p.stderr);return p.stdout;}
const unit='nss79-'+session;const checkpoint=ssh('ss -H -lntup; cat /proc/sys/kernel/random/boot_id');save('server-checkpoint-private',{observedAt:new Date().toISOString(),before:checkpoint,noPersistentConfigurationChangesPlanned:true});
assert.ok(!checkpoint.includes(':45817 ')&&!checkpoint.includes(':45818 '),'Endpoint ports already used');
const conf={token:crypto.randomBytes(32).toString('hex'),mbps:18,seconds:180,tcpPort:45817,udpPort:45818};
const source=fs.readFileSync(root+'/server.py','utf8');
ssh('sudo -n systemd-run --unit='+unit+' --collect --property=RuntimeMaxSec=190 --property=KillMode=mixed /usr/bin/python3 -u -c '+quote(source)+' '+quote(JSON.stringify(conf)));
const state=ssh('systemctl show '+unit+' -p MainPID -p ActiveState -p RuntimeMaxUSec -p KillMode; ss -H -lntup');
assert.ok(state.includes('ActiveState=active')&&state.includes('RuntimeMaxUSec=3min 10s')&&state.includes('KillMode=mixed'));
assert.match(state,/MainPID=[1-9]\d*/);assert.ok(state.includes(':45817 ')&&state.includes(':45818 '));save('server-deadline-private',{unit,state,verifiedBeforeClientTraffic:true,independentOsDeadlineSeconds:190});
const config={...conf,pps:50,clientAddress:'192.168.237.207',serverAddress:'18.138.159.236',tcpSourcePort:57000+crypto.randomInt(800),udpSourcePort:59000+crypto.randomInt(800),session};
const configPath=path.resolve(dir+'/client-config-private.json');save('client-config-private',config);
const literal=x=>"'"+x.replaceAll("'","''")+"'";
const client=path.resolve(root+'/client.py'),guard=path.resolve(root+'/client-watchdog.ps1'),binding=path.resolve(dir+'/client-binding-private.json');
const ps=`$ErrorActionPreference='Stop';$taskExe=(Get-Command python).Source;$taskClient=Start-Process -WindowStyle Hidden -FilePath $taskExe -ArgumentList @('-u',('"'+${literal(client)}+'"'),('"'+${literal(configPath)}+'"')) -RedirectStandardOutput ${literal(path.resolve(dir+'/client-stdout-private.txt'))} -RedirectStandardError ${literal(path.resolve(dir+'/client-stderr-private.txt'))} -PassThru;$taskInfo=@{clientPid=$taskClient.Id;clientStart=$taskClient.StartTime.ToUniversalTime().ToString('o');clientExe=$taskExe;scriptPath=${literal(client)};configPath=${literal(configPath)};guardResult=${literal(path.resolve(dir+'/guard-result-private.json'))}};$taskInfo|ConvertTo-Json|Set-Content -LiteralPath ${literal(binding)} -Encoding UTF8;$taskGuard=Start-Process -WindowStyle Hidden -FilePath powershell.exe -ArgumentList @('-NoProfile','-NonInteractive','-File',('"'+${literal(guard)}+'"'),'-BindingPath',('"'+${literal(binding)}+'"')) -PassThru;@{clientPid=$taskClient.Id;guardPid=$taskGuard.Id;guardStart=$taskGuard.StartTime.ToUniversalTime().ToString('o')}|ConvertTo-Json -Compress`;
const p=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',ps],{encoding:'utf8',windowsHide:true,timeout:10000});save('client-launch-private',{code:p.status,stdout:p.stdout,stderr:p.stderr});assert.equal(p.status,0,p.stderr);const started=JSON.parse(p.stdout);save('launch-receipt',{...started,unit,dir,configPath,serverIndependentDeadlineSeconds:190,clientIndependentDeadlineSeconds:210});fs.writeFileSync(root+'/load-latest-private.json',JSON.stringify({dir,...started,unit},null,2)+'\n');console.log(JSON.stringify({started:true,dir,clientPid:started.clientPid,guardPid:started.guardPid,tcpTargetMbps:18,udpPps:50,serverDeadlineSeconds:190,clientDeadlineSeconds:210}));
