import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';
import{verifyPreparation as inherited}from'../v16-three/session-binding.mjs';import{buildPayload}from'./payload.mjs';import{guardianPlan}from'./guardian-plan.mjs';
import{packGuardian}from'../nss149/pack-guardian.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';import{connectRouter}from'../nss27/connect-router.mjs';
const root='work/v17-cap',old=inherited(),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p)),save=(n,v)=>fs.writeFileSync(root+'/'+n+'.json',JSON.stringify(v,null,2)+'\n',{flag:'wx'});
const qos=fs.readFileSync(root+'/qos-physical.lua','utf8'),before=fs.readFileSync('work/v16-three/qos-physical.lua','utf8');assert.equal(qos,before.replace('local shared=up and 60 or 30;','local shared=up and 60 or 18;'));
for(const n of['classifier.lua','fast-path.lua','classified-tags.lua','wan-scope.lua','tag-normalizer.lua','module-stage-guardian.lua'])assert.equal(hash(fs.readFileSync(root+'/'+n)),hash(fs.readFileSync('work/v16-three/'+n)),n);
const plan=read('work/v16-three/modeled-three-v2-tag-plan-private.json'),model=read('work/v16-three/modeled-three-v2-class-frame-private.json');
const sources={qos,phase:fs.readFileSync('work/nss69/core-guard-phase.lua','utf8'),classifier:fs.readFileSync(root+'/classifier.lua','utf8'),tags:fs.readFileSync(root+'/classified-tags.lua','utf8'),normalizer:fs.readFileSync(root+'/tag-normalizer.lua','utf8')};
const payload=buildPayload({tagPlan:plan,selected:model.selected},sources);assert.ok(Buffer.byteLength(payload.stagedCode)<=73728);fs.writeFileSync(root+'/modeled-budget-payload-private.lua',payload.stagedCode,{flag:'wx'});
const gp=read('work/v16-three/session-20261006185337-354ba382/stage-plan-private.json');for(const k of['guardianSourceSha256','selectedGuardianSha256','oneEpochControlledPair','phaseSourceSha256','qosSourceSha256','execBytes'])delete gp[k];gp.qosCodeBytes=Buffer.byteLength(payload.stagedCode);gp.qosCodeSha256=hash(payload.stagedCode);
const guard=packGuardian(fs.readFileSync(root+'/module-stage-guardian.lua','utf8')).replace('__PLAN__',()=>JSON.stringify(guardianPlan(gp))).replace('__CORE_PHASE__',()=>'return{}').replace('__QOS_PHYSICAL__',()=>'return{}');const g=encode("lua - <<'V17_GUARD_SIZE'\n"+guard+"\nV17_GUARD_SIZE\n");
const code=qos.slice(qos.indexOf('local function specs('),qos.indexOf('function M.new('));
const test=String.raw`local P={selected=assert(j.parse([====[__SELECTED__]====])),tagPlan=assert(j.parse([====[__TAGPLAN__]====]))};local checks=0;for _,count in ipairs({3,2})do if count==2 then P.selected.udp.wan=P.selected.tcp.wan;local x=P.tagPlan.wanLeafAssignments.udp;x.wan=P.selected.udp.wan;x.upTag=(0x8e00+x.wan*16+6)*65536;x.downTag=(0x8f00+x.wan*16+6)*65536 end;for _,up in ipairs({false,true})do local s=specs(P,up);assert(#s.wans==count and s.shared==(up and 60 or 18) and s.perWan==s.shared/count);local qs,cs={},{};for _,v in pairs(s.qs)do qs[#qs+1]=v..'\n Sent 100 bytes 1 pkt (dropped 0, overlimits 0 requeues 0)'end;for h,v in pairs(s.cs)do cs[#cs+1]='class nsshtb '..h..' root '..(s.leaves[h]and'leaf '..s.leaves[h]..' 'or'')..v..'\n Sent 100 bytes 1 pkt (dropped 0, overlimits 0 requeues 0)'end;assert(validate(table.concat(qs,'\n'),table.concat(cs,'\n'),true,s).nativeOptionsValidated);checks=checks+1 end end;print(j.stringify({passed=true,checks=checks,sharedDownMbps=18,sharedUpMbps=60,backendMocked=true}))`;
// String.raw above holds escaped separators; Lua must receive the normal \n escape once.
const body=code+'\n'+test.replaceAll('\\\\n','\\n').replace('__SELECTED__',()=>JSON.stringify(model.selected)).replace('__TAGPLAN__',()=>JSON.stringify({wanLeafAssignments:plan.wanLeafAssignments}));
const e=encode("lua - <<'V17_QOS_BUDGET_MODEL'\nlocal j=require('luci.jsonc');\n"+body+"\nV17_QOS_BUDGET_MODEL\n");let c=await connectRouter();try{const r=receipt(await c.run(e.command),e);save('qos-ram-model-raw-private',r);assert.equal(r.code,0,r.stderr);const v=JSON.parse(r.stdout);assert.ok(v.passed&&v.checks===4&&v.backendMocked);save('native-qualified',{passed:true,sourceSha256:hash(qos),qosModel:v,execBytes:e.execBytes,productionWrites:false,wholeFactoryModeled:false,hardwareExecuted:false});}finally{c.close()}
save('qos-native-qualified',{passed:true,sourceSha256:hash(qos),targetRamModelPassed:true});save('normalizer-qualified',read('work/v16-three/normalizer-qualified.json'));
const manifest={};for(const n of fs.readdirSync(root))if(/\.(mjs|lua|py|ps1)$/.test(n)&&!n.includes('private')){const p=root+'/'+n;manifest[p]=hash(fs.readFileSync(p));if(n.endsWith('.mjs')){const x=spawnSync(process.execPath,['--check',p],{windowsHide:true,encoding:'utf8'});assert.equal(x.status,0,x.stderr);}}
for(const n of['qos-native-qualified.json','normalizer-qualified.json','native-qualified.json'])manifest[root+'/'+n]=hash(fs.readFileSync(root+'/'+n));
save('entry-qualified',{passed:true,sourceManifest:manifest,inheritedBindings:Object.keys(old.sourceManifest).length,hardwareExecuted:false,onlyDataPlaneChange:'shared DOWN30 to18Mbps; UP60 unchanged',exactV16NativeGateReused:true,otherLuaSourcesExact:true,guardianExecBytes:g.execBytes,modeledPayloadBytes:Buffer.byteLength(payload.stagedCode),phaseSeconds:60,sourceFreshnessSeconds:6,kernelSessionSeconds:90,ownerSeconds:180,clientSeconds:180});console.log(JSON.stringify({passed:true,bindings:Object.keys(old.sourceManifest).length+Object.keys(manifest).length,payloadBytes:Buffer.byteLength(payload.stagedCode),guardianExecBytes:g.execBytes}));
