from pathlib import Path
r=Path('work/nss159')
def write(name,data):
    with (r/name).open('x',encoding='utf-8',newline='\n') as f:f.write(data)
s=(r/'current-audit-diagnostic.mjs').read_text(encoding='utf-8')
assert 'nss158\\/' in s
write('current-audit-diagnostic-v2.mjs',s.replace('nss158\\/','nss159\\/').replace("'./session-binding.mjs'","'./session-binding-v2.mjs'"))
s=(r/'epoch-driver.mjs').read_text(encoding='utf-8')
write('epoch-driver-v2.mjs',s.replace('current-audit-diagnostic.mjs','current-audit-diagnostic-v2.mjs').replace("'./session-binding.mjs'","'./session-binding-v2.mjs'"))
s=(r/'pilot-supervisor.mjs').read_text(encoding='utf-8')
s=s.replace("'./session-binding.mjs'","'./session-binding-v2.mjs'").replace("'./epoch-driver.mjs'","'./epoch-driver-v2.mjs'").replace('current-audit-diagnostic.mjs','current-audit-diagnostic-v2.mjs')
s=s.replace("const root='work/nss159'","assert.ok(Date.now()<Date.parse('2026-10-06T11:30:00Z'),'Evening restoration margin unavailable');\nconst root='work/nss159'")
write('pilot-supervisor-v2.mjs',s)
s=(r/'session-binding.mjs').read_text(encoding='utf-8')
s=s.replace("'../nss158/session-binding.mjs'","'./session-binding.mjs'").replace('entry-qualified.json','entry-qualified-v2.json')
write('session-binding-v2.mjs',s)
s=(r/'qualify-v2.mjs').read_text(encoding='utf-8')
s=s.replace("'../nss158/session-binding.mjs'","'./session-binding.mjs'")
s=s.replace("'prepare-qualification-v2.py','qualify-v2.mjs'","'prepare-qualification-v2.py','qualify-v2.mjs','prepare-v2.py','current-audit-diagnostic-v2.mjs','epoch-driver-v2.mjs','pilot-supervisor-v2.mjs','session-binding-v2.mjs','qualify-v3.mjs'")
s=s.replace("root+'/epoch-driver.mjs'","root+'/epoch-driver-v2.mjs'")
s=s.replace("const driver=fs.readFileSync", "const driver=fs.readFileSync")
s=s.replace(".replace(\"from '../nss158/module-stage.mjs'\"", ".replace(\"'./session-binding-v2.mjs'\",\"'./session-binding.mjs'\").replaceAll('current-audit-diagnostic-v2.mjs','current-audit-diagnostic.mjs').replace(\"from '../nss158/module-stage.mjs'\"")
s=s.replace("root+'/policy-qualified.json'","root+'/policy-qualified-v2.json'")
s=s.replace("root+'/entry-qualified.json'","root+'/entry-qualified-v2.json'")
s=s.replace("import('./session-binding.mjs')","import('./session-binding-v2.mjs')")
write('qualify-v3.mjs',s)
print('Preserved failed namespace source; only new audit input namespace and binding changed')
