import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {verifyPreparation as inherited} from './session-binding-v3.mjs';
const root='work/nss159',old=inherited(),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const names=['prepare.py','download-client.mjs','download-server.py','download-policy.mjs','owned-load-policy.mjs','policy-tests.mjs','qualify.mjs','prepare-qualification-v2.py','qualify-v2.mjs','prepare-v2.py','current-audit-diagnostic-v2.mjs','epoch-driver-v2.mjs','pilot-supervisor-v2.mjs','session-binding-v2.mjs','qualify-v3.mjs','prepare-v3.py','current-audit-diagnostic-v3.mjs','epoch-driver-v3.mjs','pilot-supervisor-v3.mjs','session-binding-v3.mjs','qualify-v4.mjs','prepare-v4.py','close-endpoint-v2.mjs','current-audit-diagnostic-v4.mjs','epoch-driver-v4.mjs','pilot-supervisor-v4.mjs','session-binding-v4.mjs','qualify-v5.mjs','session-binding.mjs','pilot-supervisor.mjs','epoch-driver.mjs','match-controlled.mjs','read-controlled.mjs','start-dallas.mjs','close-endpoint.mjs','current-audit-diagnostic.mjs','declared-baseline.mjs','failed-wan-owner.lua','receiver.py','server.py','endpoint-firewall-guardian.py','discover-peer.py','probe-peer.py','client-watchdog.ps1'];
const sourceManifest={};
for(const name of names){const f=root+'/'+name,s=fs.readFileSync(f,'utf8');sourceManifest[f]=hash(fs.readFileSync(f));
 if(name.endsWith('.mjs')||name.endsWith('.py')){const p=name.endsWith('.mjs')?spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true}):spawnSync('C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-c','import sys;compile(open(sys.argv[1],encoding="utf-8").read(),sys.argv[1],"exec")',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}
 if(name.endsWith('.mjs'))for(const m of s.matchAll(/(?<!['"])\b(?:from|import)\s*['"]([^'"]+)['"]/g)){if(!m[1].startsWith('.'))continue;const d=path.posix.normalize(path.posix.join(root,m[1]));assert.ok(names.includes(path.posix.relative(root,d))||d in old.sourceManifest,'Unbound '+d);assert.ok(fs.existsSync(d));}
}
const literalSourceDependencies=[];
for(const name of names.filter(n=>n.endsWith('.mjs'))){const text=fs.readFileSync(root+'/'+name,'utf8');
 for(const m of text.matchAll(/(?:readFileSync|runNode|run)\(\s*['"](work\/[^'"]+)['"]/g)){
  if(!/\.(?:mjs|lua|py|ps1)$/.test(m[1]))continue;
  assert.ok(m[1] in old.sourceManifest||names.includes(path.posix.relative(root,m[1])),'Unbound literal source '+m[1]);assert.ok(fs.existsSync(m[1]));literalSourceDependencies.push(m[1]);
 }
}
const p=spawnSync(process.execPath,[root+'/policy-tests.mjs'],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);const model=JSON.parse(p.stdout);assert.ok(model.passed);fs.writeFileSync(root+'/policy-qualified-v4.json',JSON.stringify(model,null,2)+'\n',{flag:'wx'});
assert.equal(hash(fs.readFileSync('work/nss158/fast-path.lua')),old.sourceManifest['work/nss158/fast-path.lua']);assert.equal(hash(fs.readFileSync('work/nss158/module-stage.mjs')),old.sourceManifest['work/nss158/module-stage.mjs']);
const driver=fs.readFileSync(root+'/epoch-driver-v4.mjs','utf8').replace("'./session-binding-v4.mjs'","'./session-binding.mjs'").replaceAll('current-audit-diagnostic-v4.mjs','current-audit-diagnostic.mjs').replace("from '../nss158/module-stage.mjs'","from './module-stage.mjs'").replace("observationRoot='work/nss159'","observationRoot='work/nss157'").replaceAll('work/nss159/automatic-epoch-','work/nss158/automatic-epoch-').replaceAll('work/nss159/current-audit-diagnostic.mjs','work/nss158/current-audit-diagnostic.mjs').replaceAll('nss159\\/pilot-aba-','nss158\\/pilot-aba-');assert.equal(driver.replaceAll('\r\n','\n'),fs.readFileSync('work/nss158/epoch-driver.mjs','utf8').replaceAll('\r\n','\n'));
assert.ok(fs.readFileSync(root+'/current-audit-diagnostic-v4.mjs','utf8').includes('nss159\\/'));
assert.ok(fs.readFileSync(root+'/close-endpoint-v2.mjs','utf8').includes('^nss159-'));
assert.ok(!fs.readFileSync(root+'/epoch-driver-v4.mjs','utf8').includes('work/nss49/current-audit-diagnostic-v'));
const q={passed:true,inheritedBindings:Object.keys(old.sourceManifest).length,sourceManifest,productionExecution:false,completeLiteralReadDependenciesVerified:true,fixturePolicyCases:model.cases,staticLiteralSourceDependenciesActuallyChecked:[...new Set(literalSourceDependencies)],oldQualificationMissedLiteralDependencyPreserved:true,completeFactoryModelExecuted:false,native158ByteUnchanged:true,onlyOneRemoteSenderAtATime:true,senderStopAcknowledgementBeforeNext:true,originalBudgetsSeconds:[6,27,100,180],byteLimits:[9000,65536,73728,1048576],softwareMaximumCandidatePorts:8,softwareOfferedMbps:32,clientIndependentDeadlineSeconds:210,remoteTimeoutSeconds:185};fs.writeFileSync(root+'/entry-qualified-v4.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,bindings:Object.keys((await import('./session-binding-v4.mjs')).verifyPreparation().sourceManifest).length,modelCases:model.cases,nativeUnchanged:true,productionExecuted:false}));
