import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {verifyPreparation as inherited} from '../nss158/session-binding.mjs';
const root='work/nss159',old=inherited(),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const names=['prepare.py','download-client.mjs','download-server.py','download-policy.mjs','owned-load-policy.mjs','policy-tests.mjs','qualify.mjs','session-binding.mjs','pilot-supervisor.mjs','epoch-driver.mjs','match-controlled.mjs','read-controlled.mjs','start-dallas.mjs','close-endpoint.mjs','current-audit-diagnostic.mjs','declared-baseline.mjs','failed-wan-owner.lua','receiver.py','server.py','endpoint-firewall-guardian.py','discover-peer.py','probe-peer.py','client-watchdog.ps1'];
const sourceManifest={};
for(const name of names){const f=root+'/'+name,s=fs.readFileSync(f,'utf8');sourceManifest[f]=hash(fs.readFileSync(f));
 if(name.endsWith('.mjs')||name.endsWith('.py')){const p=name.endsWith('.mjs')?spawnSync(process.execPath,['--check',f],{encoding:'utf8',windowsHide:true}):spawnSync('C:/Users/lishu/AppData/Local/Programs/Python/Python312/python.exe',['-c','import sys;compile(open(sys.argv[1],encoding="utf-8").read(),sys.argv[1],"exec")',f],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}
 if(name.endsWith('.mjs'))for(const m of s.matchAll(/\b(?:from|import)\s*['"]([^'"]+)['"]/g)){if(!m[1].startsWith('.'))continue;const d=path.posix.normalize(path.posix.join(root,m[1]));assert.ok(names.includes(path.posix.relative(root,d))||d in old.sourceManifest,'Unbound '+d);assert.ok(fs.existsSync(d));}
}
const p=spawnSync(process.execPath,[root+'/policy-tests.mjs'],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);const model=JSON.parse(p.stdout);assert.ok(model.passed);fs.writeFileSync(root+'/policy-qualified.json',JSON.stringify(model,null,2)+'\n',{flag:'wx'});
assert.equal(hash(fs.readFileSync('work/nss158/fast-path.lua')),old.sourceManifest['work/nss158/fast-path.lua']);assert.equal(hash(fs.readFileSync('work/nss158/module-stage.mjs')),old.sourceManifest['work/nss158/module-stage.mjs']);
const driver=fs.readFileSync(root+'/epoch-driver.mjs','utf8').replace("from '../nss158/module-stage.mjs'","from './module-stage.mjs'").replace("observationRoot='work/nss159'","observationRoot='work/nss157'").replaceAll('work/nss159/automatic-epoch-','work/nss158/automatic-epoch-').replaceAll('work/nss159/current-audit-diagnostic.mjs','work/nss158/current-audit-diagnostic.mjs').replaceAll('nss159\\/pilot-aba-','nss158\\/pilot-aba-');assert.equal(driver.replaceAll('\r\n','\n'),fs.readFileSync('work/nss158/epoch-driver.mjs','utf8').replaceAll('\r\n','\n'));
const q={passed:true,inheritedBindings:Object.keys(old.sourceManifest).length,sourceManifest,productionExecution:false,completeLiteralReadDependenciesVerified:true,fixturePolicyCases:model.cases,completeFactoryModelExecuted:false,native158ByteUnchanged:true,onlyOneRemoteSenderAtATime:true,senderStopAcknowledgementBeforeNext:true,originalBudgetsSeconds:[6,27,100,180],byteLimits:[9000,65536,73728,1048576],softwareMaximumCandidatePorts:8,softwareOfferedMbps:32,clientIndependentDeadlineSeconds:210,remoteTimeoutSeconds:185};fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify(q,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,bindings:Object.keys((await import('./session-binding.mjs')).verifyPreparation().sourceManifest).length,modelCases:model.cases,nativeUnchanged:true,productionExecuted:false}));
