import fs from'node:fs';import assert from'node:assert/strict';import crypto from'node:crypto';import{spawnSync}from'node:child_process';import{verifyPreparation}from'../nss119/session-binding.mjs';import{connectRouter}from'../nss27/connect-router.mjs';import{encode,receipt}from'../nss11/v7-observe-repair/observe2/transport.mjs';import{packLua}from'./pack-lua.mjs';import{buildPayload}from'./payload.mjs';import{packetTemplate}from'./uplink-tag-plan.mjs';
const root='work/nss120',h=b=>crypto.createHash('sha256').update(b).digest('hex'),old=verifyPreparation(),checks=[];
const source=fs.readFileSync(root+'/qos-physical.lua','utf8'),prefix=source.slice(0,source.indexOf('function M.new('))+'\nreturn M';
const added=" local classHeaders=cheaders;if up then classHeaders={};for k,v in pairs(cheaders)do classHeaders[k]=v:gsub('29Mbit','59Mbit'):gsub('30Mbit','60Mbit')end end";let inverse=source.replace(added+'\r\n','').replace(added+'\n','').replaceAll('classHeaders[h]','cheaders[h]').replace("c=c:gsub('8f','8e'):gsub('29mbit','59mbit'):gsub('30mbit','60mbit')","c=c:gsub('8f','8e')");assert.equal(inverse,fs.readFileSync('work/nss119/qos-physical.lua','utf8'));checks.push({name:'only-uplink-rates-and-matching-validator-changed',passed:true,localOnly:true});
const caseDir='work/nss119/controlled-matched-aba-20261005194907-eb0894bd',record=JSON.parse(fs.readFileSync(caseDir+'/last-record-private.json'));
const q=record.qosAccelerated.uplink.qdisc.split('\n').filter(x=>x.startsWith('qdisc ')).join('\n')+'\n',c=record.qosAccelerated.uplink.classes.split('\n').filter(x=>x.startsWith('class ')).join('\n')+'\n';
const descriptors=[{kind:'full',up:true,ok:true},{kind:'old-30',up:true,ok:false},{kind:'wrong-bulk',up:true,ok:false},{kind:'full',up:false,ok:true},{kind:'down-60',up:false,ok:false},{kind:'priority',up:true,ok:false},{kind:'missing-root',up:true,ok:false},{kind:'partial',up:true,ok:true}];
const body=`local j=require('luci.jsonc');local M=assert(loadstring([====[${packLua(prefix)}]====]))();local Q=[====[${q}]====];local C=[====[${c}]====];local ds=assert(j.parse([====[${JSON.stringify(descriptors)}]====]));local checks={};for _,d in ipairs(ds)do local q,c=Q,C;if d.up then c=c:gsub('29Mbit','59Mbit'):gsub('30Mbit','60Mbit')else q=q:gsub('8e','8f');c=c:gsub('8e','8f')end;if d.kind=='old-30'then c=C elseif d.kind=='wrong-bulk'then c=c:gsub('59Mbit','58Mbit')elseif d.kind=='down-60'then c=c:gsub('29Mbit','59Mbit'):gsub('30Mbit','60Mbit')elseif d.kind=='priority'then c=c:gsub('priority 1','priority 2')elseif d.kind=='missing-root'then q=q:sub(assert(q:find('\\n'))+1)elseif d.kind=='partial'then q=q:sub(1,assert(q:find('\\n')));c=''end;local ok,result=pcall(M.validateNative,q,c,d.kind~='partial',d.up);assert(ok==d.ok,d.kind..':'..tostring(result));checks[#checks+1]={name=(d.up and'up-'or'down-')..d.kind,passed=true,targetRamOnly=true}end;print(j.stringify({passed=true,checks=checks,configurationWrites=false,hardwareQueueExecution=false}))`;
const e=encode("/usr/bin/lua - <<'NSS120_RATE_LAYOUT_RAM'\n"+body+"\nNSS120_RATE_LAYOUT_RAM\n");const router=await connectRouter();let native;try{const raw=receipt(await router.run(e.command),e);fs.writeFileSync(root+'/rate-layout-native-raw-private.json',JSON.stringify({...raw,execBytes:e.execBytes},null,2)+'\n',{flag:'wx'});assert.equal(raw.code,0,raw.stderr);native=JSON.parse(raw.stdout);assert.ok(native.passed&&native.checks.length===8);checks.push(...native.checks);}finally{router.close();}
const selected=JSON.parse(fs.readFileSync(caseDir+'/selected-private.json')),owner='a'.repeat(32),template=packetTemplate({decisions:[{slot:'tcp',protocol:6,downTag:0x8f050000,flow:selected.tcp,validUntilUptime:0},{slot:'udp',protocol:17,downTag:0x8f060000,flow:selected.udp,validUntilUptime:0}]},owner,59999);template.expected.nftables=template.expected.nftables.filter(x=>x.chain?.name!=='forward'&&x.rule?.chain!=='forward');
const payload=buildPayload({tagPlan:{table:template.expected.nftables[0].table.name,owner,mode:'rt',expected:template.expected}},{qos:source,phase:fs.readFileSync('work/nss69/core-guard-phase.lua','utf8'),classifier:fs.readFileSync('work/nss73/classifier.lua','utf8'),tags:fs.readFileSync('work/nss49/classified-tags.lua','utf8'),normalizer:fs.readFileSync(root+'/tag-normalizer.lua','utf8')});const bytes=Buffer.byteLength(payload.stagedCode);assert.ok(bytes<=73728);checks.push({name:'new-rate-payload-within-original-73728-cap',passed:true,localOnly:true,bytes});fs.writeFileSync(root+'/rate-payload-private.lua',payload.stagedCode,{flag:'wx'});
for(const name of fs.readdirSync(root).filter(x=>x.endsWith('.mjs'))){const p=spawnSync(process.execPath,['--check',root+'/'+name],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}
for(const name of ['fast-path.lua','module-stage-guardian.lua','tag-normalizer.lua','uplink-tag-plan.mjs','parse-ecm-any-wan.mjs','ssh-client.mjs','bounded-pacer.mjs'])assert.equal(h(fs.readFileSync(root+'/'+name)),h(fs.readFileSync('work/nss119/'+name)));
fs.writeFileSync(root+'/qos-native-qualification.json',JSON.stringify({...native,sourceSha256:h(fs.readFileSync(root+'/qos-physical.lua')),parserPrefixSha256:h(prefix),execBytes:e.execBytes},null,2)+'\n',{flag:'wx'});
const sourceManifest={};for(const name of fs.readdirSync(root))if(/\.(mjs|py|lua|ps1)$/.test(name)&&!name.includes('private'))sourceManifest[root+'/'+name]=h(fs.readFileSync(root+'/'+name));
fs.writeFileSync(root+'/entry-qualified.json',JSON.stringify({passed:true,productionExecution:false,onlyControlledUplinkBudgetChanged:true,serverConfirmedDeliveryMetric:true,offeredMbps:32,uplinkMbps:60,downlinkMbps:30,comparisonWan:5,naturalPbrSelectionOnly:true,phaseSeconds:20,nativeSessionSeconds:27,independentOwnerSeconds:100,classifierMaximumLeaseSeconds:6,qosSourceSha256:h(fs.readFileSync(root+'/qos-physical.lua')),payloadBytes:bytes,checks,sourceManifest,inheritedBoundInputs:Object.keys(old.sourceManifest).length},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,newChecks:checks.length,targetRamChecks:native.checks.length,execBytes:e.execBytes,payloadBytes:bytes,sourceBindings:Object.keys(sourceManifest).length,hardwareExecution:false}));
