// Actual entry binding, with only historical qualification and private transport IO substituted.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
const root=process.cwd(),here='work/nss42',old=JSON.parse(fs.readFileSync(here+'/entry-v1-qualified.json')),body=fs.readFileSync(here+'/session-binding.mjs','utf8'),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),base=path.resolve(here,'binding-fixtures-'+crypto.randomBytes(3).toString('hex'));fs.mkdirSync(base);const cases=[];
for(const scenario of ['valid-binding','changed-parser','unbound-parser','changed-baseline-source','changed-test-proof','changed-private-transport','wrong-policy-mode','wrong-runtime-configuration','new-unbound-import']){
 const dir=path.join(base,scenario);fs.mkdirSync(dir);const copy=file=>{const dst=path.join(dir,file);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(file,dst);};for(const file of [...Object.keys(old.sourceManifest),...Object.keys(old.testProofBindings)])copy(file);
 const q=structuredClone(old);for(const file of Object.keys(q.sourceManifest))q.sourceManifest[file]=hash(path.join(dir,file));for(const file of Object.keys(q.testProofBindings))q.testProofBindings[file]=hash(path.join(dir,file));let script=body.replace("import {verifyPreparation as runtime} from '../nss39/qualification.mjs';","import {verifyPreparation as runtime} from './runtime-fixture.mjs';");
 script=script.replace("import {collectDependencyClosure,externalTransportBinding} from './dependency-closure.mjs';","import {collectDependencyClosure} from './dependency-closure.mjs';const externalTransportBinding=()=>({sha256:hash('fixture-private-transport.txt')});");
 fs.writeFileSync(path.join(dir,here,'session-binding.mjs'),script);fs.writeFileSync(path.join(dir,here,'runtime-fixture.mjs'),'export function verifyPreparation(){return '+JSON.stringify({passed:true,configuration:old.configuration})+';}\n');
 fs.writeFileSync(path.join(dir,'fixture-private-transport.txt'),'approved transport source fixture\n');q.sourceManifest[here+'/session-binding.mjs']=hash(path.join(dir,here,'session-binding.mjs'));q.sourceManifest[here+'/runtime-fixture.mjs']=hash(path.join(dir,here,'runtime-fixture.mjs'));q.externalSourceBindings=[{sha256:hash(path.join(dir,'fixture-private-transport.txt'))}];
 if(scenario==='changed-parser')fs.appendFileSync(path.join(dir,here,'parse-ecm-any-wan.mjs'),'\n// changed fixture\n');
 if(scenario==='unbound-parser')delete q.sourceManifest[here+'/parse-ecm-any-wan.mjs'];
 if(scenario==='changed-baseline-source')fs.appendFileSync(path.join(dir,'work/nss11/v7-observe-repair/observe2/capture.lua'),'\n-- changed fixture\n');
 if(scenario==='changed-test-proof')fs.appendFileSync(path.join(dir,here,'parser-qualified.json'),'\n');
 if(scenario==='changed-private-transport')fs.appendFileSync(path.join(dir,'fixture-private-transport.txt'),'changed\n');
 if(scenario==='wrong-policy-mode')q.auditPurposeSeparated=false;
 if(scenario==='wrong-runtime-configuration')q.configuration.configSha256='0'.repeat(64);
 if(scenario==='new-unbound-import'){const f=path.join(dir,here,'real-session.mjs');fs.appendFileSync(f,"\nimport './missing-bound-helper.mjs';\n");fs.writeFileSync(path.join(dir,here,'missing-bound-helper.mjs'),'export const value=1;\n');q.sourceManifest[here+'/real-session.mjs']=hash(f);}
 fs.writeFileSync(path.join(dir,here,'entry-qualified.json'),JSON.stringify(q));fs.writeFileSync(path.join(dir,'run.mjs'),"import {verifyPreparation} from './work/nss42/session-binding.mjs';verifyPreparation();console.log('BOUND');\n");
 const r=spawnSync(process.execPath,['run.mjs'],{cwd:dir,encoding:'utf8',timeout:10000,windowsHide:true});assert.equal(r.error,undefined);assert.equal(r.status,scenario==='valid-binding'?0:1,r.stderr);fs.writeFileSync(path.join(dir,'result-private.json'),JSON.stringify({status:r.status,stdout:r.stdout,stderr:r.stderr}));cases.push({case:scenario,passed:true});
}
const out={passed:true,checks:cases.length,cases,testedSourceManifest:Object.fromEntries(['session-binding.mjs','dependency-closure.mjs','parse-dependency-graph.mjs','test-binding.mjs'].map(n=>[here+'/'+n,hash(here+'/'+n)])),scope:'Actual binding/graph checks in isolated workspace copies; historical runtime and encrypted-login transport source are substituted. No production source changed and no credential data accessed.',actualRuntimeSourceAltered:false,encryptedCredentialDataAccessed:false,routerWrites:false};fs.writeFileSync(here+'/binding-qualified.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({passed:true,checks:cases.length,actualRuntimeSourceAltered:false}));
