import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import zlib from 'node:zlib';import {spawnSync} from 'node:child_process';
import {validateAcceleratedState} from '../resident-general-dev-i-20261008/parse-ecm.mjs';
import {activeMask} from '../resident-general-dev-i-20261008/selection.mjs';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const root='work/resident-task-dev-i-20261008',integrationRoot='work/resident-independent-integration-20261008070722-f5696095';
const run=read(integrationRoot+'/result-private.json');assert.equal(run.state,'COMPLETE');assert.equal(run.passed,true);assert.equal(run.restorationPassed,true);
const entry=read(run.result.runtimeRoot+'/entry-result-private.json');assert.equal(entry.state,'RESTORED');assert.equal(entry.hardwareCompleted,true);assert.equal(entry.restorationPassed,true);
const pilot=read(run.result.runtimeRoot+'/pilot-reference-private.json').directory,session=read(pilot+'/case-reference-private.json').dir;
const record=read(session+'/last-record-private.json'),selected=read(session+'/selected-private.json');assert.equal(activeMask(selected),2);
assert.equal(record.phases.length,1);const phase=record.phases[0];assert.equal(phase.name,'B');assert.equal(phase.completed,true);assert.equal(phase.seconds,90);assert.equal(phase.sampleCount,181);assert.equal(record.renewals.length,30);
const samples=record.samples.filter(s=>s.phase==='B');assert.equal(samples.length,181);
// The existing lease loop opens/closes learning while the exact accelerated CI
// remains one. Report the observed control states instead of inventing a fixed one.
for(const s of samples){assert.ok(s.stop4===0||s.stop4===1);assert.equal(s.stop6,1);assert.equal(s.counts['ecm_db/connection_count'],1);assert.equal(s.counts['ecm_nss_ipv4/accelerated_count'],1);for(const [k,v]of Object.entries(s.counts))if(!['ecm_db/connection_count','ecm_nss_ipv4/accelerated_count'].includes(k))assert.equal(v,0);}
assert.equal(record.parametersPermitted.game_permit,'Y');assert.equal(record.parametersPermitted.tcp_permit,'N');assert.equal(record.parametersPermitted.tcp2_permit,'N');
for(const s of ['tcp','game','tcp2'])assert.equal(record.parametersBeforeUnload[s+'_permit'],'N');
for(const k of ['moduleLoaded','moduleUnloaded','newNssPermit','automaticPacketTagsCompleted','automaticLifecycleEpochCompleted','qosRestored','qosModuleUnloaded','dualPhysicalQueuesRestored','wanRestored','mwan3Restored','stateNodeRemoved','tagsRemoved'])assert.equal(record[k],true,k);
assert.equal(record.error,undefined);assert.equal(record.expiredState.trim(),'');const ecm=validateAcceleratedState(record.acceleratedState,selected);assert.equal(ecm.connectionCount,1);
const stage=read(session+'/stage-receipt-private.json');for(const k of ['success','rollbackBeforeFirstWrite','parentIdentityVerified','pipeInodesVerified'])assert.equal(stage[k],true,k);
const cp=read(session+'/stage-checkpoint-verified.json'),cpBytes=fs.readFileSync(session+'/stage-checkpoint-config-private.tar.gz');assert.equal(cp.gzipVerified,true);assert.equal(sha(cpBytes),cp.sha256);zlib.gunzipSync(cpBytes);
const plan=read(session+'/stage-plan-private.json');assert.ok(plan.execBytes<=9000&&plan.qosCodeBytes<=73728);assert.equal(plan.moduleSha256,sha(fs.readFileSync('work/resident-general-dev-i-20261008/endpoint-gate/rp_ecm_gate_lab_ct.runtime.ko')));
function leaf(text,handle){const rows=text.split(/(?=qdisc )/),row=rows.find(s=>s.startsWith('qdisc nssfq_codel '+handle+' '));assert.ok(row,'Expected RT leaf absent');const m=row.match(/Sent (\d+) bytes (\d+) pkt \(dropped (\d+)/);assert.ok(m);assert.ok(Number(m[2])>0);return{bytes:Number(m[1]),packets:Number(m[2]),dropped:Number(m[3])};}
// qosAccelerated is the initial snapshot. Read the existing after-B dump for
// accumulated leaf counts; no new remote observation or experiment is needed.
assert.ok(record.qosAfterTags.uptime>=phase.endedAt);const minor=(selected.udp.wan*16+6).toString(16),leaves={snapshot:'existing-after-B-tags',up:leaf(record.qosAfterTags.uplink.qdisc,'8e'+minor+':'),down:leaf(record.qosAfterTags.qdisc,'8f'+minor+':')};
const finalRaw=read(run.result.runtimeRoot+'/normal-entry-final-audit-raw-private.json'),physicalRaw=read(run.result.runtimeRoot+'/normal-entry-physical-queues-raw-private.json');assert.equal(finalRaw.code,0);assert.equal(physicalRaw.code,0);
const audit=JSON.parse(finalRaw.stdout),physical=JSON.parse(physicalRaw.stdout);assert.equal(audit.passed,true);assert.equal(audit.ecmClosedAndZero,true);assert.equal(audit.protectedConfigurationUnchanged,true);assert.equal(physical.passed,true);assert.equal(physical.defaultQueueOptionsAndHandlesExact,true);
const fixtureScopes=fs.readdirSync('work').filter(n=>/^resident-normal-fixture-\d{14}-[a-f0-9]{8}$/.test(n)).map(n=>'work/'+n).filter(p=>fs.existsSync(p+'/fixture-reference-private.json')&&read(p+'/fixture-reference-private.json').runtimeRoot===run.fixtureRoot);
assert.equal(fixtureScopes.length,1,'Exact fixture scope required');const closure=read(fixtureScopes[0]+'/fixture-closure.json');assert.equal(closure.passed,true);assert.equal(closure.endpointRestored,true);assert.equal(closure.originalIndependentClientGuardChecked,true);
const old=read('work/resident-independent-integration-20261008065825-4fc745d3/result-private.json');assert.equal(old.state,'FAILED_RESTORED');assert.equal(old.restorationPassed,true);
const oldSession='work/resident-rc1-run-20261008065912-89843eb9/session-20261008065932-3c8c9a9c',oldStage=read(oldSession+'/stage-guardian-raw-private.json');assert.equal(oldStage.code,1);assert.equal(oldStage.stdout.trim(),'');assert.ok(!fs.existsSync(oldSession+'/stage-receipt-private.json'));
const processResult=spawnSync(process.execPath,['work/resident-service-dev-i-20261008/daemon.mjs','status'],{encoding:'utf8',windowsHide:true});assert.equal(processResult.status,0);fs.writeFileSync(root+'/retained-service-status-raw-private.json',JSON.stringify({code:processResult.status,stdout:processResult.stdout,stderr:processResult.stderr})+'\n',{flag:'wx'});
const status=JSON.parse(processResult.stdout);for(const k of ['running','identityVerified','heartbeatFresh','startupHealthPassed'])assert.equal(status[k],true,k);assert.equal(status.admissionPaused,false);assert.equal(status.activeGenerationLockPresent,false);
const latest=read('work/resident-service-dev-i-20261008/service-latest-private.json'),startup=read(latest.runDirectory+'/startup-health.json');assert.equal(startup.passed,true);
const nativeProof=ecm.proof.udp,evidence={observedAt:new Date().toISOString(),milestone:'Independent eligible flow admission integrated and retained',developmentBatch:'dev-h/dev-i',passed:true,
 regression:{generalChecks:49,normalChecks:119,serviceChecks:124,scopeChecks:10,guardianPreflightChecks:16,oldGuardFailureReproduced:true,sevenSubsetLocalModelsPassed:true},
 implementation:{maximumTcpBulk:2,maximumUdpRt:1,independentEligibleSlots:true,sameWanTcpAllowed:true,unknownAndUnusedSlotsDenied:true,originalClassAndBudgetRequired:true,newFlowRequiresFreshGeneration:true},
 actualIntegration:{completed:true,activeMask:2,selectedSlots:['udp'],simulatedGamePackets:true,normalEntryCreatesTraffic:false,nativeModuleLoaded:true,nativeSourceAndBinaryUnchangedFromDevH:true,nssSeconds:phase.seconds,samples:samples.length,renewals:record.renewals.length,allSamplesEcm1:true,frontendStopStates:[...new Set(samples.map(s=>s.stop4))],unusedTcpPermitDenied:true,selectedWan:selected.udp.wan,upTag:nativeProof.upTag,downTag:nativeProof.downTag,natCorrect:nativeProof.natCorrect,fullMarkAndWanAffinityValidated:true,rtLeaves:leaves,sourceAgeMaximum:Math.max(...samples.map(s=>s.observation.queryAge)),restorationPassed:true},
 prewriteProtection:{freshCheckpointDownloadedShaAndGzipVerified:true,independentDetachedOwnerVerifiedBeforeFirstWrite:true,stageExecBytes:plan.execBytes,bundleBytes:plan.qosCodeBytes,execLimit:9000,bundleLimit:73728,sourceSeconds:6,kernelMaximumSeconds:120,ownerSeconds:180,clientSeconds:180},
 restoration:{ecmClosedAndZero:true,tagsRemoved:true,nativeAndQosModulesRemoved:true,stateNodeRemoved:true,wanAndMwanRestored:true,protectedConfigurationUnchanged:true,physicalQueueOptionsAndHandlesExact:true,endpointRestored:true,independentClientGuardClosureVerified:true,noActiveGenerationLock:true},
 originalFailure:{stageNativeIdentityPinnedOld44616ByteModule:true,actualCheckpointCreated:true,stageReceiptAbsent:true,nssPermissionGranted:false,restorationPassed:true,originalFailurePreserved:true,fix:'Pin detached staging to qualified45848-byte native; reproduce pre-fork guard checks locally',localSizeRefusalPreserved:true},
 retainedService:{...status,runDirectory:latest.runDirectory,onlyOwnedTaskLaunchArgumentsChanged:true,heartbeatRemainsPaused:true},
 scope:{cs2OrSteamOperated:false,newGameDownload:false,userDownloadPausedOrRateChanged:false,cpuExperimentRepeated:false,historicalFiveWanCoreReused:true,onlyOneSuccessfulRelatedSubsetIntegration:true,noNewFormalHardwareVersion:true,privateInputsExported:false},
 limitations:['New optional-slot hardware was integrated with RT-only mask2; other subsets have local models and historical core evidence','At most two BULK plus one admitted RT, direct owned IPv4 client only','Each NSS generation remains90 seconds, at most four starts per20 minutes; no uninterrupted permanent or all-LAN NSS claim','Reported large-download CS2 loss remains an unclosed user-experience P1; simulation does not prove its repair']};
fs.writeFileSync(root+'/integration-summary.json',JSON.stringify(evidence,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:true,nssSeconds:phase.seconds,samples:samples.length,renewals:record.renewals.length,activeMask:2,restorationPassed:true,rtLeaves:leaves,serviceState:status.state}));
