import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {connectRouter} from '../nss20/connect-router.mjs';import {encode,receipt} from '../nss11/v7-observe-repair/observe2/transport.mjs';
const raw=JSON.parse(fs.readFileSync('work/nss80/controlled-matched-aba-20261005083817-5c29bbab/last-record-private.json')).tagsAfterA2;const counters={};for(const x of raw.nftables)if(x.rule)for(const e of x.rule.expr)if(e.counter)counters[x.rule.comment.split(':').at(-1)]=e.counter;
const actual=structuredClone(counters);const cases=[{name:'actual-one-ack-skew',c:actual,expected:true}];
const add=(name,edit,expected=false)=>{const c=structuredClone(actual);edit(c);cases.push({name,c,expected})};
add('consistent-needs-no-read',c=>c.tcp_post_up_expected={...c.tcp_post_up_total});add('two-ack-skew',c=>{c.tcp_post_up_expected.packets++;c.tcp_post_up_expected.bytes+=60});add('wrong-ack-bytes',c=>c.tcp_post_up_expected.bytes++);
for(const k of ['tcp_post_up','tcp_post_down','udp_post_up','udp_post_down']){add(k+'-unexpected-packet',c=>c[k+'_unexpected'].packets=1);add(k+'-unexpected-bytes',c=>c[k+'_unexpected'].bytes=1)}
add('second-direction-skew',c=>c.udp_post_down_expected.packets++);add('missing-counter',c=>delete c.tcp_post_down_expected);add('no-traffic',c=>c.tcp_post_down_total.packets=0);add('neighbor-tagged',c=>c.udp_post_neighbor_nonzero.packets=1);add('reverse-skew',c=>c.tcp_post_up_expected.packets-=2);
const source=fs.readFileSync('work/nss81/fast-path.lua','utf8');const code=`local j=require('luci.jsonc');local M=assert(loadstring([====[${source}]====]))();local tests=assert(j.parse([===[${JSON.stringify(cases)}]===]));for _,x in ipairs(tests)do assert(M.mayRereadAck(x.c)==x.expected,x.name)end;print(j.stringify({passed=true,cases=#tests,actualFailureCounterUsed=true,strictGetterRetained=true,nssAdmissionAllowed=false}))`;
const c=await connectRouter();try{const e=encode("/usr/bin/lua - <<'ACK_ONLY'\n"+code+"\nACK_ONLY\n");const r=receipt(await c.run(e.command),e);fs.writeFileSync('work/nss81/ack-qualification-raw-private.json',JSON.stringify(r,null,2));assert.equal(r.code,0,r.stderr);const q=JSON.parse(r.stdout);q.fastSha256=crypto.createHash('sha256').update(source).digest('hex');fs.writeFileSync('work/nss81/ack-qualified.json',JSON.stringify(q,null,2));console.log(JSON.stringify(q));}finally{c.close()}
