import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const root='work/nss35',read=p=>JSON.parse(fs.readFileSync(p));const d=read(root+'/deployment-latest.json'),q=read(root+'/address-trial-qualified.json');assert.equal(d.committed,true);assert.equal(q.passed,true);
const audit=read(d.localDir+'/nss35-publish-audit.json'),closure=read(root+'/final-closure.json');assert.equal(audit.passed,true);assert.equal(closure.passed,true);
function metrics(path){const x=read(path),a=x.rows[0],b=x.rows.at(-1),dt=b.uptime-a.uptime;
 const cpu=r=>r.cpu.trim().split(/\s+/).slice(1,9).map(Number),ca=cpu(a),cb=cpu(b),cd=ca.map((v,i)=>cb[i]-v),total=cd.reduce((s,v)=>s+v,0);
 const squeeze=r=>r.softnet.trim().split('\n').reduce((s,line)=>s+parseInt(line.trim().split(/\s+/)[2],16),0);
 return{samples:x.rows.length,seconds:dt,lan4Mbps:(b.txBytes-a.txBytes)*8/dt/1e6,lan4Pps:(b.txPackets-a.txPackets)/dt,cpuBusyPercent:100*(total-cd[3]-cd[4])/total,softirqPercent:100*cd[6]/total,timeSqueezeDelta:squeeze(b)-squeeze(a),allHealthy:x.rows.every(v=>v.status==='running'&&v.guardianHealthy&&v.accel===0&&v.frontend===1),singleProducer:new Set(x.rows.map(v=>v.producer)).size===1,sourceAgeRangeSeconds:[Math.min(...x.rows.map(v=>v.age)),Math.max(...x.rows.map(v=>v.age))],projectionSemantic:x.semantic};
}
const checks=['recovery-qualified.json','query-local-qualified.json','query-native-qualified.json','history-native-qualified.json','projection-qualified.json'].map(n=>{const p=read(root+'/'+n);assert.equal(p.passed,true);return{file:n,checks:p.checks,scope:p.scope,cases:p.cases}});
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');assert.equal(sha(root+'/worker.lua'),q.workerSha256);
const runnerProof=read('work/nss11/group-runner-test.json');assert.equal(runnerProof.allPassed,true);assert.equal(runnerProof.sha256['group-runner.c'],sha('work/nss11/group-runner.c'));assert.equal(runnerProof.sha256['group-runner-aarch64'],read(root+'/query-native-qualified.json').runnerSha256);
const out={round:'NSS35',updatedAt:new Date().toISOString(),hypothesis:'A bounded address-query data failure can withdraw candidates and recover in place without a classifier respawn, provided runner cleanup is proven.',change:'Only the address-query collector and its typed worker/guardian degradation path. Existing conntrack collection, classification policy, PBR/NAT, NSS admission deadlines and qdiscs are unchanged.',checks:checks.reduce((n,x)=>n+x.checks,0),testParts:checks,
 classifier:{committed:true,deploymentReference:root+'/deployment-latest.json',configSha256:d.configHash,workerSha256:q.workerSha256,guardianSha256:q.guardianSha256,commitAt:d.commitAt,latestAuditAt:closure.observedAt,producerMatchesPermanentObservation:read(root+'/permanent-observation.json').rows[0].producer===audit.producer},
 trial:metrics(root+'/trial-observation.json'),permanentObservation:metrics(root+'/permanent-observation.json'),
 automaticRollback:{passed:q.independentRollback.passed,observedAt:q.independentRollback.observedAt,deadlineSeconds:180,controllerDidNotCallRollback:true,oldWorkerAndConfigRestored:q.independentRollback.previousWorkerAndConfigRestored,oldClassifierHealthy:q.independentRollback.previousClassifierHealthyAndFresh},
 queryFixtures:read(root+'/query-native-qualified.json'),protectedAudit:{passed:audit.passed,configurationUnchanged:audit.protectedConfigurationUnchanged,exactOwnedNativeAudit:audit.exactOwnedNativeAudit,ecmClosedAndZero:audit.ecmClosedAndZero,selectors:audit.selectors},closure,
 safety:{newCheckpointForEachInstall:true,detachedStagingGuard:true,independentTransactionGuard:true,softwareRecoveryTargetsOnlyOwnedFilters:true,fullConntrackFlush:false,productionQdiscRebuild:false,wanModeChanged:false,nssGateOrQdiscLoaded:false},
 limitations:{productionAddressFailureInjected:false,underlyingBlockingOrSignalCauseProved:false,originalAddressStallNaturallyReproduced:false,highLoadABACompleted:false,highLoadCpuBenefitProved:false,cs2JitterLossMissCaptured:false,longTermStabilityQualified:false,fullNewVersionCrashPortLifecycleRequalified:false,smallNativeFixtureLoopNotProductionServiceFault:true},
 next:'Rebind the mainline NSS controller to the current committed config and revalidate full lifecycle/admission offline before one concentrated real CS2 plus Steam single-WAN trial. Do not reuse NSS33 live qualification against NSS35.'};
assert.equal(out.checks,136);assert.ok(out.trial.allHealthy&&out.permanentObservation.allHealthy&&out.classifier.producerMatchesPermanentObservation);
out.queryFixtures.runnerSourceSha256=runnerProof.sha256['group-runner.c'];
out.classifier.sameProducerObservationSpanSeconds=closure.uptime-read(root+'/permanent-observation.json').rows[0].uptime;
fs.writeFileSync('outputs/nss35-address-recovery-observations.json',JSON.stringify(out,null,2)+'\n');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const row=(label,m)=>`<tr><td>${label}</td><td>${m.samples}</td><td>${m.seconds.toFixed(2)} s</td><td>${m.lan4Mbps.toFixed(2)} Mbps</td><td>${m.lan4Pps.toFixed(0)}</td><td>${m.cpuBusyPercent.toFixed(2)}%</td><td>${m.softirqPercent.toFixed(2)}%</td><td>${m.timeSqueezeDelta}</td></tr>`;
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>NSS35 · 分类器地址查询恢复</title><style>body{font:16px/1.7 system-ui,sans-serif;background:#f5f7fa;color:#192434;margin:0}main{max-width:1080px;margin:42px auto;padding:30px;background:white;border-radius:16px}h1{font-size:30px}h2{font-size:22px;margin-top:30px}table{border-collapse:collapse;width:100%;font-size:14px}td,th{border:1px solid #dce3eb;padding:9px;text-align:left}code{overflow-wrap:anywhere;background:#f1f4f8;padding:2px 4px}.status{padding:16px;background:#e7f2ed;border-left:4px solid #318166}.muted{color:#536478}</style><main><h1>NSS35：分类器地址查询故障恢复</h1><p class="muted">${esc(out.updatedAt)} · 现场修复与独立回滚验收</p><p class="status">修复已常驻保留。136 项离线／路由器内存检查通过，180 秒自动到期回滚实际通过。ECM/NSS 仍关闭，真人高负载闭环尚未通过。</p><h2>问题与变更</h2><p>此前两次接口地址查询失败触发整个 worker 退出。新实现保留 2 秒命令期限；先确认查询进程组已清理，再撤回候选、清空观察历史并恢复自有软件规则。重新取得完整新数据后，RT 仍需重新预热。未确认清理、身份异常和未知故障继续走终止处理。</p><p>未延长 NSS 准入有效期，未复用旧 WAN 地址；CT 采集和分类策略保持原样。底层查询为什么阻塞或收到信号仍未定，本轮证明的是故障恢复路径。</p><h2>测试证据</h2><ul>${checks.map(p=>`<li>${esc(p.file)}：${p.checks} 项；${esc(p.scope)}</li>`).join('')}</ul><p>目标路由器中的超时与派生子进程测试约 2.16–2.17 秒完成，所有测试子进程均已退出。没有向常驻生产进程注入地址故障。</p><h2>现场试装与保留</h2><p>第一次试装由独立守护在 180 秒到期后恢复旧 worker、配置和健康分类器。再次创建检查点并布置回滚后重新安装，核验通过后提交保留。结束核验无活动实验事务、暂存目录、实验状态或 gate/qdisc 模块残留。</p><table><tr><th>窗口</th><th>采样数</th><th>时长</th><th>LAN4 下载</th><th>pps</th><th>CPU busy</th><th>softirq</th><th>time_squeeze</th></tr>${row('试装',out.trial)}${row('保留前',out.permanentObservation)}</table><p class="muted">自然轻负载、LAN4 汇总，包含观测开销；两个窗口均是软件转发，不能相减当 NSS 或修复的性能收益。没有采集本轮 CS2 jitter/loss/Miss。</p><h2>当前状态与下一步</h2><p>部署：<code>${out.classifier.deploymentReference}</code><br>配置：<code>${out.classifier.configSha256}</code><br>worker：<code>${out.classifier.workerSha256}</code></p><p>下一步先将 NSS 控制器绑定到新的常驻部署并重新核验生命周期和准入，再集中做一次真人 CS2 + Steam 单 WAN 对照。旧 NSS33 资格证明不得当作当前部署资格。暂不要求用户持续挂游戏。</p><p>尚未证明长期／高负载稳定性、完整新版本 crash/换端口生命周期，以及真人游戏的 NSS 收益。没有提交上游 Issue/PR。</p><p><a href="https://github.com/ZyPulse-zy/athena-nss-mainline">私有 GitHub 主线记录</a></p></main></html>`;
fs.writeFileSync('outputs/nss35-address-recovery-report.html',html);console.log(JSON.stringify({summaryWritten:true,checks:out.checks,trial:out.trial,permanent:out.permanentObservation,nssEnabled:false}));
