// One real WAN TCP stream over the existing authenticated SSH service, plus UDP.
import fs from 'node:fs';import path from 'node:path';import net from 'node:net';import dgram from 'node:dgram';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
import{uploadAck}from'./upload-ack.mjs';import{createPacer}from'./bounded-pacer.mjs';
import ssh2 from 'file:///C:/Users/lishu/Documents/Codex/2026-09-11/ax6600-re-cs-02-jdcos-4/work/runtime/node_modules/ssh2/lib/index.js';
const configPath=path.resolve(process.argv[2]),c=JSON.parse(fs.readFileSync(configPath)),dir=path.dirname(configPath);
assert.equal(c.tcpPort,22);assert.equal(c.tcpServerAddress,'18.138.159.236');assert.ok(c.mbps===32&&c.seconds<=180&&c.pps<=50);
const token=Buffer.from(c.token,'hex');assert.equal(token.length,32);const started=performance.now(),wall=Date.now()/1000;
const stats={pid:process.pid,session:c.session,startedAt:wall,tcpBytes:0,tcpSourcePort:c.tcpSourcePort,udpSourcePort:c.udpSourcePort,udpSent:0,udpReceived:0,tcpConnected:false,errors:[],bulkTransport:'owned authenticated SSH TCP upload',tcpMetric:'server-confirmed received bytes',pacerDebtCatchupAllowed:false,maximumPacerCreditBytes:65536,tcpPaused:false};
const udpOut=fs.createWriteStream(dir+'/udp-samples-private.jsonl'),loadOut=fs.createWriteStream(dir+'/load-samples-private.jsonl');let ended=false,sock,udpTimer,statusTimer,hardTimer,seq=0,client,uploadTimer;const seen=new Set();
function stamp(){if(ended)return;const x={...stats,at:Date.now()/1000,elapsed:(performance.now()-started)/1000};fs.writeFileSync(dir+'/status-private.json.new',JSON.stringify(x));try{fs.renameSync(dir+'/status-private.json.new',dir+'/status-private.json')}catch(e){if(e.code!=='EPERM'&&e.code!=='EBUSY')throw e;stats.statusPublicationDeferrals=(stats.statusPublicationDeferrals??0)+1}loadOut.write(JSON.stringify(x)+'\n');}
function stop(reason){if(ended)return;ended=true;clearInterval(udpTimer);clearInterval(uploadTimer);clearInterval(statusTimer);clearTimeout(hardTimer);if(reason)stats.errors.push(reason);sock?.close();client?.destroy();const final={...stats,finishedAt:Date.now()/1000,seconds:(performance.now()-started)/1000};fs.writeFileSync(dir+'/result-private.json',JSON.stringify(final,null,2));udpOut.end();loadOut.end();setTimeout(()=>process.exit(stats.errors.length?1:0),50);}
function rotate(port){assert.ok(Number.isInteger(port)&&port>=c.udpSourcePort&&port<c.udpSourcePort+12);sock?.close();sock=dgram.createSocket('udp4');stats.udpSourcePort=port;const current=sock;
 current.on('error',e=>stop('UDP: '+e.message));current.on('message',b=>{if(b.length!==128||!b.subarray(0,32).equals(token))return;const number=Number(b.readBigUInt64BE(32));if(seen.has(number))return;seen.add(number);stats.udpReceived++;udpOut.write(JSON.stringify({event:'reply',sequence:number,at:Date.now()/1000,sourcePort:port,rttMs:performance.now()-b.readDoubleBE(40)})+'\n');});
 current.bind(port,c.clientAddress,()=>current.connect(c.udpPort,c.serverAddress));
}
rotate(c.udpSourcePort);
udpTimer=setInterval(()=>{if(ended)return;try{const p=dir+'/control.json';if(fs.existsSync(p)){const x=JSON.parse(fs.readFileSync(p));assert.equal(x.session,c.session);if(x.stop){stop();return}if(x.pauseTcp!==undefined){assert.equal(typeof x.pauseTcp,'boolean');if(stats.tcpPaused!==x.pauseTcp){stats.tcpPaused=x.pauseTcp;stats.pauseChangedAt=Date.now()/1000;loadOut.write(JSON.stringify({event:'tcp-pause',paused:stats.tcpPaused,at:stats.pauseChangedAt,sourcePort:stats.tcpSourcePort})+'\n')}}if(x.tcpSourcePort!==undefined&&x.tcpSourcePort!==stats.tcpSourcePort)connectTcp(x.tcpSourcePort);if(x.udpSourcePort!==undefined&&x.udpSourcePort!==stats.udpSourcePort){rotate(x.udpSourcePort);return}}
 const b=Buffer.alloc(128);token.copy(b);b.writeBigUInt64BE(BigInt(seq),32);b.writeDoubleBE(performance.now(),40);sock.send(b,e=>{if(e&&!ended)stop('UDP send: '+e.message)});stats.udpSent++;udpOut.write(JSON.stringify({event:'sent',sequence:seq++,at:Date.now()/1000,sourcePort:stats.udpSourcePort})+'\n');}catch(e){stop(String(e))}},1000/c.pps);
statusTimer=setInterval(stamp,250);hardTimer=setTimeout(()=>stop(),c.seconds*1000);stamp();
const known=spawnSync('ssh-keygen',['-F',c.tcpServerAddress],{encoding:'utf8',windowsHide:true,timeout:3000});assert.equal(known.status,0,'Existing host key missing');const pins=known.stdout.split(/\r?\n/).filter(x=>x&&!x.startsWith('#')).map(x=>crypto.createHash('sha256').update(Buffer.from(x.trim().split(/\s+/)[2],'base64')).digest('hex'));assert.ok(pins.length);
const quote=x=>"'"+x.replaceAll("'","'\\''")+"'";
assert.equal(c.bulkDirection,'upload');const py=fs.readFileSync(new URL('./upload-server.py',import.meta.url),'utf8');
function connectTcp(port){assert.ok(Number.isInteger(port)&&port>=c.tcpSourcePort&&port<c.tcpSourcePort+8);const old=client;clearInterval(uploadTimer);client=new ssh2.Client();old?.destroy();const current=client;stats.tcpSourcePort=port;stats.tcpConnected=false;
 current.on('error',e=>{if(current===client)stop('SSH: '+e.message)});current.on('ready',()=>{if(current!==client)return;stats.tcpConnected=true;current.exec('timeout -k 1 185 python3 -u -c '+quote(py),(e,stream)=>{if(current!==client)return;if(e){stop('SSH exec: '+e.message);return}let pending='',acknowledged=0,submitted=0,blocked=false;const deliveredBase=stats.tcpBytes,begin=performance.now(),pacer=createPacer(begin,32000000/8);
stream.on('data',b=>{if(current!==client)return;try{pending+=b.toString('utf8');assert.ok(pending.length<=8192,'Remote counter buffer overflow');let at;while((at=pending.indexOf('\n'))>=0){const line=pending.slice(0,at);pending=pending.slice(at+1);acknowledged=uploadAck(acknowledged,line);stats.tcpBytes=deliveredBase+acknowledged;assert.ok(stats.tcpBytes<=1024*1024*1024,'Global delivery ceiling reached');}}catch(e){stop('Remote delivery counter: '+String(e));}});
stream.on('drain',()=>{if(current===client)blocked=false});const block=Buffer.alloc(16384);
uploadTimer=setInterval(()=>{if(current!==client||ended)return;const at=performance.now();try{for(let i=0;i<4&&pacer.next(at,blocked||stats.tcpPaused);i++){assert.ok(submitted+block.length<=1024*1024*1024,'Submission ceiling reached');submitted+=block.length;if(!stream.write(block)){blocked=true;break}}}catch(e){stop('Upload: '+String(e));}},5);let error='';stream.stderr.on('data',b=>{if(error.length<2048)error+=b.toString()});stream.on('close',code=>{if(current===client)stop(code&&code!==124?'Remote stream exited '+code+': '+error:undefined)});});});
 current.connect({sock:net.connect({host:c.tcpServerAddress,port:c.tcpPort,localAddress:c.clientAddress,localPort:port}),username:'ubuntu',privateKey:fs.readFileSync(c.sshKeyPath),hostHash:'sha256',hostVerifier:h=>pins.includes(h),readyTimeout:6000,keepaliveInterval:2000});
}
connectTcp(c.tcpSourcePort);
